/* Technosqueek mappings*/
		.word word_89B8C-Map_TechnoSqueek
		.word word_89B94-Map_TechnoSqueek
		.word word_89B9C-Map_TechnoSqueek
		.word word_89BA4-Map_TechnoSqueek
		.word word_89BAC-Map_TechnoSqueek
		.word word_89BB4-Map_TechnoSqueek
		.word word_89BBC-Map_TechnoSqueek
		.word word_89BC4-Map_TechnoSqueek
		.word word_89BCC-Map_TechnoSqueek
		.word word_89BD4-Map_TechnoSqueek
word_89B8C:	.word 1			/* DATA XREF: ROM:00089B78o*/
		.byte  0xF8,   9,	  0,   0, 0xFF, 0xF4
word_89B94:	.word 1			/* DATA XREF: ROM:00089B78o*/
		.byte  0xF8,   9,	  0,   6, 0xFF, 0xF4
word_89B9C:	.word 1			/* DATA XREF: ROM:00089B78o*/
		.byte  0xFC,   4,	  0,  0xC, 0xFF, 0xF8
word_89BA4:	.word 1			/* DATA XREF: ROM:00089B78o*/
		.byte  0xFC,   4,	  0,  0xE, 0xFF, 0xF8
word_89BAC:	.word 1			/* DATA XREF: ROM:00089B78o*/
		.byte  0xFC,   4,	  0, 0x10, 0xFF, 0xF8
word_89BB4:	.word 1			/* DATA XREF: ROM:00089B78o*/
		.byte  0xF4,   6,	  0, 0x12, 0xFF, 0xF8
word_89BBC:	.word 1			/* DATA XREF: ROM:00089B78o*/
		.byte  0xF4,   6,	  0, 0x18, 0xFF, 0xF8
word_89BC4:	.word 1			/* DATA XREF: ROM:00089B78o*/
		.byte  0xF8,   1,	  0, 0x1E, 0xFF, 0xFC
word_89BCC:	.word 1			/* DATA XREF: ROM:00089B78o*/
		.byte  0xF8,   1,	  0, 0x20, 0xFF, 0xFC
word_89BD4:	.word 1			/* DATA XREF: ROM:00089B78o*/
		.byte  0xF8,   1,	  0, 0x22, 0xFF, 0xFC
