		.word word_2C724-Map_Button
		.word word_2C732-Map_Button
		.word word_2C73A-Map_Button
word_2C724:	.word 2			/* DATA XREF: ROM:0002C71Eo*/
		.byte  0xF4,  0xC,	  0,   0, 0xFF, 0xF0
		.byte  0xFC,   4,	  0,   4, 0xFF, 0xF8
word_2C732:	.word 1			/* DATA XREF: ROM:0002C71Eo*/
		.byte  0xFC,  0xC,	  0,   0, 0xFF, 0xF0
word_2C73A:	.word 2			/* DATA XREF: ROM:0002C71Eo*/
		.byte  0xF8,  0xC,	  0,   0, 0xFF, 0xF0
		.byte	0,   4,	  0,   4, 0xFF, 0xF8
