		.word word_8FA9C-Map_FirewormSegments
		.word word_8FA6C-Map_FirewormSegments
		.word word_8FA74-Map_FirewormSegments
		.word word_8FA7C-Map_FirewormSegments
		.word word_8FA84-Map_FirewormSegments
		.word word_8FA8C-Map_FirewormSegments
		.word word_8FA94-Map_FirewormSegments
		.word word_8FAA4-Map_FirewormSegments
word_8FA6C:	.word 1			
		.byte  0xF8,   5,	  0,   0, 0xFF, 0xF8
word_8FA74:	.word 1			
		.byte  0xF8,   5,	  0,   4, 0xFF, 0xF8
word_8FA7C:	.word 1			
		.byte  0xF8,   5,	  0,   8, 0xFF, 0xF8
word_8FA84:	.word 1			
		.byte  0xF8,   5,	  0,  0xC, 0xFF, 0xF8
word_8FA8C:	.word 1			
		.byte  0xF8,   5,	  0, 0x10, 0xFF, 0xF8
word_8FA94:	.word 1			
		.byte  0xFC,   0,	  0, 0x14, 0xFF, 0xFC
word_8FA9C:	.word 1			
		.byte  0xEC,  0xA,	  0, 0x15, 0xFF, 0xF4
word_8FAA4:	.word 0			
