Map_361F0E:	.word Frame_361F1A-Map_361F0E
		.word Frame_361F22-Map_361F0E
		.word Frame_361F2A-Map_361F0E
		.word Frame_361F32-Map_361F0E
		.word Frame_361F3A-Map_361F0E
		.word Frame_361F42-Map_361F0E
Frame_361F1A:	.word 1
		.byte 0xF8,  0,  0,  0,0xFF,0xFC
Frame_361F22:	.word 1
		.byte 0xF8,  0,  8,  0,0xFF,0xFC
Frame_361F2A:	.word 1
		.byte 0xF0,  1,  0,  1,0xFF,0xFC
Frame_361F32:	.word 1
		.byte 0xF0,  1,  8,  1,0xFF,0xFC
Frame_361F3A:	.word 1
		.byte 0xE8,  2,  0,  3,0xFF,0xFC
Frame_361F42:	.word 1
		.byte 0xE8,  2,  8,  3,0xFF,0xFC
