		.word word_38FD2-Map_ICZTensionBridge
		.word word_38FD2-Map_ICZTensionBridge
		.word word_38FD2-Map_ICZTensionBridge
		.word word_38FDA-Map_ICZTensionBridge
		.word word_38FDA-Map_ICZTensionBridge
		.word word_38FDA-Map_ICZTensionBridge
		.word word_38FE2-Map_ICZTensionBridge
		.word word_38FE2-Map_ICZTensionBridge
		.word word_38FE2-Map_ICZTensionBridge
		.word word_38FEA-Map_ICZTensionBridge
		.word word_38FEA-Map_ICZTensionBridge
		.word word_38FEA-Map_ICZTensionBridge
word_38FD2:	.word 1			/*  DATA XREF: ROM:00038FBAo */
		.byte  0xF8,   5,	  0, 0x7E, 0xFF, 0xF8
word_38FDA:	.word 1			/*  DATA XREF: ROM:00038FBAo */
		.byte  0xF8,   5,	  0, 0x82, 0xFF, 0xF8
word_38FE2:	.word 1			/*  DATA XREF: ROM:00038FBAo */
		.byte  0xF9,   5,	  0, 0x86, 0xFF, 0xF9
word_38FEA:	.word 1			/*  DATA XREF: ROM:00038FBAo */
		.byte  0xF8,   5,	  0, 0x8A, 0xFF, 0xF8
