Map_66A52:		.word word_66A5C-Map_66A52
		.word word_66A6A-Map_66A52
		.word word_66A78-Map_66A52
		.word word_66A86-Map_66A52
		.word word_66A94-Map_66A52
word_66A5C:	.word 2			
		.byte  0xF0,   6,	  0,   0, 0xFF, 0xFC
		.byte	8,   4,	  0,   6, 0xFF, 0xF4
word_66A6A:	.word 2			
		.byte  0xF0,   6,	  0,   8, 0xFF, 0xFC
		.byte	8,   4,	  0,   6, 0xFF, 0xF4
word_66A78:	.word 2			
		.byte  0xF0,  0xA,	  0,  0xE, 0xFF, 0xFC
		.byte	8,   4,	  0,   6, 0xFF, 0xF4
word_66A86:	.word 2			
		.byte  0xF0,  0xA,	  0, 0x17, 0xFF, 0xFC
		.byte	8,   4,	  0,   6, 0xFF, 0xF4
word_66A94:	.word 1			
		.byte  0xF0,   6,	  0,   0, 0xFF, 0xFC
