		.word	word_3E206-Map_MHZMushroomCap
		.word word_3E214-Map_MHZMushroomCap
		.word word_3E222-Map_MHZMushroomCap
		.word word_3E230-Map_MHZMushroomCap
word_3E206:	.word 2			/*  DATA XREF: ROM:0003E1FEo */
		.byte  0xE3,  0xF,	  0,   0, 0xFF, 0xE0
		.byte  0xE3,  0xF,	  0, 0x10,   0,	 0
word_3E214:	.word 2			/*  DATA XREF: ROM:0003E1FEo */
		.byte  0xF7,  0xD,	  0, 0x20, 0xFF, 0xE0
		.byte  0xF7,  0xD,	  0, 0x28,   0,	 0
word_3E222:	.word 2			/*  DATA XREF: ROM:0003E1FEo */
		.byte  0xE1,  0xF,	  0,   0, 0xFF, 0xE0
		.byte  0xE1,  0xF,	  0, 0x10,   0,	 0
word_3E230:	.word 2			/*  DATA XREF: ROM:0003E1FEo */
		.byte  0xE0,  0xF,	  0,   0, 0xFF, 0xE0
		.byte  0xE0,  0xF,	  0, 0x10,   0,	 0
