Map_DPZDissolvingSandBar_:.word word_36110-Map_DPZDissolvingSandBar_
		.word word_3611E-Map_DPZDissolvingSandBar_
		.word word_3612C-Map_DPZDissolvingSandBar_
		.word word_3613A-Map_DPZDissolvingSandBar_
		.word word_36148-Map_DPZDissolvingSandBar_
		.word word_36148-Map_DPZDissolvingSandBar_
		.word word_36148-Map_DPZDissolvingSandBar_
		.word word_36148-Map_DPZDissolvingSandBar_
		.word word_36156-Map_DPZDissolvingSandBar_
		.word word_36156-Map_DPZDissolvingSandBar_
		.word word_36156-Map_DPZDissolvingSandBar_
		.word word_36156-Map_DPZDissolvingSandBar_
		.word word_36164-Map_DPZDissolvingSandBar_
		.word word_36164-Map_DPZDissolvingSandBar_
		.word word_36164-Map_DPZDissolvingSandBar_
		.word word_36164-Map_DPZDissolvingSandBar_
		.word word_36172-Map_DPZDissolvingSandBar_
		.word word_36172-Map_DPZDissolvingSandBar_
		.word word_36172-Map_DPZDissolvingSandBar_
		.word word_36172-Map_DPZDissolvingSandBar_
		.word word_36180-Map_DPZDissolvingSandBar_
		.word word_36180-Map_DPZDissolvingSandBar_
		.word word_36180-Map_DPZDissolvingSandBar_
		.word word_36180-Map_DPZDissolvingSandBar_
		.word word_3618E-Map_DPZDissolvingSandBar_
		.word word_3618E-Map_DPZDissolvingSandBar_
		.word word_3618E-Map_DPZDissolvingSandBar_
		.word word_3618E-Map_DPZDissolvingSandBar_
		.word word_362A0-Map_DPZDissolvingSandBar_
		.word word_3619C-Map_DPZDissolvingSandBar_
Map_DPZDissolvingSandBar2:
Map_360D6:	.word word_3619C-Map_360D6

		.word word_361B6-Map_360D6
		.word word_361D0-Map_360D6
		.word word_361EA-Map_360D6
		.word word_36204-Map_360D6
		.word word_36204-Map_360D6
		.word word_36204-Map_360D6
		.word word_36204-Map_360D6
		.word word_3621E-Map_360D6
		.word word_3621E-Map_360D6
		.word word_3621E-Map_360D6
		.word word_3621E-Map_360D6
		.word word_36238-Map_360D6
		.word word_36238-Map_360D6
		.word word_36238-Map_360D6
		.word word_36238-Map_360D6
		.word word_36252-Map_360D6
		.word word_36252-Map_360D6
		.word word_36252-Map_360D6
		.word word_36252-Map_360D6
		.word word_3626C-Map_360D6
		.word word_3626C-Map_360D6
		.word word_3626C-Map_360D6
		.word word_3626C-Map_360D6
		.word word_36286-Map_360D6
		.word word_36286-Map_360D6
		.word word_36286-Map_360D6
		.word word_36286-Map_360D6
		.word word_362A0-Map_360D6
word_36110:	.word 2
		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xE0
		.byte  0xF0,  0xF,	  0, 0x10,   0,	 0
word_3611E:	.word 2
		.byte  0xF0,  0xF,	  0, 0x10, 0xFF, 0xE0
		.byte  0xF0,  0xF,	  0, 0x20,   0,	 0
word_3612C:	.word 2
		.byte  0xF0,  0xF,	  0, 0x20, 0xFF, 0xE0
		.byte  0xF0,  0xF,	  0, 0x30,   0,	 0
word_3613A:	.word 2
		.byte  0xF0,  0xF,	  0, 0x30, 0xFF, 0xE0
		.byte  0xF0,  0xF,	  0,   0,   0,	 0
word_36148:	.word 2
		.byte  0xF0,  0xF,	  0, 0x40, 0xFF, 0xE0
		.byte  0xF0,  0xF,	  0, 0x40,   0,	 0
word_36156:	.word 2
		.byte  0xF0,  0xF,	  0, 0x50, 0xFF, 0xE0
		.byte  0xF0,  0xF,	  0, 0x50,   0,	 0
word_36164:	.word 2
		.byte  0xF8,  0xF,	  0, 0x60, 0xFF, 0xE0
		.byte  0xF8,  0xF,	  0, 0x60,   0,	 0
word_36172:	.word 2
		.byte  0xF8,  0xF,	  0, 0x70, 0xFF, 0xE0
		.byte  0xF8,  0xF,	  0, 0x70,   0,	 0
word_36180:	.word 2
		.byte	0,  0xF,	  0, 0x80, 0xFF, 0xE0
		.byte	0,  0xF,	  0, 0x80,   0,	 0
word_3618E:	.word 2
		.byte	8,  0xE,	  0, 0x90, 0xFF, 0xE0
		.byte	8,  0xE,	  0, 0x90,   0,	 0
word_3619C:	.word 4

		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xC0
		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xE0
		.byte  0xF0,  0xF,	  0, 0x10,   0,	 0
		.byte  0xF0,  0xF,	  0,   0,   0, 0x20
word_361B6:	.word 4
		.byte  0xF0,  0xF,	  0, 0x10, 0xFF, 0xC0
		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xE0
		.byte  0xF0,  0xF,	  0, 0x20,   0,	 0
		.byte  0xF0,  0xF,	  0,   0,   0, 0x20
word_361D0:	.word 4
		.byte  0xF0,  0xF,	  0, 0x20, 0xFF, 0xC0
		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xE0
		.byte  0xF0,  0xF,	  0, 0x30,   0,	 0
		.byte  0xF0,  0xF,	  0,   0,   0, 0x20
word_361EA:	.word 4
		.byte  0xF0,  0xF,	  0, 0x30, 0xFF, 0xC0
		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xE0
		.byte  0xF0,  0xF,	  0,   0,   0,	 0
		.byte  0xF0,  0xF,	  0,   0,   0, 0x20
word_36204:	.word 4
		.byte  0xF0,  0xF,	  0, 0x40, 0xFF, 0xC0
		.byte  0xF0,  0xF,	  0, 0x40, 0xFF, 0xE0
		.byte  0xF0,  0xF,	  0, 0x40,   0,	 0
		.byte  0xF0,  0xF,	  0, 0x40,   0, 0x20
word_3621E:	.word 4
		.byte  0xF0,  0xF,	  0, 0x50, 0xFF, 0xC0
		.byte  0xF0,  0xF,	  0, 0x50, 0xFF, 0xE0
		.byte  0xF0,  0xF,	  0, 0x50,   0,   0
		.byte  0xF0,  0xF,	  0, 0x50,   0, 0x20
word_36238:	.word 4
		.byte  0xF8,  0xF,	  0, 0x60, 0xFF, 0xC0
		.byte  0xF8,  0xF,	  0, 0x60, 0xFF, 0xE0
		.byte  0xF8,  0xF,	  0, 0x60,   0,	 0
		.byte  0xF8,  0xF,	  0, 0x60,   0, 0x20
word_36252:	.word 4
		.byte  0xF8,  0xF,	  0, 0x70, 0xFF, 0xC0
		.byte  0xF8,  0xF,	  0, 0x70, 0xFF, 0xE0
		.byte  0xF8,  0xF,	  0, 0x70,   0,	 0
		.byte  0xF8,  0xF,	  0, 0x70,   0, 0x20
word_3626C:	.word 4
		.byte	0,  0xF,	  0, 0x80, 0xFF, 0xC0
		.byte	0,  0xF,	  0, 0x80, 0xFF, 0xE0
		.byte	0,  0xF,	  0, 0x80,   0,	 0
		.byte	0,  0xF,	  0, 0x80,   0, 0x20
word_36286:	.word 4
		.byte	8,  0xE,	  0, 0x90, 0xFF, 0xC0
		.byte	8,  0xE,	  0, 0x90, 0xFF, 0xE0
		.byte	8,  0xE,	  0, 0x90,   0,	 0
		.byte	8,  0xE,	  0, 0x90,   0, 0x20
word_362A0:	.word 0