		.word byte_18DCA-Ani_DashSplashDrown
		.word byte_18DCD-Ani_DashSplashDrown
		.word byte_18DD9-Ani_DashSplashDrown
		.word byte_18DE2-Ani_DashSplashDrown
		.word byte_18DE8-Ani_DashSplashDrown
byte_18DCA:	.byte  0x1F,   0,	0xFF	
byte_18DCD:	.byte	3,   1,	  2,   3,   4,	 5,   6,   7,	8,   9,	0xFD,   0
					
byte_18DD9:	.byte	1,  0xA,	 0xB,  0xC,  0xD,	0xE,  0xF, 0x10, 0xFF 
byte_18DE2:	.byte	3, 0x11,	0x12, 0x13, 0x14, 0xFC 
byte_18DE8:	.byte	5, 0x16,	0x17, 0x18, 0x19, 0x1A, 0x1B, 0x1C, 0x1D, 0xFD,	  0,   0
					
