		.word word_18F1E-DPLC_DashSplashDrown
		.word word_18F20-DPLC_DashSplashDrown
		.word word_18F24-DPLC_DashSplashDrown
		.word word_18F28-DPLC_DashSplashDrown
		.word word_18F2C-DPLC_DashSplashDrown
		.word word_18F30-DPLC_DashSplashDrown
		.word word_18F34-DPLC_DashSplashDrown
		.word word_18F38-DPLC_DashSplashDrown
		.word word_18F3C-DPLC_DashSplashDrown
		.word word_18F40-DPLC_DashSplashDrown
		.word word_18F44-DPLC_DashSplashDrown
		.word word_18F48-DPLC_DashSplashDrown
		.word word_18F4C-DPLC_DashSplashDrown
		.word word_18F50-DPLC_DashSplashDrown
		.word word_18F54-DPLC_DashSplashDrown
		.word word_18F58-DPLC_DashSplashDrown
		.word word_18F5C-DPLC_DashSplashDrown
		.word word_18F60-DPLC_DashSplashDrown
		.word word_18F60-DPLC_DashSplashDrown
		.word word_18F60-DPLC_DashSplashDrown
		.word word_18F60-DPLC_DashSplashDrown
		.word word_18F62-DPLC_DashSplashDrown
		.word word_18F66-DPLC_DashSplashDrown
		.word word_18F6A-DPLC_DashSplashDrown
		.word word_18F6E-DPLC_DashSplashDrown
		.word word_18F72-DPLC_DashSplashDrown
		.word word_18F76-DPLC_DashSplashDrown
		.word word_18F7A-DPLC_DashSplashDrown
		.word word_18F7E-DPLC_DashSplashDrown
		.word word_18F82-DPLC_DashSplashDrown
word_18F1E:	.word	0		/*  DATA XREF: ROM:00018EE2o */
word_18F20:	.word	1		/*  DATA XREF: ROM:00018EE2o */
		.word 0x5000
word_18F24:	.word	1		/*  DATA XREF: ROM:00018EE2o */
		.word 0xF006
word_18F28:	.word	1		/*  DATA XREF: ROM:00018EE2o */
		.word 0xF016
word_18F2C:	.word	1		/*  DATA XREF: ROM:00018EE2o */
		.word 0xF026
word_18F30:	.word	1		/*  DATA XREF: ROM:00018EE2o */
		.word 0xF036
word_18F34:	.word	1		/*  DATA XREF: ROM:00018EE2o */
		.word 0xB046
word_18F38:	.word	1		/*  DATA XREF: ROM:00018EE2o */
		.word 0x7052
word_18F3C:	.word	1		/*  DATA XREF: ROM:00018EE2o */
		.word 0x305A
word_18F40:	.word	1		/*  DATA XREF: ROM:00018EE2o */
		.word 0x305E
word_18F44:	.word	1		/*  DATA XREF: ROM:00018EE2o */
		.word 0x7062
word_18F48:	.word	1		/*  DATA XREF: ROM:00018EE2o */
		.word 0x706A
word_18F4C:	.word	1		/*  DATA XREF: ROM:00018EE2o */
		.word 0x7072
word_18F50:	.word	1		/*  DATA XREF: ROM:00018EE2o */
		.word 0xB07A
word_18F54:	.word	1		/*  DATA XREF: ROM:00018EE2o */
		.word 0xB086
word_18F58:	.word	1		/*  DATA XREF: ROM:00018EE2o */
		.word 0xB092
word_18F5C:	.word	1		/*  DATA XREF: ROM:00018EE2o */
		.word 0xB09E
word_18F60:	.word	0		/*  DATA XREF: ROM:00018EE2o */
word_18F62:	.word	1		/*  DATA XREF: ROM:00018EE2o */
		.word 0xF0AA
word_18F66:	.word	1		/*  DATA XREF: ROM:00018EE2o */
		.word 0xB000
word_18F6A:	.word	1		/*  DATA XREF: ROM:00018EE2o */
		.word 0xF00C
word_18F6E:	.word	1		/*  DATA XREF: ROM:00018EE2o */
		.word 0xF01C
word_18F72:	.word	1		/*  DATA XREF: ROM:00018EE2o */
		.word 0xF02C
word_18F76:	.word	1		/*  DATA XREF: ROM:00018EE2o */
		.word 0xF03C
word_18F7A:	.word	1		/*  DATA XREF: ROM:00018EE2o */
		.word 0xF04C
word_18F7E:	.word	1		/*  DATA XREF: ROM:00018EE2o */
		.word 0xF05C
word_18F82:	.word	1		/*  DATA XREF: ROM:00018EE2o */
		.word 0xF06C
