		.word word_1911C-Map_DashDust2P
		.word word_1911E-Map_DashDust2P
		.word word_19126-Map_DashDust2P
		.word word_1912E-Map_DashDust2P
		.word word_19136-Map_DashDust2P
		.word word_1913E-Map_DashDust2P
		.word word_19146-Map_DashDust2P
		.word word_1914E-Map_DashDust2P
word_1911C:	.word 0			/* DATA XREF: ROM:0001910Co*/
word_1911E:	.word 1			/* DATA XREF: ROM:0001910Co*/
		.byte	4,   8,	  0,   0, 0xFF, 0xEC
word_19126:	.word 1			/* DATA XREF: ROM:0001910Co*/
		.byte	4,   8,	  0,   3, 0xFF, 0xEC
word_1912E:	.word 1			/* DATA XREF: ROM:0001910Co*/
		.byte  0xFC,   9,	  0,   6, 0xFF, 0xEC
word_19136:	.word 1			/* DATA XREF: ROM:0001910Co*/
		.byte  0xFC,   9,	  0,  0xC, 0xFF, 0xEC
word_1913E:	.word 1			/* DATA XREF: ROM:0001910Co*/
		.byte  0xFC,   0,	  0, 0x12, 0xFF, 0xFC
word_19146:	.word 1			/* DATA XREF: ROM:0001910Co*/
		.byte  0xFC,   0,	  0, 0x13, 0xFF, 0xFC
word_1914E:	.word 1			/* DATA XREF: ROM:0001910Co*/
		.byte  0xFC,   0,	  0, 0x14, 0xFF, 0xFC
