		.word word_18E30-Map_DashDust
		.word word_18E32-Map_DashDust
		.word word_18E3A-Map_DashDust
		.word word_18E42-Map_DashDust
		.word word_18E4A-Map_DashDust
		.word word_18E52-Map_DashDust
		.word word_18E5A-Map_DashDust
		.word word_18E62-Map_DashDust
		.word word_18E6A-Map_DashDust
		.word word_18E72-Map_DashDust
		.word word_18E7A-Map_DashDust
		.word word_18E82-Map_DashDust
		.word word_18E8A-Map_DashDust
		.word word_18E92-Map_DashDust
		.word word_18E9A-Map_DashDust
		.word word_18EA2-Map_DashDust
		.word word_18EAA-Map_DashDust
		.word word_18EB2-Map_DashDust
		.word word_18EBA-Map_DashDust
		.word word_18EC2-Map_DashDust
		.word word_18ECA-Map_DashDust
		.word word_18E30-Map_DashDust
		.word word_18ED2-Map_DashDust
		.word word_18EDA-Map_DashDust
		.word word_18EDA-Map_DashDust
		.word word_18EDA-Map_DashDust
		.word word_18EDA-Map_DashDust
		.word word_18EDA-Map_DashDust
		.word word_18EDA-Map_DashDust
		.word word_18EDA-Map_DashDust
word_18E30:	.word 0			/* DATA XREF: ROM:00018DF4o*/
word_18E32:	.word 1			/* DATA XREF: ROM:00018DF4o*/
		.byte  0xF2,   9,	  0,   0, 0xFF, 0xF0
word_18E3A:	.word 1			/* DATA XREF: ROM:00018DF4o*/
		.byte  0xE2,  0xF,	  0,   0, 0xFF, 0xF0
word_18E42:	.word 1			/* DATA XREF: ROM:00018DF4o*/
		.byte  0xE2,  0xF,	  0,   0, 0xFF, 0xF0
word_18E4A:	.word 1			/* DATA XREF: ROM:00018DF4o*/
		.byte  0xE2,  0xF,	  0,   0, 0xFF, 0xF0
word_18E52:	.word 1			/* DATA XREF: ROM:00018DF4o*/
		.byte  0xE2,  0xF,	  0,   0, 0xFF, 0xF0
word_18E5A:	.word 1			/* DATA XREF: ROM:00018DF4o*/
		.byte  0xEA,  0xE,	  0,   0, 0xFF, 0xF0
word_18E62:	.word 1			/* DATA XREF: ROM:00018DF4o*/
		.byte  0xF2,  0xD,	  0,   0, 0xFF, 0xF0
word_18E6A:	.word 1			/* DATA XREF: ROM:00018DF4o*/
		.byte  0xFA,  0xC,	  0,   0, 0xFF, 0xF0
word_18E72:	.word 1			/* DATA XREF: ROM:00018DF4o*/
		.byte  0xFA,  0xC,	  0,   0, 0xFF, 0xF0
word_18E7A:	.word 1			/* DATA XREF: ROM:00018DF4o*/
		.byte	4,  0xD,	  0,   0, 0xFF, 0xE0
word_18E82:	.word 1			/* DATA XREF: ROM:00018DF4o*/
		.byte	4,  0xD,	  0,   0, 0xFF, 0xE0
word_18E8A:	.word 1			/* DATA XREF: ROM:00018DF4o*/
		.byte	4,  0xD,	  0,   0, 0xFF, 0xE0
word_18E92:	.word 1			/* DATA XREF: ROM:00018DF4o*/
		.byte  0xFC,  0xE,	  0,   0, 0xFF, 0xE0
word_18E9A:	.word 1			/* DATA XREF: ROM:00018DF4o*/
		.byte  0xFC,  0xE,	  0,   0, 0xFF, 0xE0
word_18EA2:	.word 1			/* DATA XREF: ROM:00018DF4o*/
		.byte  0xFC,  0xE,	  0,   0, 0xFF, 0xE0
word_18EAA:	.word 1			/* DATA XREF: ROM:00018DF4o*/
		.byte  0xFC,  0xE,	  0,   0, 0xFF, 0xE0
word_18EB2:	.word 1			/* DATA XREF: ROM:00018DF4o*/
		.byte  0xF8,   5,	  0,   0, 0xFF, 0xF8
word_18EBA:	.word 1			/* DATA XREF: ROM:00018DF4o*/
		.byte  0xF8,   5,	  0,   4, 0xFF, 0xF8
word_18EC2:	.word 1			/* DATA XREF: ROM:00018DF4o*/
		.byte  0xF8,   5,	  0,   8, 0xFF, 0xF8
word_18ECA:	.word 1			/* DATA XREF: ROM:00018DF4o*/
		.byte  0xF8,   5,	  0,  0xC, 0xFF, 0xF8
word_18ED2:	.word 1			/* DATA XREF: ROM:00018DF4o*/
		.byte  0xE8,  0xE,	  0,   0, 0xFF, 0xF0
word_18EDA:	.word 1			/* DATA XREF: ROM:00018DF4o*/
		.byte  0xE0,  0xF,	  0,   0, 0xFF, 0xF0
