Ani_36A58:		.word byte_36A70-Ani_36A58
		.word byte_36A73-Ani_36A58
		.word byte_36A76-Ani_36A58
		.word byte_36A79-Ani_36A58
		.word byte_36A7F-Ani_36A58
		.word byte_36A82-Ani_36A58
		.word byte_36A85-Ani_36A58
		.word byte_36A88-Ani_36A58
		.word byte_36A8B-Ani_36A58
		.word byte_36A91-Ani_36A58
		.word byte_36A9A-Ani_36A58
		.word byte_36A9F-Ani_36A58
byte_36A70:	.byte  0x1F,   0,	0xFF	
byte_36A73:	.byte  0x1F,   1,	0xFF	
byte_36A76:	.byte  0x1F,   2,	0xFF	
byte_36A79:	.byte	7,   3,	  4,   5, 0x19, 0xFF 
byte_36A7F:	.byte  0x1F, 0x11,	0xFF	
byte_36A82:	.byte  0x1F,   6,	0xFF	
byte_36A85:	.byte  0x1F,   7,	0xFF	
byte_36A88:	.byte  0x1F, 0x1A,	0xFF	
byte_36A8B:	.byte	5,   9,	 0xA,  0xB,  0xC, 0xFC 
byte_36A91:	.byte	5,  0xD,	 0xE,  0xF, 0x10, 0xFC, 0x1A, 0xFE,	1 
byte_36A9A:	.byte   0xB,   8,	  7, 0xFD,   9 
byte_36A9F:	.byte	5, 0x1B,	0x1C, 0x1D, 0x1E, 0x1F, 0xFC	
