		.word word_37002-Map_2PGoalMarker
		.word word_37010-Map_2PGoalMarker
		.word word_3701E-Map_2PGoalMarker
		.word word_3702C-Map_2PGoalMarker
word_37002:	.word 2			/*  DATA XREF: ROM:00036FFAo */
		.byte  0xEC,   2,	  0,   0, 0xFF, 0xFC
		.byte	4,   1,	  0,   3, 0xFF, 0xFC
word_37010:	.word 2			/*  DATA XREF: ROM:00036FFAo */
		.byte  0xEC,   2,	  0,   5, 0xFF, 0xFC
		.byte	4,   1,	  0,   3, 0xFF, 0xFC
word_3701E:	.word 2			/*  DATA XREF: ROM:00036FFAo */
		.byte  0xEC,   2,	  0,   8, 0xFF, 0xFC
		.byte	4,   1,	  0,   3, 0xFF, 0xFC
word_3702C:	.word 2			/*  DATA XREF: ROM:00036FFAo */
		.byte  0xEC,   2,	  0,  0xB, 0xFF, 0xFC
		.byte	4,   1,	  0,   3, 0xFF, 0xFC
