		.word word_36AE6-Map_2PItem
		.word word_36AEE-Map_2PItem
		.word word_36AF6-Map_2PItem
		.word word_36AFE-Map_2PItem
		.word word_36B06-Map_2PItem
		.word word_36B0E-Map_2PItem
		.word word_36B16-Map_2PItem
		.word word_36B1E-Map_2PItem
		.word word_36B26-Map_2PItem
		.word word_36B2E-Map_2PItem
		.word word_36B36-Map_2PItem
		.word word_36B3E-Map_2PItem
		.word word_36B46-Map_2PItem
		.word word_36B4E-Map_2PItem
		.word word_36B56-Map_2PItem
		.word word_36B5E-Map_2PItem
		.word word_36B66-Map_2PItem
		.word word_36B6E-Map_2PItem
		.word word_36B76-Map_2PItem
		.word word_36B7E-Map_2PItem
		.word word_36B86-Map_2PItem
		.word word_36B8E-Map_2PItem
		.word word_36B96-Map_2PItem
		.word word_36B9E-Map_2PItem
		.word word_36BA6-Map_2PItem
		.word word_36BAE-Map_2PItem
		.word word_36BB6-Map_2PItem
		.word word_36BB8-Map_2PItem
		.word word_36BC0-Map_2PItem
		.word word_36BC8-Map_2PItem
		.word word_36BD0-Map_2PItem
		.word word_36BD8-Map_2PItem
word_36AE6:	.word 1			/*  DATA XREF: ROM:00036AA6o */
		.byte  0xF8,   5,	  0,   0, 0xFF, 0xF8
word_36AEE:	.word 1			/*  DATA XREF: ROM:00036AA6o */
		.byte  0xF8,   5,	  0,   4, 0xFF, 0xF8
word_36AF6:	.word 1			/*  DATA XREF: ROM:00036AA6o */
		.byte  0xF8,   5,	  0,   8, 0xFF, 0xF8
word_36AFE:	.word 1			/*  DATA XREF: ROM:00036AA6o */
		.byte  0xF8,   5,	0x60,  0xC, 0xFF, 0xF8
word_36B06:	.word 1			/*  DATA XREF: ROM:00036AA6o */
		.byte  0xF8,   5,	0x60, 0x10, 0xFF, 0xF8
word_36B0E:	.word 1			/*  DATA XREF: ROM:00036AA6o */
		.byte  0xF8,   1,	0x60, 0x14, 0xFF, 0xFC
word_36B16:	.word 1			/*  DATA XREF: ROM:00036AA6o */
		.byte  0xF8,   5,	  0, 0x16, 0xFF, 0xF8
word_36B1E:	.word 1			/*  DATA XREF: ROM:00036AA6o */
		.byte  0xF8,   5,	  0, 0x1A, 0xFF, 0xF8
word_36B26:	.word 1			/*  DATA XREF: ROM:00036AA6o */
		.byte  0xF8,   5,	  0, 0x1E, 0xFF, 0xF8
word_36B2E:	.word 1			/*  DATA XREF: ROM:00036AA6o */
		.byte  0xF8,   5,	0x60, 0x22, 0xFF, 0xF8
word_36B36:	.word 1			/*  DATA XREF: ROM:00036AA6o */
		.byte  0xF8,   5,	0x78, 0x22, 0xFF, 0xF8
word_36B3E:	.word 1			/*  DATA XREF: ROM:00036AA6o */
		.byte  0xF8,   5,	0x68, 0x22, 0xFF, 0xF8
word_36B46:	.word 1			/*  DATA XREF: ROM:00036AA6o */
		.byte  0xF8,   5,	0x70, 0x22, 0xFF, 0xF8
word_36B4E:	.word 1			/*  DATA XREF: ROM:00036AA6o */
		.byte  0xF8,   5,	  0, 0x26, 0xFF, 0xF8
word_36B56:	.word 1			/*  DATA XREF: ROM:00036AA6o */
		.byte  0xF8,   5,	0x18, 0x26, 0xFF, 0xF8
word_36B5E:	.word 1			/*  DATA XREF: ROM:00036AA6o */
		.byte  0xF8,   5,	  8, 0x26, 0xFF, 0xF8
word_36B66:	.word 1			/*  DATA XREF: ROM:00036AA6o */
		.byte  0xF8,   5,	0x10, 0x26, 0xFF, 0xF8
word_36B6E:	.word 1			/*  DATA XREF: ROM:00036AA6o */
		.byte  0xF8,   5,	  0, 0x2A, 0xFF, 0xF8
word_36B76:	.word 1			/*  DATA XREF: ROM:00036AA6o */
		.byte  0xF8,   5,	  0, 0x36, 0xFF, 0xF8
word_36B7E:	.word 1			/*  DATA XREF: ROM:00036AA6o */
		.byte  0xF8,   5,	  0, 0x2E, 0xFF, 0xF8
word_36B86:	.word 1			/*  DATA XREF: ROM:00036AA6o */
		.byte  0xF8,   5,	0x10, 0x32, 0xFF, 0xF8
word_36B8E:	.word 1			/*  DATA XREF: ROM:00036AA6o */
		.byte  0xF8,   5,	0x18, 0x2A, 0xFF, 0xF8
word_36B96:	.word 1			/*  DATA XREF: ROM:00036AA6o */
		.byte  0xF8,   5,	0x18, 0x36, 0xFF, 0xF8
word_36B9E:	.word 1			/*  DATA XREF: ROM:00036AA6o */
		.byte  0xF8,   5,	0x18, 0x2E, 0xFF, 0xF8
word_36BA6:	.word 1			/*  DATA XREF: ROM:00036AA6o */
		.byte  0xF8,   5,	  8, 0x32, 0xFF, 0xF8
word_36BAE:	.word 1			/*  DATA XREF: ROM:00036AA6o */
		.byte  0xF8,   5,	0x68, 0x10, 0xFF, 0xF8
word_36BB6:	.word 0			/*  DATA XREF: ROM:00036AA6o */
word_36BB8:	.word 1			/*  DATA XREF: ROM:00036AA6o */
		.byte  0xF8,   5,	  3, 0x76, 0xFF, 0xF8
word_36BC0:	.word 1			/*  DATA XREF: ROM:00036AA6o */
		.byte  0xF8,   5,	  3, 0x7A, 0xFF, 0xF8
word_36BC8:	.word 1			/*  DATA XREF: ROM:00036AA6o */
		.byte  0xF8,   5,	  3, 0x7E, 0xFF, 0xF8
word_36BD0:	.word 1			/*  DATA XREF: ROM:00036AA6o */
		.byte  0xF8,   5,	  3, 0x82, 0xFF, 0xF8
word_36BD8:	.word 1			/*  DATA XREF: ROM:00036AA6o */
		.byte  0xF8,   5,	  3, 0x86, 0xFF, 0xF8
