Map_370D6:		.word word_370EA-Map_370D6
		.word word_370F2-Map_370D6
		.word word_370FA-Map_370D6
		.word word_37102-Map_370D6
		.word word_3710A-Map_370D6
		.word word_37112-Map_370D6
		.word word_3711A-Map_370D6
		.word word_37122-Map_370D6
		.word word_3712A-Map_370D6
		.word word_37132-Map_370D6
word_370EA:	.word 1			
		.byte  0xF4,   6,	  0,   0, 0xFF, 0xF8
word_370F2:	.word 1			
		.byte  0xF4,   6,	  0,   6, 0xFF, 0xF8
word_370FA:	.word 1			
		.byte  0xF4,   6,	  0,  0xC, 0xFF, 0xF8
word_37102:	.word 1			
		.byte  0xF4,   6,	  0, 0x12, 0xFF, 0xF8
word_3710A:	.word 1			
		.byte  0xF4,   6,	  0, 0x18, 0xFF, 0xF8
word_37112:	.word 1			
		.byte  0xF4,   6,	  0, 0x1E, 0xFF, 0xF8
word_3711A:	.word 1			
		.byte  0xF4,   6,	  0, 0x24, 0xFF, 0xF8
word_37122:	.word 1			
		.byte  0xF4,   6,	  0, 0x2A, 0xFF, 0xF8
word_3712A:	.word 1			
		.byte  0xF4,   6,	  0, 0x30, 0xFF, 0xF8
word_37132:	.word 1			
		.byte  0xF4,   6,	  0, 0x36, 0xFF, 0xF8
