Map_380C6:		.word word_380D0-Map_380C6
		.word word_380D8-Map_380C6
		.word word_380E0-Map_380C6
		.word word_380E8-Map_380C6
		.word word_380F0-Map_380C6
word_380D0:	.word 1			
		.byte  0xFC,   0,	  0,   0, 0xFF, 0xFC
word_380D8:	.word 1			
		.byte  0xFC,   0,	  0,   1, 0xFF, 0xFC
word_380E0:	.word 1			
		.byte  0xFC,   0,	  0,   2, 0xFF, 0xFC
word_380E8:	.word 1			
		.byte  0xFC,   0,	  0,   3, 0xFF, 0xFC
word_380F0:	.word 1			
		.byte  0xFC,   0,	  0,   4, 0xFF, 0xFC
