DPLC_66B10:		.word word_66B18-DPLC_66B10
		.word word_66B1E-DPLC_66B10
		.word word_66B24-DPLC_66B10
		.word word_66B2A-DPLC_66B10
word_66B18:	.word 1			/* DATA XREF: ROM:00066B10o*/
		.word 5
		.word 0x6B
word_66B1E:	.word 1			/* DATA XREF: ROM:00066B10o*/
		.word 0x122
		.word 0x15F
word_66B24:	.word 1			/* DATA XREF: ROM:00066B10o*/
		.word 0x251
		.word 0x27F
word_66B2A:	.word 1			/* DATA XREF: ROM:00066B10o*/
		.word 5
		.word 0x37B
