DPLC_673D8:		.word word_673E2-DPLC_673D8
		.word word_673EC-DPLC_673D8
		.word word_673F6-DPLC_673D8
		.word word_67402-DPLC_673D8
		.word word_67408-DPLC_673D8
word_673E2:	.word 3			
		.word 2
		.word 0x33
		.word 0x71
		.word 0x93
word_673EC:	.word 3			
		.word 2
		.word 0xD3
		.word 0x111
		.word 0x133
word_673F6:	.word 4			
		.word 0x172
		.word 0x1A3
		.word 0x1E1
		.word 0x200
		.word 0x213
word_67402:	.word 1			
		.word 0x258
		.word 0x2E0
word_67408:	.word 3			
		.word 2
		.word 0x2F3
		.word 0x71
		.word 0x93
