DPLC_66BDA:		.word word_66BE8-DPLC_66BDA
		.word word_66BF0-DPLC_66BDA
		.word word_66BF6-DPLC_66BDA
		.word word_66BFC-DPLC_66BDA
		.word word_66C02-DPLC_66BDA
		.word word_66C08-DPLC_66BDA
		.word word_66C0C-DPLC_66BDA
word_66BE8:	.word 2			/* DATA XREF: ROM:00066BDAo*/
		.word 0
		.word 0x15
		.word 0x77
word_66BF0:	.word 1			/* DATA XREF: ROM:00066BDAo*/
		.word 0xF1
		.word 0x11B
word_66BF6:	.word 1			/* DATA XREF: ROM:00066BDAo*/
		.word 0x1D5
		.word 0x237
word_66BFC:	.word 1			/* DATA XREF: ROM:00066BDAo*/
		.word 0x2B2
		.word 0x2E7
word_66C02:	.word 1			/* DATA XREF: ROM:00066BDAo*/
		.word 0x362
		.word 0x397
word_66C08:	.word 0			/* DATA XREF: ROM:00066BDAo*/
		.word 0x41B
word_66C0C:	.word 1			/* DATA XREF: ROM:00066BDAo*/
		.word 0x4DB
		.word 0x590
