Map_67352:		.word word_6735C-Map_67352
		.word word_67376-Map_67352
		.word word_67390-Map_67352
		.word word_673B0-Map_67352
		.word word_673BE-Map_67352
word_6735C:	.word 4			
		.byte  0xF4,   2,	  0,   0, 0xFF, 0xEC
		.byte  0xF4,   5,	  0,   3, 0xFF, 0xF4
		.byte	4,   4,	  0,   7, 0xFF, 0xF4
		.byte  0xFC,   5,	  0,   9,   0,	 4
word_67376:	.word 4			
		.byte  0xF4,   2,	  0,   0, 0xFF, 0xEC
		.byte  0xF4,   5,	  0,   3, 0xFF, 0xF4
		.byte	4,   4,	  0,   7, 0xFF, 0xF4
		.byte  0xFC,   5,	  0,   9,   0,	 4
word_67390:	.word 5			
		.byte  0xF4,   2,	  0,   0, 0xFF, 0xEC
		.byte  0xF4,   5,	  0,   3, 0xFF, 0xF4
		.byte	4,   4,	  0,   7, 0xFF, 0xF4
		.byte  0xF4,   0,	  0,   9,   0,	 4
		.byte  0xFC,   5,	  0,  0xA,   0,	 4
word_673B0:	.word 2			
		.byte  0xF4,  0xA,	  0,   0, 0xFF, 0xF4
		.byte	4,   0,	  0,   9,   0,	0xC
word_673BE:	.word 4			
		.byte  0xF4,   2,	  0,   0, 0xFF, 0xEC
		.byte  0xF4,   5,	  0,   3, 0xFF, 0xF4
		.byte	4,   4,	  0,   7, 0xFF, 0xF4
		.byte  0xFC,   5,	  0,   9,   0,	 4
