Map_66B6A:		.word word_66B78-Map_66B6A
		.word word_66B8C-Map_66B6A
		.word word_66B9A-Map_66B6A
		.word word_66BA8-Map_66B6A
		.word word_66BB6-Map_66B6A
		.word word_66BC4-Map_66B6A
		.word word_66BCC-Map_66B6A
word_66B78:	.word 3			
		.byte	4,   0,	  0,   0, 0xFF, 0xE6
		.byte  0xF4,   9,	  0,   1, 0xFF, 0xEE
		.byte	4,  0xD,	  0,   7, 0xFF, 0xEE
word_66B8C:	.word 2			
		.byte  0xF4,   4,	  0,   0, 0xFF, 0xF5
		.byte  0xFC,  0xE,	  0,   2, 0xFF, 0xED
word_66B9A:	.word 2			
		.byte  0xF4,   9,	  0,   0, 0xFF, 0xED
		.byte	4,  0xD,	  0,   6, 0xFF, 0xED
word_66BA8:	.word 2			
		.byte  0xFC,   8,	  0,   0, 0xFF, 0xED
		.byte	4,  0xD,	  0,   3, 0xFF, 0xED
word_66BB6:	.word 2			
		.byte  0xFC,   8,	  0,   0, 0xFF, 0xED
		.byte	4,  0xD,	  0,   3, 0xFF, 0xED
word_66BC4:	.word 1			
		.byte  0xFC,  0xE,	  0,   0, 0xFF, 0xED
word_66BCC:	.word 2			
		.byte  0xFC,  0xE,	  0,   0, 0xFF, 0xEE
		.byte	4,   0,	  0,  0xC,   0,	0xE
