/*  Sandworm mappings */
		.word word_186D22-Map_Sandworm
		.word word_186D2A-Map_Sandworm
		.word word_186D32-Map_Sandworm
		.word word_186D3A-Map_Sandworm
		.word word_186D42-Map_Sandworm
		.word word_186D4A-Map_Sandworm
		.word word_186D52-Map_Sandworm
		.word word_186D5A-Map_Sandworm
		.word word_186D62-Map_Sandworm
word_186D22:	.word 1			/*  DATA XREF: ROM:00186D10o */
		.byte  0xF4,   6,	  0,   0, 0xFF, 0xF8
word_186D2A:	.word 1			/*  DATA XREF: ROM:00186D10o */
		.byte  0xF8,   5,	  0,   6, 0xFF, 0xF8
word_186D32:	.word 1			/*  DATA XREF: ROM:00186D10o */
		.byte  0xF4,   6,	  0,  0xA, 0xFF, 0xF8
word_186D3A:	.word 1			/*  DATA XREF: ROM:00186D10o */
		.byte  0xFC,   4,	  0, 0x10, 0xFF, 0xF8
word_186D42:	.word 1			/*  DATA XREF: ROM:00186D10o */
		.byte  0xFC,   4,	  8, 0x10, 0xFF, 0xF8
word_186D4A:	.word 1			/*  DATA XREF: ROM:00186D10o */
		.byte  0xF0,   3,	  0, 0x12, 0xFF, 0xFC
word_186D52:	.word 1			/*  DATA XREF: ROM:00186D10o */
		.byte  0xF0,   3,	  8, 0x12, 0xFF, 0xFC
word_186D5A:	.word 1			/*  DATA XREF: ROM:00186D10o */
		.byte  0xF0,   3,	  0, 0x16, 0xFF, 0xFC
word_186D62:	.word 1			/*  DATA XREF: ROM:00186D10o */
		.byte  0xF0,   3,	  0, 0x1A, 0xFF, 0xFC
