Map_6068E:		.word word_606C4-Map_6068E
		.word word_606CC-Map_6068E
		.word word_606D4-Map_6068E
		.word word_606DC-Map_6068E
		.word word_606E4-Map_6068E
		.word word_606EC-Map_6068E
		.word word_606F4-Map_6068E
		.word word_606FC-Map_6068E
		.word word_60704-Map_6068E
		.word word_6070C-Map_6068E
		.word word_60714-Map_6068E
		.word word_6071C-Map_6068E
		.word word_60724-Map_6068E
		.word word_6072C-Map_6068E
		.word word_60734-Map_6068E
		.word word_6073C-Map_6068E
		.word word_60744-Map_6068E
		.word word_6074C-Map_6068E
		.word word_60754-Map_6068E
		.word word_6075C-Map_6068E
		.word word_60764-Map_6068E
		.word word_6076C-Map_6068E
		.word word_60774-Map_6068E
		.word word_6077C-Map_6068E
		.word word_60784-Map_6068E
		.word word_6078C-Map_6068E
		.word word_60794-Map_6068E
word_606C4:	.word 1			
		.byte  0xF8,  0xD,	  0,   0, 0xFF, 0xF0
word_606CC:	.word 1			
		.byte  0xF8,  0xD,	  0,   8, 0xFF, 0xF0
word_606D4:	.word 1			
		.byte  0xF8,  0xD,	  8,   0, 0xFF, 0xF0
word_606DC:	.word 1			
		.byte  0xF8,  0xD,	  8,   8, 0xFF, 0xF0
word_606E4:	.word 1			
		.byte  0xFC,   8,	  0, 0x10, 0xFF, 0xF4
word_606EC:	.word 1			
		.byte  0xFC,   8,	  0, 0x13, 0xFF, 0xF4
word_606F4:	.word 1			
		.byte  0xFC,   8,	  0, 0x16, 0xFF, 0xF4
word_606FC:	.word 1			
		.byte  0xFC,   8,	  0, 0x19, 0xFF, 0xF4
word_60704:	.word 1			
		.byte  0xFC,   8,	  0, 0x1C, 0xFF, 0xF4
word_6070C:	.word 1			
		.byte  0xFC,   8,	  0, 0x1F, 0xFF, 0xF4
word_60714:	.word 1			
		.byte  0xFC,   4,	  0, 0x22, 0xFF, 0xF8
word_6071C:	.word 1			
		.byte  0xFC,   4,	  0, 0x24, 0xFF, 0xF8
word_60724:	.word 1			
		.byte  0xFC,   4,	  0, 0x26, 0xFF, 0xF8
word_6072C:	.word 1			
		.byte  0xFC,   4,	  0, 0x28, 0xFF, 0xF8
word_60734:	.word 1			
		.byte  0xF0,   3,	  0, 0x2A, 0xFF, 0xFC
word_6073C:	.word 1			
		.byte  0xF0,   3,	  0, 0x2E, 0xFF, 0xFC
word_60744:	.word 1			
		.byte  0xF0,   3,	  0, 0x32, 0xFF, 0xFC
word_6074C:	.word 1			
		.byte  0xF0,   3,	  0, 0x36, 0xFF, 0xFC
word_60754:	.word 1			
		.byte  0xF4,   2,	  0, 0x2A, 0xFF, 0xFC
word_6075C:	.word 1			
		.byte  0xF4,   2,	  0, 0x2E, 0xFF, 0xFC
word_60764:	.word 1			
		.byte  0xF4,   2,	  0, 0x32, 0xFF, 0xFC
word_6076C:	.word 1			
		.byte 0xF4, 2, 0,	0x36, 0xFF, 0xFC
word_60774:	.word 1			
		.byte  0xFC,   0,	  0, 0x3A, 0xFF, 0xFC
word_6077C:	.word 1			
		.byte  0xFC,   0,	  0, 0x3B, 0xFF, 0xFC
word_60784:	.word 1			
		.byte  0xFC,   0,	  0, 0x3C, 0xFF, 0xFC
word_6078C:	.word 1			
		.byte  0xFC,   0,	  0, 0x3D, 0xFF, 0xFC
word_60794:	.word 0			
