DPLC_66EBA:		.word word_66ED4-DPLC_66EBA
		.word word_66ED8-DPLC_66EBA
		.word word_66EDE-DPLC_66EBA
		.word word_66EE6-DPLC_66EBA
		.word word_66EEE-DPLC_66EBA
		.word word_66EF6-DPLC_66EBA
		.word word_66EFE-DPLC_66EBA
		.word word_66F06-DPLC_66EBA
		.word word_66F0E-DPLC_66EBA
		.word word_66F16-DPLC_66EBA
		.word word_66F1E-DPLC_66EBA
		.word word_66F26-DPLC_66EBA
		.word word_66F2E-DPLC_66EBA
word_66ED4:	.word 0			/*  DATA XREF: ROM:00066EBAo */
		.word 1
word_66ED8:	.word 1			/*  DATA XREF: ROM:00066EBAo */
		.word 0x21
		.word 0x43
word_66EDE:	.word 2			/*  DATA XREF: ROM:00066EBAo */
		.word 0x82
		.word 0xB3
		.word 0xF2
word_66EE6:	.word 2			/*  DATA XREF: ROM:00066EBAo */
		.word 0x122
		.word 0x153
		.word 0x192
word_66EEE:	.word 2			/*  DATA XREF: ROM:00066EBAo */
		.word 0x1C1
		.word 0x1E3
		.word 0x225
word_66EF6:	.word 2			/*  DATA XREF: ROM:00066EBAo */
		.word 0x281
		.word 0x2A1
		.word 0x2CB
word_66EFE:	.word 2			/*  DATA XREF: ROM:00066EBAo */
		.word 0x382
		.word 0x3B1
		.word 0x3DB
word_66F06:	.word 2			/*  DATA XREF: ROM:00066EBAo */
		.word 0x492
		.word 0x4C5
		.word 0x525
word_66F0E:	.word 2			/*  DATA XREF: ROM:00066EBAo */
		.word 0x582
		.word 0x5B5
		.word 0x615
word_66F16:	.word 2			/*  DATA XREF: ROM:00066EBAo */
		.word 0x672
		.word 0x6A5
		.word 0x705
word_66F1E:	.word 2			/*  DATA XREF: ROM:00066EBAo */
		.word 0x672
		.word 0x765
		.word 0x7C5
word_66F26:	.word 2			/*  DATA XREF: ROM:00066EBAo */
		.word 0x822
		.word 0x855
		.word 0x8B5
word_66F2E:	.word 2			/*  DATA XREF: ROM:00066EBAo */
		.word 0x912
		.word 0x941
		.word 0x967
