Map_66CD6:		.word word_66CF0-Map_66CD6
		.word word_66CFE-Map_66CD6
		.word word_66D18-Map_66CD6
		.word word_66D3E-Map_66CD6
		.word word_66D64-Map_66CD6
		.word word_66D8A-Map_66CD6
		.word word_66DB0-Map_66CD6
		.word word_66DD6-Map_66CD6
		.word word_66DFC-Map_66CD6
		.word word_66E22-Map_66CD6
		.word word_66E48-Map_66CD6
		.word word_66E6E-Map_66CD6
		.word word_66E94-Map_66CD6
word_66CF0:	.word 2			
		.byte  0xFC,   4,	  0,   0, 0xFF, 0xF0
		.byte  0xFC,   4,	  8,   0,   0,	 0
word_66CFE:	.word 4			
		.byte  0xFC,   4,	  0,   0, 0xFF, 0xE0
		.byte  0xF4,   5,	  0,   2, 0xFF, 0xF0
		.byte  0xF4,   5,	  8,   2,   0,	 0
		.byte  0xFC,   4,	  8,   0,   0, 0x10
word_66D18:	.word 6			
		.byte  0xFC,   8,	  0,   0, 0xFF, 0xD0
		.byte  0xF4,   5,	  0,   3, 0xFF, 0xE8
		.byte  0xEC,   2,	  0,   7, 0xFF, 0xF8
		.byte  0xEC,   2,	  8,   7,   0,	 0
		.byte  0xF4,   5,	  8,   3,   0,	 8
		.byte  0xFC,   8,	  8,   0,   0, 0x18
word_66D3E:	.word 6			
		.byte  0xFC,   8,	  0,   0, 0xFF, 0xD0
		.byte  0xF4,   5,	  0,   3, 0xFF, 0xE8
		.byte  0xEC,   2,	  0,   7, 0xFF, 0xF8
		.byte  0xEC,   2,	  8,   7,   0,	 0
		.byte  0xF4,   5,	  8,   3,   0,	 8
		.byte  0xFC,   8,	  8,   0,   0, 0x18
word_66D64:	.word 6			
		.byte  0xFC,   4,	  0,   0, 0xFF, 0xD0
		.byte  0xF4,   5,	  0,   2, 0xFF, 0xE0
		.byte  0xEC,   6,	  0,   6, 0xFF, 0xF0
		.byte  0xEC,   6,	  8,   6,   0,	 0
		.byte  0xF4,   5,	  8,   2,   0, 0x10
		.byte  0xFC,   4,	  8,   0,   0, 0x20
word_66D8A:	.word 6			
		.byte  0xFC,   4,	  0,   0, 0xFF, 0xC8
		.byte  0xF4,   1,	  0,   2, 0xFF, 0xD8
		.byte  0xEC,  0xE,	  0,   4, 0xFF, 0xE0
		.byte  0xEC,  0xE,	  8,   4,   0,	 0
		.byte  0xF4,   1,	  8,   2,   0, 0x20
		.byte  0xFC,   4,	  8,   0,   0, 0x28
word_66DB0:	.word 6			
		.byte  0xFC,   8,	  0,   0, 0xFF, 0xC0
		.byte  0xF4,   1,	  0,   3, 0xFF, 0xD8
		.byte  0xEC,  0xE,	  0,   5, 0xFF, 0xE0
		.byte  0xEC,  0xE,	  8,   5,   0,	 0
		.byte  0xF4,   1,	  8,   3,   0, 0x20
		.byte  0xFC,   8,	  8,   0,   0, 0x28
word_66DD6:	.word 6			
		.byte  0xFC,   8,	  0,   0, 0xFF, 0xC0
		.byte  0xF4,   9,	  0,   3, 0xFF, 0xD8
		.byte  0xEC,   6,	  0,   9, 0xFF, 0xF0
		.byte  0xEC,   6,	  8,   9,   0,	 0
		.byte  0xF4,   9,	  8,   3,   0, 0x10
		.byte  0xFC,   8,	  8,   0,   0, 0x28
word_66DFC:	.word 6			
		.byte  0xFC,   8,	  0,   0, 0xFF, 0xC0
		.byte  0xF4,   9,	  0,   3, 0xFF, 0xD8
		.byte  0xEC,   6,	  0,   9, 0xFF, 0xF0
		.byte  0xEC,   6,	  8,   9,   0,	 0
		.byte  0xF4,   9,	  8,   3,   0, 0x10
		.byte  0xFC,   8,	  8,   0,   0, 0x28
word_66E22:	.word 6			
		.byte  0xFC,   8,	  0,   0, 0xFF, 0xC0
		.byte  0xF4,   9,	  0,   3, 0xFF, 0xD8
		.byte  0xEC,   6,	  0,   9, 0xFF, 0xF0
		.byte  0xEC,   6,	  8,   9,   0,	 0
		.byte  0xF4,   9,	  8,   3,   0, 0x10
		.byte  0xFC,   8,	  8,   0,   0, 0x28
word_66E48:	.word 6			
		.byte  0xFC,   8,	  0,   0, 0xFF, 0xC0
		.byte  0xF4,   9,	  0,   3, 0xFF, 0xD8
		.byte  0xEC,   6,	  0,   9, 0xFF, 0xF0
		.byte  0xEC,   6,	  8,   9,   0,	 0
		.byte  0xF4,   9,	  8,   3,   0, 0x10
		.byte  0xFC,   8,	  8,   0,   0, 0x28
word_66E6E:	.word 6			
		.byte  0xFC,   8,	  0,   0, 0xFF, 0xC0
		.byte  0xF4,   9,	  0,   3, 0xFF, 0xD8
		.byte  0xEC,   6,	  0,   9, 0xFF, 0xF0
		.byte  0xEC,   6,	  8,   9,   0,	 0
		.byte  0xF4,   9,	  8,   3,   0, 0x10
		.byte  0xFC,   8,	  8,   0,   0, 0x28
word_66E94:	.word 6			
		.byte  0xFC,   8,	  0,   0, 0xFF, 0xC0
		.byte  0xF4,   1,	  0,   3, 0xFF, 0xD8
		.byte  0xF4,  0xD,	  0,   5, 0xFF, 0xE0
		.byte  0xF4,  0xD,	  8,   5,   0,	 0
		.byte  0xF4,   1,	  8,   3,   0, 0x20
		.byte  0xFC,   8,	  8,   0,   0, 0x28
