Map_21DDEC:	.word Frame_21DDFC-Map_21DDEC /* ...*/
		.word Frame_21DE04-Map_21DDEC
		.word Frame_21DE0C-Map_21DDEC
		.word Frame_21DE04-Map_21DDEC
		.word Frame_21DE0C-Map_21DDEC
		.word Frame_21DE04-Map_21DDEC
		.word Frame_21DE0C-Map_21DDEC
		.word Frame_21DE14-Map_21DDEC
Frame_21DDFC:	.word 1
		.byte 0xF0, 0xF,  0, 0xE,0xFF,0xF0
Frame_21DE04:	.word 1
		.byte 0xF8,  5,  0,0x1E,0xFF,0xF8
Frame_21DE0C:	.word 1
		.byte 0xF8,  5,  0,0x22,0xFF,0xF8
Frame_21DE14:	.word 1
		.byte 0xFC,  0,0xFD,  0,0xFF,0xFC
