		.word word_3825A-Map_EMZDripper
		.word word_38262-Map_EMZDripper
		.word word_3826A-Map_EMZDripper
		.word word_38272-Map_EMZDripper
word_3825A:	.word 1			/*  DATA XREF: ROM:00038252o */
		.byte  0xFC,   4,	  0,   0, 0xFF, 0xF8
word_38262:	.word 1			/*  DATA XREF: ROM:00038252o */
		.byte  0xFC,   0,	  0,   2, 0xFF, 0xFC
word_3826A:	.word 1			/*  DATA XREF: ROM:00038252o */
		.byte  0xFC,   0,	  0,   3, 0xFF, 0xFC
word_38272:	.word 1			/*  DATA XREF: ROM:00038252o */
		.byte  0xFC,   0,	  0,   4, 0xFF, 0xFC
