/*  Knuckles pattern load cues */
PLC_14BD0A:		.word word_14BF00-PLC_14BD0A/*  0 */
		.word word_14BF02-PLC_14BD0A/*  1 */
		.word word_14BF0C-PLC_14BD0A/*  2 */
		.word word_14BF14-PLC_14BD0A/*  3 */
		.word word_14BF1C-PLC_14BD0A/*  4 */
		.word word_14BF22-PLC_14BD0A/*  5 */
		.word word_14BF2C-PLC_14BD0A/*  6 */
		.word word_14BF36-PLC_14BD0A/*  7 */
		.word word_14BF3E-PLC_14BD0A/*  8 */
		.word word_14BF48-PLC_14BD0A/*  9 */
		.word word_14BF50-PLC_14BD0A/*  10 */
		.word word_14BF58-PLC_14BD0A/*  11 */
		.word word_14BF60-PLC_14BD0A/*  12 */
		.word word_14BF6A-PLC_14BD0A/*  13 */
		.word word_14BF72-PLC_14BD0A/*  14 */
		.word word_14BF78-PLC_14BD0A/*  15 */
		.word word_14BF80-PLC_14BD0A/*  16 */
		.word word_14BF88-PLC_14BD0A/*  17 */
		.word word_14BF92-PLC_14BD0A/*  18 */
		.word word_14BF9C-PLC_14BD0A/*  19 */
		.word word_14BFA4-PLC_14BD0A/*  20 */
		.word word_14BFAA-PLC_14BD0A/*  21 */
		.word word_14BFB4-PLC_14BD0A/*  22 */
		.word word_14BFBE-PLC_14BD0A/*  23 */
		.word word_14BFC6-PLC_14BD0A/*  24 */
		.word word_14BFD0-PLC_14BD0A/*  25 */
		.word word_14BFD8-PLC_14BD0A/*  26 */
		.word word_14BFE0-PLC_14BD0A/*  27 */
		.word word_14BFE8-PLC_14BD0A/*  28 */
		.word word_14BFF0-PLC_14BD0A/*  29 */
		.word word_14BFF6-PLC_14BD0A/*  30 */
		.word word_14BFFC-PLC_14BD0A/*  31 */
		.word word_14C004-PLC_14BD0A/*  32 */
		.word word_14C00C-PLC_14BD0A/*  33 */
		.word word_14C012-PLC_14BD0A/*  34 */
		.word word_14C018-PLC_14BD0A/*  35 */
		.word word_14C01E-PLC_14BD0A/*  36 */
		.word word_14C024-PLC_14BD0A/*  37 */
		.word word_14C02E-PLC_14BD0A/*  38 */
		.word word_14C038-PLC_14BD0A/*  39 */
		.word word_14C040-PLC_14BD0A/*  40 */
		.word word_14C048-PLC_14BD0A/*  41 */
		.word word_14C04E-PLC_14BD0A/*  42 */
		.word word_14C054-PLC_14BD0A/*  43 */
		.word word_14C05A-PLC_14BD0A/*  44 */
		.word word_14C060-PLC_14BD0A/*  45 */
		.word word_14C06A-PLC_14BD0A/*  46 */
		.word word_14C074-PLC_14BD0A/*  47 */
		.word word_14C07C-PLC_14BD0A/*  48 */
		.word word_14C084-PLC_14BD0A/*  49 */
		.word word_14C08E-PLC_14BD0A/*  50 */
		.word word_14C094-PLC_14BD0A/*  51 */
		.word word_14C09C-PLC_14BD0A/*  52 */
		.word word_14C0A4-PLC_14BD0A/*  53 */
		.word word_14C0AC-PLC_14BD0A/*  54 */
		.word word_14C0B4-PLC_14BD0A/*  55 */
		.word word_14C0BA-PLC_14BD0A/*  56 */
		.word word_14C0C2-PLC_14BD0A/*  57 */
		.word word_14C0C8-PLC_14BD0A/*  58 */
		.word word_14C0CE-PLC_14BD0A/*  59 */
		.word word_14C0D6-PLC_14BD0A/*  60 */
		.word word_14C0DC-PLC_14BD0A/*  61 */
		.word word_14C0E2-PLC_14BD0A/*  62 */
		.word word_14C0EA-PLC_14BD0A/*  63 */
		.word word_14C0F0-PLC_14BD0A/*  64 */
		.word word_14C0F8-PLC_14BD0A/*  65 */
		.word word_14C0FE-PLC_14BD0A/*  66 */
		.word word_14C108-PLC_14BD0A/*  67 */
		.word word_14C10E-PLC_14BD0A/*  68 */
		.word word_14C112-PLC_14BD0A/*  69 */
		.word word_14C11A-PLC_14BD0A/*  70 */
		.word word_14C120-PLC_14BD0A/*  71 */
		.word word_14C126-PLC_14BD0A/*  72 */
		.word word_14C12C-PLC_14BD0A/*  73 */
		.word word_14C134-PLC_14BD0A/*  74 */
		.word word_14C13C-PLC_14BD0A/*  75 */
		.word word_14C142-PLC_14BD0A/*  76 */
		.word word_14C148-PLC_14BD0A/*  77 */
		.word word_14C14C-PLC_14BD0A/*  78 */
		.word word_14C154-PLC_14BD0A/*  79 */
		.word word_14C15A-PLC_14BD0A/*  80 */
		.word word_14C162-PLC_14BD0A/*  81 */
		.word word_14C16A-PLC_14BD0A/*  82 */
		.word word_14C172-PLC_14BD0A/*  83 */
		.word word_14C17A-PLC_14BD0A/*  84 */
		.word word_14C180-PLC_14BD0A/*  85 */
		.word word_14C188-PLC_14BD0A/*  86 */
		.word word_14C18E-PLC_14BD0A/*  87 */
		.word word_14C194-PLC_14BD0A/*  88 */
		.word word_14C19A-PLC_14BD0A/*  89 */
		.word word_14C1A2-PLC_14BD0A/*  90 */
		.word word_14C1A8-PLC_14BD0A/*  91 */
		.word word_14C1AE-PLC_14BD0A/*  92 */
		.word word_14C1B4-PLC_14BD0A/*  93 */
		.word word_14C1BA-PLC_14BD0A/*  94 */
		.word word_14C1C0-PLC_14BD0A/*  95 */
		.word word_14C1C6-PLC_14BD0A/*  96 */
		.word word_14C1CA-PLC_14BD0A/*  97 */
		.word word_14C1CE-PLC_14BD0A/*  98 */
		.word word_14C1D6-PLC_14BD0A/*  99 */
		.word word_14C1DC-PLC_14BD0A/*  100 */
		.word word_14C1E2-PLC_14BD0A/*  101 */
		.word word_14C1E8-PLC_14BD0A/*  102 */
		.word word_14C1EE-PLC_14BD0A/*  103 */
		.word word_14C1F2-PLC_14BD0A/*  104 */
		.word word_14C1F6-PLC_14BD0A/*  105 */
		.word word_14C1FE-PLC_14BD0A/*  106 */
		.word word_14C204-PLC_14BD0A/*  107 */
		.word word_14C20A-PLC_14BD0A/*  108 */
		.word word_14C212-PLC_14BD0A/*  109 */
		.word word_14C218-PLC_14BD0A/*  110 */
		.word word_14C220-PLC_14BD0A/*  111 */
		.word word_14C22A-PLC_14BD0A/*  112 */
		.word word_14C230-PLC_14BD0A/*  113 */
		.word word_14C234-PLC_14BD0A/*  114 */
		.word word_14C23A-PLC_14BD0A/*  115 */
		.word word_14C242-PLC_14BD0A/*  116 */
		.word word_14C248-PLC_14BD0A/*  117 */
		.word word_14C24E-PLC_14BD0A/*  118 */
		.word word_14C256-PLC_14BD0A/*  119 */
		.word word_14C25C-PLC_14BD0A/*  120 */
		.word word_14C264-PLC_14BD0A/*  121 */
		.word word_14C26E-PLC_14BD0A/*  122 */
		.word word_14C276-PLC_14BD0A/*  123 */
		.word word_14C280-PLC_14BD0A/*  124 */
		.word word_14C288-PLC_14BD0A/*  125 */
		.word word_14C292-PLC_14BD0A/*  126 */
		.word word_14C29A-PLC_14BD0A/*  127 */
		.word word_14C2A4-PLC_14BD0A/*  128 */
		.word word_14C2AC-PLC_14BD0A/*  129 */
		.word word_14C2B6-PLC_14BD0A/*  130 */
		.word word_14C2BE-PLC_14BD0A/*  131 */
		.word word_14C2C4-PLC_14BD0A/*  132 */
		.word word_14C2CE-PLC_14BD0A/*  133 */
		.word word_14C2D8-PLC_14BD0A/*  134 */
		.word word_14C2E0-PLC_14BD0A/*  135 */
		.word word_14C2E8-PLC_14BD0A/*  136 */
		.word word_14C2F0-PLC_14BD0A/*  137 */
		.word word_14C2F8-PLC_14BD0A/*  138 */
		.word word_14C300-PLC_14BD0A/*  139 */
		.word word_14C308-PLC_14BD0A/*  140 */
		.word word_14C310-PLC_14BD0A/*  141 */
		.word word_14C31A-PLC_14BD0A/*  142 */
		.word word_14C322-PLC_14BD0A/*  143 */
		.word word_14C32A-PLC_14BD0A/*  144 */
		.word word_14C334-PLC_14BD0A/*  145 */
		.word word_14C33A-PLC_14BD0A/*  146 */
		.word word_14C342-PLC_14BD0A/*  147 */
		.word word_14C34A-PLC_14BD0A/*  148 */
		.word word_14C354-PLC_14BD0A/*  149 */
		.word word_14C35E-PLC_14BD0A/*  150 */
		.word word_14C362-PLC_14BD0A/*  151 */
		.word word_14C366-PLC_14BD0A/*  152 */
		.word word_14C36A-PLC_14BD0A/*  153 */
		.word word_14C36E-PLC_14BD0A/*  154 */
		.word word_14C372-PLC_14BD0A/*  155 */
		.word word_14C378-PLC_14BD0A/*  156 */
		.word word_14C37E-PLC_14BD0A/*  157 */
		.word word_14C384-PLC_14BD0A/*  158 */
		.word word_14C38E-PLC_14BD0A/*  159 */
		.word word_14C398-PLC_14BD0A/*  160 */
		.word word_14C3A2-PLC_14BD0A/*  161 */
		.word word_14C3AC-PLC_14BD0A/*  162 */
		.word word_14C3B6-PLC_14BD0A/*  163 */
		.word word_14C3C0-PLC_14BD0A/*  164 */
		.word word_14C3CA-PLC_14BD0A/*  165 */
		.word word_14C3D4-PLC_14BD0A/*  166 */
		.word word_14C3DE-PLC_14BD0A/*  167 */
		.word word_14C3E8-PLC_14BD0A/*  168 */
		.word word_14C3F2-PLC_14BD0A/*  169 */
		.word word_14C3FC-PLC_14BD0A/*  170 */
		.word word_14C406-PLC_14BD0A/*  171 */
		.word word_14C410-PLC_14BD0A/*  172 */
		.word word_14C41A-PLC_14BD0A/*  173 */
		.word word_14C424-PLC_14BD0A/*  174 */
		.word word_14C42C-PLC_14BD0A/*  175 */
		.word word_14C434-PLC_14BD0A/*  176 */
		.word word_14C43C-PLC_14BD0A/*  177 */
		.word word_14C442-PLC_14BD0A/*  178 */
		.word word_14C44A-PLC_14BD0A/*  179 */
		.word word_14C450-PLC_14BD0A/*  180 */
		.word word_14C458-PLC_14BD0A/*  181 */
		.word word_14C460-PLC_14BD0A/*  182 */
		.word word_14C468-PLC_14BD0A/*  183 */
		.word word_14C46E-PLC_14BD0A/*  184 */
		.word word_14C472-PLC_14BD0A/*  185 */
		.word word_14C478-PLC_14BD0A/*  186 */
		.word word_14C480-PLC_14BD0A/*  187 */
		.word word_14C484-PLC_14BD0A/*  188 */
		.word word_14C488-PLC_14BD0A/*  189 */
		.word word_14C492-PLC_14BD0A/*  190 */
		.word word_14C498-PLC_14BD0A/*  191 */
		.word word_14C4A0-PLC_14BD0A/*  192 */
		.word word_14C4A8-PLC_14BD0A/*  193 */
		.word word_14C4AE-PLC_14BD0A/*  194 */
		.word word_14C4B2-PLC_14BD0A/*  195 */
		.word word_14C4B8-PLC_14BD0A/*  196 */
		.word word_14C4C0-PLC_14BD0A/*  197 */
		.word word_14C4C6-PLC_14BD0A/*  198 */
		.word word_14C4CE-PLC_14BD0A/*  199 */
		.word word_14C4D2-PLC_14BD0A/*  200 */
		.word word_14C4DA-PLC_14BD0A/*  201 */
		.word word_14C4E0-PLC_14BD0A/*  202 */
		.word word_14C4EA-PLC_14BD0A/*  203 */
		.word word_14C4F4-PLC_14BD0A/*  204 */
		.word word_14C4FE-PLC_14BD0A/*  205 */
		.word word_14C506-PLC_14BD0A/*  206 */
		.word word_14C510-PLC_14BD0A/*  207 */
		.word word_14C51A-PLC_14BD0A/*  208 */
		.word word_14C526-PLC_14BD0A/*  209 */
		.word word_14C530-PLC_14BD0A/*  210 */
		.word word_14C536-PLC_14BD0A/*  211 */
		.word word_14C53C-PLC_14BD0A/*  212 */
		.word word_14C542-PLC_14BD0A/*  213 */
		.word word_14C548-PLC_14BD0A/*  214 */
		.word word_14C54E-PLC_14BD0A/*  215 */
		.word word_14C554-PLC_14BD0A/*  216 */
		.word word_14C55E-PLC_14BD0A/*  217 */
		.word word_14C56A-PLC_14BD0A/*  218 */
		.word word_14C574-PLC_14BD0A/*  219 */
		.word word_14C57E-PLC_14BD0A/*  220 */
		.word word_14C586-PLC_14BD0A/*  221 */
		.word word_14C58E-PLC_14BD0A/*  222 */
		.word word_14C598-PLC_14BD0A/*  223 */
		.word word_14C5A0-PLC_14BD0A/*  224 */
		.word word_14C5A8-PLC_14BD0A/*  225 */
		.word word_14C5AC-PLC_14BD0A/*  226 */
		.word word_14C5B2-PLC_14BD0A/*  227 */
		.word word_14C5B8-PLC_14BD0A/*  228 */
		.word word_14C5C2-PLC_14BD0A/*  229 */
		.word word_14C5C8-PLC_14BD0A/*  230 */
		.word word_14C5D0-PLC_14BD0A/*  231 */
		.word word_14C5D8-PLC_14BD0A/*  232 */
		.word word_14C5E2-PLC_14BD0A/*  233 */
		.word word_14C5EA-PLC_14BD0A/*  234 */
		.word word_14C5F0-PLC_14BD0A/*  235 */
		.word word_14C5F8-PLC_14BD0A/*  236 */
		.word word_14C600-PLC_14BD0A/*  237 */
		.word word_14C600-PLC_14BD0A/*  238 */
		.word word_14C608-PLC_14BD0A/*  239 */
		.word word_14C610-PLC_14BD0A/*  240 */
		.word word_14C618-PLC_14BD0A/*  241 */
		.word word_14C61E-PLC_14BD0A/*  242 */
		.word word_14C618-PLC_14BD0A/*  243 */
		.word word_14C624-PLC_14BD0A/*  244 */
		.word word_14C62C-PLC_14BD0A/*  245 */
		.word word_14C634-PLC_14BD0A/*  246 */
		.word word_14C63A-PLC_14BD0A/*  247 */
		.word word_14C644-PLC_14BD0A/*  248 */
		.word word_14C63A-PLC_14BD0A/*  249 */
		.word word_14C64C-PLC_14BD0A/*  250 */
word_14BF00:	.word 0			/*  DATA XREF: ROM:0014BD0Ao */
word_14BF02:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x2000
		.word 0xB003
		.word 0x200F
		.word 0x1012
word_14BF0C:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x1014
		.word 0xF016
		.word 0x2026
word_14BF14:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x5029
		.word 0x702F
		.word 0x1037
word_14BF1C:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x5039
		.word 0xB03F
word_14BF22:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x204B
		.word 0xB04E
		.word 0x105A
		.word 0x305C
word_14BF2C:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x1060
		.word 0x2062
		.word 0xB065
		.word 0x1071
word_14BF36:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x1073
		.word 0xB075
		.word 0x2081
word_14BF3E:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x2084
		.word 0x2087
		.word 0xB08A
		.word 0x96
word_14BF48:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xB097
		.word 0x20A3
		.word 0x30A6
word_14BF50:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xF0AA
		.word 0x20BA
		.word 0x10BD
word_14BF58:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x20BF
		.word 0xB0C2
		.word 0xCE
word_14BF60:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x20CF
		.word 0x70D2
		.word 0x20DA
		.word 0x10DD
word_14BF6A:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xF0DF
		.word 0x10EF
		.word 0x10F1
word_14BF72:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xB0F3
		.word 0x30FF
word_14BF78:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x2103
		.word 0xB106
		.word 0x112
word_14BF80:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x2113
		.word 0xB116
		.word 0x1122
word_14BF88:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x3124
		.word 0xB128
		.word 0x134
		.word 0x2135
word_14BF92:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x3138
		.word 0x713C
		.word 0x144
		.word 0x7145
word_14BF9C:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xB14D
		.word 0x1159
		.word 0x115B
word_14BFA4:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x515D
		.word 0xB163
word_14BFAA:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x216F
		.word 0xB172
		.word 0x17E
		.word 0x217F
word_14BFB4:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x2182
		.word 0xB185
		.word 0x1191
		.word 0x1193
word_14BFBE:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x2195
		.word 0xB198
		.word 0x11A4
word_14BFC6:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x11A6
		.word 0xB1A8
		.word 0x21B4
		.word 0x1B7
word_14BFD0:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x21B8
		.word 0xB1BB
		.word 0x31C7
word_14BFD8:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x21CB
		.word 0xF1CE
		.word 0x11DE
word_14BFE0:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x21E0
		.word 0xB1E3
		.word 0x1EF
word_14BFE8:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x11F0
		.word 0xB1F2
		.word 0x11FE
word_14BFF0:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xF200
		.word 0x5210
word_14BFF6:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xB216
		.word 0x3222
word_14BFFC:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x2226
		.word 0xB229
		.word 0x235
word_14C004:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x2236
		.word 0xB239
		.word 0x1245
word_14C00C:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x2247
		.word 0xF24A
word_14C012:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x225A
		.word 0xF25D
word_14C018:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x2247
		.word 0xF26D
word_14C01E:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x227D
		.word 0xF280
word_14C024:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x2293
		.word 0xB296
		.word 0x12A2
		.word 0x22A4
word_14C02E:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x22A7
		.word 0xB2AA
		.word 0x12B6
		.word 0x22B8
word_14C038:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x22BB
		.word 0x72BE
		.word 0x52C6
word_14C040:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x22CC
		.word 0xF2CF
		.word 0x12DF
word_14C048:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x22E1
		.word 0xF2E4
word_14C04E:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x22F4
		.word 0xF2F7
word_14C054:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x2307
		.word 0xF30A
word_14C05A:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x231A
		.word 0xF31D
word_14C060:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x132D
		.word 0xB32F
		.word 0x133B
		.word 0x333D
word_14C06A:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x3341
		.word 0xB345
		.word 0x1351
		.word 0x1353
word_14C074:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xB355
		.word 0x1361
		.word 0x2363
word_14C07C:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xF366
		.word 0x2376
		.word 0x1379
word_14C084:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x237B
		.word 0x737E
		.word 0x2386
		.word 0x1389
word_14C08E:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x138B
		.word 0xF38D
word_14C094:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x539D
		.word 0x33A3
		.word 0x23A7
word_14C09C:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x23AA
		.word 0xB3AD
		.word 0x3B9
word_14C0A4:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x23BA
		.word 0x73BD
		.word 0x23C5
word_14C0AC:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x13C8
		.word 0x73CA
		.word 0x53D2
word_14C0B4:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xF3D8
		.word 0x23E8
word_14C0BA:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x33EB
		.word 0x33EF
		.word 0x53F3
word_14C0C2:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xB3F9
		.word 0x2405
word_14C0C8:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x7408
		.word 0x2410
word_14C0CE:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x7413
		.word 0x241B
		.word 0x341E
word_14C0D6:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x8422
		.word 0x742B
word_14C0DC:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xB433
		.word 0x243F
word_14C0E2:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x2442
		.word 0x7445
		.word 0x144D
word_14C0EA:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x744F
		.word 0x2457
word_14C0F0:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x245A
		.word 0x745D
		.word 0x1465
word_14C0F8:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xB467
		.word 0x5473
word_14C0FE:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x3479
		.word 0x247D
		.word 0x3480
		.word 0x5484
word_14C108:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xB48A
		.word 0x2496
word_14C10E:	.word 1			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xF499
word_14C112:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x24A9
		.word 0x74AC
		.word 0x4B4
word_14C11A:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x54B5
		.word 0x74BB
word_14C120:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x54C3
		.word 0xB4C9
word_14C126:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x5D69
		.word 0xBD6F
word_14C12C:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xF4D5
		.word 0x24E5
		.word 0x14E8
word_14C134:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xB4EA
		.word 0x24F6
		.word 0x4F9
word_14C13C:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x84FA
		.word 0x1503
word_14C142:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xB505
		.word 0x3511
word_14C148:	.word 1			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xB515
word_14C14C:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x2521
		.word 0xB524
		.word 0x1530
word_14C154:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x3532
		.word 0xB536
word_14C15A:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x542
		.word 0xB543
		.word 0x154F
word_14C162:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x1551
		.word 0x8553
		.word 0x355C
word_14C16A:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x1560
		.word 0x7562
		.word 0x156A
word_14C172:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x256C
		.word 0x756F
		.word 0x2577
word_14C17A:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xB57A
		.word 0x2586
word_14C180:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x258A
		.word 0x358D
		.word 0x8591
word_14C188:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x5D69
		.word 0xBD6F
word_14C18E:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x559A
		.word 0xB5A0
word_14C194:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xB5AC
		.word 0x25B8
word_14C19A:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x25BB
		.word 0x75BE
		.word 0x55C6
word_14C1A2:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xB5CC
		.word 0x25D8
word_14C1A8:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xB5DB
		.word 0x25E7
word_14C1AE:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xB5EA
		.word 0x85F6
word_14C1B4:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xB5FF
		.word 0x260B
word_14C1BA:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xB60E
		.word 0x261A
word_14C1C0:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xB61D
		.word 0x8629
word_14C1C6:	.word 1			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xB632
word_14C1CA:	.word 1			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xB63E
word_14C1CE:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x364A
		.word 0x764E
		.word 0x3656
word_14C1D6:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xB65A
		.word 0x8666
word_14C1DC:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xB66F
		.word 0x267B
word_14C1E2:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xB67E
		.word 0x268A
word_14C1E8:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xB68D
		.word 0x8699
word_14C1EE:	.word 1			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xB6A2
word_14C1F2:	.word 1			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xB6AE
word_14C1F6:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x16BA
		.word 0x56BC
		.word 0x76C2
word_14C1FE:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x86CA
		.word 0x16D3
word_14C204:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x26D5
		.word 0x76D8
word_14C20A:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x16E0
		.word 0xB6E2
		.word 0x16EE
word_14C212:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xF6F0
		.word 0x2700
word_14C218:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x703
		.word 0x8704
		.word 0x370D
word_14C220:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x2711
		.word 0x3714
		.word 0x2718
		.word 0x371B
word_14C22A:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x171F
		.word 0x8721
word_14C230:	.word 1			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xF72A
word_14C234:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x773A
		.word 0x8742
word_14C23A:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x174B
		.word 0x174D
		.word 0xB74F
word_14C242:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xF75B
		.word 0x176B
word_14C248:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x76D
		.word 0xB76E
word_14C24E:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x277A
		.word 0xB77D
		.word 0x789
word_14C256:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x178A
		.word 0xB78C
word_14C25C:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x3798
		.word 0x879C
		.word 0x77A5
word_14C264:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x27AD
		.word 0x77B0
		.word 0x57B8
		.word 0x27BE
word_14C26E:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x7C1
		.word 0xB7C2
		.word 0x77CE
word_14C276:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x27D6
		.word 0x17D9
		.word 0x27DB
		.word 0xB7DE
word_14C280:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x3798
		.word 0x879C
		.word 0x77A5
word_14C288:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x27AD
		.word 0x77B0
		.word 0x57B8
		.word 0x27BE
word_14C292:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x7C1
		.word 0xB7C2
		.word 0x77CE
word_14C29A:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x27D6
		.word 0x17D9
		.word 0x27DB
		.word 0xB7DE
word_14C2A4:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xF800
		.word 0x810
		.word 0x5811
word_14C2AC:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x817
		.word 0x3818
		.word 0xB81C
		.word 0x2828
word_14C2B6:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x182B
		.word 0xB82D
		.word 0x8839
word_14C2BE:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xF842
		.word 0x5852
word_14C2C4:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x1858
		.word 0x585A
		.word 0x3860
		.word 0x8864
word_14C2CE:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x186D
		.word 0x386F
		.word 0x8873
		.word 0x387C
word_14C2D8:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x2880
		.word 0x7883
		.word 0x288B
word_14C2E0:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x288E
		.word 0x7891
		.word 0x2899
word_14C2E8:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x289C
		.word 0x789F
		.word 0x2899
word_14C2F0:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x28A7
		.word 0x78AA
		.word 0x2899
word_14C2F8:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x28B2
		.word 0x78B5
		.word 0x2899
word_14C300:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x288E
		.word 0x78BD
		.word 0x2899
word_14C308:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xB8C5
		.word 0x58D1
		.word 0x18D7
word_14C310:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x88D9
		.word 0x38E2
		.word 0x78E6
		.word 0x8EE
word_14C31A:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x18EF
		.word 0x88F1
		.word 0x38FA
word_14C322:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x18FE
		.word 0xB900
		.word 0x190C
word_14C32A:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x190E
		.word 0x8910
		.word 0x5919
		.word 0x191F
word_14C334:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xB921
		.word 0x592D
word_14C33A:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x8933
		.word 0x393C
		.word 0x3940
word_14C342:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x8933
		.word 0x3944
		.word 0x1948
word_14C34A:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x795B
		.word 0x194A
		.word 0xB94C
		.word 0x2958
word_14C354:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x5963
		.word 0x194A
		.word 0xB94C
		.word 0x2958
word_14C35E:	.word 1			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xF969
word_14C362:	.word 1			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xF979
word_14C366:	.word 1			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xF989
word_14C36A:	.word 1			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xF999
word_14C36E:	.word 1			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xF9A9
word_14C372:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x29B9
		.word 0xB9BC
word_14C378:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x29C8
		.word 0x79CB
word_14C37E:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x19D3
		.word 0xF9D5
word_14C384:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x29E5
		.word 0xF9E8
		.word 0x9F8
		.word 0x39F9
word_14C38E:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x29FD
		.word 0xBA00
		.word 0x1A0C
		.word 0x2A0E
word_14C398:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x2A11
		.word 0xBA14
		.word 0x5A20
		.word 0x2A26
word_14C3A2:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xA29
		.word 0xBA2A
		.word 0x7A36
		.word 0x5A3E
word_14C3AC:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xBA44
		.word 0x1A50
		.word 0x1A52
		.word 0x5A54
word_14C3B6:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xA5A
		.word 0xBA5B
		.word 0x3A67
		.word 0x5A6B
word_14C3C0:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xBA71
		.word 0x1A7D
		.word 0x2A7F
		.word 0x1A82
word_14C3CA:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x1A84
		.word 0x1A86
		.word 0xBA88
		.word 0x5A94
word_14C3D4:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x5A9A
		.word 0xBAA0
		.word 0x2AAC
		.word 0x2AAF
word_14C3DE:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xBAB2
		.word 0x1ABE
		.word 0x5AC0
		.word 0x1AC6
word_14C3E8:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x1AC8
		.word 0x7ACA
		.word 0x8AD2
		.word 0x3ADB
word_14C3F2:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x5ADF
		.word 0x1AE5
		.word 0xBAE7
		.word 0x8AF3
word_14C3FC:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x1AFC
		.word 0x1AFE
		.word 0xFB00
		.word 0x5B10
word_14C406:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x7B16
		.word 0x1B1E
		.word 0x5B20
		.word 0x3B26
word_14C410:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x7B2A
		.word 0x1B1C
		.word 0x5B32
		.word 0x3B38
word_14C41A:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x7B3C
		.word 0x1B1C
		.word 0x5B44
		.word 0x3B26
word_14C424:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xBB4A
		.word 0xB56
		.word 0x5B57
word_14C42C:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xBB5D
		.word 0xB69
		.word 0x5B6A
word_14C434:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x37EA
		.word 0xF7EE
		.word 0x7FE
word_14C43C:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x2B70
		.word 0xFB73
word_14C442:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x2B83
		.word 0xFB86
		.word 0x2B96
word_14C44A:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x1B99
		.word 0xFB9B
word_14C450:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x2BAB
		.word 0xFBAE
		.word 0x1BBE
word_14C458:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xBBC0
		.word 0x2BCC
		.word 0x3BCF
word_14C460:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xBBD3
		.word 0x2BDF
		.word 0x3BE2
word_14C468:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xFBE6
		.word 0xBF6
word_14C46E:	.word 1			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xFBF7
word_14C472:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xFC07
		.word 0x1C17
word_14C478:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x2C19
		.word 0xBC1C
		.word 0x1C28
word_14C480:	.word 1			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xFC2A
word_14C484:	.word 1			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xFC3A
word_14C488:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x7C4A
		.word 0x2C52
		.word 0x1C55
		.word 0xC57
word_14C492:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xBC58
		.word 0x3C64
word_14C498:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x1C68
		.word 0xFC6A
		.word 0xC7A
word_14C4A0:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x3C7B
		.word 0x7C7F
		.word 0x3C87
word_14C4A8:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xBC8B
		.word 0x1C97
word_14C4AE:	.word 1			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xBC99
word_14C4B2:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xBC8B
		.word 0x1C97
word_14C4B8:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x3C7B
		.word 0x7C7F
		.word 0x3C87
word_14C4C0:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xBCA5
		.word 0x5CB1
word_14C4C6:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x3CB7
		.word 0x7CBB
		.word 0x3CC3
word_14C4CE:	.word 1			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xBCC7
word_14C4D2:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x3CB7
		.word 0x7CBB
		.word 0x3CC3
word_14C4DA:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xBCA5
		.word 0x5CB1
word_14C4E0:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x7CD3
		.word 0x7CDB
		.word 0x3CE3
		.word 0x2CE7
word_14C4EA:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xBCEA
		.word 0xCF6
		.word 0x3CF7
		.word 0x3CFB
word_14C4F4:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x1CFF
		.word 0x3D01
		.word 0x3D05
		.word 0x2D09
word_14C4FE:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x2D0C
		.word 0xBD0F
		.word 0x1D1B
word_14C506:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x2D1D
		.word 0x3D20
		.word 0xBD24
		.word 0xD30
word_14C510:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x2D31
		.word 0xBD34
		.word 0x1D40
		.word 0x2D42
word_14C51A:	.word 5			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x2D45
		.word 0x3D48
		.word 0xD4C
		.word 0x3D4D
		.word 0x7D51
word_14C526:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x2D31
		.word 0xBD59
		.word 0xD65
		.word 0x2D66
word_14C530:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xBD7B
		.word 0x3D87
word_14C536:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xBD7B
		.word 0x3D8B
word_14C53C:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xBD8F
		.word 0x3D87
word_14C542:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x5D9B
		.word 0xBDA1
word_14C548:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x5DAD
		.word 0xBDB3
word_14C54E:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x5DBF
		.word 0xBDC5
word_14C554:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x2DD1
		.word 0x7DD4
		.word 0x2DDC
		.word 0x3DDF
word_14C55E:	.word 5			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x2DE3
		.word 0x3DE6
		.word 0x3DEA
		.word 0x2DEE
		.word 0x3DDF
word_14C56A:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x2DF1
		.word 0x7DF4
		.word 0x2DFC
		.word 0x3DFF
word_14C574:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x2E03
		.word 0x7E06
		.word 0x2E0E
		.word 0x3E11
word_14C57E:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x2E15
		.word 0x7E18
		.word 0x5E20
word_14C586:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x8E26
		.word 0x3E2F
		.word 0x5E33
word_14C58E:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xBE39
		.word 0x1E45
		.word 0x2E47
		.word 0x3E4A
word_14C598:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x5E4E
		.word 0x7E54
		.word 0x1E5C
word_14C5A0:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x2E5E
		.word 0x7E61
		.word 0x1E69
word_14C5A8:	.word 1			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xFE6B
word_14C5AC:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xBE7B
		.word 0x1E87
word_14C5B2:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x8E89
		.word 0x7E92
word_14C5B8:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x1E9A
		.word 0x2E9C
		.word 0x7E9F
		.word 0x5EA7
word_14C5C2:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xB921
		.word 0x592D
word_14C5C8:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xFEAD
		.word 0x2EBD
		.word 0x1EC0
word_14C5D0:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xBEC2
		.word 0x1ECE
		.word 0x2ED0
word_14C5D8:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x5ED3
		.word 0x3ED9
		.word 0x2EDD
		.word 0x5EE0
word_14C5E2:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x5EE6
		.word 0x7EEC
		.word 0x5EF4
word_14C5EA:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xBEFA
		.word 0x5F06
word_14C5F0:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x5F0C
		.word 0x3F12
		.word 0x5F16
word_14C5F8:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x3F1C
		.word 0x2F20
		.word 0xFF23
word_14C600:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x3F33
		.word 0xFF37
		.word 0x3F47
word_14C608:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x1F4B
		.word 0xBF4D
		.word 0x2F59
word_14C610:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x1F5C
		.word 0xBF5E
		.word 0x1F6A
word_14C618:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xBF6C
		.word 0x2F78
word_14C61E:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xBF7B
		.word 0xF87
word_14C624:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x2F88
		.word 0xBF8B
		.word 0x1F97
word_14C62C:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x2F99
		.word 0xBF9C
		.word 0x2FA8
word_14C634:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xFFAB
		.word 0x1FBB
word_14C63A:	.word 4			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x2FBD
		.word 0x7FC0
		.word 0x2FC8
		.word 0x1FCB
word_14C644:	.word 3			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0x8FCD
		.word 0x1FD6
		.word 0x1FD8
word_14C64C:	.word 2			/*  DATA XREF: ROM:0014BD0Ao */
		.word 0xBFDA
		.word 0x5FE6
