/* Knuckles mappings*/
Map_14A8D6:		.word word_14AACC-Map_14A8D6/* 0*/
		.word word_14AACE-Map_14A8D6/* 1*/
		.word word_14AAE8-Map_14A8D6/* 2*/
		.word word_14AAFC-Map_14A8D6/* 3*/
		.word word_14AB10-Map_14A8D6/* 4*/
		.word word_14AB1E-Map_14A8D6/* 5*/
		.word word_14AB38-Map_14A8D6/* 6*/
		.word word_14AB52-Map_14A8D6/* 7*/
		.word word_14AB66-Map_14A8D6/* 8*/
		.word word_14AB80-Map_14A8D6/* 9*/
		.word word_14AB94-Map_14A8D6/* 10*/
		.word word_14ABA8-Map_14A8D6/* 11*/
		.word word_14ABBC-Map_14A8D6/* 12*/
		.word word_14ABD6-Map_14A8D6/* 13*/
		.word word_14ABEA-Map_14A8D6/* 14*/
		.word word_14ABF8-Map_14A8D6/* 15*/
		.word word_14AC0C-Map_14A8D6/* 16*/
		.word word_14AC20-Map_14A8D6/* 17*/
		.word word_14AC3A-Map_14A8D6/* 18*/
		.word word_14AC54-Map_14A8D6/* 19*/
		.word word_14AC68-Map_14A8D6/* 20*/
		.word word_14AC76-Map_14A8D6/* 21*/
		.word word_14AC90-Map_14A8D6/* 22*/
		.word word_14ACAA-Map_14A8D6/* 23*/
		.word word_14ACBE-Map_14A8D6/* 24*/
		.word word_14ACD8-Map_14A8D6/* 25*/
		.word word_14ACEC-Map_14A8D6/* 26*/
		.word word_14AD00-Map_14A8D6/* 27*/
		.word word_14AD14-Map_14A8D6/* 28*/
		.word word_14AD28-Map_14A8D6/* 29*/
		.word word_14AD36-Map_14A8D6/* 30*/
		.word word_14AD44-Map_14A8D6/* 31*/
		.word word_14AD58-Map_14A8D6/* 32*/
		.word word_14AD6C-Map_14A8D6/* 33*/
		.word word_14AD7A-Map_14A8D6/* 34*/
		.word word_14AD88-Map_14A8D6/* 35*/
		.word word_14AD96-Map_14A8D6/* 36*/
		.word word_14ADA4-Map_14A8D6/* 37*/
		.word word_14ADBE-Map_14A8D6/* 38*/
		.word word_14ADD8-Map_14A8D6/* 39*/
		.word word_14ADEC-Map_14A8D6/* 40*/
		.word word_14AE00-Map_14A8D6/* 41*/
		.word word_14AE0E-Map_14A8D6/* 42*/
		.word word_14AE1C-Map_14A8D6/* 43*/
		.word word_14AE2A-Map_14A8D6/* 44*/
		.word word_14AE38-Map_14A8D6/* 45*/
		.word word_14AE52-Map_14A8D6/* 46*/
		.word word_14AE6C-Map_14A8D6/* 47*/
		.word word_14AE80-Map_14A8D6/* 48*/
		.word word_14AE94-Map_14A8D6/* 49*/
		.word word_14AEAE-Map_14A8D6/* 50*/
		.word word_14AEBC-Map_14A8D6/* 51*/
		.word word_14AED0-Map_14A8D6/* 52*/
		.word word_14AEE4-Map_14A8D6/* 53*/
		.word word_14AEF8-Map_14A8D6/* 54*/
		.word word_14AF0C-Map_14A8D6/* 55*/
		.word word_14AF1A-Map_14A8D6/* 56*/
		.word word_14AF2E-Map_14A8D6/* 57*/
		.word word_14AF3C-Map_14A8D6/* 58*/
		.word word_14AF4A-Map_14A8D6/* 59*/
		.word word_14AF5E-Map_14A8D6/* 60*/
		.word word_14AF6C-Map_14A8D6/* 61*/
		.word word_14AF7A-Map_14A8D6/* 62*/
		.word word_14AF8E-Map_14A8D6/* 63*/
		.word word_14AF9C-Map_14A8D6/* 64*/
		.word word_14AFB0-Map_14A8D6/* 65*/
		.word word_14AFBE-Map_14A8D6/* 66*/
		.word word_14AFD8-Map_14A8D6/* 67*/
		.word word_14AFE6-Map_14A8D6/* 68*/
		.word word_14AFEE-Map_14A8D6/* 69*/
		.word word_14B002-Map_14A8D6/* 70*/
		.word word_14B010-Map_14A8D6/* 71*/
		.word word_14B01E-Map_14A8D6/* 72*/
		.word word_14B02C-Map_14A8D6/* 73*/
		.word word_14B040-Map_14A8D6/* 74*/
		.word word_14B054-Map_14A8D6/* 75*/
		.word word_14B062-Map_14A8D6/* 76*/
		.word word_14B070-Map_14A8D6/* 77*/
		.word word_14B078-Map_14A8D6/* 78*/
		.word word_14B08C-Map_14A8D6/* 79*/
		.word word_14B09A-Map_14A8D6/* 80*/
		.word word_14B0AE-Map_14A8D6/* 81*/
		.word word_14B0C2-Map_14A8D6/* 82*/
		.word word_14B0D6-Map_14A8D6/* 83*/
		.word word_14B0EA-Map_14A8D6/* 84*/
		.word word_14B0F8-Map_14A8D6/* 85*/
		.word word_14B10C-Map_14A8D6/* 86*/
		.word word_14B11A-Map_14A8D6/* 87*/
		.word word_14B128-Map_14A8D6/* 88*/
		.word word_14B136-Map_14A8D6/* 89*/
		.word word_14B14A-Map_14A8D6/* 90*/
		.word word_14B158-Map_14A8D6/* 91*/
		.word word_14B166-Map_14A8D6/* 92*/
		.word word_14B174-Map_14A8D6/* 93*/
		.word word_14B182-Map_14A8D6/* 94*/
		.word word_14B190-Map_14A8D6/* 95*/
		.word word_14B19E-Map_14A8D6/* 96*/
		.word word_14B1A6-Map_14A8D6/* 97*/
		.word word_14B1AE-Map_14A8D6/* 98*/
		.word word_14B1C2-Map_14A8D6/* 99*/
		.word word_14B1D0-Map_14A8D6/* 100*/
		.word word_14B1DE-Map_14A8D6/* 101*/
		.word word_14B1EC-Map_14A8D6/* 102*/
		.word word_14B1FA-Map_14A8D6/* 103*/
		.word word_14B202-Map_14A8D6/* 104*/
		.word word_14B20A-Map_14A8D6/* 105*/
		.word word_14B21E-Map_14A8D6/* 106*/
		.word word_14B22C-Map_14A8D6/* 107*/
		.word word_14B23A-Map_14A8D6/* 108*/
		.word word_14B24E-Map_14A8D6/* 109*/
		.word word_14B25C-Map_14A8D6/* 110*/
		.word word_14B270-Map_14A8D6/* 111*/
		.word word_14B28A-Map_14A8D6/* 112*/
		.word word_14B298-Map_14A8D6/* 113*/
		.word word_14B2A0-Map_14A8D6/* 114*/
		.word word_14B2AE-Map_14A8D6/* 115*/
		.word word_14B2C2-Map_14A8D6/* 116*/
		.word word_14B2D0-Map_14A8D6/* 117*/
		.word word_14B2DE-Map_14A8D6/* 118*/
		.word word_14B2F2-Map_14A8D6/* 119*/
		.word word_14B300-Map_14A8D6/* 120*/
		.word word_14B314-Map_14A8D6/* 121*/
		.word word_14B32E-Map_14A8D6/* 122*/
		.word word_14B342-Map_14A8D6/* 123*/
		.word word_14B35C-Map_14A8D6/* 124*/
		.word word_14B370-Map_14A8D6/* 125*/
		.word word_14B38A-Map_14A8D6/* 126*/
		.word word_14B39E-Map_14A8D6/* 127*/
		.word word_14B3B8-Map_14A8D6/* 128*/
		.word word_14B3CC-Map_14A8D6/* 129*/
		.word word_14B3E6-Map_14A8D6/* 130*/
		.word word_14B3FA-Map_14A8D6/* 131*/
		.word word_14B408-Map_14A8D6/* 132*/
		.word word_14B422-Map_14A8D6/* 133*/
		.word word_14B43C-Map_14A8D6/* 134*/
		.word word_14B450-Map_14A8D6/* 135*/
		.word word_14B464-Map_14A8D6/* 136*/
		.word word_14B478-Map_14A8D6/* 137*/
		.word word_14B48C-Map_14A8D6/* 138*/
		.word word_14B4A0-Map_14A8D6/* 139*/
		.word word_14B4B4-Map_14A8D6/* 140*/
		.word word_14B4C8-Map_14A8D6/* 141*/
		.word word_14B4E2-Map_14A8D6/* 142*/
		.word word_14B4F6-Map_14A8D6/* 143*/
		.word word_14B50A-Map_14A8D6/* 144*/
		.word word_14B524-Map_14A8D6/* 145*/
		.word word_14B532-Map_14A8D6/* 146*/
		.word word_14B546-Map_14A8D6/* 147*/
		.word word_14B55A-Map_14A8D6/* 148*/
		.word word_14B574-Map_14A8D6/* 149*/
		.word word_14B58E-Map_14A8D6/* 150*/
		.word word_14B596-Map_14A8D6/* 151*/
		.word word_14B59E-Map_14A8D6/* 152*/
		.word word_14B5A6-Map_14A8D6/* 153*/
		.word word_14B5AE-Map_14A8D6/* 154*/
		.word word_14B5B6-Map_14A8D6/* 155*/
		.word word_14B5C4-Map_14A8D6/* 156*/
		.word word_14B5D2-Map_14A8D6/* 157*/
		.word word_14B5E0-Map_14A8D6/* 158*/
		.word word_14B5FA-Map_14A8D6/* 159*/
		.word word_14B614-Map_14A8D6/* 160*/
		.word word_14B62E-Map_14A8D6/* 161*/
		.word word_14B648-Map_14A8D6/* 162*/
		.word word_14B662-Map_14A8D6/* 163*/
		.word word_14B67C-Map_14A8D6/* 164*/
		.word word_14B696-Map_14A8D6/* 165*/
		.word word_14B6B0-Map_14A8D6/* 166*/
		.word word_14B6CA-Map_14A8D6/* 167*/
		.word word_14B6E4-Map_14A8D6/* 168*/
		.word word_14B6FE-Map_14A8D6/* 169*/
		.word word_14B718-Map_14A8D6/* 170*/
		.word word_14B732-Map_14A8D6/* 171*/
		.word word_14B74C-Map_14A8D6/* 172*/
		.word word_14B766-Map_14A8D6/* 173*/
		.word word_14B780-Map_14A8D6/* 174*/
		.word word_14B794-Map_14A8D6/* 175*/
		.word word_14B7A8-Map_14A8D6/* 176*/
		.word word_14B7BC-Map_14A8D6/* 177*/
		.word word_14B7CA-Map_14A8D6/* 178*/
		.word word_14B7DE-Map_14A8D6/* 179*/
		.word word_14B7EC-Map_14A8D6/* 180*/
		.word word_14B800-Map_14A8D6/* 181*/
		.word word_14B814-Map_14A8D6/* 182*/
		.word word_14B828-Map_14A8D6/* 183*/
		.word word_14B836-Map_14A8D6/* 184*/
		.word word_14B83E-Map_14A8D6/* 185*/
		.word word_14B84C-Map_14A8D6/* 186*/
		.word word_14B860-Map_14A8D6/* 187*/
		.word word_14B868-Map_14A8D6/* 188*/
		.word word_14B870-Map_14A8D6/* 189*/
		.word word_14B88A-Map_14A8D6/* 190*/
		.word word_14B898-Map_14A8D6/* 191*/
		.word word_14B8AC-Map_14A8D6/* 192*/
		.word word_14B8C0-Map_14A8D6/* 193*/
		.word word_14B8CE-Map_14A8D6/* 194*/
		.word word_14B8D6-Map_14A8D6/* 195*/
		.word word_14B8E4-Map_14A8D6/* 196*/
		.word word_14B8F8-Map_14A8D6/* 197*/
		.word word_14B906-Map_14A8D6/* 198*/
		.word word_14B91A-Map_14A8D6/* 199*/
		.word word_14B922-Map_14A8D6/* 200*/
		.word word_14B936-Map_14A8D6/* 201*/
		.word word_14B944-Map_14A8D6/* 202*/
		.word word_14B95E-Map_14A8D6/* 203*/
		.word word_14B978-Map_14A8D6/* 204*/
		.word word_14B992-Map_14A8D6/* 205*/
		.word word_14B9A6-Map_14A8D6/* 206*/
		.word word_14B9C0-Map_14A8D6/* 207*/
		.word word_14B9DA-Map_14A8D6/* 208*/
		.word word_14B9FA-Map_14A8D6/* 209*/
		.word word_14BA14-Map_14A8D6/* 210*/
		.word word_14BA22-Map_14A8D6/* 211*/
		.word word_14BA30-Map_14A8D6/* 212*/
		.word word_14BA3E-Map_14A8D6/* 213*/
		.word word_14BA4C-Map_14A8D6/* 214*/
		.word word_14BA5A-Map_14A8D6/* 215*/
		.word word_14BA68-Map_14A8D6/* 216*/
		.word word_14BA82-Map_14A8D6/* 217*/
		.word word_14BAA2-Map_14A8D6/* 218*/
		.word word_14BABC-Map_14A8D6/* 219*/
		.word word_14BAD6-Map_14A8D6/* 220*/
		.word word_14BAEA-Map_14A8D6/* 221*/
		.word word_14BAFE-Map_14A8D6/* 222*/
		.word word_14BB18-Map_14A8D6/* 223*/
		.word word_14BB2C-Map_14A8D6/* 224*/
		.word word_14BB40-Map_14A8D6/* 225*/
		.word word_14BB48-Map_14A8D6/* 226*/
		.word word_14BB56-Map_14A8D6/* 227*/
		.word word_14BB64-Map_14A8D6/* 228*/
		.word word_14BB7E-Map_14A8D6/* 229*/
		.word word_14BB8C-Map_14A8D6/* 230*/
		.word word_14BBA0-Map_14A8D6/* 231*/
		.word word_14BBB4-Map_14A8D6/* 232*/
		.word word_14BBCE-Map_14A8D6/* 233*/
		.word word_14BBE2-Map_14A8D6/* 234*/
		.word word_14BBF0-Map_14A8D6/* 235*/
		.word word_14BC04-Map_14A8D6/* 236*/
		.word word_14BC18-Map_14A8D6/* 237*/
		.word word_14BC18-Map_14A8D6/* 238*/
		.word word_14BC2C-Map_14A8D6/* 239*/
		.word word_14BC40-Map_14A8D6/* 240*/
		.word word_14BC54-Map_14A8D6/* 241*/
		.word word_14BC62-Map_14A8D6/* 242*/
		.word word_14BC70-Map_14A8D6/* 243*/
		.word word_14BC7E-Map_14A8D6/* 244*/
		.word word_14BC92-Map_14A8D6/* 245*/
		.word word_14BCA6-Map_14A8D6/* 246*/
		.word word_14BCB4-Map_14A8D6/* 247*/
		.word word_14BCCE-Map_14A8D6/* 248*/
		.word word_14BCE2-Map_14A8D6/* 249*/
		.word word_14BCFC-Map_14A8D6/* 250*/
word_14AACC:	.word 0			/* DATA XREF: ROM:0014A8D6o*/
word_14AACE:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   8,	  0,   0, 0xFF, 0xF3
		.byte  0xF4,  0xE,	  0,   3, 0xFF, 0xF3
		.byte  0xFC,   2,	  0,  0xF, 0xFF, 0xEB
		.byte   0xC,   4,	  0, 0x12,   0,	 3
word_14AAE8:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   4,	  0,   0, 0xFF, 0xF9
		.byte  0xF4,  0xF,	  0,   2, 0xFF, 0xF1
		.byte  0xFC,   2,	  0, 0x12, 0xFF, 0xE9
word_14AAFC:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   9,	  0,   0, 0xFF, 0xF4
		.byte  0xFC,  0xD,	  0,   6, 0xFF, 0xEC
		.byte   0xC,   4,	  0,  0xE, 0xFF, 0xF4
word_14AB10:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   9,	  0,   0, 0xFF, 0xF5
		.byte  0xFC,  0xE,	  0,   6, 0xFF, 0xED
word_14AB1E:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   8,	  0,   0, 0xFF, 0xF3
		.byte  0xF4,  0xE,	  0,   3, 0xFF, 0xF3
		.byte  0xFC,   1,	  0,  0xF, 0xFF, 0xEB
		.byte   0xC,  0xC,	  0, 0x11, 0xFF, 0xEB
word_14AB38:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEA,   4,	  0,   0, 0xFF, 0xFA
		.byte  0xF2,   8,	  0,   2, 0xFF, 0xF2
		.byte  0xFA,  0xE,	  0,   5, 0xFF, 0xF2
		.byte	2,   1,	  0, 0x11, 0xFF, 0xEA
word_14AB52:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   4,	  0,   0, 0xFF, 0xF7
		.byte  0xF4,  0xE,	  0,   2, 0xFF, 0xEF
		.byte   0xC,   8,	  0,  0xE, 0xFF, 0xEF
word_14AB66:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   8,	  0,   0, 0xFF, 0xF3
		.byte  0xF4,   8,	  0,   3, 0xFF, 0xF3
		.byte  0xFC,  0xE,	  0,   6, 0xFF, 0xF3
		.byte  0xFC,   0,	  0, 0x12, 0xFF, 0xEB
word_14AB80:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xED,  0xE,	  0,   0, 0xFF, 0xF2
		.byte	5,   8,	  0,  0xC, 0xFF, 0xF2
		.byte   0xD,   5,	  0,  0xF, 0xFF, 0xFA
word_14AB94:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEF,  0xF,	  0,   0, 0xFF, 0xF0
		.byte  0xF7,   2,	  0, 0x10,   0, 0x10
		.byte   0xF,   4,	  0, 0x13, 0xFF, 0xF8
word_14ABA8:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEF,   8,	  0,   0, 0xFF, 0xF4
		.byte  0xF7,  0xE,	  0,   3, 0xFF, 0xF4
		.byte   0xF,   0,	  0,  0xF,   0,	 4
word_14ABBC:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF0,   8,	  0,   0, 0xFF, 0xF3
		.byte  0xF8,  0xD,	  0,   3, 0xFF, 0xF3
		.byte	8,   8,	  0,  0xB, 0xFF, 0xF3
		.byte  0x10,   4,	  0,  0xE, 0xFF, 0xFB
word_14ABD6:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEB,  0xF,	  0,   0, 0xFF, 0xF2
		.byte   0xB,   4,	  0, 0x10, 0xFF, 0xF2
		.byte  0x13,   4,	  0, 0x12, 0xFF, 0xFA
word_14ABEA:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEF,  0xE,	  0,   0, 0xFF, 0xF5
		.byte	7,   5,	  0,  0xC, 0xFF, 0xF5
word_14ABF8:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF0,   8,	  0,   0, 0xFF, 0xF5
		.byte  0xF8,  0xE,	  0,   3, 0xFF, 0xF5
		.byte  0x10,   0,	  0,  0xF,   0,	 5
word_14AC0C:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   8,	  0,   0, 0xFF, 0xF3
		.byte  0xF4,  0xE,	  0,   3, 0xFF, 0xF3
		.byte   0xC,   4,	  0,  0xF, 0xFF, 0xFB
word_14AC20:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEE,  0xC,	  0,   0, 0xFF, 0xF4
		.byte  0xF6,  0xE,	  0,   4, 0xFF, 0xEC
		.byte  0xF6,   0,	  0, 0x10,   0,	0xC
		.byte   0xE,   8,	  0, 0x11, 0xFF, 0xFC
word_14AC3A:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF0,  0xC,	  0,   0, 0xFF, 0xF4
		.byte  0xF8,  0xD,	  0,   4, 0xFF, 0xEC
		.byte  0xF8,   0,	  0,  0xC,   0,	0xC
		.byte	8,  0xD,	  0,  0xD, 0xFF, 0xF4
word_14AC54:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF5,  0xE,	  0,   0, 0xFF, 0xEC
		.byte  0xFD,   1,	  0,  0xC,   0,	0xC
		.byte   0xD,   4,	  0,  0xE, 0xFF, 0xFC
word_14AC68:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF4,   6,	  0,   0, 0xFF, 0xEC
		.byte  0xF4,  0xB,	  0,   6, 0xFF, 0xFC
word_14AC76:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xED,   8,	  0,   0, 0xFF, 0xF4
		.byte  0xF5,  0xE,	  0,   3, 0xFF, 0xEC
		.byte  0xF5,   0,	  0,  0xF,   0,	0xC
		.byte   0xD,   8,	  0, 0x10, 0xFF, 0xFC
word_14AC90:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEF,   8,	  0,   0, 0xFF, 0xFB
		.byte  0xF7,  0xE,	  0,   3, 0xFF, 0xF3
		.byte  0xF7,   1,	  0,  0xF, 0xFF, 0xEB
		.byte   0xF,   4,	  0, 0x11,   0,	 3
word_14ACAA:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF2,   8,	  0,   0, 0xFF, 0xF4
		.byte  0xFA,  0xE,	  0,   3, 0xFF, 0xF4
		.byte  0xFA,   1,	  0,  0xF, 0xFF, 0xEC
word_14ACBE:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEE,   4,	  0,   0, 0xFF, 0xFC
		.byte  0xF6,  0xE,	  0,   2, 0xFF, 0xEC
		.byte  0xF6,   2,	  0,  0xE,   0,	0xC
		.byte   0xE,   0,	  0, 0x11, 0xFF, 0xFC
word_14ACD8:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF0,   8,	  0,   0, 0xFF, 0xEE
		.byte  0xF8,  0xE,	  0,   3, 0xFF, 0xEE
		.byte  0xF8,   5,	  0,  0xF,   0,	0xE
word_14ACEC:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xE9,   8,	  0,   0, 0xFF, 0xF7
		.byte  0xF1,  0xF,	  0,   3, 0xFF, 0xEF
		.byte  0xF9,   1,	  0, 0x13,   0,	0xF
word_14AD00:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEB,   8,	  0,   0, 0xFF, 0xF8
		.byte  0xF3,  0xE,	  0,   3, 0xFF, 0xF0
		.byte  0xF3,   0,	  0,  0xF,   0, 0x10
word_14AD14:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   4,	  0,   0, 0xFF, 0xFA
		.byte  0xF4,  0xE,	  0,   2, 0xFF, 0xF2
		.byte  0xF4,   1,	  0,  0xE,   0, 0x12
word_14AD28:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEE,  0xF,	  0,   0, 0xFF, 0xEB
		.byte  0xF6,   6,	  0, 0x10,   0,	0xB
word_14AD36:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xED,  0xB,	  0,   0, 0xFF, 0xEE
		.byte  0xFD,   5,	  0,  0xC,   0,	 6
word_14AD44:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEB,   8,	  0,   0, 0xFF, 0xF9
		.byte  0xF3,  0xE,	  0,   3, 0xFF, 0xF1
		.byte  0xF3,   0,	  0,  0xF,   0, 0x11
word_14AD58:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   8,	  0,   0, 0xFF, 0xF6
		.byte  0xF4,  0xE,	  0,   3, 0xFF, 0xEE
		.byte  0xF4,   1,	  0,  0xF,   0,	0xE
word_14AD6C:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   8,	  0,   0, 0xFF, 0xF4
		.byte  0xF4,  0xF,	  0,   3, 0xFF, 0xEC
word_14AD7A:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xED,   8,	  0,   0, 0xFF, 0xF4
		.byte  0xF5,  0xF,	  0,   3, 0xFF, 0xEC
word_14AD88:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   8,	  0,   0, 0xFF, 0xF4
		.byte  0xF4,  0xF,	  0,   3, 0xFF, 0xEC
word_14AD96:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xED,   8,	  0,   0, 0xFF, 0xF4
		.byte  0xF5,  0xF,	  0,   3, 0xFF, 0xEC
word_14ADA4:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF0,   8,	  0,   0, 0xFF, 0xEE
		.byte  0xF8,  0xE,	  0,   3, 0xFF, 0xEE
		.byte	0,   1,	  0,  0xF,   0,	0xE
		.byte  0x10,   8,	  0, 0x11, 0xFF, 0xF6
word_14ADBE:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF0,   8,	  0,   0, 0xFF, 0xF1
		.byte  0xF8,  0xE,	  0,   3, 0xFF, 0xF1
		.byte  0xF8,   1,	  0,  0xF, 0xFF, 0xE9
		.byte  0x10,   8,	  0, 0x11, 0xFF, 0xF9
word_14ADD8:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF1,   8,	  0,   0, 0xFF, 0xEF
		.byte  0xF9,  0xD,	  0,   3, 0xFF, 0xEF
		.byte	9,   9,	  0,  0xB, 0xFF, 0xF7
word_14ADEC:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF0,   8,	  0,   0, 0xFF, 0xF1
		.byte  0xF8,  0xF,	  0,   3, 0xFF, 0xF1
		.byte  0xF8,   1,	  0, 0x13, 0xFF, 0xE9
word_14AE00:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF4,   2,	  0,   0, 0xFF, 0xEA
		.byte  0xF4,  0xF,	  0,   3, 0xFF, 0xF2
word_14AE0E:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF4,   2,	  0,   0, 0xFF, 0xEB
		.byte  0xF4,  0xF,	  0,   3, 0xFF, 0xF3
word_14AE1C:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF4,   2,	  0,   0, 0xFF, 0xEA
		.byte  0xF4,  0xF,	  0,   3, 0xFF, 0xF2
word_14AE2A:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF4,   2,	  0,   0, 0xFF, 0xEB
		.byte  0xF4,  0xF,	  0,   3, 0xFF, 0xF3
word_14AE38:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEB,   4,	  0,   0,   0,	 0
		.byte  0xF3,  0xE,	  0,   2, 0xFF, 0xF8
		.byte  0xFB,   1,	  0,  0xE, 0xFF, 0xF0
		.byte   0xB,  0xC,	  0, 0x10, 0xFF, 0xF0
word_14AE52:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF0,  0xC,	  0,   0, 0xFF, 0xF8
		.byte  0xF8,  0xE,	  0,   4, 0xFF, 0xF0
		.byte  0xF8,   1,	  0, 0x10,   0, 0x10
		.byte  0x10,   4,	  0, 0x12, 0xFF, 0xF8
word_14AE6C:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF2,  0xE,	  0,   0, 0xFF, 0xF9
		.byte  0xFA,   1,	  0,  0xC, 0xFF, 0xF1
		.byte   0xA,   8,	  0,  0xE, 0xFF, 0xF1
word_14AE80:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xF8
		.byte  0xF8,   2,	  0, 0x10, 0xFF, 0xF0
		.byte  0x10,   4,	  0, 0x13, 0xFF, 0xF8
word_14AE94:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   8,	  0,   0, 0xFF, 0xF3
		.byte  0xF4,  0xD,	  0,   3, 0xFF, 0xF3
		.byte	4,   8,	  0,  0xB, 0xFF, 0xF3
		.byte   0xC,   4,	  0,  0xE, 0xFF, 0xFB
word_14AEAE:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEA,   4,	  0,   0, 0xFF, 0xFB
		.byte  0xF2,  0xF,	  0,   2, 0xFF, 0xF3
word_14AEBC:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xED,   9,	  0,   0, 0xFF, 0xF4
		.byte  0xFD,  0xC,	  0,   6, 0xFF, 0xF4
		.byte	5,   8,	  0,  0xA, 0xFF, 0xF4
word_14AED0:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEF,   8,	  0,   0, 0xFF, 0xF3
		.byte  0xF7,  0xE,	  0,   3, 0xFF, 0xF3
		.byte   0xF,   0,	  0,  0xF,   0,	 3
word_14AEE4:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF2,   8,	  0,   0, 0xFF, 0xF4
		.byte  0xFA,  0xD,	  0,   3, 0xFF, 0xF4
		.byte   0xA,   8,	  0,  0xB, 0xFF, 0xF4
word_14AEF8:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   4,	  0,   0, 0xFF, 0xFB
		.byte  0xF4,  0xD,	  0,   2, 0xFF, 0xF3
		.byte	4,   9,	  0,  0xA, 0xFF, 0xF3
word_14AF0C:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,  0xF,	  0,   0, 0xFF, 0xF2
		.byte   0xC,   8,	  0, 0x10, 0xFF, 0xF2
word_14AF1A:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEB,   5,	  0,   0, 0xFF, 0xFB
		.byte  0xFB,  0xC,	  0,   4, 0xFF, 0xF3
		.byte	3,   9,	  0,   8, 0xFF, 0xF3
word_14AF2E:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF2,  0xE,	  0,   0, 0xFF, 0xF3
		.byte   0xA,   8,	  0,  0xC, 0xFF, 0xF3
word_14AF3C:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF4,  0xD,	  0,   0, 0xFF, 0xF3
		.byte	4,   8,	  0,   8, 0xFF, 0xF3
word_14AF4A:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF3,  0xD,	  0,   0, 0xFF, 0xF2
		.byte	3,   8,	  0,   8, 0xFF, 0xF2
		.byte   0xB,  0xC,	  0,  0xB, 0xFF, 0xF2
word_14AF5E:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,  0xA,	  0,   0, 0xFF, 0xF4
		.byte	4,  0xD,	  0,   9, 0xFF, 0xF4
word_14AF6C:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,  0xB,	  0,   0, 0xFF, 0xF4
		.byte   0xC,   8,	  0,  0xC, 0xFF, 0xF4
word_14AF7A:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF3,   8,	  0,   0, 0xFF, 0xF4
		.byte  0xFB,  0xD,	  0,   3, 0xFF, 0xF4
		.byte   0xB,   4,	  0,  0xB, 0xFF, 0xF4
word_14AF8E:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF6,  0xD,	  0,   0, 0xFF, 0xF4
		.byte	6,   8,	  0,   8, 0xFF, 0xF4
word_14AF9C:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF2,   8,	  0,   0, 0xFF, 0xF9
		.byte  0xFA,  0xD,	  0,   3, 0xFF, 0xF1
		.byte   0xA,   4,	  0,  0xB, 0xFF, 0xF9
word_14AFB0:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEF,  0xE,	  0,   0, 0xFF, 0xF3
		.byte	7,   9,	  0,  0xC, 0xFF, 0xF3
word_14AFBE:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,  0xC,	  0,   0, 0xFF, 0xF4
		.byte  0xF4,   8,	  0,   4, 0xFF, 0xF4
		.byte  0xFC,  0xC,	  0,   7, 0xFF, 0xF4
		.byte	4,   9,	  0,  0xB, 0xFF, 0xF4
word_14AFD8:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xED,  0xB,	  0,   0, 0xFF, 0xF4
		.byte   0xD,   8,	  0,  0xC, 0xFF, 0xF4
word_14AFE6:	.word 1			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xF4
word_14AFEE:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF2,   8,	  0,   0, 0xFF, 0xF4
		.byte  0xFA,  0xD,	  0,   3, 0xFF, 0xF4
		.byte   0xA,   0,	  0,  0xB, 0xFF, 0xFC
word_14B002:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF1,   9,	  0,   0, 0xFF, 0xF3
		.byte	1,  0xD,	  0,   6, 0xFF, 0xF3
word_14B010:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xED,   9,	  0,   0, 0xFF, 0xF3
		.byte  0xFD,  0xE,	  0,   6, 0xFF, 0xF3
word_14B01E:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   9,	  0,   0, 0xFF, 0xF3
		.byte  0xFC,  0xE,	  0,   6, 0xFF, 0xF3
word_14B02C:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xED,  0xF,	  0,   0, 0xFF, 0xF1
		.byte  0xF5,   2,	  0, 0x10, 0xFF, 0xE9
		.byte   0xD,   4,	  0, 0x13, 0xFF, 0xF9
word_14B040:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF0,  0xE,	  0,   0, 0xFF, 0xEE
		.byte	8,   8,	  0,  0xC, 0xFF, 0xEE
		.byte  0x10,   0,	  0,  0xF, 0xFF, 0xEE
word_14B054:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF4,  0xA,	  0,   0, 0xFF, 0xF4
		.byte   0xC,   4,	  0,   9, 0xFF, 0xF4
word_14B062:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF5,  0xE,	  0,   0, 0xFF, 0xF0
		.byte   0xD,  0xC,	  0,  0xC, 0xFF, 0xF0
word_14B070:	.word 1			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF4,  0xE,	  0,   0, 0xFF, 0xF3
word_14B078:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xED,   8,	  0,   0, 0xFF, 0xF8
		.byte  0xF5,  0xE,	  0,   3, 0xFF, 0xF0
		.byte  0xF5,   1,	  0,  0xF,   0, 0x10
word_14B08C:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xED,  0xC,	  0,   0, 0xFF, 0xF6
		.byte  0xF5,  0xE,	  0,   4, 0xFF, 0xEE
word_14B09A:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEE,   0,	  0,   0,   0,	 4
		.byte  0xF6,  0xE,	  0,   1, 0xFF, 0xEC
		.byte  0xF6,   1,	  0,  0xD,   0,	0xC
word_14B0AE:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   4,	  0,   0,   0,	 1
		.byte  0xF4,  0xA,	  0,   2, 0xFF, 0xF1
		.byte  0xF4,   5,	  0,  0xB,   0,	 9
word_14B0C2:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEF,   4,	  0,   0, 0xFF, 0xF8
		.byte  0xF7,  0xD,	  0,   2, 0xFF, 0xF0
		.byte	7,   4,	  0,  0xA, 0xFF, 0xF8
word_14B0D6:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEE,   8,	  0,   0, 0xFF, 0xF0
		.byte  0xF6,  0xD,	  0,   3, 0xFF, 0xF0
		.byte	6,   8,	  0,  0xB, 0xFF, 0xF8
word_14B0EA:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF0,  0xE,	  0,   0, 0xFF, 0xF0
		.byte	8,   8,	  0,  0xC, 0xFF, 0xF0
word_14B0F8:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   8,	  0,   0, 0xFF, 0xF4
		.byte  0xF4,  0xC,	  0,   3, 0xFF, 0xF4
		.byte  0xFC,  0xA,	  0,   7, 0xFF, 0xF4
word_14B10C:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   9,	  0,   0, 0xFF, 0xF3
		.byte  0xFC,  0xE,	  0,   6, 0xFF, 0xF3
word_14B11A:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   9,	  0,   0, 0xFF, 0xF3
		.byte  0xFC,  0xE,	  0,   6, 0xFF, 0xF3
word_14B128:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,  0xB,	  0,   0, 0xFF, 0xF3
		.byte   0xC,   8,	  0,  0xC, 0xFF, 0xF3
word_14B136:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   8,	  0,   0, 0xFF, 0xF2
		.byte  0xF4,  0xD,	  0,   3, 0xFF, 0xF2
		.byte	4,   9,	  0,  0xB, 0xFF, 0xF2
word_14B14A:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,  0xB,	  0,   0, 0xFF, 0xF2
		.byte   0xC,   8,	  0,  0xC, 0xFF, 0xF2
word_14B158:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,  0xB,	  0,   0, 0xFF, 0xF3
		.byte   0xC,   8,	  0,  0xC, 0xFF, 0xF3
word_14B166:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF5,  0xE,	  0,   0, 0xFF, 0xE3
		.byte  0xF5,  0xA,	  0,  0xC,   0,	 3
word_14B174:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF5,  0xE,	  0,   0, 0xFF, 0xEA
		.byte  0xF5,   2,	  0,  0xC,   0,	0xA
word_14B182:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF5,  0xE,	  0,   0, 0xFF, 0xEA
		.byte  0xF5,   2,	  0,  0xC,   0,	0xA
word_14B190:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF5,  0xE,	  0,   0, 0xFF, 0xE4
		.byte  0xF5,  0xA,	  0,  0xC,   0,	 4
word_14B19E:	.word 1			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF5,  0xE,	  0,   0, 0xFF, 0xF2
word_14B1A6:	.word 1			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF5,  0xE,	  0,   0, 0xFF, 0xE8
word_14B1AE:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF5,  0xC,	  0,   0, 0xFF, 0xEF
		.byte  0xFD,  0xD,	  0,   4, 0xFF, 0xE7
		.byte  0xFD,   5,	  0,  0xC,   0,	 7
word_14B1C2:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xE3,  0xB,	  0,   0, 0xFF, 0xF5
		.byte	3,  0xA,	  0,  0xC, 0xFF, 0xF5
word_14B1D0:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,  0xB,	  0,   0, 0xFF, 0xF5
		.byte   0xC,   8,	  0,  0xC, 0xFF, 0xF5
word_14B1DE:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,  0xB,	  0,   0, 0xFF, 0xF5
		.byte   0xC,   8,	  0,  0xC, 0xFF, 0xF5
word_14B1EC:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xE5,  0xB,	  0,   0, 0xFF, 0xF5
		.byte	5,  0xA,	  0,  0xC, 0xFF, 0xF5
word_14B1FA:	.word 1			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF0,  0xB,	  0,   0, 0xFF, 0xF5
word_14B202:	.word 1			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF5,  0xB,	  0,   0, 0xFF, 0xF5
word_14B20A:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xE8,   4,	  0,   0, 0xFF, 0xFB
		.byte  0xF0,   9,	  0,   2, 0xFF, 0xF3
		.byte	0,  0xD,	  0,   8, 0xFF, 0xF3
word_14B21E:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEF,  0xA,	  0,   0, 0xFF, 0xF5
		.byte	7,   4,	  0,   9, 0xFF, 0xFD
word_14B22C:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF5,   8,	  0,   0, 0xFF, 0xF3
		.byte  0xFD,  0xD,	  0,   3, 0xFF, 0xF3
word_14B23A:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   4,	  0,   0, 0xFF, 0xFA
		.byte  0xF4,  0xE,	  0,   2, 0xFF, 0xEA
		.byte  0xF4,   1,	  0,  0xE,   0,	0xA
word_14B24E:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF1,  0xF,	  0,   0, 0xFF, 0xF2
		.byte  0xF9,   2,	  0, 0x10, 0xFF, 0xEA
word_14B25C:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEE,   0,	  0,   0, 0xFF, 0xFF
		.byte  0xF6,  0xA,	  0,   1, 0xFF, 0xEF
		.byte  0xF6,   5,	  0,  0xA,   0,	 7
word_14B270:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEF,   8,	  0,   0, 0xFF, 0xF9
		.byte  0xF7,  0xC,	  0,   3, 0xFF, 0xF1
		.byte  0xFF,   8,	  0,   7, 0xFF, 0xF1
		.byte	7,  0xC,	  0,  0xA, 0xFF, 0xF1
word_14B28A:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xED,   4,	  0,   0, 0xFF, 0xFE
		.byte  0xF5,  0xA,	  0,   2, 0xFF, 0xF6
word_14B298:	.word 1			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xED,  0xF,	  0,   0, 0xFF, 0xEF
word_14B2A0:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   7,	  0,   0, 0xFF, 0xF0
		.byte  0xF4,  0xA,	  0,   8,   0,	 0
word_14B2AE:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEF,   4,	  0,   0, 0xFF, 0xFE
		.byte  0xF7,   1,	  0,   2, 0xFF, 0xEE
		.byte  0xF7,  0xE,	  0,   4, 0xFF, 0xF6
word_14B2C2:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xEE
		.byte  0xF8,   1,	  0, 0x10,   0,	0xE
word_14B2D0:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xED,   0,	  0,   0, 0xFF, 0xFB
		.byte  0xF5,  0xE,	  0,   1, 0xFF, 0xF3
word_14B2DE:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF0,   8,	  0,   0, 0xFF, 0xF1
		.byte  0xF8,  0xE,	  0,   3, 0xFF, 0xF1
		.byte  0xF8,   0,	  0,  0xF, 0xFF, 0xE9
word_14B2F2:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xED,   4,	  0,   0, 0xFF, 0xF7
		.byte  0xF5,  0xE,	  0,   2, 0xFF, 0xEF
word_14B300:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xE6,  0xC,	  0,   0, 0xFF, 0xF1
		.byte  0xEE,  0xA,	  0,   4, 0xFF, 0xF1
		.byte	6,  0xD,	  0,  0xD, 0xFF, 0xF9
word_14B314:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   8,	  0,   0, 0xFF, 0xE5
		.byte  0xF4,  0xD,	  0,   3, 0xFF, 0xE5
		.byte  0xF4,   6,	  0,  0xB,   0,	 5
		.byte	4,   8,	  0, 0x11, 0xFF, 0xED
word_14B32E:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF0,   0,	  0,   0, 0xFF, 0xE6
		.byte  0xF8,  0xE,	  0,   1, 0xFF, 0xE6
		.byte  0xE8,   7,	  0,  0xD,   0,	 6
word_14B342:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   8,	  0,   0, 0xFF, 0xF4
		.byte  0xF4,   4,	  0,   3, 0xFF, 0xFC
		.byte  0xFC,   8,	  0,   5, 0xFF, 0xF4
		.byte	4,  0xE,	  0,   8, 0xFF, 0xEC
word_14B35C:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0x13,  0xC,	0x18,   0, 0xFF, 0xF0
		.byte  0xFB,  0xA,	0x18,   4, 0xFF, 0xF8
		.byte  0xEB,  0xD,	0x18,  0xD, 0xFF, 0xE8
word_14B370:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte   0xE,   8,	0x18,   0,   0,	 3
		.byte  0xFE,  0xD,	0x18,   3, 0xFF, 0xFB
		.byte  0xF6,   6,	0x18,  0xB, 0xFF, 0xEB
		.byte  0xF6,   8,	0x18, 0x11, 0xFF, 0xFB
word_14B38A:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte	8,   0,	0x18,   0,   0, 0x13
		.byte  0xF0,  0xE,	0x18,   1, 0xFF, 0xFB
		.byte  0xF8,   7,	0x18,  0xD, 0xFF, 0xEB
word_14B39E:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte   0xE,   8,	0x18,   0, 0xFF, 0xF5
		.byte	6,   4,	0x18,   3, 0xFF, 0xF5
		.byte  0xFE,   8,	0x18,   5, 0xFF, 0xF5
		.byte  0xE6,  0xE,	0x18,   8, 0xFF, 0xF5
word_14B3B8:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xE8,  0xF,	  0,   0, 0xFF, 0xEE
		.byte  0xE8,   0,	  0, 0x10,   0,	0xE
		.byte	8,   9,	  0, 0x11, 0xFF, 0xEE
word_14B3CC:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xE1,   0,	  0,   0, 0xFF, 0xFF
		.byte  0xE9,  0xC,	  0,   1, 0xFF, 0xEF
		.byte  0xF1,  0xB,	  0,   5, 0xFF, 0xEF
		.byte  0x11,   8,	  0, 0x11, 0xFF, 0xEF
word_14B3E6:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xE1,   4,	  0,   0, 0xFF, 0xF4
		.byte  0xE9,  0xE,	  0,   2, 0xFF, 0xF4
		.byte	1,  0xA,	  0,  0xE, 0xFF, 0xF4
word_14B3FA:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xE7,  0xF,	  0,   0, 0xFF, 0xEE
		.byte	7,   9,	  0, 0x10, 0xFF, 0xF6
word_14B408:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xE2,   4,	  0,   0, 0xFF, 0xFC
		.byte  0xEA,   9,	  0,   2, 0xFF, 0xF4
		.byte  0xFA,  0xC,	  0,   8, 0xFF, 0xF4
		.byte	2,  0xA,	  0,  0xC, 0xFF, 0xF4
word_14B422:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xE2,   4,	  0,   0, 0xFF, 0xF4
		.byte  0xEA,  0xC,	  0,   2, 0xFF, 0xF4
		.byte  0xF2,  0xA,	  0,   6, 0xFF, 0xF4
		.byte   0xA,   5,	  0,  0xF, 0xFF, 0xFC
word_14B43C:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF8,   8,	  0,   0, 0xFF, 0xFC
		.byte	0,  0xD,	  0,   3, 0xFF, 0xF4
		.byte  0x10,   8,	  0,  0xB, 0xFF, 0xF4
word_14B450:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF8,   8,	  0,   0, 0xFF, 0xFC
		.byte	0,  0xD,	  0,   3, 0xFF, 0xF4
		.byte  0x10,   8,	  0,  0xB, 0xFF, 0xF4
word_14B464:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF8,   8,	  0,   0, 0xFF, 0xFC
		.byte	0,  0xD,	  0,   3, 0xFF, 0xF4
		.byte  0x10,   8,	  0,  0xB, 0xFF, 0xF4
word_14B478:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF8,   8,	  0,   0, 0xFF, 0xFC
		.byte	0,  0xD,	  0,   3, 0xFF, 0xF4
		.byte  0x10,   8,	  0,  0xB, 0xFF, 0xF4
word_14B48C:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF8,   8,	  0,   0, 0xFF, 0xFC
		.byte	0,  0xD,	  0,   3, 0xFF, 0xF4
		.byte  0x10,   8,	  0,  0xB, 0xFF, 0xF4
word_14B4A0:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF8,   8,	  0,   0, 0xFF, 0xFC
		.byte	0,  0xD,	  0,   3, 0xFF, 0xF4
		.byte  0x10,   8,	  0,  0xB, 0xFF, 0xF4
word_14B4B4:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEF,  0xB,	  0,   0, 0xFF, 0xF0
		.byte  0xEF,   6,	  0,  0xC,   0,	 8
		.byte   0xF,   4,	  0, 0x12, 0xFF, 0xF8
word_14B4C8:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEB,  0xA,	  0,   0, 0xFF, 0xF2
		.byte  0xEB,   5,	  0,   9,   0,	0xA
		.byte	3,  0xD,	  0,  0xD, 0xFF, 0xF2
		.byte	3,   0,	  0, 0x15,   0, 0x12
word_14B4E2:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xE8,   4,	  0,   0, 0xFF, 0xF6
		.byte  0xF0,  0xA,	  0,   2, 0xFF, 0xF6
		.byte	8,   5,	  0,  0xB, 0xFF, 0xF6
word_14B4F6:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF3,   1,	  0,   0, 0xFF, 0xE7
		.byte  0xF3,  0xE,	  0,   2, 0xFF, 0xEF
		.byte   0xB,   4,	  0,  0xE, 0xFF, 0xFF
word_14B50A:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xE6,   4,	  0,   0, 0xFF, 0xF9
		.byte  0xEE,  0xA,	  0,   2, 0xFF, 0xF1
		.byte	6,   9,	  0,  0xB, 0xFF, 0xF9
		.byte  0x16,   4,	  0, 0x11, 0xFF, 0xF9
word_14B524:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xE6,  0xB,	  0,   0, 0xFF, 0xF2
		.byte	6,   9,	  0,  0xC, 0xFF, 0xFA
word_14B532:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xE6,  0xA,	  0,   0, 0xFF, 0xF2
		.byte  0xFE,  0xC,	  0,   9, 0xFF, 0xF2
		.byte	6,   5,	  0,  0xD,   0,	 2
word_14B546:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xE6,  0xA,	  0,   0, 0xFF, 0xF2
		.byte  0xFE,  0xC,	  0,   9, 0xFF, 0xF2
		.byte	6,   4,	  0,  0xD,   0,	 2
word_14B55A:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xE9,  0xD,	  0,   0, 0xFF, 0xF1
		.byte  0xEB,   4,	  0,   8, 0xFF, 0xF4
		.byte  0xF3,  0xB,	  0,  0xA, 0xFF, 0xF4
		.byte  0x13,   8,	  0, 0x16, 0xFF, 0xF4
word_14B574:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xE9,   9,	  0,   0, 0xFF, 0xF4
		.byte  0xEB,   4,	  0,   6, 0xFF, 0xF4
		.byte  0xF3,  0xB,	  0,   8, 0xFF, 0xF4
		.byte  0x13,   8,	  0, 0x14, 0xFF, 0xF4
word_14B58E:	.word 1			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF1,  0xF,	  0,   0, 0xFF, 0xF0
word_14B596:	.word 1			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF1,  0xF,	  0,   0, 0xFF, 0xF0
word_14B59E:	.word 1			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF1,  0xF,	  0,   0, 0xFF, 0xF0
word_14B5A6:	.word 1			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF1,  0xF,	  0,   0, 0xFF, 0xF0
word_14B5AE:	.word 1			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF1,  0xF,	  0,   0, 0xFF, 0xF0
word_14B5B6:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF4,   8,	  0,   0, 0xFF, 0xF3
		.byte  0xFC,  0xE,	  0,   3, 0xFF, 0xF3
word_14B5C4:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xFC,   8,	  0,   0, 0xFF, 0xF5
		.byte	4,  0xD,	  0,   3, 0xFF, 0xF5
word_14B5D2:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   4,	  0,   0, 0xFF, 0xF8
		.byte  0xF4,  0xF,	  0,   2, 0xFF, 0xF0
word_14B5E0:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   8,	  0,   0, 0xFF, 0xEE
		.byte  0xF4,  0xF,	  0,   3, 0xFF, 0xF6
		.byte  0xF4,   0,	  0, 0x13, 0xFF, 0xEE
		.byte  0xFC,   5,	  0, 0x14, 0xFF, 0xE6
word_14B5FA:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   8,	  0,   0, 0xFF, 0xF8
		.byte  0xF4,  0xE,	  0,   3, 0xFF, 0xF0
		.byte  0xFC,   1,	  0,  0xF,   0, 0x10
		.byte   0xC,   8,	  0, 0x11, 0xFF, 0xF0
word_14B614:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   8,	  0,   0, 0xFF, 0xF7
		.byte  0xF4,  0xE,	  0,   3, 0xFF, 0xEF
		.byte  0xF4,   6,	  0,  0xF,   0,	0xF
		.byte   0xC,   8,	  0, 0x15, 0xFF, 0xEF
word_14B62E:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xE4,   0,	  0,   0, 0xFF, 0xF6
		.byte  0xEC,  0xE,	  0,   1, 0xFF, 0xEE
		.byte  0xEC,   7,	  0,  0xD,   0,	0xE
		.byte	4,   9,	  0, 0x15, 0xFF, 0xEE
word_14B648:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xE8,  0xE,	  0,   0, 0xFF, 0xF9
		.byte  0xF0,   1,	  0,  0xC,   0, 0x19
		.byte	0,   4,	  0,  0xE, 0xFF, 0xF9
		.byte	8,   9,	  0, 0x10, 0xFF, 0xF1
word_14B662:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xE6,   0,	  0,   0, 0xFF, 0xFE
		.byte  0xEE,  0xE,	  0,   1, 0xFF, 0xEE
		.byte  0xF6,   5,	  0,  0xD,   0,	0xE
		.byte	6,   9,	  0, 0x11, 0xFF, 0xEE
word_14B67C:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF1,  0xE,	  0,   0, 0xFF, 0xF1
		.byte  0xF1,   1,	  0,  0xC,   0, 0x11
		.byte	9,   8,	  0,  0xE, 0xFF, 0xF1
		.byte  0x11,   4,	  0, 0x11, 0xFF, 0xF9
word_14B696:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xE4,   4,	  0,   0, 0xFF, 0xF1
		.byte  0xEC,   1,	  0,   2,   0, 0x11
		.byte  0xEC,  0xE,	  0,   4, 0xFF, 0xF1
		.byte	4,   9,	  0, 0x10, 0xFF, 0xF1
word_14B6B0:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   6,	  0,   0,   0, 0x11
		.byte  0xEC,  0xE,	  0,   6, 0xFF, 0xF1
		.byte	4,   8,	  0, 0x12, 0xFF, 0xF9
		.byte   0xC,   8,	  0, 0x15, 0xFF, 0xF1
word_14B6CA:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,  0xE,	  0,   0, 0xFF, 0xF6
		.byte  0xF4,   1,	  0,  0xC,   0, 0x16
		.byte	4,   9,	  0,  0xE, 0xFF, 0xEE
		.byte	4,   4,	  0, 0x14,   0,	 6
word_14B6E4:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   1,	  0,   0,   0, 0x16
		.byte  0xEC,  0xD,	  0,   2, 0xFF, 0xF6
		.byte  0xFC,  0xA,	  0,  0xA, 0xFF, 0xEE
		.byte  0xFC,   5,	  0, 0x13,   0,	 6
word_14B6FE:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xE4,   9,	  0,   0, 0xFF, 0xF9
		.byte   0xC,   4,	  0,   6, 0xFF, 0xF9
		.byte  0xF4,  0xE,	  0,   8, 0xFF, 0xE9
		.byte  0xF4,  0xA,	  0, 0x14,   0,	 9
word_14B718:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xE4,   4,	  0,   0,   0,	 3
		.byte   0xC,   4,	  0,   2, 0xFF, 0xFB
		.byte  0xEC,  0xF,	  0,   4, 0xFF, 0xFB
		.byte  0xF4,   6,	  0, 0x14, 0xFF, 0xEB
word_14B732:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEE,  0xD,	  0,   0, 0xFF, 0xF3
		.byte  0xEE,   1,	  0,   8, 0xFF, 0xEB
		.byte  0xFE,   9,	  0,  0xA, 0xFF, 0xF3
		.byte   0xE,  0xC,	  0, 0x10, 0xFF, 0xF3
word_14B74C:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEE,  0xD,	  0,   0, 0xFF, 0xEB
		.byte  0xEE,   1,	  0,   8,   0,	0xB
		.byte  0xFE,   9,	  0,  0xA, 0xFF, 0xF3
		.byte   0xE,  0xC,	  0, 0x10, 0xFF, 0xF3
word_14B766:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEE,  0xD,	  0,   0, 0xFF, 0xEB
		.byte  0xEE,   1,	  0,   8,   0,	0xB
		.byte  0xFE,   9,	  0,  0xA, 0xFF, 0xF3
		.byte   0xE,  0xC,	  0, 0x10, 0xFF, 0xF3
word_14B780:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF4,  0xE,	  0,   0, 0xFF, 0xE6
		.byte  0xF4,   0,	  0,  0xC,   0,	 6
		.byte  0xFC,   9,	  0,  0xD,   0,	 6
word_14B794:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF4,  0xE,	  0,   0, 0xFF, 0xE6
		.byte  0xF4,   0,	  0,  0xC,   0,	 6
		.byte  0xFC,   9,	  0,  0xD,   0,	 6
word_14B7A8:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEA,  0xC,	  0,   0, 0xFF, 0xF4
		.byte  0xF2,  0xF,	  0,   4, 0xFF, 0xEC
		.byte  0xF2,   0,	  0, 0x14,   0,	0xC
word_14B7BC:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   8,	  0,   0, 0xFF, 0xF3
		.byte  0xF4,  0xF,	  0,   3, 0xFF, 0xF3
word_14B7CA:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   8,	  0,   0, 0xFF, 0xFB
		.byte  0xF4,  0xF,	  0,   3, 0xFF, 0xF3
		.byte  0xFC,   2,	  0, 0x13,   0, 0x13
word_14B7DE:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   4,	  0,   0, 0xFF, 0xFC
		.byte  0xF4,  0xF,	  0,   2, 0xFF, 0xF4
word_14B7EC:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   8,	  0,   0, 0xFF, 0xFC
		.byte  0xF4,  0xF,	  0,   3, 0xFF, 0xF4
		.byte  0xFC,   1,	  0, 0x13,   0, 0x14
word_14B800:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xE6,  0xB,	  0,   0, 0xFF, 0xF4
		.byte	6,   8,	  0,  0xC, 0xFF, 0xF4
		.byte   0xE,   5,	  0,  0xF, 0xFF, 0xF4
word_14B814:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xE6,  0xB,	  0,   0, 0xFF, 0xF4
		.byte	6,   8,	  0,  0xC, 0xFF, 0xF4
		.byte   0xE,   5,	  0,  0xF, 0xFF, 0xF4
word_14B828:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEE,  0xF,	  0,   0, 0xFF, 0xEB
		.byte   0xE,   0,	  0, 0x10,   0,	 3
word_14B836:	.word 1			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xEB
word_14B83E:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,  0xF,	  0,   0, 0xFF, 0xEB
		.byte   0xC,   4,	  0, 0x10, 0xFF, 0xFB
word_14B84C:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   8,	  0,   0, 0xFF, 0xEB
		.byte  0xF4,  0xE,	  0,   3, 0xFF, 0xEB
		.byte   0xC,   4,	  0,  0xF, 0xFF, 0xFB
word_14B860:	.word 1			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEE,  0xF,	  0,   0, 0xFF, 0xEB
word_14B868:	.word 1			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEF,  0xF,	  0,   0, 0xFF, 0xEB
word_14B870:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,  0xD,	  0,   0, 0xFF, 0xF0
		.byte  0xFC,   8,	  0,   8, 0xFF, 0xF0
		.byte	4,   4,	  0,  0xB, 0xFF, 0xF8
		.byte   0xC,   0,	  0,  0xD,   0,	 0
word_14B88A:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,  0xE,	  0,   0, 0xFF, 0xF0
		.byte	4,   5,	  0,  0xC, 0xFF, 0xF0
word_14B898:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   4,	  0,   0, 0xFF, 0xFC
		.byte  0xF4,  0xF,	  0,   2, 0xFF, 0xF4
		.byte   0xC,   0,	  0, 0x12, 0xFF, 0xEC
word_14B8AC:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF4,  0xC,	  0,   0, 0xFF, 0xF0
		.byte  0xFC,  0xD,	  0,   4, 0xFF, 0xE8
		.byte  0xFC,   5,	  0,  0xC,   0,	 8
word_14B8C0:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF4,  0xE,	  0,   0, 0xFF, 0xF4
		.byte  0xFC,   1,	  0,  0xC, 0xFF, 0xEC
word_14B8CE:	.word 1			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF4,  0xE,	  0,   0, 0xFF, 0xF0
word_14B8D6:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF4,  0xE,	  8,   0, 0xFF, 0xEC
		.byte  0xFC,   1,	  8,  0xC,   0,	0xC
word_14B8E4:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF4,  0xC,	  8,   0, 0xFF, 0xF0
		.byte  0xFC,  0xD,	  8,   4, 0xFF, 0xF8
		.byte  0xFC,   5,	  8,  0xC, 0xFF, 0xE8
word_14B8F8:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF4,  0xE,	  0,   0, 0xFF, 0xEB
		.byte  0xF4,   6,	  0,  0xC,   0,	0xB
word_14B906:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF4,  0xC,	  0,   0, 0xFF, 0xF6
		.byte  0xFC,  0xD,	  0,   4, 0xFF, 0xEE
		.byte  0xFC,   5,	  0,  0xC,   0,	0xE
word_14B91A:	.word 1			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF4,  0xE,	  0,   0, 0xFF, 0xF0
word_14B922:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF4,  0xC,	  8,   0, 0xFF, 0xEB
		.byte  0xFC,  0xD,	  8,   4, 0xFF, 0xF3
		.byte  0xFC,   5,	  8,  0xC, 0xFF, 0xE3
word_14B936:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF4,  0xE,	  8,   0, 0xFF, 0xF6
		.byte  0xF4,   6,	  8,  0xC, 0xFF, 0xE6
word_14B944:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEF,  0xD,	  0,   0, 0xFF, 0xF0
		.byte  0xFF,  0xD,	  0,   8, 0xFF, 0xE8
		.byte  0xFF,   5,	  0, 0x10,   0,	 8
		.byte   0xF,   8,	  0, 0x14, 0xFF, 0xE8
word_14B95E:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xE8,  0xE,	  0,   0, 0xFF, 0xF0
		.byte  0xF8,   0,	  0,  0xC, 0xFF, 0xE8
		.byte	0,  0xC,	  0,  0xD, 0xFF, 0xE8
		.byte	8,   5,	  0, 0x11, 0xFF, 0xF8
word_14B978:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF3,   4,	  0,   0, 0xFF, 0xFC
		.byte  0xFB,  0xC,	  0,   2, 0xFF, 0xF4
		.byte	3,  0xC,	  0,   6, 0xFF, 0xE4
		.byte	3,   8,	  0,  0xA,   0,	 4
word_14B992:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF4,   8,	  0,   0, 0xFF, 0xF8
		.byte  0xFC,  0xE,	  0,   3, 0xFF, 0xF0
		.byte	4,   1,	  0,  0xF, 0xFF, 0xE8
word_14B9A6:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   8,	  0,   0, 0xFF, 0xF4
		.byte  0xF4,  0xC,	  0,   3, 0xFF, 0xF4
		.byte  0xFC,  0xE,	  0,   7, 0xFF, 0xEC
		.byte  0xFC,   0,	  0, 0x13,   0,	0xC
word_14B9C0:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   8,	  0,   0, 0xFF, 0xF4
		.byte  0xF4,  0xE,	  0,   3, 0xFF, 0xF4
		.byte  0xFC,   1,	  0,  0xF, 0xFF, 0xEC
		.byte   0xC,   8,	  0, 0x11, 0xFF, 0xEC
word_14B9DA:	.word 5			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   8,	  0,   0, 0xFF, 0xF4
		.byte  0xF4,  0xC,	  0,   3, 0xFF, 0xF4
		.byte  0xFC,   0,	  0,   7, 0xFF, 0xEC
		.byte  0xFC,  0xC,	  0,   8, 0xFF, 0xF4
		.byte	4,  0xD,	  0,  0xC, 0xFF, 0xEC
word_14B9FA:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   8,	  0,   0, 0xFF, 0xF4
		.byte  0xF4,  0xE,	  0,   3, 0xFF, 0xF4
		.byte  0xFC,   0,	  0,  0xF, 0xFF, 0xEC
		.byte   0xC,   8,	  0, 0x10, 0xFF, 0xEC
word_14BA14:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,  0xB,	  0,   0, 0xFF, 0xF2
		.byte   0xC,  0xC,	  0,  0xC, 0xFF, 0xF2
word_14BA22:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,  0xB,	  0,   0, 0xFF, 0xF2
		.byte   0xC,  0xC,	  0,  0xC, 0xFF, 0xF2
word_14BA30:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,  0xB,	  0,   0, 0xFF, 0xF2
		.byte   0xC,  0xC,	  0,  0xC, 0xFF, 0xF2
word_14BA3E:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   9,	  0,   0, 0xFF, 0xF4
		.byte  0xFC,  0xE,	  0,   6, 0xFF, 0xF4
word_14BA4C:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   9,	  0,   0, 0xFF, 0xF4
		.byte  0xFC,  0xE,	  0,   6, 0xFF, 0xF4
word_14BA5A:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   9,	  0,   0, 0xFF, 0xF4
		.byte  0xFC,  0xE,	  0,   6, 0xFF, 0xF4
word_14BA68:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   8,	  0,   0, 0xFF, 0xF4
		.byte  0xF4,  0xD,	  0,   3, 0xFF, 0xF4
		.byte	4,   8,	  0,  0xB, 0xFF, 0xF4
		.byte   0xC,  0xC,	  0,  0xE, 0xFF, 0xF4
word_14BA82:	.word 5			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   8,	  0,   0, 0xFF, 0xF4
		.byte  0xF4,  0xC,	  0,   3, 0xFF, 0xF4
		.byte  0xFC,  0xC,	  0,   7, 0xFF, 0xF4
		.byte	4,   8,	  0,  0xB, 0xFF, 0xF4
		.byte   0xC,  0xC,	  0,  0xE, 0xFF, 0xF4
word_14BAA2:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   8,	  0,   0, 0xFF, 0xF4
		.byte  0xF4,  0xD,	  0,   3, 0xFF, 0xF4
		.byte	4,   8,	  0,  0xB, 0xFF, 0xF4
		.byte   0xC,  0xC,	  0,  0xE, 0xFF, 0xF4
word_14BABC:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   8,	  0,   0, 0xFF, 0xF4
		.byte  0xF4,  0xD,	  0,   3, 0xFF, 0xF4
		.byte	4,   8,	  0,  0xB, 0xFF, 0xF4
		.byte   0xC,  0xC,	  0,  0xE, 0xFF, 0xF4
word_14BAD6:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   8,	  0,   0, 0xFF, 0xF6
		.byte  0xF4,  0xD,	  0,   3, 0xFF, 0xF6
		.byte	4,   9,	  0,  0xB, 0xFF, 0xF6
word_14BAEA:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,  0xA,	  0,   0, 0xFF, 0xF7
		.byte  0xF4,   5,	  0,   9,   0,	0xF
		.byte	4,   9,	  0,  0xD, 0xFF, 0xF7
word_14BAFE:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,  0xE,	  0,   0, 0xFF, 0xF4
		.byte  0xF4,   1,	  0,  0xC,   0, 0x14
		.byte	4,   8,	  0,  0xE, 0xFF, 0xF4
		.byte   0xC,  0xC,	  0, 0x11, 0xFF, 0xF4
word_14BB18:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xED,   9,	  0,   0, 0xFF, 0xF1
		.byte  0xFD,  0xD,	  0,   6, 0xFF, 0xF1
		.byte   0xD,   4,	  0,  0xE, 0xFF, 0xF9
word_14BB2C:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF0,   8,	  0,   0, 0xFF, 0xF1
		.byte  0xF8,  0xD,	  0,   3, 0xFF, 0xF1
		.byte	8,   4,	  0,  0xB, 0xFF, 0xF9
word_14BB40:	.word 1			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xF4,  0xF,	  0,   0, 0xFF, 0xF0
word_14BB48:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEE,  0xB,	  0,   0, 0xFF, 0xF3
		.byte   0xE,   4,	  0,  0xC, 0xFF, 0xF3
word_14BB56:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEF,  0xA,	  0,   0, 0xFF, 0xF4
		.byte	7,  0xD,	  0,   9, 0xFF, 0xF4
word_14BB64:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xE8,   4,	  0,   0, 0xFF, 0xF8
		.byte  0xF0,   8,	  0,   2, 0xFF, 0xF0
		.byte  0xF8,  0xD,	  0,   5, 0xFF, 0xF0
		.byte	8,   9,	  0,  0xD, 0xFF, 0xF8
word_14BB7E:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xE8,  0xB,	  0,   0, 0xFF, 0xF4
		.byte	8,   9,	  0,  0xC, 0xFF, 0xFC
word_14BB8C:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xE8,  0xF,	  0,   0, 0xFF, 0xF0
		.byte	8,   8,	  0, 0x10, 0xFF, 0xF8
		.byte  0x10,   4,	  0, 0x13,   0,	 0
word_14BBA0:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xE8,  0xB,	  0,   0, 0xFF, 0xF4
		.byte	8,   4,	  0,  0xC, 0xFF, 0xFC
		.byte  0x10,   8,	  0,  0xE, 0xFF, 0xF4
word_14BBB4:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xE8,   9,	  0,   0, 0xFF, 0xF6
		.byte  0xF8,  0xC,	  0,   6, 0xFF, 0xEE
		.byte	0,   8,	  0,  0xA, 0xFF, 0xF6
		.byte	8,   9,	  0,  0xD, 0xFF, 0xEE
word_14BBCE:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xE8,   9,	  0,   0, 0xFF, 0xF3
		.byte  0xF8,  0xD,	  0,   6, 0xFF, 0xF3
		.byte	8,   9,	  0,  0xE, 0xFF, 0xF3
word_14BBE2:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xE8,  0xB,	  0,   0, 0xFF, 0xF4
		.byte	8,   9,	  0,  0xC, 0xFF, 0xF4
word_14BBF0:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   9,	  0,   0, 0xFF, 0xF4
		.byte  0xFC,  0xC,	  0,   6, 0xFF, 0xF4
		.byte	4,   9,	  0,  0xA, 0xFF, 0xF4
word_14BC04:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,  0xC,	  0,   0, 0xFF, 0xE9
		.byte  0xF4,   2,	  0,   4, 0xFF, 0xE9
		.byte  0xF4,  0xF,	  0,   7, 0xFF, 0xF1
word_14BC18:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,  0xC,	  0,   0, 0xFF, 0xEA
		.byte  0xF4,  0xF,	  0,   4, 0xFF, 0xEA
		.byte  0xF4,   3,	  0, 0x14,   0,	0xA
word_14BC2C:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xE8,   4,	  0,   0, 0xFF, 0xF8
		.byte  0xF0,  0xE,	  0,   2, 0xFF, 0xF0
		.byte	8,   8,	  0,  0xE, 0xFF, 0xF0
word_14BC40:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xE8,   4,	  0,   0, 0xFF, 0xF8
		.byte  0xF0,  0xE,	  0,   2, 0xFF, 0xF0
		.byte	8,   4,	  0,  0xE, 0xFF, 0xF8
word_14BC54:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xE8,  0xB,	  0,   0, 0xFF, 0xF4
		.byte	8,   8,	  0,  0xC, 0xFF, 0xF4
word_14BC62:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEB,  0xB,	  0,   0, 0xFF, 0xF4
		.byte   0xB,   0,	  0,  0xC, 0xFF, 0xFC
word_14BC70:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xE8,  0xB,	  8,   0, 0xFF, 0xF4
		.byte	8,   8,	  8,  0xC, 0xFF, 0xF4
word_14BC7E:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,   8,	  0,   0, 0xFF, 0xF0
		.byte  0xF4,  0xE,	  0,   3, 0xFF, 0xF0
		.byte   0xC,   4,	  0,  0xF, 0xFF, 0xF8
word_14BC92:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEB,   8,	  0,   0, 0xFF, 0xF0
		.byte  0xF3,  0xE,	  0,   3, 0xFF, 0xF0
		.byte   0xB,   8,	  0,  0xF, 0xFF, 0xF0
word_14BCA6:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,  0xF,	  0,   0, 0xFF, 0xF0
		.byte   0xC,   4,	  0, 0x10, 0xFF, 0xF8
word_14BCB4:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEB,   8,	  0,   0, 0xFF, 0xF8
		.byte  0xF3,  0xD,	  0,   3, 0xFF, 0xF0
		.byte	3,   8,	  0,  0xB, 0xFF, 0xF8
		.byte   0xB,   4,	  0,  0xE, 0xFF, 0xF8
word_14BCCE:	.word 3			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEC,  0xA,	  0,   0, 0xFF, 0xF4
		.byte	4,   4,	  0,   9, 0xFF, 0xFC
		.byte   0xC,   4,	  0,  0xB, 0xFF, 0xF4
word_14BCE2:	.word 4			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEB,   8,	  8,   0, 0xFF, 0xF0
		.byte  0xF3,  0xD,	  8,   3, 0xFF, 0xF0
		.byte	3,   8,	  8,  0xB, 0xFF, 0xF0
		.byte   0xB,   4,	  8,  0xE, 0xFF, 0xF8
word_14BCFC:	.word 2			/* DATA XREF: ROM:0014A8D6o*/
		.byte  0xEB,  0xE,	  0,   0, 0xFF, 0xF0
		.byte	3,   9,	  0,  0xC, 0xFF, 0xF0
