Map_2A02AA:	.word Frame_2A030E-Map_2A02AA /* ...*/
		.word Frame_2A0310-Map_2A02AA
		.word Frame_2A0318-Map_2A02AA
		.word Frame_2A0320-Map_2A02AA
		.word Frame_2A0328-Map_2A02AA
		.word Frame_2A0330-Map_2A02AA
		.word Frame_2A0338-Map_2A02AA
		.word Frame_2A0340-Map_2A02AA
		.word Frame_2A0348-Map_2A02AA
		.word Frame_2A0350-Map_2A02AA
		.word Frame_2A0358-Map_2A02AA
		.word Frame_2A0360-Map_2A02AA
		.word Frame_2A0368-Map_2A02AA
		.word Frame_2A0370-Map_2A02AA
		.word Frame_2A0378-Map_2A02AA
		.word Frame_2A0380-Map_2A02AA
		.word Frame_2A0388-Map_2A02AA
		.word Frame_2A0390-Map_2A02AA
		.word Frame_2A0398-Map_2A02AA
		.word Frame_2A03A0-Map_2A02AA
		.word Frame_2A03A8-Map_2A02AA
		.word Frame_2A03B0-Map_2A02AA
		.word Frame_2A03B8-Map_2A02AA
		.word Frame_2A03C0-Map_2A02AA
		.word Frame_2A03C8-Map_2A02AA
		.word Frame_2A03D0-Map_2A02AA
		.word Frame_2A03D8-Map_2A02AA
		.word Frame_2A03E0-Map_2A02AA
		.word Frame_2A03E8-Map_2A02AA
		.word Frame_2A03F0-Map_2A02AA
		.word Frame_2A03F8-Map_2A02AA
		.word Frame_2A0400-Map_2A02AA
		.word Frame_2A0408-Map_2A02AA
		.word Frame_2A0410-Map_2A02AA
		.word Frame_2A0418-Map_2A02AA
		.word Frame_2A0420-Map_2A02AA
		.word Frame_2A0428-Map_2A02AA
		.word Frame_2A0430-Map_2A02AA
		.word Frame_2A0438-Map_2A02AA
		.word Frame_2A0440-Map_2A02AA
		.word Frame_2A0448-Map_2A02AA
		.word Frame_2A0450-Map_2A02AA
		.word Frame_2A0458-Map_2A02AA
		.word Frame_2A0460-Map_2A02AA
		.word Frame_2A0468-Map_2A02AA
		.word Frame_2A0470-Map_2A02AA
		.word Frame_2A0478-Map_2A02AA
		.word Frame_2A0480-Map_2A02AA
		.word Frame_2A0488-Map_2A02AA
		.word Frame_2A0490-Map_2A02AA
Frame_2A030E:	.word 0
Frame_2A0310:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A0318:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A0320:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A0328:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A0330:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A0338:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A0340:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A0348:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A0350:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A0358:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A0360:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A0368:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A0370:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A0378:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A0380:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A0388:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A0390:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A0398:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A03A0:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A03A8:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A03B0:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A03B8:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A03C0:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A03C8:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A03D0:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A03D8:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A03E0:	.word 1
		.byte 0xF4,  6,  0,  0,0xFF,0xF8
Frame_2A03E8:	.word 1
		.byte 0xF4,  6,  0,  0,0xFF,0xF8
Frame_2A03F0:	.word 1
		.byte 0xF4,  6,  0,  0,0xFF,0xF8
Frame_2A03F8:	.word 1
		.byte 0xF4,  6,  0,  0,0xFF,0xF8
Frame_2A0400:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A0408:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A0410:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A0418:	.word 1
		.byte 0xF4, 0xE,  0,  0,0xFF,0xF0
Frame_2A0420:	.word 1
		.byte 0xFC,  9,  0,  0,0xFF,0xF4
Frame_2A0428:	.word 1
		.byte 0xFC,  9,  0,  0,0xFF,0xF4
Frame_2A0430:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A0438:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A0440:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A0448:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A0450:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A0458:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A0460:	.word 1
		.byte 0xFC,  5,  0,  0,0xFF,0xF8
Frame_2A0468:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A0470:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A0478:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A0480:	.word 1
		.byte 0xF8, 0xD,  0,  0,0xFF,0xF0
Frame_2A0488:	.word 1
		.byte 0xF8,  9,  0,  0,0xFF,0xF4
Frame_2A0490:	.word 1
		.byte 0xF0, 0xB,  0,  0,0xFF,0xF4
