Map_3616C0:	.word Frame_3616CA-Map_3616C0
		.word Frame_3616F0-Map_3616C0
		.word Frame_361716-Map_3616C0
		.word Frame_361748-Map_3616C0
		.word Frame_36176E-Map_3616C0
Frame_3616CA:	.word 6
		.byte 0xEA,  6,  0,  7,0xFF,0xF0
		.byte 0xEA,  6,  8,  7,  0,  0
		.byte   8,  0,  0,  0,0xFF,0xE8
		.byte   0,  6,  0,  1,0xFF,0xF0
		.byte   0,  6,  8,  1,  0,  0
		.byte   8,  0,  8,  0,  0,0x10
Frame_3616F0:	.word 6
		.byte 0xEA,  6,  0, 0xD,0xFF,0xF0
		.byte 0xEA,  6,  8, 0xD,  0,  0
		.byte   8,  0,  0,  0,0xFF,0xE8
		.byte   0,  6,  0,  1,0xFF,0xF0
		.byte   0,  6,  8,  1,  0,  0
		.byte   8,  0,  8,  0,  0,0x10
Frame_361716:	.word 8
		.byte 0xE2,  0,  0,0x13,0xFF,0xF8
		.byte 0xEA,  6,  0,0x14,0xFF,0xF0
		.byte 0xE2,  0,  8,0x13,  0,  0
		.byte 0xEA,  6,  8,0x14,  0,  0
		.byte   8,  0,  0,  0,0xFF,0xE8
		.byte   0,  6,  0,  1,0xFF,0xF0
		.byte   0,  6,  8,  1,  0,  0
		.byte   8,  0,  8,  0,  0,0x10
Frame_361748:	.word 6
		.byte 0xEC,  6,  0,  7,0xFF,0xF0
		.byte 0xEC,  6,  8,  7,  0,  0
		.byte   8,  0,  0,  0,0xFF,0xE8
		.byte   0,  6,  0,  1,0xFF,0xF0
		.byte   0,  6,  8,  1,  0,  0
		.byte   8,  0,  8,  0,  0,0x10
Frame_36176E:	.word 1
		.byte 0xF8,  5,  0,0x1A,0xFF,0xF8
