		.word	word_3596A-Map_MGZTopPlatform
		.word word_35978-Map_MGZTopPlatform
		.word word_35986-Map_MGZTopPlatform
word_3596A:	.word 2			/*  DATA XREF: ROM:00035964o */
		.byte  0xF4,  0xA,	  0,   0, 0xFF, 0xE8
		.byte  0xF4,  0xA,	  0,   9,   0,	 0
word_35978:	.word 2			/*  DATA XREF: ROM:00035964o */
		.byte  0xF4,  0xA,	  0, 0x12, 0xFF, 0xE8
		.byte  0xF4,  0xA,	  0, 0x1B,   0,	 0
word_35986:	.word 1			/*  DATA XREF: ROM:00035964o */
		.byte	8,   9,	  0,   0, 0xFF, 0xF4
