Map_83FFC:		.word word_84008-Map_83FFC
		.word word_84010-Map_83FFC
		.word word_84018-Map_83FFC
		.word word_84020-Map_83FFC
		.word word_84028-Map_83FFC
		.word word_84030-Map_83FFC
word_84008:	.word 1			/*  DATA XREF: ROM:00083FFCo */
		.byte  0xF8,   5,	  0,   0, 0xFF, 0xF8
word_84010:	.word 1			/*  DATA XREF: ROM:00083FFCo */
		.byte  0xF4,  0xA,	  0,   4, 0xFF, 0xF4
word_84018:	.word 1			/*  DATA XREF: ROM:00083FFCo */
		.byte  0xF4,  0xA,	  0,  0xD, 0xFF, 0xF4
word_84020:	.word 1			/*  DATA XREF: ROM:00083FFCo */
		.byte  0xF4,  0xA,	  0, 0x16, 0xFF, 0xF4
word_84028:	.word 1			/*  DATA XREF: ROM:00083FFCo */
		.byte  0xF3,  0xA,	  0, 0x1F, 0xFF, 0xF4
word_84030:	.word 1			/*  DATA XREF: ROM:00083FFCo */
		.byte  0xF6,   9,	  0, 0x28, 0xFF, 0xF4
