		.word AniSonic2P00-AniSonic2P
		.word AniSonic2P01-AniSonic2P
		.word AniSonic2P02-AniSonic2P
		.word AniSonic2P03-AniSonic2P
		.word AniSonic2P04-AniSonic2P
		.word AniSonic2P05-AniSonic2P
		.word AniSonic2P05-AniSonic2P
		.word AniSonic2P05-AniSonic2P
		.word AniSonic2P08-AniSonic2P
		.word AniSonic2P09-AniSonic2P
		.word AniSonic2P05-AniSonic2P
		.word AniSonic2P05-AniSonic2P
		.word AniSonic2P05-AniSonic2P
		.word AniSonic2P0D-AniSonic2P
		.word AniSonic2P0E-AniSonic2P
		.word AniSonic2P0F-AniSonic2P
		.word AniSonic2P10-AniSonic2P
		.word AniSonic2P11-AniSonic2P
		.word AniSonic2P12-AniSonic2P
		.word AniSonic2P13-AniSonic2P
		.word AniSonic2P14-AniSonic2P
		.word AniSonic2P15-AniSonic2P
		.word AniSonic2P16-AniSonic2P
		.word AniSonic2P17-AniSonic2P
		.word AniSonic2P18-AniSonic2P
		.word AniSonic2P19-AniSonic2P
		.word AniSonic2P19-AniSonic2P
		.word AniSonic2P1B-AniSonic2P
		.word AniSonic2P1C-AniSonic2P
		.word AniSonic2P05-AniSonic2P
		.word AniSonic2P05-AniSonic2P
		.word AniSonic1F-AniSonic2P
		.word AniSonic2P20-AniSonic2P
		.word AniSonic2P21-AniSonic2P
		.word AniSonic2P22-AniSonic2P
		.word AniSonic2P23-AniSonic2P
AniKnuckles2P:	.word AniSonic2P00-AniKnuckles2P
		.word AniSonic2P01-AniKnuckles2P
		.word AniSonic2P02-AniKnuckles2P
		.word AniSonic2P03-AniKnuckles2P
		.word AniKnuckles2P04-AniKnuckles2P
		.word AniSonic2P05-AniKnuckles2P
		.word AniSonic2P05-AniKnuckles2P
		.word AniSonic2P05-AniKnuckles2P
		.word AniSonic2P08-AniKnuckles2P
		.word AniSonic2P09-AniKnuckles2P
		.word AniSonic2P05-AniKnuckles2P
		.word AniSonic2P05-AniKnuckles2P
		.word AniSonic2P05-AniKnuckles2P
		.word AniSonic2P0D-AniKnuckles2P
		.word AniSonic2P0E-AniKnuckles2P
		.word AniSonic2P0F-AniKnuckles2P
		.word AniSonic2P10-AniKnuckles2P
		.word AniSonic2P11-AniKnuckles2P
		.word AniSonic2P12-AniKnuckles2P
		.word AniSonic2P13-AniKnuckles2P
		.word AniSonic2P14-AniKnuckles2P
		.word AniSonic2P15-AniKnuckles2P
		.word AniSonic2P16-AniKnuckles2P
		.word AniSonic2P17-AniKnuckles2P
		.word AniSonic2P18-AniKnuckles2P
		.word AniSonic2P19-AniKnuckles2P
		.word AniSonic2P19-AniKnuckles2P
		.word AniSonic2P1B-AniKnuckles2P
		.word AniSonic2P1C-AniKnuckles2P
		.word AniSonic2P05-AniKnuckles2P
		.word AniSonic2P05-AniKnuckles2P
		.word AniSonic1F-AniKnuckles2P
		.word AniSonic2P20-AniKnuckles2P
		.word AniSonic2P21-AniKnuckles2P
		.word AniSonic2P22-AniKnuckles2P
		.word AniSonic2P23-AniKnuckles2P
AniSonic2P00:	.byte  0xFF,   1,   2,   3,   2, 0xFF
AniSonic2P01:	.byte  0xFF,  0xD,  0xE, 0xFF, 0xFF, 0xFF
AniSonic2P02:	.byte  0xFE, 0x29, 0x28, 0x2A, 0x28, 0xFF
AniSonic2P03:	.byte  0xFE, 0x29, 0x28, 0x2A, 0x28, 0xFF
AniSonic2P04:	.byte  0xFD, 0x25, 0x26, 0xFF, 0xFF, 0xFF
AniKnuckles2P04:.byte  0xFD, 0x25, 0x26, 0x27, 0x26, 0xFF
AniSonic2P05:	.byte    7, 0x1B, 0x1B, 0x1B, 0x1B, 0x1B, 0x1B, 0x1B, 0x1B, 0x1C, 0x1C, 0x1C, 0x1C, 0x1C, 0x1C, 0x1D
		.byte  0x1E, 0x1D, 0x1E, 0x1D, 0x1E, 0x1D, 0x1E, 0x1D, 0x1E, 0xFE, 0x10
AniSonic2P08:	.byte    5, 0x2B, 0xFF
AniSonic2P09:	.byte    0, 0x23, 0x24, 0xFF
AniSonic2P0D:	.byte    5, 0x22, 0x22, 0x22, 0x22, 0xFD,   0
AniSonic2P0E:	.byte    7, 0x15, 0xFF
AniSonic2P0F:	.byte    7, 0x15, 0xFF
AniSonic2P10:	.byte  0x2F, 0x15, 0xFD,   0
AniSonic2P11:	.byte    1, 0x15, 0xFF
AniSonic2P12:	.byte   0xF, 0x15, 0xFF
AniSonic2P13:	.byte   0xF, 0x1F, 0xFF
AniSonic2P14:	.byte  0x13, 0x15, 0xFF
AniSonic2P15:	.byte   0xB, 0x15, 0xFF
AniSonic2P16:	.byte  0x20, 0x20, 0xFF
AniSonic2P17:	.byte  0x20, 0x20, 0xFF
AniSonic2P18:	.byte  0x20, 0x20, 0xFF
AniSonic2P19:	.byte  0x40, 0x21, 0xFF
AniSonic2P1B:	.byte    9, 0x21, 0xFF
AniSonic2P1C:	.byte  0x77,   0, 0xFF
AniSonic2P20:	.byte    9, 0x1B, 0xFF
AniSonic2P21:	.byte    3, 0x1B, 0xFD,   0
AniSonic2P22:	.byte   0xB, 0x1B, 0xFF
AniSonic2P23:	.byte   0xB, 0x1B, 0xFF
		.balign 2
