		.word word_20F24-DPLC_SurfboardIntro
		.word word_20F26-DPLC_SurfboardIntro
		.word word_20F2E-DPLC_SurfboardIntro
		.word word_20F36-DPLC_SurfboardIntro
		.word word_20F40-DPLC_SurfboardIntro
		.word word_20F48-DPLC_SurfboardIntro
		.word word_20F50-DPLC_SurfboardIntro
		.word word_20F5A-DPLC_SurfboardIntro
		.word word_20F64-DPLC_SurfboardIntro
		.word word_20F6C-DPLC_SurfboardIntro
word_20F24:	.word 0
word_20F26:	.word 3
		.word 0xF000
		.word 0x7010
		.word 0x7018
word_20F2E:	.word 3
		.word 0xF020
		.word 0x7030
		.word 0x7038
word_20F36:	.word 4
		.word 0xF040
		.word 0x5050
		.word 0x7056
		.word 0x705E
word_20F40:	.word 3
		.word 0xB066
		.word 0xB072
		.word 0xB07E
word_20F48:	.word 3
		.word 0xB08A
		.word 0xB096
		.word 0xB0A2
word_20F50:	.word 4
		.word 0xF0AE
		.word 0x50BE
		.word 0x70C4
		.word 0x70CC
word_20F5A:	.word 4
		.word 0x10D4
		.word 0xF0D6
		.word 0xE6
		.word 0x20E7
word_20F64:	.word 3
		.word 0x50EA
		.word 0xF0F0
		.word 0x1100
word_20F6C:	.word 3
		.word 0x5102
		.word 0xF108
		.word 0x2118
