Map_29FC3A:	.word Frame_29FC92-Map_29FC3A /* ...*/
		.word Frame_29FC94-Map_29FC3A
		.word Frame_29FC9C-Map_29FC3A
		.word Frame_29FCA4-Map_29FC3A
		.word Frame_29FCAC-Map_29FC3A
		.word Frame_29FCB4-Map_29FC3A
		.word Frame_29FCBC-Map_29FC3A
		.word Frame_29FCC4-Map_29FC3A
		.word Frame_29FCCC-Map_29FC3A
		.word Frame_29FCD4-Map_29FC3A
		.word Frame_29FCDC-Map_29FC3A
		.word Frame_29FCE4-Map_29FC3A
		.word Frame_29FCEC-Map_29FC3A
		.word Frame_29FCF4-Map_29FC3A
		.word Frame_29FCFC-Map_29FC3A
		.word Frame_29FD04-Map_29FC3A
		.word Frame_29FD0C-Map_29FC3A
		.word Frame_29FD14-Map_29FC3A
		.word Frame_29FD1C-Map_29FC3A
		.word Frame_29FD24-Map_29FC3A
		.word Frame_29FD2C-Map_29FC3A
		.word Frame_29FD34-Map_29FC3A
		.word Frame_29FD3C-Map_29FC3A
		.word Frame_29FD44-Map_29FC3A
		.word Frame_29FD4C-Map_29FC3A
		.word Frame_29FD54-Map_29FC3A
		.word Frame_29FD5C-Map_29FC3A
		.word Frame_29FD64-Map_29FC3A
		.word Frame_29FD6C-Map_29FC3A
		.word Frame_29FD74-Map_29FC3A
		.word Frame_29FD7C-Map_29FC3A
		.word Frame_29FD84-Map_29FC3A
		.word Frame_29FD8C-Map_29FC3A
		.word Frame_29FD94-Map_29FC3A
		.word Frame_29FD9C-Map_29FC3A
		.word Frame_29FDA4-Map_29FC3A
		.word Frame_29FDAC-Map_29FC3A
		.word Frame_29FDB4-Map_29FC3A
		.word Frame_29FDBC-Map_29FC3A
		.word Frame_29FDBC-Map_29FC3A
		.word Frame_29FDC4-Map_29FC3A
		.word Frame_29FDCC-Map_29FC3A
		.word Frame_29FDD4-Map_29FC3A
		.word Frame_29FDDC-Map_29FC3A
Frame_29FC92:	.word 0
Frame_29FC94:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_29FC9C:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_29FCA4:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_29FCAC:	.word 1
		.byte 0xF0, 0xB,  0,  0,0xFF,0xF4
Frame_29FCB4:	.word 1
		.byte 0xF0, 0xB,  0,  0,0xFF,0xF4
Frame_29FCBC:	.word 1
		.byte 0xF0, 0xB,  0,  0,0xFF,0xF4
Frame_29FCC4:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_29FCCC:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_29FCD4:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_29FCDC:	.word 1
		.byte 0xF4, 0xE,  0,  0,0xFF,0xF0
Frame_29FCE4:	.word 1
		.byte 0xF4, 0xE,  0,  0,0xFF,0xF0
Frame_29FCEC:	.word 1
		.byte 0xF4, 0xE,  0,  0,0xFF,0xF0
Frame_29FCF4:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_29FCFC:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_29FD04:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_29FD0C:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_29FD14:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_29FD1C:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_29FD24:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_29FD2C:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_29FD34:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_29FD3C:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_29FD44:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_29FD4C:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_29FD54:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_29FD5C:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_29FD64:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_29FD6C:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_29FD74:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_29FD7C:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_29FD84:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_29FD8C:	.word 1
		.byte 0xF0, 0xB,  0,  0,0xFF,0xF4
Frame_29FD94:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_29FD9C:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_29FDA4:	.word 1
		.byte 0xFC,  9,  0,  0,0xFF,0xF4
Frame_29FDAC:	.word 1
		.byte 0xFC,  9,  0,  0,0xFF,0xF4
Frame_29FDB4:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_29FDBC:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_29FDC4:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_29FDCC:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_29FDD4:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_29FDDC:	.word 1
		.byte 0xFC,  9,  0,  0,0xFF,0xF4
