Map_HyperSonic_1948C:		.word word_19498-Map_HyperSonic_1948C
		.word word_194A0-Map_HyperSonic_1948C
		.word word_194A8-Map_HyperSonic_1948C
		.word word_194B6-Map_HyperSonic_1948C
		.word word_194BE-Map_HyperSonic_1948C
		.word word_194C6-Map_HyperSonic_1948C
word_19498:	.word 1			/* DATA XREF: ROM:0001948Co*/
		.byte  0xF8,   5,	  0,   0, 0xFF, 0xF8
word_194A0:	.word 1			/* DATA XREF: ROM:0001948Co*/
		.byte  0xF8,   5,	  0,   4, 0xFF, 0xF8
word_194A8:	.word 2			/* DATA XREF: ROM:0001948Co*/
		.byte  0xF0,  0xD,	  0,   8, 0xFF, 0xF0
		.byte	0,  0xD,	0x10,   8, 0xFF, 0xF0
word_194B6:	.word 1			/* DATA XREF: ROM:0001948Co*/
		.byte  0xF8,   5,	  0, 0x10, 0xFF, 0xF8
word_194BE:	.word 1			/* DATA XREF: ROM:0001948Co*/
		.byte  0xF4,   6,	  0, 0x14, 0xFF, 0xF8
word_194C6:	.word 1			/* DATA XREF: ROM:0001948Co*/
		.byte  0xF4,  0xA,	  0, 0x1A, 0xFF, 0xF4
