		.word word_142C14-PLC_Sonic
		.word word_142C16-PLC_Sonic
		.word word_142C1E-PLC_Sonic
		.word word_142C26-PLC_Sonic
		.word word_142C2E-PLC_Sonic
		.word word_142C34-PLC_Sonic
		.word word_142C3C-PLC_Sonic
		.word word_142C44-PLC_Sonic
		.word word_142C4C-PLC_Sonic
		.word word_142C52-PLC_Sonic
		.word word_142C5C-PLC_Sonic
		.word word_142C66-PLC_Sonic
		.word word_142C70-PLC_Sonic
		.word word_142C7A-PLC_Sonic
		.word word_142C84-PLC_Sonic
		.word word_142C8E-PLC_Sonic
		.word word_142C98-PLC_Sonic
		.word word_142CA2-PLC_Sonic
		.word word_142CAA-PLC_Sonic
		.word word_142CB2-PLC_Sonic
		.word word_142CBA-PLC_Sonic
		.word word_142CC0-PLC_Sonic
		.word word_142CC8-PLC_Sonic
		.word word_142CD2-PLC_Sonic
		.word word_142CDA-PLC_Sonic
		.word word_142CE0-PLC_Sonic
		.word word_142CEA-PLC_Sonic
		.word word_142CF4-PLC_Sonic
		.word word_142CFE-PLC_Sonic
		.word word_142D08-PLC_Sonic
		.word word_142D12-PLC_Sonic
		.word word_142D1C-PLC_Sonic
		.word word_142D26-PLC_Sonic
		.word word_142D30-PLC_Sonic
		.word word_142D36-PLC_Sonic
		.word word_142D3C-PLC_Sonic
		.word word_142D42-PLC_Sonic
		.word word_142D48-PLC_Sonic
		.word word_142D52-PLC_Sonic
		.word word_142D58-PLC_Sonic
		.word word_142D62-PLC_Sonic
		.word word_142D68-PLC_Sonic
		.word word_142D6E-PLC_Sonic
		.word word_142D74-PLC_Sonic
		.word word_142D7A-PLC_Sonic
		.word word_142D80-PLC_Sonic
		.word word_142D88-PLC_Sonic
		.word word_142D8E-PLC_Sonic
		.word word_142D96-PLC_Sonic
		.word word_142D9C-PLC_Sonic
		.word word_142DA4-PLC_Sonic
		.word word_142DAE-PLC_Sonic
		.word word_142DB8-PLC_Sonic
		.word word_142DC2-PLC_Sonic
		.word word_142DCC-PLC_Sonic
		.word word_142DD4-PLC_Sonic
		.word word_142DDA-PLC_Sonic
		.word word_142DE0-PLC_Sonic
		.word word_142DE8-PLC_Sonic
		.word word_142DF2-PLC_Sonic
		.word word_142DF8-PLC_Sonic
		.word word_142DFE-PLC_Sonic
		.word word_142E06-PLC_Sonic
		.word word_142E0A-PLC_Sonic
		.word word_142E12-PLC_Sonic
		.word word_142E1C-PLC_Sonic
		.word word_142E26-PLC_Sonic
		.word word_142E30-PLC_Sonic
		.word word_142E36-PLC_Sonic
		.word word_142E3A-PLC_Sonic
		.word word_142E40-PLC_Sonic
		.word word_142E44-PLC_Sonic
		.word word_142E4A-PLC_Sonic
		.word word_142E52-PLC_Sonic
		.word word_142E5C-PLC_Sonic
		.word word_142E66-PLC_Sonic
		.word word_142E6E-PLC_Sonic
		.word word_142E76-PLC_Sonic
		.word word_142E7E-PLC_Sonic
		.word word_142E82-PLC_Sonic
		.word word_142E8C-PLC_Sonic
		.word word_142E96-PLC_Sonic
		.word word_142E9C-PLC_Sonic
		.word word_142EA4-PLC_Sonic
		.word word_142EAC-PLC_Sonic
		.word word_142EB2-PLC_Sonic
		.word word_142EBC-PLC_Sonic
		.word word_142EC4-PLC_Sonic
		.word word_142ECA-PLC_Sonic
		.word word_142ED0-PLC_Sonic
		.word word_142EDA-PLC_Sonic
		.word word_142EE2-PLC_Sonic
		.word word_142EE8-PLC_Sonic
		.word word_142EF0-PLC_Sonic
		.word word_142EF4-PLC_Sonic
		.word word_142EFA-PLC_Sonic
		.word word_142F02-PLC_Sonic
		.word word_142F06-PLC_Sonic
		.word word_142F0C-PLC_Sonic
		.word word_142F12-PLC_Sonic
		.word word_142F1A-PLC_Sonic
		.word word_142F1E-PLC_Sonic
		.word word_142F24-PLC_Sonic
		.word word_142F2C-PLC_Sonic
		.word word_142F30-PLC_Sonic
		.word word_142F36-PLC_Sonic
		.word word_142F3C-PLC_Sonic
		.word word_142F46-PLC_Sonic
		.word word_142F4E-PLC_Sonic
		.word word_142F56-PLC_Sonic
		.word word_142F5C-PLC_Sonic
		.word word_142F64-PLC_Sonic
		.word word_142F6C-PLC_Sonic
		.word word_142F74-PLC_Sonic
		.word word_142F7A-PLC_Sonic
		.word word_142F84-PLC_Sonic
		.word word_142F8C-PLC_Sonic
		.word word_142F94-PLC_Sonic
		.word word_142F9A-PLC_Sonic
		.word word_142FA2-PLC_Sonic
		.word word_142FA6-PLC_Sonic
		.word word_142FB0-PLC_Sonic
		.word word_142FBA-PLC_Sonic
		.word word_142FC2-PLC_Sonic
		.word word_142FCC-PLC_Sonic
		.word word_142FD6-PLC_Sonic
		.word word_142FE0-PLC_Sonic
		.word word_142FE8-PLC_Sonic
		.word word_142FF2-PLC_Sonic
		.word word_142FFC-PLC_Sonic
		.word word_143006-PLC_Sonic
		.word word_14300E-PLC_Sonic
		.word word_143018-PLC_Sonic
		.word word_143020-PLC_Sonic
		.word word_143026-PLC_Sonic
		.word word_14302E-PLC_Sonic
		.word word_143034-PLC_Sonic
		.word word_14303A-PLC_Sonic
		.word word_143040-PLC_Sonic
		.word word_143046-PLC_Sonic
		.word word_14304C-PLC_Sonic
		.word word_143054-PLC_Sonic
		.word word_14305C-PLC_Sonic
		.word word_143062-PLC_Sonic
		.word word_14306A-PLC_Sonic
		.word word_143074-PLC_Sonic
		.word word_14307E-PLC_Sonic
		.word word_143088-PLC_Sonic
		.word word_14308E-PLC_Sonic
		.word word_14309A-PLC_Sonic
		.word word_1430A6-PLC_Sonic
		.word word_1430AA-PLC_Sonic
		.word word_1430AE-PLC_Sonic
		.word word_1430B2-PLC_Sonic
		.word word_1430B6-PLC_Sonic
		.word word_1430BA-PLC_Sonic
		.word word_1430C0-PLC_Sonic
		.word word_1430C6-PLC_Sonic
		.word word_1430D0-PLC_Sonic
		.word word_1430DA-PLC_Sonic
		.word word_1430E4-PLC_Sonic
		.word word_1430EC-PLC_Sonic
		.word word_1430F4-PLC_Sonic
		.word word_1430FE-PLC_Sonic
		.word word_143106-PLC_Sonic
		.word word_143110-PLC_Sonic
		.word word_143118-PLC_Sonic
		.word word_143122-PLC_Sonic
		.word word_14312A-PLC_Sonic
		.word word_143132-PLC_Sonic
		.word word_14313A-PLC_Sonic
		.word word_143142-PLC_Sonic
		.word word_14314A-PLC_Sonic
		.word word_143154-PLC_Sonic
		.word word_14315E-PLC_Sonic
		.word word_143168-PLC_Sonic
		.word word_143172-PLC_Sonic
		.word word_143178-PLC_Sonic
		.word word_143180-PLC_Sonic
		.word word_143188-PLC_Sonic
		.word word_143190-PLC_Sonic
		.word word_143198-PLC_Sonic
		.word word_1431A0-PLC_Sonic
		.word word_1431A8-PLC_Sonic
		.word word_1431B0-PLC_Sonic
		.word word_1431B8-PLC_Sonic
		.word word_1431C0-PLC_Sonic
		.word word_1431CA-PLC_Sonic
		.word word_1431D2-PLC_Sonic
		.word word_1431DC-PLC_Sonic
		.word word_1431E6-PLC_Sonic
		.word word_1431F0-PLC_Sonic
		.word word_1431FA-PLC_Sonic
		.word word_143204-PLC_Sonic
		.word word_14320A-PLC_Sonic
		.word word_143214-PLC_Sonic
		.word word_14321E-PLC_Sonic
		.word word_143228-PLC_Sonic
		.word word_143230-PLC_Sonic
		.word word_14323A-PLC_Sonic
		.word word_143244-PLC_Sonic
		.word word_14324C-PLC_Sonic
		.word word_143254-PLC_Sonic
		.word word_14324C-PLC_Sonic
		.word word_143244-PLC_Sonic
		.word word_14325A-PLC_Sonic
		.word word_143260-PLC_Sonic
		.word word_14325A-PLC_Sonic
		.word word_143266-PLC_Sonic
		.word word_14326E-PLC_Sonic
		.word word_143466-PLC_Sonic
		.word word_14346A-PLC_Sonic
		.word word_143472-PLC_Sonic
		.word word_143478-PLC_Sonic
		.word word_143480-PLC_Sonic
		.word word_143276-PLC_Sonic
		.word word_14327E-PLC_Sonic
		.word word_143286-PLC_Sonic
PLC_SuperSonic: .word word_143290-PLC_SuperSonic
		.word word_143292-PLC_SuperSonic
		.word word_14329A-PLC_SuperSonic
		.word word_1432A2-PLC_SuperSonic
		.word word_1432AA-PLC_SuperSonic
		.word word_1432B2-PLC_SuperSonic
		.word word_1432BC-PLC_SuperSonic
		.word word_1432C6-PLC_SuperSonic
		.word word_1432CE-PLC_SuperSonic
		.word word_1432D4-PLC_SuperSonic
		.word word_1432DE-PLC_SuperSonic
		.word word_1432E8-PLC_SuperSonic
		.word word_1432F2-PLC_SuperSonic
		.word word_1432FC-PLC_SuperSonic
		.word word_143306-PLC_SuperSonic
		.word word_143310-PLC_SuperSonic
		.word word_14331A-PLC_SuperSonic
		.word word_143324-PLC_SuperSonic
		.word word_14332C-PLC_SuperSonic
		.word word_143334-PLC_SuperSonic
		.word word_14333C-PLC_SuperSonic
		.word word_143344-PLC_SuperSonic
		.word word_14334E-PLC_SuperSonic
		.word word_143358-PLC_SuperSonic
		.word word_143360-PLC_SuperSonic
		.word word_143366-PLC_SuperSonic
		.word word_143370-PLC_SuperSonic
		.word word_14337A-PLC_SuperSonic
		.word word_143384-PLC_SuperSonic
		.word word_14338E-PLC_SuperSonic
		.word word_143398-PLC_SuperSonic
		.word word_1433A2-PLC_SuperSonic
		.word word_1433AC-PLC_SuperSonic
		.word word_1433B6-PLC_SuperSonic
		.word word_1433C0-PLC_SuperSonic
		.word word_1433B6-PLC_SuperSonic
		.word word_1433C0-PLC_SuperSonic
		.word word_1433CA-PLC_SuperSonic
		.word word_1433D4-PLC_SuperSonic
		.word word_1433CA-PLC_SuperSonic
		.word word_1433D4-PLC_SuperSonic
		.word word_1433DE-PLC_SuperSonic
		.word word_1433E8-PLC_SuperSonic
		.word word_1433DE-PLC_SuperSonic
		.word word_1433E8-PLC_SuperSonic
		.word word_1433F2-PLC_SuperSonic
		.word word_1433FC-PLC_SuperSonic
		.word word_1433F2-PLC_SuperSonic
		.word word_1433FC-PLC_SuperSonic
		.word word_142D9C-PLC_SuperSonic
		.word word_142DA4-PLC_SuperSonic
		.word word_142DAE-PLC_SuperSonic
		.word word_142DB8-PLC_SuperSonic
		.word word_142DC2-PLC_SuperSonic
		.word word_142DCC-PLC_SuperSonic
		.word word_142DD4-PLC_SuperSonic
		.word word_142DDA-PLC_SuperSonic
		.word word_142DE0-PLC_SuperSonic
		.word word_142DE8-PLC_SuperSonic
		.word word_142DF2-PLC_SuperSonic
		.word word_142DF8-PLC_SuperSonic
		.word word_142DFE-PLC_SuperSonic
		.word word_142E06-PLC_SuperSonic
		.word word_142E0A-PLC_SuperSonic
		.word word_142E12-PLC_SuperSonic
		.word word_142E1C-PLC_SuperSonic
		.word word_142E26-PLC_SuperSonic
		.word word_142E30-PLC_SuperSonic
		.word word_142E36-PLC_SuperSonic
		.word word_142E3A-PLC_SuperSonic
		.word word_142E40-PLC_SuperSonic
		.word word_142E44-PLC_SuperSonic
		.word word_142E4A-PLC_SuperSonic
		.word word_142E52-PLC_SuperSonic
		.word word_142E5C-PLC_SuperSonic
		.word word_142E66-PLC_SuperSonic
		.word word_142E6E-PLC_SuperSonic
		.word word_142E76-PLC_SuperSonic
		.word word_142E7E-PLC_SuperSonic
		.word word_142E82-PLC_SuperSonic
		.word word_142E8C-PLC_SuperSonic
		.word word_142E96-PLC_SuperSonic
		.word word_142E9C-PLC_SuperSonic
		.word word_142EA4-PLC_SuperSonic
		.word word_142EAC-PLC_SuperSonic
		.word word_142EB2-PLC_SuperSonic
		.word word_142EBC-PLC_SuperSonic
		.word word_142EC4-PLC_SuperSonic
		.word word_142ECA-PLC_SuperSonic
		.word word_142ED0-PLC_SuperSonic
		.word word_142EDA-PLC_SuperSonic
		.word word_142EE2-PLC_SuperSonic
		.word word_142EE8-PLC_SuperSonic
		.word word_142EF0-PLC_SuperSonic
		.word word_142EF4-PLC_SuperSonic
		.word word_142EFA-PLC_SuperSonic
		.word word_142F02-PLC_SuperSonic
		.word word_142F06-PLC_SuperSonic
		.word word_142F0C-PLC_SuperSonic
		.word word_142F12-PLC_SuperSonic
		.word word_142F1A-PLC_SuperSonic
		.word word_142F1E-PLC_SuperSonic
		.word word_142F24-PLC_SuperSonic
		.word word_142F2C-PLC_SuperSonic
		.word word_142F30-PLC_SuperSonic
		.word word_142F36-PLC_SuperSonic
		.word word_142F3C-PLC_SuperSonic
		.word word_142F46-PLC_SuperSonic
		.word word_142F4E-PLC_SuperSonic
		.word word_142F56-PLC_SuperSonic
		.word word_142F5C-PLC_SuperSonic
		.word word_142F64-PLC_SuperSonic
		.word word_142F6C-PLC_SuperSonic
		.word word_142F74-PLC_SuperSonic
		.word word_142F7A-PLC_SuperSonic
		.word word_142F84-PLC_SuperSonic
		.word word_142F8C-PLC_SuperSonic
		.word word_142F94-PLC_SuperSonic
		.word word_142F9A-PLC_SuperSonic
		.word word_142FA2-PLC_SuperSonic
		.word word_142FA6-PLC_SuperSonic
		.word word_142FB0-PLC_SuperSonic
		.word word_142FBA-PLC_SuperSonic
		.word word_142FC2-PLC_SuperSonic
		.word word_142FCC-PLC_SuperSonic
		.word word_142FD6-PLC_SuperSonic
		.word word_142FE0-PLC_SuperSonic
		.word word_142FE8-PLC_SuperSonic
		.word word_142FF2-PLC_SuperSonic
		.word word_142FFC-PLC_SuperSonic
		.word word_143006-PLC_SuperSonic
		.word word_14300E-PLC_SuperSonic
		.word word_143018-PLC_SuperSonic
		.word word_143020-PLC_SuperSonic
		.word word_143026-PLC_SuperSonic
		.word word_14302E-PLC_SuperSonic
		.word word_143034-PLC_SuperSonic
		.word word_14303A-PLC_SuperSonic
		.word word_143040-PLC_SuperSonic
		.word word_143046-PLC_SuperSonic
		.word word_14304C-PLC_SuperSonic
		.word word_143054-PLC_SuperSonic
		.word word_14305C-PLC_SuperSonic
		.word word_143062-PLC_SuperSonic
		.word word_14306A-PLC_SuperSonic
		.word word_143074-PLC_SuperSonic
		.word word_14307E-PLC_SuperSonic
		.word word_143088-PLC_SuperSonic
		.word word_14308E-PLC_SuperSonic
		.word word_14309A-PLC_SuperSonic
		.word word_1430A6-PLC_SuperSonic
		.word word_1430AA-PLC_SuperSonic
		.word word_1430AE-PLC_SuperSonic
		.word word_1430B2-PLC_SuperSonic
		.word word_1430B6-PLC_SuperSonic
		.word word_143406-PLC_SuperSonic
		.word word_143406-PLC_SuperSonic
		.word word_1430C6-PLC_SuperSonic
		.word word_1430D0-PLC_SuperSonic
		.word word_1430DA-PLC_SuperSonic
		.word word_1430E4-PLC_SuperSonic
		.word word_14340C-PLC_SuperSonic
		.word word_143416-PLC_SuperSonic
		.word word_143420-PLC_SuperSonic
		.word word_14340C-PLC_SuperSonic
		.word word_143416-PLC_SuperSonic
		.word word_143420-PLC_SuperSonic
		.word word_143122-PLC_SuperSonic
		.word word_14312A-PLC_SuperSonic
		.word word_143132-PLC_SuperSonic
		.word word_14313A-PLC_SuperSonic
		.word word_143142-PLC_SuperSonic
		.word word_14314A-PLC_SuperSonic
		.word word_143154-PLC_SuperSonic
		.word word_14315E-PLC_SuperSonic
		.word word_143168-PLC_SuperSonic
		.word word_143172-PLC_SuperSonic
		.word word_143178-PLC_SuperSonic
		.word word_143180-PLC_SuperSonic
		.word word_143188-PLC_SuperSonic
		.word word_143190-PLC_SuperSonic
		.word word_143198-PLC_SuperSonic
		.word word_14342A-PLC_SuperSonic
		.word word_143432-PLC_SuperSonic
		.word word_14343A-PLC_SuperSonic
		.word word_143442-PLC_SuperSonic
		.word word_14344A-PLC_SuperSonic
		.word word_143454-PLC_SuperSonic
		.word word_14344A-PLC_SuperSonic
		.word word_143454-PLC_SuperSonic
		.word word_14344A-PLC_SuperSonic
		.word word_143454-PLC_SuperSonic
		.word word_14344A-PLC_SuperSonic
		.word word_143454-PLC_SuperSonic
		.word word_14344A-PLC_SuperSonic
		.word word_143214-PLC_SuperSonic
		.word word_14321E-PLC_SuperSonic
		.word word_143454-PLC_SuperSonic
		.word word_14344A-PLC_SuperSonic
		.word word_143454-PLC_SuperSonic
		.word word_143244-PLC_SuperSonic
		.word word_14324C-PLC_SuperSonic
		.word word_143254-PLC_SuperSonic
		.word word_14324C-PLC_SuperSonic
		.word word_143244-PLC_SuperSonic
		.word word_14325A-PLC_SuperSonic
		.word word_143260-PLC_SuperSonic
		.word word_14325A-PLC_SuperSonic
		.word word_143266-PLC_SuperSonic
		.word word_14326E-PLC_SuperSonic
		.word word_143466-PLC_SuperSonic
		.word word_14346A-PLC_SuperSonic
		.word word_143472-PLC_SuperSonic
		.word word_143478-PLC_SuperSonic
		.word word_143480-PLC_SuperSonic
		.word word_143276-PLC_SuperSonic
		.word word_14327E-PLC_SuperSonic
		.word word_143286-PLC_SuperSonic
word_142C14:	.word 0
word_142C16:	.word 3
		.word 0x7000
		.word 0x5008
		.word 0x800E
word_142C1E:	.word 3
		.word 0xB017
		.word 0x1023
		.word 0x7000
word_142C26:	.word 3
		.word 0x8025
		.word 0x302E
		.word 0x2032
word_142C2E:	.word 2
		.word 0xB035
		.word 0x5041
word_142C34:	.word 3
		.word 0xB047
		.word 0x1053
		.word 0x5041
word_142C3C:	.word 3
		.word 0xB055
		.word 0x1061
		.word 0x5041
word_142C44:	.word 3
		.word 0x8063
		.word 0x302E
		.word 0x2032
word_142C4C:	.word 2
		.word 0x806C
		.word 0x7000
word_142C52:	.word 4
		.word 0xB0AF
		.word 0x70BB
		.word 0xC3
		.word 0x30C4
word_142C5C:	.word 4
		.word 0xB0C8
		.word 0x70D4
		.word 0x10DC
		.word 0x10DE
word_142C66:	.word 4
		.word 0x80E0
		.word 0x10E9
		.word 0x30EB
		.word 0x30EF
word_142C70:	.word 4
		.word 0xB0F3
		.word 0x70FF
		.word 0x1107
		.word 0x109
word_142C7A:	.word 4
		.word 0xB10A
		.word 0x7116
		.word 0x111E
		.word 0x5120
word_142C84:	.word 4
		.word 0xF126
		.word 0x5136
		.word 0x213C
		.word 0x313F
word_142C8E:	.word 4
		.word 0x8143
		.word 0x714C
		.word 0x1154
		.word 0x156
word_142C98:	.word 4
		.word 0x8157
		.word 0x2160
		.word 0x3163
		.word 0x3167
word_142CA2:	.word 3
		.word 0x51EF
		.word 0x81F5
		.word 0x71FE
word_142CAA:	.word 3
		.word 0xB206
		.word 0x1212
		.word 0x7214
word_142CB2:	.word 3
		.word 0x821C
		.word 0x5225
		.word 0x22B
word_142CBA:	.word 2
		.word 0xB22C
		.word 0x7238
word_142CC0:	.word 3
		.word 0x1240
		.word 0xB242
		.word 0x7238
word_142CC8:	.word 4
		.word 0x124E
		.word 0xB250
		.word 0x525C
		.word 0x262
word_142CD2:	.word 3
		.word 0x8263
		.word 0x5225
		.word 0x22B
word_142CDA:	.word 2
		.word 0x826C
		.word 0x71FE
word_142CE0:	.word 4
		.word 0xB2E3
		.word 0x52EF
		.word 0x32F5
		.word 0x22F9
word_142CEA:	.word 4
		.word 0xB2FC
		.word 0x1308
		.word 0x330A
		.word 0x530E
word_142CF4:	.word 4
		.word 0x8314
		.word 0x331D
		.word 0x3321
		.word 0x1325
word_142CFE:	.word 4
		.word 0xB327
		.word 0x3333
		.word 0x3337
		.word 0x233B
word_142D08:	.word 4
		.word 0xB33E
		.word 0x534A
		.word 0x7350
		.word 0x358
word_142D12:	.word 4
		.word 0xF359
		.word 0x2369
		.word 0x136C
		.word 0x736E
word_142D1C:	.word 4
		.word 0x8376
		.word 0x337F
		.word 0x3383
		.word 0x2387
word_142D26:	.word 4
		.word 0x838A
		.word 0x3393
		.word 0x3397
		.word 0x239B
word_142D30:	.word 2
		.word 0x2421
		.word 0xF424
word_142D36:	.word 2
		.word 0x2434
		.word 0xF437
word_142D3C:	.word 2
		.word 0x2421
		.word 0xF447
word_142D42:	.word 2
		.word 0x2434
		.word 0xF457
word_142D48:	.word 4
		.word 0xB48B
		.word 0x497
		.word 0x3498
		.word 0x249C
word_142D52:	.word 2
		.word 0x249F
		.word 0xF4A2
word_142D58:	.word 4
		.word 0xB4B2
		.word 0x4BE
		.word 0x34BF
		.word 0x24C3
word_142D62:	.word 2
		.word 0x249F
		.word 0xF4C6
word_142D68:	.word 2
		.word 0x2504
		.word 0xF507
word_142D6E:	.word 2
		.word 0x2517
		.word 0xF51A
word_142D74:	.word 2
		.word 0x2504
		.word 0xF52A
word_142D7A:	.word 2
		.word 0x2517
		.word 0xF53A
word_142D80:	.word 3
		.word 0x1570
		.word 0xB572
		.word 0x557E
word_142D88:	.word 2
		.word 0x2584
		.word 0xF587
word_142D8E:	.word 3
		.word 0x1597
		.word 0xB599
		.word 0x55A5
word_142D96:	.word 2
		.word 0x2584
		.word 0xF5AB
word_142D9C:	.word 3
		.word 0x25E6
		.word 0xB5E9
		.word 0x25F5
word_142DA4:	.word 4
		.word 0x55F8
		.word 0x35FE
		.word 0x2602
		.word 0x1605
word_142DAE:	.word 4
		.word 0x1607
		.word 0x2609
		.word 0x360C
		.word 0x1610
word_142DB8:	.word 4
		.word 0x2612
		.word 0x3615
		.word 0x2619
		.word 0x361C
word_142DC2:	.word 4
		.word 0x1620
		.word 0x2622
		.word 0x3625
		.word 0x2629
word_142DCC:	.word 3
		.word 0x162C
		.word 0x762E
		.word 0x5636
word_142DD4:	.word 2
		.word 0xF63C
		.word 0x264C
word_142DDA:	.word 2
		.word 0xB64F
		.word 0x65B
word_142DE0:	.word 3
		.word 0x165C
		.word 0x765E
		.word 0x2666
word_142DE8:	.word 4
		.word 0x2669
		.word 0x366C
		.word 0x2670
		.word 0x1673
word_142DF2:	.word 2
		.word 0x8675
		.word 0x367E
word_142DF8:	.word 2
		.word 0xB682
		.word 0x268E
word_142DFE:	.word 3
		.word 0x691
		.word 0xB692
		.word 0x269E
word_142E06:	.word 1
		.word 0xB6A1
word_142E0A:	.word 3
		.word 0x26AD
		.word 0x76B0
		.word 0x16B8
word_142E12:	.word 4
		.word 0x26BA
		.word 0x36BD
		.word 0x26C1
		.word 0x16C4
word_142E1C:	.word 4
		.word 0x56C6
		.word 0x36CC
		.word 0x26D0
		.word 0x16D3
word_142E26:	.word 4
		.word 0x56D5
		.word 0x26DB
		.word 0x36DE
		.word 0x26E2
word_142E30:	.word 2
		.word 0xB6E5
		.word 0x26F1
word_142E36:	.word 1
		.word 0xB6F4
word_142E3A:	.word 2
		.word 0x7700
		.word 0x2708
word_142E40:	.word 1
		.word 0xB70B
word_142E44:	.word 2
		.word 0x1717
		.word 0xB719
word_142E4A:	.word 3
		.word 0x2725
		.word 0x7728
		.word 0x5730
word_142E52:	.word 4
		.word 0x8736
		.word 0x373F
		.word 0x3743
		.word 0x2747
word_142E5C:	.word 4
		.word 0x274A
		.word 0x774D
		.word 0x2755
		.word 0x3758
word_142E66:	.word 3
		.word 0x575C
		.word 0x3762
		.word 0x2766
word_142E6E:	.word 3
		.word 0x2769
		.word 0x776C
		.word 0x2774
word_142E76:	.word 3
		.word 0x1777
		.word 0x7779
		.word 0x1781
word_142E7E:	.word 1
		.word 0xF783
word_142E82:	.word 4
		.word 0x793
		.word 0x7794
		.word 0x79C
		.word 0x779D
word_142E8C:	.word 4
		.word 0x17A5
		.word 0x27A7
		.word 0x87AA
		.word 0x37B3
word_142E96:	.word 2
		.word 0x17B7
		.word 0xB7B9
word_142E9C:	.word 3
		.word 0x17C5
		.word 0x77C7
		.word 0x17CF
word_142EA4:	.word 3
		.word 0x7D1
		.word 0x87D2
		.word 0x17DB
word_142EAC:	.word 2
		.word 0xF7DD
		.word 0x7ED
word_142EB2:	.word 4
		.word 0x2800
		.word 0x7803
		.word 0x280B
		.word 0x280E
word_142EBC:	.word 3
		.word 0x2811
		.word 0x7814
		.word 0x581C
word_142EC4:	.word 2
		.word 0xB822
		.word 0x382E
word_142ECA:	.word 2
		.word 0xB832
		.word 0x283E
word_142ED0:	.word 4
		.word 0x2841
		.word 0x3844
		.word 0x2848
		.word 0x784B
word_142EDA:	.word 3
		.word 0x8853
		.word 0x385C
		.word 0x2860
word_142EE2:	.word 2
		.word 0xB863
		.word 0x286F
word_142EE8:	.word 3
		.word 0x8872
		.word 0x587B
		.word 0x881
word_142EF0:	.word 1
		.word 0xB882
word_142EF4:	.word 2
		.word 0xB88E
		.word 0x289A
word_142EFA:	.word 3
		.word 0x389D
		.word 0xB8A1
		.word 0x8AD
word_142F02:	.word 1
		.word 0xB8AE
word_142F06:	.word 2
		.word 0x8BA
		.word 0xB8BB
word_142F0C:	.word 2
		.word 0x88C7
		.word 0x58D0
word_142F12:	.word 3
		.word 0x88D6
		.word 0x38DF
		.word 0x28E3
word_142F1A:	.word 1
		.word 0xB8E6
word_142F1E:	.word 2
		.word 0xB8F2
		.word 0x28FE
word_142F24:	.word 3
		.word 0x2901
		.word 0x1904
		.word 0xB906
word_142F2C:	.word 1
		.word 0xB912
word_142F30:	.word 2
		.word 0x91E
		.word 0xB91F
word_142F36:	.word 2
		.word 0xB92B
		.word 0x2937
word_142F3C:	.word 4
		.word 0x193A
		.word 0x393C
		.word 0x5940
		.word 0x1946
word_142F46:	.word 3
		.word 0x948
		.word 0x7949
		.word 0x2951
word_142F4E:	.word 3
		.word 0x954
		.word 0x7955
		.word 0x295D
word_142F56:	.word 2
		.word 0x5960
		.word 0xB966
word_142F5C:	.word 3
		.word 0x972
		.word 0x8973
		.word 0x397C
word_142F64:	.word 3
		.word 0x1980
		.word 0x5982
		.word 0x3988
word_142F6C:	.word 3
		.word 0x598C
		.word 0x3992
		.word 0x1996
word_142F74:	.word 2
		.word 0x998
		.word 0xB999
word_142F7A:	.word 4
		.word 0x19A5
		.word 0x9A7
		.word 0x9A8
		.word 0xB9A9
word_142F84:	.word 3
		.word 0x19B5
		.word 0xB9B7
		.word 0x29C3
word_142F8C:	.word 3
		.word 0x19C6
		.word 0x79C8
		.word 0x29D0
word_142F94:	.word 2
		.word 0x9D3
		.word 0x89D4
word_142F9A:	.word 3
		.word 0x29DD
		.word 0x79E0
		.word 0x29E8
word_142FA2:	.word 1
		.word 0xB9EB
word_142FA6:	.word 4
		.word 0x39F7
		.word 0x29FB
		.word 0x79FE
		.word 0x7A06
word_142FB0:	.word 4
		.word 0x1A0E
		.word 0xBA10
		.word 0x5A1C
		.word 0x2A22
word_142FBA:	.word 3
		.word 0x2A25
		.word 0xBA28
		.word 0x7A34
word_142FC2:	.word 4
		.word 0x2A3C
		.word 0x1A3F
		.word 0x1A41
		.word 0xFA43
word_142FCC:	.word 4
		.word 0x39F7
		.word 0x29FB
		.word 0x79FE
		.word 0x7A06
word_142FD6:	.word 4
		.word 0x1A0E
		.word 0xBA10
		.word 0x5A1C
		.word 0x2A22
word_142FE0:	.word 3
		.word 0x2A25
		.word 0xBA28
		.word 0x7A34
word_142FE8:	.word 4
		.word 0x2A3C
		.word 0x1A3F
		.word 0x1A41
		.word 0xFA43
word_142FF2:	.word 4
		.word 0xBA53
		.word 0xA5F
		.word 0x1A60
		.word 0x5A62
word_142FFC:	.word 4
		.word 0x3A68
		.word 0x7A6C
		.word 0x3A74
		.word 0x2A78
word_143006:	.word 3
		.word 0x2A7B
		.word 0x3A7E
		.word 0xBA82
word_14300E:	.word 4
		.word 0xA8E
		.word 0x7A8F
		.word 0x2A97
		.word 0x5A9A
word_143018:	.word 3
		.word 0xBAA0
		.word 0x5AAC
		.word 0x1AB2
word_143020:	.word 2
		.word 0xBAB4
		.word 0x5AC0
word_143026:	.word 3
		.word 0x2AC6
		.word 0x7AC9
		.word 0x2AD1
word_14302E:	.word 2
		.word 0xBAD4
		.word 0x2AE0
word_143034:	.word 2
		.word 0xBAE3
		.word 0x2AE0
word_14303A:	.word 2
		.word 0xBAEF
		.word 0x2AE0
word_143040:	.word 2
		.word 0xBAFB
		.word 0x2AE0
word_143046:	.word 2
		.word 0xBB07
		.word 0x2AE0
word_14304C:	.word 3
		.word 0xBB13
		.word 0x2B1F
		.word 0x2B22
word_143054:	.word 3
		.word 0xBB25
		.word 0x2B1F
		.word 0x2B22
word_14305C:	.word 2
		.word 0xB7EF
		.word 0x37FB
word_143062:	.word 3
		.word 0x3B31
		.word 0x3B35
		.word 0x8B39
word_14306A:	.word 4
		.word 0x5B42
		.word 0x3B48
		.word 0x2B4C
		.word 0x5B4F
word_143074:	.word 4
		.word 0x5B55
		.word 0x3B5B
		.word 0x2B5F
		.word 0x7B62
word_14307E:	.word 4
		.word 0x2B6A
		.word 0xBB6D
		.word 0xB79
		.word 0x1B7A
word_143088:	.word 2
		.word 0x2B6A
		.word 0xBB7C
word_14308E:	.word 5
		.word 0x7B88
		.word 0x1B93
		.word 0x5B95
		.word 0x3B9B
		.word 0x2B9F
word_14309A:	.word 5
		.word 0x2B90
		.word 0x1B93
		.word 0x5B95
		.word 0x3B9B
		.word 0x2B9F
word_1430A6:	.word 1
		.word 0xFBA2
word_1430AA:	.word 1
		.word 0xFBB2
word_1430AE:	.word 1
		.word 0xFBC2
word_1430B2:	.word 1
		.word 0xFBD2
word_1430B6:	.word 1
		.word 0xFBE2
word_1430BA:	.word 2
		.word 0xBF2
		.word 0xBBF3
word_1430C0:	.word 2
		.word 0xBFF
		.word 0xBC00
word_1430C6:	.word 4
		.word 0x8C0C
		.word 0x1C15
		.word 0x3C17
		.word 0x2C1B
word_1430D0:	.word 4
		.word 0x8C0C
		.word 0x1C1E
		.word 0x3C20
		.word 0x2C24
word_1430DA:	.word 4
		.word 0x2C27
		.word 0x7C2A
		.word 0x2C32
		.word 0x1C35
word_1430E4:	.word 3
		.word 0x2C37
		.word 0xBC3A
		.word 0x2C46
word_1430EC:	.word 3
		.word 0x7C49
		.word 0xC51
		.word 0x8C52
word_1430F4:	.word 4
		.word 0xC5B
		.word 0xBC5C
		.word 0xC68
		.word 0x5C69
word_1430FE:	.word 3
		.word 0xC6F
		.word 0xFC70
		.word 0x2C80
word_143106:	.word 4
		.word 0x2C83
		.word 0xBC86
		.word 0x1C92
		.word 0x2C94
word_143110:	.word 3
		.word 0xFC97
		.word 0xCA7
		.word 0x2CA8
word_143118:	.word 4
		.word 0x2C83
		.word 0xBCAB
		.word 0x1CB7
		.word 0x2CB9
word_143122:	.word 3
		.word 0x2CBC
		.word 0xFCBF
		.word 0xCCF
word_14312A:	.word 3
		.word 0x2CD0
		.word 0xFCD3
		.word 0xCCF
word_143132:	.word 3
		.word 0x1CE3
		.word 0xFCE5
		.word 0xCCF
word_14313A:	.word 3
		.word 0xBCF5
		.word 0xD01
		.word 0x5D02
word_143142:	.word 3
		.word 0xBD08
		.word 0xD14
		.word 0x5D15
word_14314A:	.word 4
		.word 0xFD1B
		.word 0xD2B
		.word 0x1D2C
		.word 0x1D2E
word_143154:	.word 4
		.word 0x2D30
		.word 0x7D33
		.word 0x1D3B
		.word 0x2D3D
word_14315E:	.word 4
		.word 0x2D30
		.word 0x7D40
		.word 0x1D3B
		.word 0x2D3D
word_143168:	.word 4
		.word 0x2D48
		.word 0x3D4B
		.word 0x7D4F
		.word 0x2D3D
word_143172:	.word 2
		.word 0x7D76
		.word 0x8D7E
word_143178:	.word 3
		.word 0x2D87
		.word 0x7D8A
		.word 0x5D92
word_143180:	.word 3
		.word 0x2D87
		.word 0x7D98
		.word 0x5D92
word_143188:	.word 3
		.word 0x2D87
		.word 0x7DA0
		.word 0x5D92
word_143190:	.word 3
		.word 0xBDA8
		.word 0x2DB4
		.word 0x3DB7
word_143198:	.word 3
		.word 0xBDBB
		.word 0x2DC7
		.word 0x3DCA
word_1431A0:	.word 3
		.word 0x1DCE
		.word 0x8DD0
		.word 0x3DD9
word_1431A8:	.word 3
		.word 0x1DCE
		.word 0x8DDD
		.word 0x1DE6
word_1431B0:	.word 3
		.word 0x1DCE
		.word 0x5DE8
		.word 0x7DEE
word_1431B8:	.word 3
		.word 0x1DCE
		.word 0x8DF6
		.word 0x1DFF
word_1431C0:	.word 4
		.word 0x8E01
		.word 0x2811
		.word 0x3E0A
		.word 0x815
word_1431CA:	.word 3
		.word 0x2E0E
		.word 0x7E11
		.word 0x5E19
word_1431D2:	.word 4
		.word 0x2E1F
		.word 0x7E22
		.word 0x2E2A
		.word 0x2E2D
word_1431DC:	.word 4
		.word 0x2D87
		.word 0x7E30
		.word 0x2E2A
		.word 0x2E2D
word_1431E6:	.word 4
		.word 0x2D87
		.word 0x7E30
		.word 0x2E2A
		.word 0x2E38
word_1431F0:	.word 4
		.word 0x2D87
		.word 0x7E3B
		.word 0x2E2A
		.word 0x2E2D
word_1431FA:	.word 4
		.word 0x2D87
		.word 0x7E3B
		.word 0x2E2A
		.word 0x2E38
word_143204:	.word 2
		.word 0xBE43
		.word 0x3E4F
word_14320A:	.word 4
		.word 0x2E53
		.word 0x7E56
		.word 0x2E5E
		.word 0x3E4F
word_143214:	.word 4
		.word 0x2E61
		.word 0x7E64
		.word 0x2E6C
		.word 0x2E6F
word_14321E:	.word 4
		.word 0x2E72
		.word 0x3E75
		.word 0x3E79
		.word 0x5E7D
word_143228:	.word 3
		.word 0xBE83
		.word 0x2E8F
		.word 0x2E6F
word_143230:	.word 4
		.word 0x2E92
		.word 0x7E95
		.word 0x2E9D
		.word 0x2EA0
word_14323A:	.word 4
		.word 0x2EA3
		.word 0x3EA6
		.word 0x5EAA
		.word 0x2E6F
word_143244:	.word 3
		.word 0x8EB0
		.word 0x1EB9
		.word 0x2EBB
word_14324C:	.word 3
		.word 0x5EBE
		.word 0x3EC4
		.word 0xEC8
word_143254:	.word 2
		.word 0x5EC9
		.word 0x3ECF
word_14325A:	.word 2
		.word 0xBED3
		.word 0xEDF
word_143260:	.word 2
		.word 0x5EE0
		.word 0x3EE6
word_143266:	.word 3
		.word 0xBB13
		.word 0x2B1F
		.word 0x2B22
word_14326E:	.word 3
		.word 0xBB25
		.word 0x2B1F
		.word 0x2B22
word_143276:	.word 3
		.word 0xBB13
		.word 0x2B1F
		.word 0x2B22
word_14327E:	.word 3
		.word 0xBB25
		.word 0x2B1F
		.word 0x2B22
word_143286:	.word 4
		.word 0xBD57
		.word 0xD63
		.word 0x3D64
		.word 0x2D68
word_143290:	.word 0
word_143292:	.word 3
		.word 0x800E
		.word 0x5008
		.word 0xB075
word_14329A:	.word 3
		.word 0xB017
		.word 0x1023
		.word 0xB081
word_1432A2:	.word 3
		.word 0x708D
		.word 0x8025
		.word 0x2095
word_1432AA:	.word 3
		.word 0xB035
		.word 0x5098
		.word 0x309E
word_1432B2:	.word 4
		.word 0xB047
		.word 0x1053
		.word 0x30A2
		.word 0x50A6
word_1432BC:	.word 4
		.word 0xB055
		.word 0x1061
		.word 0x309E
		.word 0x5098
word_1432C6:	.word 3
		.word 0x8063
		.word 0x20AC
		.word 0x708D
word_1432CE:	.word 2
		.word 0x806C
		.word 0xB081
word_1432D4:	.word 4
		.word 0xB0AF
		.word 0x116B
		.word 0xB16D
		.word 0x5179
word_1432DE:	.word 4
		.word 0xB0C8
		.word 0x117F
		.word 0x8181
		.word 0x718A
word_1432E8:	.word 4
		.word 0x80E0
		.word 0x7192
		.word 0x19A
		.word 0x119B
word_1432F2:	.word 4
		.word 0xB0F3
		.word 0xB19D
		.word 0x1A9
		.word 0x31AA
word_1432FC:	.word 4
		.word 0xB10A
		.word 0x81AE
		.word 0x51B7
		.word 0x51BD
word_143306:	.word 4
		.word 0xF126
		.word 0x71C3
		.word 0x21CB
		.word 0x31CE
word_143310:	.word 4
		.word 0x8143
		.word 0x51D2
		.word 0x81D8
		.word 0x11E1
word_14331A:	.word 4
		.word 0x8157
		.word 0x71E3
		.word 0x1EB
		.word 0x21EC
word_143324:	.word 3
		.word 0x51EF
		.word 0x81F5
		.word 0xB275
word_14332C:	.word 3
		.word 0x1281
		.word 0xB283
		.word 0xB28F
word_143334:	.word 3
		.word 0x829B
		.word 0x82A4
		.word 0x12AD
word_14333C:	.word 3
		.word 0xB22C
		.word 0x82AF
		.word 0x2B8
word_143344:	.word 4
		.word 0xB242
		.word 0x1240
		.word 0x82B9
		.word 0x2C2
word_14334E:	.word 4
		.word 0xB2C3
		.word 0x12CF
		.word 0x82AF
		.word 0x2B8
word_143358:	.word 3
		.word 0x82D1
		.word 0x82DA
		.word 0x12AD
word_143360:	.word 2
		.word 0x826C
		.word 0xB28F
word_143366:	.word 4
		.word 0xB2E3
		.word 0x539E
		.word 0xB3A4
		.word 0x3B0
word_143370:	.word 4
		.word 0xB2FC
		.word 0x73B1
		.word 0x73B9
		.word 0x13C1
word_14337A:	.word 4
		.word 0x8314
		.word 0x3C3
		.word 0x13C4
		.word 0x83C6
word_143384:	.word 4
		.word 0xB327
		.word 0x33CF
		.word 0xB3D3
		.word 0x33A
word_14338E:	.word 4
		.word 0xB33E
		.word 0x53DF
		.word 0x83E5
		.word 0x53EE
word_143398:	.word 4
		.word 0xF359
		.word 0x33F4
		.word 0x3F8
		.word 0xB3F9
word_1433A2:	.word 4
		.word 0x8376
		.word 0x3405
		.word 0xB409
		.word 0x386
word_1433AC:	.word 4
		.word 0x838A
		.word 0x3415
		.word 0x5419
		.word 0x141F
word_1433B6:	.word 4
		.word 0x7467
		.word 0x246F
		.word 0x5472
		.word 0x1478
word_1433C0:	.word 4
		.word 0x747A
		.word 0x2482
		.word 0x5485
		.word 0x1478
word_1433CA:	.word 4
		.word 0x14D6
		.word 0x74D8
		.word 0x4E0
		.word 0xB4E1
word_1433D4:	.word 4
		.word 0x14ED
		.word 0x74EF
		.word 0x4F7
		.word 0xB4F8
word_1433DE:	.word 4
		.word 0xB54A
		.word 0x1556
		.word 0x558
		.word 0x3559
word_1433E8:	.word 4
		.word 0xB55D
		.word 0x1569
		.word 0x56B
		.word 0x356C
word_1433F2:	.word 4
		.word 0x35BB
		.word 0x75BF
		.word 0x55C7
		.word 0x35CD
word_1433FC:	.word 4
		.word 0x25D1
		.word 0x75D4
		.word 0x55DC
		.word 0x35E2
word_143406:	.word 2
		.word 0xFFC3
		.word 0xFD3
word_14340C:	.word 4
		.word 0x3EEA
		.word 0x3EEE
		.word 0x7EF2
		.word 0x5EFA
word_143416:	.word 4
		.word 0x3EEA
		.word 0x3EEE
		.word 0x7F00
		.word 0x5F08
word_143420:	.word 4
		.word 0x3EEA
		.word 0x3EEE
		.word 0x7F0E
		.word 0x5F16
word_14342A:	.word 3
		.word 0x2F6E
		.word 0xFF71
		.word 0x3F81
word_143432:	.word 3
		.word 0x2F85
		.word 0xFF88
		.word 0x2F98
word_14343A:	.word 3
		.word 0xF9B
		.word 0xFF9C
		.word 0x3FAC
word_143442:	.word 3
		.word 0x2F85
		.word 0xFFB0
		.word 0x2FC0
word_14344A:	.word 4
		.word 0x8E01
		.word 0x7FD4
		.word 0x2FDC
		.word 0xFDF
word_143454:	.word 4
		.word 0x8E01
		.word 0x7FE0
		.word 0x2FE8
		.word 0xFEB
		.word 3
		.word 0x8E01
		.word 0xBFEC
		.word 0xFF8
word_143466:	.word 1
		.word 0xBF1C
word_14346A:	.word 3
		.word 0x5F28
		.word 0x7F2E
		.word 0x5F36
word_143472:	.word 2
		.word 0xFF3C
		.word 0x5F4C
word_143478:	.word 3
		.word 0x8F52
		.word 0x3F5B
		.word 0x5F5F
word_143480:	.word 3
		.word 0x8F65
		.word 0x3F5B
		.word 0x5F5F
