DPLC_61BFA:		.word word_61C02-DPLC_61BFA
		.word word_61C0A-DPLC_61BFA
		.word word_61C12-DPLC_61BFA
		.word word_61C1C-DPLC_61BFA
word_61C02:	.word 2			
		.word 2
		.word 0x35
		.word 0x90
word_61C0A:	.word 2			
		.word 0xA3
		.word 0xE7
		.word 0x161
word_61C12:	.word 3			
		.word 0x182
		.word 0x1BB
		.word 0x273
		.word 0x2B1
word_61C1C:	.word 1			
		.word 0x182
		.word 0x1BB
		.word 1
		.word 0x273
		.word 0x2B1
