DPLC_61ABE:		.word word_61AD6-DPLC_61ABE
		.word word_61ADA-DPLC_61ABE
		.word word_61ADE-DPLC_61ABE
		.word word_61AE2-DPLC_61ABE
		.word word_61AE6-DPLC_61ABE
		.word word_61AEA-DPLC_61ABE
		.word word_61AF0-DPLC_61ABE
		.word word_61AFA-DPLC_61ABE
		.word word_61B04-DPLC_61ABE
		.word word_61B0E-DPLC_61ABE
		.word word_61B18-DPLC_61ABE
		.word word_61B1E-DPLC_61ABE
word_61AD6:	.word 0			
		.word 3
word_61ADA:	.word 0			
		.word 0x43
word_61ADE:	.word 0			
		.word 0x88
word_61AE2:	.word 0			
		.word 0x118
word_61AE6:	.word 0			
		.word 0x1AF
word_61AEA:	.word 1			
		.word 0x2AF
		.word 0x3A3
word_61AF0:	.word 3			
		.word 0x3E5
		.word 0x445
		.word 0x4A5
		.word 0x505
word_61AFA:	.word 3			
		.word 0x562
		.word 0x59F
		.word 0x693
		.word 0x6D2
word_61B04:	.word 3			
		.word 0x70F
		.word 0x80F
		.word 0x90F
		.word 0xA0F
word_61B0E:	.word 3			
		.word 0xB0F
		.word 0xC0B
		.word 0xCCF
		.word 0xDCB
word_61B18:	.word 1			
		.word 0xE8B
		.word 0xF4B
word_61B1E:	.word 3			
		.word 0x100F
		.word 0x110B
		.word 0x11CF
		.word 0x12CB
