		.word word_49E96-Map_PachinkoFlipper
		.word word_49E9E-Map_PachinkoFlipper
		.word word_49EB2-Map_PachinkoFlipper
		.word word_49EC6-Map_PachinkoFlipper
		.word word_49EDA-Map_PachinkoFlipper
word_49E96:	.word 1			/* DATA XREF: ROM:00049E8Co*/
		.byte	4,   5,	0x20,   0, 0xFF, 0xE0
word_49E9E:	.word 3			/* DATA XREF: ROM:00049E8Co*/
		.byte	4,   5,	0x20,   0, 0xFF, 0xE0
		.byte  0xE4,   5,	0x60,   4, 0xFF, 0xF0
		.byte  0xF4,   3,	0x60,   8, 0xFF, 0xF0
word_49EB2:	.word 3			/* DATA XREF: ROM:00049E8Co*/
		.byte	4,   5,	0x20,   0, 0xFF, 0xE0
		.byte  0xF7,  0xA,	0x60,  0xC, 0xFF, 0xF0
		.byte  0xF7,   5,	0x60, 0x15,   0,	 8
word_49EC6:	.word 3			/* DATA XREF: ROM:00049E8Co*/
		.byte	4,   5,	0x20,   0, 0xFF, 0xE0
		.byte	2,   9,	0x60, 0x19, 0xFF, 0xF0
		.byte	2,   5,	0x60, 0x1F,   0,	 8
word_49EDA:	.word 3			/* DATA XREF: ROM:00049E8Co*/
		.byte	4,   5,	0x20,   0, 0xFF, 0xE0
		.byte	4,  0xA,	0x70,  0xC, 0xFF, 0xF0
		.byte   0xC,   5,	0x70, 0x15,   0,	 8
