		.word word_4A122-Map_PachinkoInvisibleUnknown
		.word word_4A136-Map_PachinkoInvisibleUnknown
		.word word_4A14A-Map_PachinkoInvisibleUnknown
		.word word_4A15E-Map_PachinkoInvisibleUnknown
		.word word_4A172-Map_PachinkoInvisibleUnknown
word_4A122:	.word 3			/*  DATA XREF: ROM:0004A118o */
		.byte  0xF8,   5,	  0,   0, 0xFF, 0x80
		.byte  0xF8,   5,	  0,   0,   0,	 0
		.byte  0xF8,   5,	  0,   0,   0, 0x7F
word_4A136:	.word 3			/*  DATA XREF: ROM:0004A118o */
		.byte  0xF8,   5,	  0,   4, 0xFF, 0x80
		.byte  0xF8,   5,	  0,   4,   0,	 0
		.byte  0xF8,   5,	  0,   4,   0, 0x7F
word_4A14A:	.word 3			/*  DATA XREF: ROM:0004A118o */
		.byte  0xF8,   5,	  0,   8, 0xFF, 0x80
		.byte  0xF8,   5,	  0,   8,   0,	 0
		.byte  0xF8,   5,	  0,   8,   0, 0x7F
word_4A15E:	.word 3			/*  DATA XREF: ROM:0004A118o */
		.byte  0xF8,   5,	  0,  0xC, 0xFF, 0x80
		.byte  0xF8,   5,	  0,  0xC,   0,	 0
		.byte  0xF8,   5,	  0,  0xC,   0, 0x7F
word_4A172:	.word 3			/*  DATA XREF: ROM:0004A118o */
		.byte  0xF8,   5,	  0, 0x10, 0xFF, 0x80
		.byte  0xF8,   5,	  0, 0x10,   0,	 0
		.byte  0xF8,   5,	  0, 0x10,   0, 0x7F
