Map_PachinkoBumper_:.word word_330A6-Map_PachinkoBumper_
		.word word_330AE-Map_PachinkoBumper_
word_330A6:	.word 1			/*  DATA XREF: ROM:000330A2o */
		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xF0
word_330AE:	.word 4			/*  DATA XREF: ROM:000330A2o */
		.byte  0xE8,  0xB,	  0, 0x10, 0xFF, 0xE8
		.byte  0xE8,  0xB,	  8, 0x10,   0,	 0
		.byte	8,   4,	  0, 0x1C, 0xFF, 0xF0
		.byte	8,   4,	  8, 0x1C,   0,	 0
