Map_PachinkoItemOrb_:.word word_4A29E-Map_PachinkoItemOrb_
		.word word_4A2A6-Map_PachinkoItemOrb_
		.word word_4A2AE-Map_PachinkoItemOrb_
		.word word_4A2B6-Map_PachinkoItemOrb_
		.word word_4A2BE-Map_PachinkoItemOrb_
word_4A29E:	.word 1			/* DATA XREF: ROM:0004A294o*/
		.byte  0xF8,   5,	  0,   0, 0xFF, 0xF8
word_4A2A6:	.word 1			/* DATA XREF: ROM:0004A294o*/
		.byte  0xF8,   5,	  0,   4, 0xFF, 0xF8
word_4A2AE:	.word 1			/* DATA XREF: ROM:0004A294o*/
		.byte  0xF8,   5,	  0,   8, 0xFF, 0xF8
word_4A2B6:	.word 1			/* DATA XREF: ROM:0004A294o*/
		.byte  0xF8,   5,	  0,  0xC, 0xFF, 0xF8
word_4A2BE:	.word 1			/* DATA XREF: ROM:0004A294o*/
		.byte  0xF8,   5,	  0, 0x10, 0xFF, 0xF8
