Map_SB_Slot_:	.word byte_4B7A0-Map_SB_Slot_
		.word byte_4B81B-Map_SB_Slot_
		.word byte_4B7C9-Map_SB_Slot_
		.word byte_4B81B-Map_SB_Slot_
		.word byte_4B7F2-Map_SB_Slot_
		.word byte_4B81B-Map_SB_Slot_
byte_4B7A0:	.byte 8
		.byte  0xF0,   8,	0x40,   0, 0xE8
		.byte  0xF0,   8,	0x48,   0,   0
		.byte  0xF8,   8,	0x40,   0, 0xE8
		.byte  0xF8,   8,	0x48,   0,   0
		.byte	0,   8,	0x40,   0, 0xE8
		.byte	0,   8,	0x48,   0,   0
		.byte	8,   8,	0x40,   0, 0xE8
		.byte	8,   8,	0x48,   0,   0
byte_4B7C9:	.byte 8
		.byte  0xF0,   8,	0x20,   0, 0xE8
		.byte  0xF0,   8,	0x28,   0,   0
		.byte  0xF8,   8,	0x20,   0, 0xE8
		.byte  0xF8,   8,	0x28,   0,   0
		.byte	0,   8,	0x20,   0, 0xE8
		.byte	0,   8,	0x28,   0,   0
		.byte	8,   8,	0x20,   0, 0xE8
		.byte	8,   8,	0x28,   0,   0
byte_4B7F2:	.byte 8
		.byte  0xF0,   8,	0x60,   0, 0xE8
		.byte  0xF0,   8,	0x68,   0,   0
		.byte  0xF8,   8,	0x60,   0, 0xE8
		.byte  0xF8,   8,	0x68,   0,   0
		.byte	0,   8,	0x60,   0, 0xE8
		.byte	0,   8,	0x68,   0,   0
		.byte	8,   8,	0x60,   0, 0xE8
		.byte	8,   8,	0x68,   0,   0
byte_4B81B:	.byte 8
		.byte  0xF0,   8,	0x40,   3, 0xE8
		.byte  0xF0,   8,	0x48,   3,   0
		.byte  0xF8,   8,	0x40,   3, 0xE8
		.byte  0xF8,   8,	0x48,   3,   0
		.byte	0,   8,	0x40,   3, 0xE8
		.byte	0,   8,	0x48,   3,   0
		.byte	8,   8,	0x40,   3, 0xE8
		.byte	8,   8,	0x48,   3,   0