Map_SB_R_and_Peppermint_:	.word byte_4B84C-Map_SB_R_and_Peppermint_
		.word byte_4B852-Map_SB_R_and_Peppermint_
		.word byte_4B858-Map_SB_R_and_Peppermint_
		.word byte_4B85E-Map_SB_R_and_Peppermint_
byte_4B84C:	.byte 1
		.byte  0xF4,  0xA,	  0,   0, 0xF4
byte_4B852:	.byte 1
		.byte  0xF4,  0xA,	  0,   9, 0xF4
byte_4B858:	.byte 1
		.byte  0xF4,  0xA,	  8,   0, 0xF4
byte_4B85E:	.byte 1
		.byte  0xF4,  0xA,	  0, 0x12, 0xF4