Map_SB_Ring_:	.word byte_4B8A6-Map_SB_Ring_
		.word byte_4B8AC-Map_SB_Ring_
		.word byte_4B8B2-Map_SB_Ring_
		.word byte_4B8B8-Map_SB_Ring_
		.word byte_4B8BE-Map_SB_Ring_
		.word byte_4B8C4-Map_SB_Ring_
		.word byte_4B8CA-Map_SB_Ring_
		.word byte_4B8D0-Map_SB_Ring_
		.word byte_4B8D6-Map_SB_Ring_
byte_4B8A6:	.byte 1
		.byte  0xF8,   5,	  0,   0, 0xF8
byte_4B8AC:	.byte 1
		.byte  0xF8,   5,	  0,   4, 0xF8
byte_4B8B2:	.byte 1
		.byte  0xF8,   1,	  0,   8, 0xFC
byte_4B8B8:	.byte 1
		.byte  0xF8,   5,	  8,   4, 0xF8
byte_4B8BE:	.byte 1
		.byte  0xF8,   5,	  0,  0xA, 0xF8
byte_4B8C4:	.byte 1
		.byte  0xF8,   5,	0x18,  0xA, 0xF8
byte_4B8CA:	.byte 1
		.byte  0xF8,   5,	  8,  0xA, 0xF8
byte_4B8D0:	.byte 1
		.byte  0xF8,   5,	0x10,  0xA, 0xF8
byte_4B8D6:	.byte 0
		.byte 0