Map_SB_ColoredWall_:	.word byte_4B8F8-Map_SB_ColoredWall_
		.word byte_4B8FE-Map_SB_ColoredWall_
		.word byte_4B904-Map_SB_ColoredWall_
		.word byte_4B90A-Map_SB_ColoredWall_
		.word byte_4B910-Map_SB_ColoredWall_
		.word byte_4B916-Map_SB_ColoredWall_
		.word byte_4B91C-Map_SB_ColoredWall_
		.word byte_4B922-Map_SB_ColoredWall_
		.word byte_4B928-Map_SB_ColoredWall_
		.word byte_4B92E-Map_SB_ColoredWall_
		.word byte_4B934-Map_SB_ColoredWall_
		.word byte_4B93A-Map_SB_ColoredWall_
		.word byte_4B940-Map_SB_ColoredWall_
		.word byte_4B946-Map_SB_ColoredWall_
		.word byte_4B94C-Map_SB_ColoredWall_
		.word byte_4B952-Map_SB_ColoredWall_
byte_4B8F8:	.byte 1
		.byte  0xF4,  0xA,	  0,   0, 0xF4
byte_4B8FE:	.byte 1
		.byte  0xF0,  0xF,	  0,   9, 0xF0
byte_4B904:	.byte 1
		.byte  0xF0,  0xF,	  0, 0x19, 0xF0
byte_4B90A:	.byte 1
		.byte  0xF0,  0xF,	  0, 0x29, 0xF0
byte_4B910:	.byte 1
		.byte  0xF0,  0xF,	  0, 0x39, 0xF0
byte_4B916:	.byte 1
		.byte  0xF0,  0xF,	  0, 0x49, 0xF0
byte_4B91C:	.byte 1
		.byte  0xF0,  0xF,	  0, 0x59, 0xF0
byte_4B922:	.byte 1
		.byte  0xF0,  0xF,	  0, 0x69, 0xF0
byte_4B928:	.byte 1
		.byte  0xF0,  0xF,	  0, 0x79, 0xF0
byte_4B92E:	.byte 1
		.byte  0xF0,  0xF,	  0, 0x89, 0xF0
byte_4B934:	.byte 1
		.byte  0xF0,  0xF,	  0, 0x99, 0xF0
byte_4B93A:	.byte 1
		.byte  0xF0,  0xF,	  0, 0xA9, 0xF0
byte_4B940:	.byte 1
		.byte  0xF0,  0xF,	  0, 0xB9, 0xF0
byte_4B946:	.byte 1
		.byte  0xF0,  0xF,	  0, 0xC9, 0xF0
byte_4B94C:	.byte 1
		.byte  0xF0,  0xF,	  0, 0xD9, 0xF0
byte_4B952:	.byte 1
		.byte  0xF0,  0xF,	  0, 0xE9, 0xF0