Map_5CD00:		.word word_5CD12-Map_5CD00
		.word word_5CD20-Map_5CD00
		.word word_5CD2E-Map_5CD00
		.word word_5CD36-Map_5CD00
		.word word_5CD3E-Map_5CD00
		.word word_5CD46-Map_5CD00
		.word word_5CD4E-Map_5CD00
		.word word_5CD56-Map_5CD00
		.word word_5CD5E-Map_5CD00
word_5CD12:	.word 2			
		.byte  0xF4,   5,	  0,   0, 0xFF, 0xF4
		.byte	4,   8,	  0,   4, 0xFF, 0xF4
word_5CD20:	.word 2			
		.byte  0xF4,   5,	  0,   0, 0xFF, 0xF4
		.byte	4,   8,	  0,   7, 0xFF, 0xF4
word_5CD2E:	.word 1			
		.byte  0xF4,   6,	  0,  0xA, 0xFF, 0xF8
word_5CD36:	.word 1			
		.byte  0xF4,   6,	  0, 0x10, 0xFF, 0xF8
word_5CD3E:	.word 1			
		.byte  0xFC,   5,	  0, 0x16, 0xFF, 0xF2
word_5CD46:	.word 1			
		.byte  0xFC,   5,	  0, 0x1A, 0xFF, 0xF2
word_5CD4E:	.word 1			
		.byte  0xFC,   5,	  0, 0x1E, 0xFF, 0xF2
word_5CD56:	.word 1			
		.byte  0xF4,   6,	  0, 0x22, 0xFF, 0xF8
word_5CD5E:	.word 1			
		.byte  0xF4,   6,	  0, 0x28, 0xFF, 0xF8
