		.word word_2D352-Map_StarPost
		.word word_2D36C-Map_StarPost
		.word word_2D380-Map_StarPost
		.word word_2D388-Map_StarPost
		.word word_2D390-Map_StarPost
word_2D352:	.word 4			/*  DATA XREF: ROM:0002D348o */
		.byte  0xE8,   1,	  0,  0xE, 0xFF, 0xFC
		.byte  0xF8,   3,	  0, 0x10, 0xFF, 0xF8
		.byte  0xF8,   3,	  8, 0x10,   0,	 0
		.byte  0xD8,   5,	  0,   6, 0xFF, 0xF8
word_2D36C:	.word 3			/*  DATA XREF: ROM:0002D348o */
		.byte  0xE8,   1,	  0,  0xE, 0xFF, 0xFC
		.byte  0xF8,   3,	  0, 0x10, 0xFF, 0xF8
		.byte  0xF8,   3,	  8, 0x10,   0,	 0
word_2D380:	.word 1			/*  DATA XREF: ROM:0002D348o */
		.byte  0xF8,   5,	  0,   6, 0xFF, 0xF8
word_2D388:	.word 1			/*  DATA XREF: ROM:0002D348o */
		.byte  0xF8,   5,	  0,  0xA, 0xFF, 0xF8
word_2D390:	.word 4			/*  DATA XREF: ROM:0002D348o */
		.byte  0xE8,   1,	  0,  0xE, 0xFF, 0xFC
		.byte  0xF8,   3,	  0, 0x10, 0xFF, 0xF8
		.byte  0xF8,   3,	  8, 0x10,   0,	 0
		.byte  0xD8,   5,	  0,  0xA, 0xFF, 0xF8
