		.word byte_186E2-Ani_Shields
		.word byte_186EB-Ani_Shields
		.word byte_186F4-Ani_Shields
		.word byte_186FD-Ani_Shields
		.word byte_18706-Ani_Shields
		.word byte_1870F-Ani_Shields
		.word byte_18718-Ani_Shields
		.word byte_1871D-Ani_Shields
		.word byte_18725-Ani_Shields
		.word byte_1872D-Ani_Shields
		.word byte_18735-Ani_Shields
		.word byte_1873D-Ani_Shields
		.word byte_18745-Ani_Shields
		.word byte_1874D-Ani_Shields
		.word byte_1874F-Ani_Shields
byte_186E2:	.byte	5,   0,	  1,   2,   3,	 4,   9,  0xD, 0xFC 
byte_186EB:	.byte	5,   0,	  1,   2,   3,	 4,  0xC, 0x12, 0xFC 
byte_186F4:	.byte	5,   0,	  1,   2,   3,	 4,  0xC, 0x11, 0xFC 
byte_186FD:	.byte	5,   0,	  1,   2,   3,	 4,  0xB, 0x10, 0xFC 
byte_18706:	.byte	5,   0,	  1,   2,   3,	 4,  0xC,  0xF, 0xFC 
byte_1870F:	.byte	5,   0,	  1,   2,   3,	 4,  0xA,  0xE, 0xFC 
byte_18718:	.byte   0xE,   0,	  1,   2, 0xFC 
byte_1871D:	.byte	7, 0x16,	 0xD, 0x16,  0xD, 0x16,  0xD, 0xFC 
byte_18725:	.byte	7, 0x16,	0x12, 0x16, 0x12, 0x16, 0x12, 0xFC 
byte_1872D:	.byte	7, 0x16,	0x11, 0x16, 0x11, 0x16, 0x11, 0xFC 
byte_18735:	.byte	7, 0x16,	0x10, 0x16, 0x10, 0x16, 0x10, 0xFC 
byte_1873D:	.byte	7, 0x16,	 0xF, 0x16,  0xF, 0x16,  0xF, 0xFC 
byte_18745:	.byte	7, 0x16,	 0xE, 0x16,  0xE, 0x16,  0xE, 0xFC 
byte_1874D:	.byte   0xE, 0xFC		
byte_1874F:	.byte   0xE,   1,	  2,   3,   4, 0xFC,   0	
