		.word byte_19A80-Ani_BubbleShield
		.word byte_19AB8-Ani_BubbleShield
		.word byte_19ABF-Ani_BubbleShield
byte_19A80:	.byte    1,   0,   9,   0,   9,   0,   9,   1,  0xA,   1,  0xA,   1,  0xA,   2,   9,   2,   9,   2,   9,   3
		.byte   0xA,   3,  0xA,   3,  0xA,   4,   9,   4,   9,   4,   9,   5,  0xA,   5,  0xA,   5,  0xA,   6,   9,   6
		.byte    9,   6,   9,   7,  0xA,   7,  0xA,   7,  0xA,   8,   9,   8,   9,   8,   9, 0xFF
byte_19AB8:	.byte	5,   9,	 0xB,  0xB,  0xB, 0xFD,   0
byte_19ABF:	.byte	5,  0xC,	 0xC,  0xB, 0xFD,	 0,   0
