		.word word_1A164-DPLC_InstaShield
		.word word_1A164-DPLC_InstaShield
		.word word_1A164-DPLC_InstaShield
		.word word_1A16A-DPLC_InstaShield
		.word word_1A16A-DPLC_InstaShield
		.word word_1A16A-DPLC_InstaShield
		.word word_1A16A-DPLC_InstaShield
		.word word_1A16A-DPLC_InstaShield
word_1A164:	.word 2			/* DATA XREF: ROM:0001A154o*/
		.word 0xF000
		.word 0x6010
word_1A16A:	.word 2			/* DATA XREF: ROM:0001A154o*/
		.word 0xF017
		.word 0xC027
