		.word word_19D18-DPLC_FireShield
		.word word_19D20-DPLC_FireShield
		.word word_19D28-DPLC_FireShield
		.word word_19D30-DPLC_FireShield
		.word word_19D38-DPLC_FireShield
		.word word_19D3E-DPLC_FireShield
		.word word_19D46-DPLC_FireShield
		.word word_19D4E-DPLC_FireShield
		.word word_19D56-DPLC_FireShield
		.word word_19D5E-DPLC_FireShield
		.word word_19D66-DPLC_FireShield
		.word word_19D6C-DPLC_FireShield
		.word word_19D74-DPLC_FireShield
		.word word_19D7C-DPLC_FireShield
		.word word_19D82-DPLC_FireShield
		.word word_19D88-DPLC_FireShield
		.word word_19D8E-DPLC_FireShield
		.word word_19D94-DPLC_FireShield
		.word word_19D9C-DPLC_FireShield
		.word word_19DA4-DPLC_FireShield
		.word word_19DAA-DPLC_FireShield
		.word word_19DB2-DPLC_FireShield
		.word word_19DBA-DPLC_FireShield
		.word word_19DC0-DPLC_FireShield
		.word word_19DC6-DPLC_FireShield
word_19D18:	.word 3			/* DATA XREF: ROM:00019CE6o*/
		.word 0
		.word 0x2001
		.word 0x5004
word_19D20:	.word 3			/* DATA XREF: ROM:00019CE6o*/
		.word 0x100A
		.word 0x500C
		.word 0x5012
word_19D28:	.word 3			/* DATA XREF: ROM:00019CE6o*/
		.word 0x18
		.word 0x8019
		.word 0x8022
word_19D30:	.word 3			/* DATA XREF: ROM:00019CE6o*/
		.word 0x202B
		.word 0x802E
		.word 0x8037
word_19D38:	.word 2			/* DATA XREF: ROM:00019CE6o*/
		.word 0x5040
		.word 0x5046
word_19D3E:	.word 3			/* DATA XREF: ROM:00019CE6o*/
		.word 0x202B
		.word 0x802E
		.word 0x8037
word_19D46:	.word 3			/* DATA XREF: ROM:00019CE6o*/
		.word 0x18
		.word 0x8019
		.word 0x8022
word_19D4E:	.word 3			/* DATA XREF: ROM:00019CE6o*/
		.word 0x100A
		.word 0x500C
		.word 0x5012
word_19D56:	.word 3			/* DATA XREF: ROM:00019CE6o*/
		.word 0
		.word 0x2001
		.word 0x5004
word_19D5E:	.word 3			/* DATA XREF: ROM:00019CE6o*/
		.word 0x704C
		.word 0x2054
		.word 0x1057
word_19D66:	.word 2			/* DATA XREF: ROM:00019CE6o*/
		.word 0x8059
		.word 0x8062
word_19D6C:	.word 3			/* DATA XREF: ROM:00019CE6o*/
		.word 0xB06B
		.word 0x8077
		.word 0xB06B
word_19D74:	.word 3			/* DATA XREF: ROM:00019CE6o*/
		.word 0x704C
		.word 0x2054
		.word 0x1057
word_19D7C:	.word 2			/* DATA XREF: ROM:00019CE6o*/
		.word 0xB080
		.word 0x808C
word_19D82:	.word 2			/* DATA XREF: ROM:00019CE6o*/
		.word 0xB095
		.word 0xB0A1
word_19D88:	.word 2			/* DATA XREF: ROM:00019CE6o*/
		.word 0x50AD
		.word 0x50B3
word_19D8E:	.word 2			/* DATA XREF: ROM:00019CE6o*/
		.word 0x80B9
		.word 0x80C2
word_19D94:	.word 3			/* DATA XREF: ROM:00019CE6o*/
		.word 0xB0CB
		.word 0x80D7
		.word 0xE0
word_19D9C:	.word 3			/* DATA XREF: ROM:00019CE6o*/
		.word 0xB0E1
		.word 0xB0ED
		.word 0x10F9
word_19DA4:	.word 2			/* DATA XREF: ROM:00019CE6o*/
		.word 0x80FB
		.word 0x8104
word_19DAA:	.word 3			/* DATA XREF: ROM:00019CE6o*/
		.word 0xB0E1
		.word 0xB0ED
		.word 0x10F9
word_19DB2:	.word 3			/* DATA XREF: ROM:00019CE6o*/
		.word 0xB0CB
		.word 0x80D7
		.word 0xE0
word_19DBA:	.word 2			/* DATA XREF: ROM:00019CE6o*/
		.word 0x80C2
		.word 0x80B9
word_19DC0:	.word 2			/* DATA XREF: ROM:00019CE6o*/
		.word 0x50AD
		.word 0x50B3
word_19DC6:	.word 0			/* DATA XREF: ROM:00019CE6o*/
