		.word word_1A090-DPLC_BubbleShield
		.word word_1A094-DPLC_BubbleShield
		.word word_1A098-DPLC_BubbleShield
		.word word_1A09C-DPLC_BubbleShield
		.word word_1A0A0-DPLC_BubbleShield
		.word word_1A0A4-DPLC_BubbleShield
		.word word_1A0A8-DPLC_BubbleShield
		.word word_1A0AC-DPLC_BubbleShield
		.word word_1A0B0-DPLC_BubbleShield
		.word word_1A0B4-DPLC_BubbleShield
		.word word_1A0BA-DPLC_BubbleShield
		.word word_1A0C0-DPLC_BubbleShield
		.word word_1A0C8-DPLC_BubbleShield
word_1A090:	.word 1			/* DATA XREF: ROM:0001A076o*/
		.word 0x3000
word_1A094:	.word 1			/* DATA XREF: ROM:0001A076o*/
		.word 0x5004
word_1A098:	.word 1			/* DATA XREF: ROM:0001A076o*/
		.word 0x800A
word_1A09C:	.word 1			/* DATA XREF: ROM:0001A076o*/
		.word 0x8013
word_1A0A0:	.word 1			/* DATA XREF: ROM:0001A076o*/
		.word 0xB01C
word_1A0A4:	.word 1			/* DATA XREF: ROM:0001A076o*/
		.word 0x8013
word_1A0A8:	.word 1			/* DATA XREF: ROM:0001A076o*/
		.word 0x800A
word_1A0AC:	.word 1			/* DATA XREF: ROM:0001A076o*/
		.word 0x5004
word_1A0B0:	.word 1			/* DATA XREF: ROM:0001A076o*/
		.word 0x1000
word_1A0B4:	.word 2			/* DATA XREF: ROM:0001A076o*/
		.word 0x8028
		.word 0x8031
word_1A0BA:	.word 2			/* DATA XREF: ROM:0001A076o*/
		.word 0x803A
		.word 0x8043
word_1A0C0:	.word 3			/* DATA XREF: ROM:0001A076o*/
		.word 0x704C
		.word 0x5054
		.word 0xB05A
word_1A0C8:	.word 3			/* DATA XREF: ROM:0001A076o*/
		.word 0xF066
		.word 0x3076
		.word 0xF07A
