		.word word_19F28-DPLC_LightningShield
		.word word_19F30-DPLC_LightningShield
		.word word_19F36-DPLC_LightningShield
		.word word_19F3E-DPLC_LightningShield
		.word word_19F46-DPLC_LightningShield
		.word word_19F4C-DPLC_LightningShield
		.word word_19F54-DPLC_LightningShield
		.word word_19F5C-DPLC_LightningShield
		.word word_19F62-DPLC_LightningShield
		.word word_19F6A-DPLC_LightningShield
		.word word_19F70-DPLC_LightningShield
		.word word_19F76-DPLC_LightningShield
		.word word_19F7A-DPLC_LightningShield
		.word word_19F7E-DPLC_LightningShield
		.word word_19F28-DPLC_LightningShield
		.word word_19F30-DPLC_LightningShield
		.word word_19F36-DPLC_LightningShield
		.word word_19F3E-DPLC_LightningShield
		.word word_19F46-DPLC_LightningShield
		.word word_19F4C-DPLC_LightningShield
		.word word_19F54-DPLC_LightningShield
		.word word_19F5C-DPLC_LightningShield
		.word word_19F62-DPLC_LightningShield
word_19F28:	.word 3			/*  DATA XREF: ROM:00019EFAo */
		.word 0x3000
		.word 0x7004
		.word 0x300C
word_19F30:	.word 2			/*  DATA XREF: ROM:00019EFAo */
		.word 0x8010
		.word 0x8019
word_19F36:	.word 3			/*  DATA XREF: ROM:00019EFAo */
		.word 0x2022
		.word 0xB025
		.word 0x2031
word_19F3E:	.word 3			/*  DATA XREF: ROM:00019EFAo */
		.word 0x2034
		.word 0xB037
		.word 0x5043
word_19F46:	.word 2			/*  DATA XREF: ROM:00019EFAo */
		.word 0x5049
		.word 0x504F
word_19F4C:	.word 3			/*  DATA XREF: ROM:00019EFAo */
		.word 0x2034
		.word 0xB037
		.word 0x5043
word_19F54:	.word 3			/*  DATA XREF: ROM:00019EFAo */
		.word 0x2022
		.word 0xB025
		.word 0x2031
word_19F5C:	.word 2			/*  DATA XREF: ROM:00019EFAo */
		.word 0x8010
		.word 0x8019
word_19F62:	.word 3			/*  DATA XREF: ROM:00019EFAo */
		.word 0x3000
		.word 0x7004
		.word 0x300C
word_19F6A:	.word 2			/*  DATA XREF: ROM:00019EFAo */
		.word 0x8055
		.word 0x805E
word_19F70:	.word 2			/*  DATA XREF: ROM:00019EFAo */
		.word 0x8067
		.word 0x8070
word_19F76:	.word 1			/*  DATA XREF: ROM:00019EFAo */
		.word 0x8079
word_19F7A:	.word 1			/*  DATA XREF: ROM:00019EFAo */
		.word 0x82
word_19F7E:	.word 1			/*  DATA XREF: ROM:00019EFAo */
		.word 0x3083
