		.word word_1A0E0-Map_InstaShield
		.word word_1A0F4-Map_InstaShield
		.word word_1A108-Map_InstaShield
		.word word_1A116-Map_InstaShield
		.word word_1A12A-Map_InstaShield
		.word word_1A13E-Map_InstaShield
		.word word_1A152-Map_InstaShield
		.word word_1A152-Map_InstaShield
word_1A0E0:	.word 3			/*  DATA XREF: ROM:0001A0D0o */
		.byte  0xE8,   8,	  0,   0, 0xFF, 0xF0
		.byte  0xF0,   4,	  0,   3, 0xFF, 0xF8
		.byte  0xF8,   0,	  0,   5,   0,	 0
word_1A0F4:	.word 3			/*  DATA XREF: ROM:0001A0D0o */
		.byte  0xF0,   4,	  0,   6,   0,	 8
		.byte  0xF8,   8,	  0,   8,   0,	 0
		.byte	0,   4,	  0,  0xB,   0,	 0
word_1A108:	.word 2			/*  DATA XREF: ROM:0001A0D0o */
		.byte	0,   9,	  0,  0xD,   0,	 0
		.byte  0x10,  0xC,	  0, 0x13, 0xFF, 0xF8
word_1A116:	.word 3			/*  DATA XREF: ROM:0001A0D0o */
		.byte  0xF0,  0xC,	  0,   0, 0xFF, 0xE8
		.byte  0xF8,   8,	  0,   4, 0xFF, 0xE8
		.byte	0,   6,	  0,   7, 0xFF, 0xE8
word_1A12A:	.word 3			/*  DATA XREF: ROM:0001A0D0o */
		.byte  0xE8,   4,	  0,  0xD, 0xFF, 0xF0
		.byte  0xE8,  0xB,	  0,  0xF,   0,	 0
		.byte	8,   4,	  0, 0x1B,   0,	 8
word_1A13E:	.word 3			/*  DATA XREF: ROM:0001A0D0o */
		.byte  0xF0,   4,	0x18, 0x1B, 0xFF, 0xE8
		.byte  0xF8,  0xB,	0x18,  0xF, 0xFF, 0xE8
		.byte  0x10,   4,	0x18,  0xD,   0,	 0
word_1A152:	.word 0			/*  DATA XREF: ROM:0001A0D0o */
