		.word word_1787C-Map_Invincibility
		.word word_1787E-Map_Invincibility
		.word word_17886-Map_Invincibility
		.word word_1788E-Map_Invincibility
		.word word_17896-Map_Invincibility
		.word word_1789E-Map_Invincibility
		.word word_178A6-Map_Invincibility
		.word word_178AE-Map_Invincibility
		.word word_178B6-Map_Invincibility
word_1787C:	.word 0
word_1787E:	.word 1
		.byte  0xF8,   0,   0,   0, 0xFF, 0xFC
word_17886:	.word 1
		.byte  0xF8,   0,   0,   1, 0xFF, 0xFC
word_1788E:	.word 1
		.byte  0xF8,   1,   0,   2, 0xFF, 0xFC
word_17896:	.word 1
		.byte  0xF8,   1,   0,   4, 0xFF, 0xFC
word_1789E:	.word 1
		.byte  0xF8,   1,   0,   6, 0xFF, 0xFC
word_178A6:	.word 1
		.byte  0xF8,   5,   0,   8, 0xFF, 0xF8
word_178AE:	.word 1
		.byte  0xF8,   5,   0,  0xC, 0xFF, 0xF8
word_178B6:	.word 1
		.byte  0xF0,  0xF,   0, 0x10, 0xFF, 0xF0
