		.word word_19F9C-Map_BubbleShield
		.word word_19FA4-Map_BubbleShield
		.word word_19FB2-Map_BubbleShield
		.word word_19FC0-Map_BubbleShield
		.word word_19FCE-Map_BubbleShield
		.word word_19FDC-Map_BubbleShield
		.word word_19FEA-Map_BubbleShield
		.word word_19FF8-Map_BubbleShield
		.word word_1A006-Map_BubbleShield
		.word word_1A014-Map_BubbleShield
		.word word_1A02E-Map_BubbleShield
		.word word_1A048-Map_BubbleShield
		.word word_1A062-Map_BubbleShield
word_19F9C:	.word 1			/*  DATA XREF: ROM:00019F82o */
		.byte  0xE8,  0xC,	  0,   0, 0xFF, 0xF0
word_19FA4:	.word 2			/*  DATA XREF: ROM:00019F82o */
		.byte  0xE8,   9,	  0,   0, 0xFF, 0xE8
		.byte  0xE8,   9,	  8,   0,   0,	 0
word_19FB2:	.word 2			/*  DATA XREF: ROM:00019F82o */
		.byte  0xE8,  0xA,	  0,   0, 0xFF, 0xE8
		.byte  0xE8,  0xA,	  8,   0,   0,	 0
word_19FC0:	.word 2			/*  DATA XREF: ROM:00019F82o */
		.byte  0xE8,  0xA,	  0,   0, 0xFF, 0xE8
		.byte  0xE8,  0xA,	  8,   0,   0,	 0
word_19FCE:	.word 2			/*  DATA XREF: ROM:00019F82o */
		.byte  0xF0,  0xB,	  0,   0, 0xFF, 0xE8
		.byte  0xF0,  0xB,	  8,   0,   0,	 0
word_19FDC:	.word 2			/*  DATA XREF: ROM:00019F82o */
		.byte	0,  0xA,	0x10,   0, 0xFF, 0xE8
		.byte	0,  0xA,	0x18,   0,   0,	 0
word_19FEA:	.word 2			/*  DATA XREF: ROM:00019F82o */
		.byte	0,  0xA,	0x10,   0, 0xFF, 0xE8
		.byte	0,  0xA,	0x18,   0,   0,	 0
word_19FF8:	.word 2			/*  DATA XREF: ROM:00019F82o */
		.byte	8,   9,	0x10,   0, 0xFF, 0xE8
		.byte	8,   9,	0x18,   0,   0,	 0
word_1A006:	.word 2			/*  DATA XREF: ROM:00019F82o */
		.byte  0x10,   4,	0x10,   0, 0xFF, 0xF0
		.byte  0x10,   4,	0x18,   0,   0,	 0
word_1A014:	.word 4			/*  DATA XREF: ROM:00019F82o */
		.byte  0xE8,  0xA,	  0,   0, 0xFF, 0xE8
		.byte  0xE8,  0xA,	  0,   9,   0,	 0
		.byte	0,  0xA,	0x10,   0, 0xFF, 0xE8
		.byte	0,  0xA,	0x18,   0,   0,	 0
word_1A02E:	.word 4			/*  DATA XREF: ROM:00019F82o */
		.byte  0xE8,  0xA,	  0,   0, 0xFF, 0xE8
		.byte  0xE8,  0xA,	  0,   9,   0,	 0
		.byte	0,  0xA,	0x10,   0, 0xFF, 0xE8
		.byte	0,  0xA,	0x18,   0,   0,	 0
word_1A048:	.word 4			/*  DATA XREF: ROM:00019F82o */
		.byte  0xEC,  0xD,	  0,   0, 0xFF, 0xE4
		.byte  0xEC,   9,	  0,   8,   0,	 4
		.byte  0xFC,  0xE,	  0,  0xE, 0xFF, 0xE4
		.byte  0xFC,  0xA,	  8,  0xE,   0,	 4
word_1A062:	.word 3			/*  DATA XREF: ROM:00019F82o */
		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xDC
		.byte  0xF0,   3,	  0, 0x10, 0xFF, 0xFC
		.byte  0xF0,  0xF,	  0, 0x14,   0,	 4
