		.word word_177CE-Map_Shield_S2
		.word word_177E8-Map_Shield_S2
		.word word_17802-Map_Shield_S2
		.word word_1781C-Map_Shield_S2
		.word word_17836-Map_Shield_S2
		.word word_17850-Map_Shield_S2
word_177CE:	.word 4
		.byte  0xF0,   5,   0,   0, 0xFF, 0xF0
		.byte  0xF0,   5,   8,   0,   0,   0
		.byte    0,   5, 0x10,   0, 0xFF, 0xF0
		.byte    0,   5, 0x18,   0,   0,   0
word_177E8:	.word 4
		.byte  0xF0,   5,   0,   4, 0xFF, 0xF0
		.byte  0xF0,   5,   8,   4,   0,   0
		.byte    0,   5, 0x10,   4, 0xFF, 0xF0
		.byte    0,   5, 0x18,   4,   0,   0
word_17802:	.word 4
		.byte  0xF0,   5,   0,   8, 0xFF, 0xF0
		.byte  0xF0,   5,   8,   8,   0,   0
		.byte    0,   5, 0x10,   8, 0xFF, 0xF0
		.byte    0,   5, 0x18,   8,   0,   0
word_1781C:	.word 4
		.byte  0xF0,   5,   0,  0xC, 0xFF, 0xF0
		.byte  0xF0,   5,   8,  0xC,   0,   0
		.byte    0,   5, 0x10,  0xC, 0xFF, 0xF0
		.byte    0,   5, 0x18,  0xC,   0,   0
word_17836:	.word 4
		.byte  0xF0,   5,   0, 0x10, 0xFF, 0xF0
		.byte  0xF0,   5,   8, 0x10,   0,   0
		.byte    0,   5, 0x10, 0x10, 0xFF, 0xF0
		.byte    0,   5, 0x18, 0x10,   0,   0
word_17850:	.word 4
		.byte  0xE0,  0xB,   0, 0x14, 0xFF, 0xE8
		.byte  0xE0,  0xB,   8, 0x14,   0,   0
		.byte    0,  0xB, 0x10, 0x14, 0xFF, 0xE8
		.byte    0,  0xB, 0x18, 0x14,   0,   0
