		.word word_19DF8-Map_LightningShield
		.word word_19E0C-Map_LightningShield
		.word word_19E1A-Map_LightningShield
		.word word_19E2E-Map_LightningShield
		.word word_19E42-Map_LightningShield
		.word word_19E50-Map_LightningShield
		.word word_19E64-Map_LightningShield
		.word word_19E78-Map_LightningShield
		.word word_19E86-Map_LightningShield
		.word word_19E9A-Map_LightningShield
		.word word_19EB4-Map_LightningShield
		.word word_19ECE-Map_LightningShield
		.word word_19EE8-Map_LightningShield
		.word word_19EF0-Map_LightningShield
		.word word_19DF8-Map_LightningShield
		.word word_19E0C-Map_LightningShield
		.word word_19E1A-Map_LightningShield
		.word word_19E2E-Map_LightningShield
		.word word_19E42-Map_LightningShield
		.word word_19E50-Map_LightningShield
		.word word_19E64-Map_LightningShield
		.word word_19E78-Map_LightningShield
		.word word_19E86-Map_LightningShield
		.word word_19EF8-Map_LightningShield
word_19DF8:	.word 3			/* DATA XREF: ROM:00019DC8o*/
		.byte  0xE8,  0xC,	  0,   0, 0xFF, 0xF8
		.byte  0xF0,   7,	  0,   4,   0,	 8
		.byte  0x10,  0xC,	  0,  0xC, 0xFF, 0xF8
word_19E0C:	.word 2			/* DATA XREF: ROM:00019DC8o*/
		.byte  0xE8,  0xA,	  0,   0,   0,	 0
		.byte	0,  0xA,	  0,   9,   0,	 0
word_19E1A:	.word 3			/* DATA XREF: ROM:00019DC8o*/
		.byte  0xE8,   8,	  0,   0, 0xFF, 0xF8
		.byte  0xF0,  0xB,	  0,   3,   0,	 0
		.byte  0x10,   8,	  0,  0xF, 0xFF, 0xF8
word_19E2E:	.word 3			/* DATA XREF: ROM:00019DC8o*/
		.byte  0xE8,   8,	  0,   0, 0xFF, 0xF8
		.byte  0xF0,  0xE,	  0,   3, 0xFF, 0xF8
		.byte	8,   9,	  0,  0xF, 0xFF, 0xF8
word_19E42:	.word 2			/* DATA XREF: ROM:00019DC8o*/
		.byte  0xE8,   6,	  0,   0, 0xFF, 0xF8
		.byte	0,   6,	  0,   6, 0xFF, 0xF8
word_19E50:	.word 3			/* DATA XREF: ROM:00019DC8o*/
		.byte  0xE8,   8,	  8,   0, 0xFF, 0xF0
		.byte  0xF0,  0xE,	  8,   3, 0xFF, 0xE8
		.byte	8,   9,	  8,  0xF, 0xFF, 0xF0
word_19E64:	.word 3			/* DATA XREF: ROM:00019DC8o*/
		.byte  0xE8,   8,	  8,   0, 0xFF, 0xF0
		.byte  0xF0,  0xB,	  8,   3, 0xFF, 0xE8
		.byte  0x10,   8,	  8,  0xF, 0xFF, 0xF0
word_19E78:	.word 2			/* DATA XREF: ROM:00019DC8o*/
		.byte  0xE8,  0xA,	  8,   0, 0xFF, 0xE8
		.byte	0,  0xA,	  8,   9, 0xFF, 0xE8
word_19E86:	.word 3			/* DATA XREF: ROM:00019DC8o*/
		.byte  0xE8,  0xC,	  8,   0, 0xFF, 0xE8
		.byte  0xF0,   7,	  8,   4, 0xFF, 0xE8
		.byte  0x10,  0xC,	  8,  0xC, 0xFF, 0xE8
word_19E9A:	.word 4			/* DATA XREF: ROM:00019DC8o*/
		.byte  0xE8,  0xA,	  0,   0, 0xFF, 0xE8
		.byte	0,  0xA,	  0,   9, 0xFF, 0xE8
		.byte  0xE8,  0xA,	0x18,   9,   0,	 0
		.byte	0,  0xA,	0x18,   0,   0,	 0
word_19EB4:	.word 4			/* DATA XREF: ROM:00019DC8o*/
		.byte  0xE8,  0xA,	  0,   0, 0xFF, 0xE8
		.byte  0xE8,  0xA,	  0,   9,   0,	 0
		.byte	0,  0xA,	0x18,   9, 0xFF, 0xE8
		.byte	0,  0xA,	0x18,   0,   0,	 0
word_19ECE:	.word 4			/* DATA XREF: ROM:00019DC8o*/
		.byte  0xE8,  0xA,	  0,   0, 0xFF, 0xE8
		.byte  0xE8,  0xA,	  8,   0,   0,	 0
		.byte	0,  0xA,	0x10,   0, 0xFF, 0xE8
		.byte	0,  0xA,	0x18,   0,   0,	 0
word_19EE8:	.word 1			/* DATA XREF: ROM:00019DC8o*/
		.byte  0xFC,   0,	  0, 0x1F, 0xFF, 0xFC
word_19EF0:	.word 1			/* DATA XREF: ROM:00019DC8o*/
		.byte  0xF8,   5,	  0, 0x20, 0xFF, 0xF8
word_19EF8:	.word 0			/* DATA XREF: ROM:00019DC8o*/
