		.word word_19AF8-Map_FireShield
		.word word_19B0C-Map_FireShield
		.word word_19B20-Map_FireShield
		.word word_19B34-Map_FireShield
		.word word_19B48-Map_FireShield
		.word word_19B62-Map_FireShield
		.word word_19B76-Map_FireShield
		.word word_19B8A-Map_FireShield
		.word word_19B9E-Map_FireShield
		.word word_19BB2-Map_FireShield
		.word word_19BC6-Map_FireShield
		.word word_19BE0-Map_FireShield
		.word word_19BFA-Map_FireShield
		.word word_19C0E-Map_FireShield
		.word word_19C28-Map_FireShield
		.word word_19C42-Map_FireShield
		.word word_19C50-Map_FireShield
		.word word_19C5E-Map_FireShield
		.word word_19C72-Map_FireShield
		.word word_19C86-Map_FireShield
		.word word_19CA0-Map_FireShield
		.word word_19CB4-Map_FireShield
		.word word_19CC8-Map_FireShield
		.word word_19CD6-Map_FireShield
		.word word_19CE4-Map_FireShield
word_19AF8:	.word 3			/* DATA XREF: ROM:00019AC6o*/
		.byte	8,   0,	  0,   0, 0xFF, 0xF0
		.byte  0x10,   8,	  0,   1, 0xFF, 0xE8
		.byte	8,   9,	  0,   4,   0,	 0
word_19B0C:	.word 3			/* DATA XREF: ROM:00019AC6o*/
		.byte	0,   4,	  0,   0, 0xFF, 0xF0
		.byte	8,   9,	  0,   2, 0xFF, 0xE8
		.byte	8,   9,	  0,   8,   0,	 0
word_19B20:	.word 3			/* DATA XREF: ROM:00019AC6o*/
		.byte  0xF8,   0,	  0,   0, 0xFF, 0xF8
		.byte	0,  0xA,	  0,   1, 0xFF, 0xE8
		.byte	0,  0xA,	  0,  0xA,   0,	 0
word_19B34:	.word 3			/* DATA XREF: ROM:00019AC6o*/
		.byte  0xF0,   8,	  0,   0, 0xFF, 0xF0
		.byte  0xF8,  0xA,	  0,   3, 0xFF, 0xE8
		.byte  0xF8,  0xA,	  0,  0xC,   0,	 0
word_19B48:	.word 4			/* DATA XREF: ROM:00019AC6o*/
		.byte  0xF0,   9,	  0,   0, 0xFF, 0xE8
		.byte  0xF0,   9,	  0,   6,   0,	 0
		.byte	0,   9,	0x10,   0, 0xFF, 0xE8
		.byte	0,   9,	0x10,   6,   0,	 0
word_19B62:	.word 3			/* DATA XREF: ROM:00019AC6o*/
		.byte	8,   8,	0x18,   0, 0xFF, 0xF8
		.byte  0xF0,  0xA,	0x18,   3,   0,	 0
		.byte  0xF0,  0xA,	0x18,  0xC, 0xFF, 0xE8
word_19B76:	.word 3			/* DATA XREF: ROM:00019AC6o*/
		.byte	0,   0,	0x18,   0,   0,	 0
		.byte  0xE8,  0xA,	0x18,   1,   0,	 0
		.byte  0xE8,  0xA,	0x18,  0xA, 0xFF, 0xE8
word_19B8A:	.word 3			/* DATA XREF: ROM:00019AC6o*/
		.byte  0xF8,   4,	0x18,   0,   0,	 0
		.byte  0xE8,   9,	0x18,   2,   0,	 0
		.byte  0xE8,   9,	0x18,   8, 0xFF, 0xE8
word_19B9E:	.word 3			/* DATA XREF: ROM:00019AC6o*/
		.byte  0xF0,   0,	0x18,   0,   0,	 8
		.byte  0xE8,   8,	0x18,   1,   0,	 0
		.byte  0xE8,   9,	0x18,   4, 0xFF, 0xE8
word_19BB2:	.word 3			/* DATA XREF: ROM:00019AC6o*/
		.byte  0xE8,   7,	  0,   0,   0,	0xC
		.byte	8,   8,	  0,   8,   0,	 4
		.byte  0x10,   4,	  0,  0xB,   0,	0xC
word_19BC6:	.word 4			/* DATA XREF: ROM:00019AC6o*/
		.byte  0xE8,  0xA,	  0,   0, 0xFF, 0xEC
		.byte  0xE8,  0xA,	  0,   9,   0,	 4
		.byte	0,  0xA,	0x10,   0, 0xFF, 0xEC
		.byte	0,  0xA,	0x10,   9,   0,	 4
word_19BE0:	.word 4			/* DATA XREF: ROM:00019AC6o*/
		.byte  0xE8,  0xE,	  0,   0, 0xFF, 0xE4
		.byte  0xE8,  0xA,	  0,  0xC,   0,	 4
		.byte	0,  0xE,	0x10, 0x15, 0xFF, 0xE4
		.byte	0,  0xA,	0x10,  0xC,   0,	 4
word_19BFA:	.word 3			/* DATA XREF: ROM:00019AC6o*/
		.byte  0xF8,   7,	0x10,   0,   0,	0xC
		.byte  0xF0,   8,	0x10,   8,   0,	 4
		.byte  0xE8,   4,	0x10,  0xB,   0,	0xC
word_19C0E:	.word 4			/* DATA XREF: ROM:00019AC6o*/
		.byte  0xE8,  0xE,	  0,   0, 0xFF, 0xE4
		.byte  0xE8,  0xA,	  0,  0xC,   0,	 4
		.byte	0,  0xE,	0x10,   0, 0xFF, 0xE4
		.byte	0,  0xA,	0x10,  0xC,   0,	 4
word_19C28:	.word 4			/* DATA XREF: ROM:00019AC6o*/
		.byte  0xE8,  0xE,	  0,   0, 0xFF, 0xE0
		.byte  0xE8,  0xE,	  0,  0xC,   0,	 0
		.byte	0,  0xE,	0x10,   0, 0xFF, 0xE0
		.byte	0,  0xE,	0x10,  0xC,   0,	 0
word_19C42:	.word 2			/* DATA XREF: ROM:00019AC6o*/
		.byte  0xE8,   9,	  0,   0, 0xFF, 0xE8
		.byte  0xE8,   9,	  0,   6,   0,	 0
word_19C50:	.word 2			/* DATA XREF: ROM:00019AC6o*/
		.byte  0xE8,  0xA,	  0,   0, 0xFF, 0xE8
		.byte  0xE8,  0xA,	  0,   9,   0,	 0
word_19C5E:	.word 3			/* DATA XREF: ROM:00019AC6o*/
		.byte  0xE8,  0xB,	  0,   0, 0xFF, 0xE8
		.byte  0xE8,  0xA,	  0,  0xC,   0,	 0
		.byte	0,   0,	  0, 0x15,   0,	 8
word_19C72:	.word 3			/* DATA XREF: ROM:00019AC6o*/
		.byte  0xE8,  0xB,	  0,   0, 0xFF, 0xE8
		.byte  0xE8,  0xB,	  0,  0xC,   0,	 0
		.byte	8,   4,	  0, 0x18,   0,	 8
word_19C86:	.word 4			/* DATA XREF: ROM:00019AC6o*/
		.byte  0xE8,  0xA,	  0,   0, 0xFF, 0xE8
		.byte  0xE8,  0xA,	  0,   9,   0,	 0
		.byte	0,  0xA,	0x10,   0, 0xFF, 0xE8
		.byte	0,  0xA,	0x10,   9,   0,	 0
word_19CA0:	.word 3			/* DATA XREF: ROM:00019AC6o*/
		.byte  0xF8,  0xB,	0x18,   0,   0,	 0
		.byte  0xF8,  0xB,	0x18,  0xC, 0xFF, 0xE8
		.byte  0xF0,   4,	0x18, 0x18, 0xFF, 0xE8
word_19CB4:	.word 3			/* DATA XREF: ROM:00019AC6o*/
		.byte  0xF8,  0xB,	0x18,   0,   0,	 0
		.byte	0,  0xA,	0x18,  0xC, 0xFF, 0xE8
		.byte  0xF8,   0,	0x18, 0x15, 0xFF, 0xF0
word_19CC8:	.word 2			/* DATA XREF: ROM:00019AC6o*/
		.byte	0,  0xA,	0x18,   0, 0xFF, 0xE8
		.byte	0,  0xA,	0x18,   9,   0,	 0
word_19CD6:	.word 2			/* DATA XREF: ROM:00019AC6o*/
		.byte	8,   9,	0x18,   0,   0,	 0
		.byte	8,   9,	0x18,   6, 0xFF, 0xE8
word_19CE4:	.word 0			/* DATA XREF: ROM:00019AC6o*/
