		.word word_160E20-Map_Toxomister
		.word word_160E28-Map_Toxomister
		.word word_160E42-Map_Toxomister
		.word word_160E4A-Map_Toxomister
		.word word_160E52-Map_Toxomister
		.word word_160E5A-Map_Toxomister
		.word word_160E62-Map_Toxomister
		.word word_160E6A-Map_Toxomister
word_160E20:	.word 1
		.byte  0xF8,   5,   0,   0, 0xFF, 0xF8
word_160E28:	.word 4
		.byte  0xF0,   1,   0,   4, 0xFF, 0xF8
		.byte  0xF0,   1,   8,   4,   0,   0
		.byte    0,   1,   0,   4, 0xFF, 0xF8
		.byte    0,   1,   8,   4,   0,   0
word_160E42:	.word 1
		.byte  0xFC,   0,   0,   6, 0xFF, 0xFC
word_160E4A:	.word 1
		.byte  0xFC,   0,   0,   7, 0xFF, 0xFC
word_160E52:	.word 1
		.byte  0xF8,   5,   0,   8, 0xFF, 0xF8
word_160E5A:	.word 1
		.byte  0xF8,   5,   0,  0xC, 0xFF, 0xF8
word_160E62:	.word 1
		.byte  0xF8,   5,   0, 0x10, 0xFF, 0xF8
word_160E6A:	.word 1
		.byte  0xF8,   5,   0, 0x14, 0xFF, 0xF8
