		.word word_9009E-Map_Toxomister
		.word word_900B8-Map_Toxomister
		.word word_900C0-Map_Toxomister
		.word word_900C8-Map_Toxomister
		.word word_900D0-Map_Toxomister
		.word word_900D8-Map_Toxomister
		.word word_900E0-Map_Toxomister
		.word word_900E8-Map_Toxomister
word_9009E:	.word 4			/*  DATA XREF: ROM:0009008Eo */
		.byte  0xF0,   1,	  0,   4, 0xFF, 0xF8
		.byte  0xF0,   1,	  8,   4,   0,	 0
		.byte	0,   1,	  0,   4, 0xFF, 0xF8
		.byte	0,   1,	  8,   4,   0,	 0
word_900B8:	.word 1			/*  DATA XREF: ROM:0009008Eo */
		.byte  0xF8,   5,	  0,   0, 0xFF, 0xF8
word_900C0:	.word 1			/*  DATA XREF: ROM:0009008Eo */
		.byte  0xFC,   0,	  0,   6, 0xFF, 0xFC
word_900C8:	.word 1			/*  DATA XREF: ROM:0009008Eo */
		.byte  0xFC,   0,	  0,   7, 0xFF, 0xFC
word_900D0:	.word 1			/*  DATA XREF: ROM:0009008Eo */
		.byte  0xF8,   5,	  0,   8, 0xFF, 0xF8
word_900D8:	.word 1			/*  DATA XREF: ROM:0009008Eo */
		.byte  0xF8,   5,	  0,  0xC, 0xFF, 0xF8
word_900E0:	.word 1			/*  DATA XREF: ROM:0009008Eo */
		.byte  0xF8,   5,	  0, 0x10, 0xFF, 0xF8
word_900E8:	.word 1			/*  DATA XREF: ROM:0009008Eo */
		.byte  0xF8,   5,	  0, 0x14, 0xFF, 0xF8
