Map_361BD0:	.word Frame_361BDE-Map_361BD0
		.word Frame_361BEC-Map_361BD0
		.word Frame_361BFA-Map_361BD0
		.word Frame_361C14-Map_361BD0
		.word Frame_361C22-Map_361BD0
		.word Frame_361C30-Map_361BD0
		.word Frame_361C38-Map_361BD0
Frame_361BDE:	.word 2
		.byte 0xF8, 0xD,  0,  0,0xFF,0xE0
		.byte 0xF8, 0xD,  8,  0,  0,  0
Frame_361BEC:	.word 2
		.byte 0xF8, 0xD,  0,  8,0xFF,0xE0
		.byte 0xF8, 0xD,  8,  8,  0,  0
Frame_361BFA:	.word 4
		.byte   0,  9,  0,0x10,0xFF,0xE0
		.byte 0xF8,  1,  0,0x16,0xFF,0xF8
		.byte 0xF8,  1,  8,0x16,  0,  0
		.byte   0,  9,  8,0x10,  0,  8
Frame_361C14:	.word 2
		.byte 0xF8,  1,  0,0x18,0xFF,0xF8
		.byte 0xF8,  1,  8,0x18,  0,  0
Frame_361C22:	.word 2
		.byte 0xF8,  1,  0,0x1A,0xFF,0xF8
		.byte 0xF8,  1,  8,0x1A,  0,  0
Frame_361C30:	.word 1
		.byte 0xFC,  0,  0,0x1C,0xFF,0xFC
Frame_361C38:	.word 1
		.byte 0xFC,  0,  0,0x1D,0xFF,0xFC
