		.word word_83362-Map_DDZMissileAsteroid
		.word word_833AC-Map_DDZMissileAsteroid
		.word word_833AC-Map_DDZMissileAsteroid
		.word word_833AC-Map_DDZMissileAsteroid
		.word word_833AC-Map_DDZMissileAsteroid
		.word word_833AC-Map_DDZMissileAsteroid
		.word word_833BA-Map_DDZMissileAsteroid
		.word word_833C8-Map_DDZMissileAsteroid
		.word word_833D6-Map_DDZMissileAsteroid
		.word word_833E4-Map_DDZMissileAsteroid
		.word word_833F8-Map_DDZMissileAsteroid
		.word word_83406-Map_DDZMissileAsteroid
		.word word_8341A-Map_DDZMissileAsteroid
		.word word_83428-Map_DDZMissileAsteroid
		.word word_8343C-Map_DDZMissileAsteroid
		.word word_8344A-Map_DDZMissileAsteroid
		.word word_8345E-Map_DDZMissileAsteroid
		.word word_83466-Map_DDZMissileAsteroid
		.word word_8346E-Map_DDZMissileAsteroid
		.word word_83476-Map_DDZMissileAsteroid
		.word word_8347E-Map_DDZMissileAsteroid
		.word word_83486-Map_DDZMissileAsteroid
		.word word_8348E-Map_DDZMissileAsteroid
		.word word_83496-Map_DDZMissileAsteroid
		.word word_8349E-Map_DDZMissileAsteroid
		.word word_834A6-Map_DDZMissileAsteroid
		.word word_834AE-Map_DDZMissileAsteroid
		.word word_834B6-Map_DDZMissileAsteroid
		.word word_834BE-Map_DDZMissileAsteroid
		.word word_834C6-Map_DDZMissileAsteroid
		.word word_834CE-Map_DDZMissileAsteroid
		.word word_834D6-Map_DDZMissileAsteroid
		.word word_834DE-Map_DDZMissileAsteroid
		.word word_834E6-Map_DDZMissileAsteroid
		.word word_834EE-Map_DDZMissileAsteroid
		.word word_834F6-Map_DDZMissileAsteroid
		.word word_834FE-Map_DDZMissileAsteroid
		.word word_83506-Map_DDZMissileAsteroid
		.word word_8350E-Map_DDZMissileAsteroid
		.word word_83516-Map_DDZMissileAsteroid
		.word word_83530-Map_DDZMissileAsteroid
		.word word_8356E-Map_DDZMissileAsteroid
		.word word_83576-Map_DDZMissileAsteroid
		.word word_8357E-Map_DDZMissileAsteroid
		.word word_83586-Map_DDZMissileAsteroid
		.word word_8358E-Map_DDZMissileAsteroid
		.word word_83596-Map_DDZMissileAsteroid
		.word word_8359E-Map_DDZMissileAsteroid
		.word word_835A6-Map_DDZMissileAsteroid
		.word word_835AE-Map_DDZMissileAsteroid
		.word word_835BC-Map_DDZMissileAsteroid
		.word word_835CA-Map_DDZMissileAsteroid
		.word word_835D2-Map_DDZMissileAsteroid
		.word word_835DA-Map_DDZMissileAsteroid
		.word word_835E2-Map_DDZMissileAsteroid
		.word word_835EA-Map_DDZMissileAsteroid
		.word word_835F2-Map_DDZMissileAsteroid
		.word word_8360C-Map_DDZMissileAsteroid
		.word word_8360E-Map_DDZMissileAsteroid
		.word word_8362E-Map_DDZMissileAsteroid
		.word word_8364E-Map_DDZMissileAsteroid
		.word word_8366E-Map_DDZMissileAsteroid
		.word word_83694-Map_DDZMissileAsteroid
		.word word_836BA-Map_DDZMissileAsteroid
word_83362:	.word 0xC			/*  DATA XREF: ROM:000832E2o */
		.byte  0xD4,  0xF,	  0,   0, 0xFF, 0xF0
		.byte  0xD4,  0xF,	  0, 0x10,   0, 0x10
		.byte  0xE4,   0,	  0, 0x20,   0, 0x30
		.byte  0xE4,   9,	  0, 0x21, 0xFF, 0xD8
		.byte  0xFC,   2,	  0, 0x27, 0xFF, 0xC8
		.byte  0xF4,  0xF,	  0, 0x2A, 0xFF, 0xD0
		.byte  0xF4,  0xF,	  0, 0x3A, 0xFF, 0xF0
		.byte  0xF4,  0xF,	  0, 0x4A,   0, 0x10
		.byte  0x14,   0,	  0, 0x5A, 0xFF, 0xE0
		.byte  0x14,  0xE,	  0, 0x5B, 0xFF, 0xE8
		.byte  0x14,  0xE,	  0, 0x67,   0,	 8
		.byte  0x14,   0,	  8, 0x5A,   0, 0x28
word_833AC:	.word 2			/*  DATA XREF: ROM:000832E2o */
		.byte  0xF0,  0xF,	  0, 0xE4, 0xFF, 0xE0
		.byte  0xF0,  0xF,	  0, 0xF4,   0,	 0
word_833BA:	.word 2			/*  DATA XREF: ROM:000832E2o */
		.byte  0xF0,  0xD,	  1,   4, 0xFF, 0xF0
		.byte	0,  0xD,	0x11,   4, 0xFF, 0xF0
word_833C8:	.word 2			/*  DATA XREF: ROM:000832E2o */
		.byte  0xE8,  0xE,	  1,  0xC, 0xFF, 0xF0
		.byte	0,  0xE,	0x11,  0xC, 0xFF, 0xF0
word_833D6:	.word 2			/*  DATA XREF: ROM:000832E2o */
		.byte  0xF8,   7,	0x11, 0x34, 0xFF, 0xF8
		.byte  0xE8,   5,	0x11, 0x3C, 0xFF, 0xF8
word_833E4:	.word 3			/*  DATA XREF: ROM:000832E2o */
		.byte  0xEC,   6,	0x11, 0x24, 0xFF, 0xEC
		.byte  0xF4,   7,	0x11, 0x2A, 0xFF, 0xFC
		.byte	4,   1,	0x11, 0x32,   0,	0xC
word_833F8:	.word 2			/*  DATA XREF: ROM:000832E2o */
		.byte  0xF8,  0xD,	  1, 0x18, 0xFF, 0xE8
		.byte  0xF8,   5,	  1, 0x20,   0,	 8
word_83406:	.word 3			/*  DATA XREF: ROM:000832E2o */
		.byte  0xFC,   6,	  1, 0x24, 0xFF, 0xEC
		.byte  0xEC,   7,	  1, 0x2A, 0xFF, 0xFC
		.byte  0xEC,   1,	  1, 0x32,   0,	0xC
word_8341A:	.word 2			/*  DATA XREF: ROM:000832E2o */
		.byte  0xE8,   7,	  1, 0x34, 0xFF, 0xF8
		.byte	8,   5,	  1, 0x3C, 0xFF, 0xF8
word_83428:	.word 3			/*  DATA XREF: ROM:000832E2o */
		.byte  0xFC,   6,	  9, 0x24,   0,	 4
		.byte  0xEC,   7,	  9, 0x2A, 0xFF, 0xF4
		.byte  0xEC,   1,	  9, 0x32, 0xFF, 0xEC
word_8343C:	.word 2			/*  DATA XREF: ROM:000832E2o */
		.byte  0xF8,  0xD,	  9, 0x18, 0xFF, 0xF8
		.byte  0xF8,   5,	  9, 0x20, 0xFF, 0xE8
word_8344A:	.word 3			/*  DATA XREF: ROM:000832E2o */
		.byte  0xEC,   6,	0x19, 0x24,   0,	 4
		.byte  0xF4,   7,	0x19, 0x2A, 0xFF, 0xF4
		.byte	4,   1,	0x19, 0x32, 0xFF, 0xEC
word_8345E:	.word 1			/*  DATA XREF: ROM:000832E2o */
		.byte  0xF8,   5,	0x11, 0x48, 0xFF, 0xF8
word_83466:	.word 1			/*  DATA XREF: ROM:000832E2o */
		.byte  0xF8,   5,	0x11, 0x44, 0xFF, 0xF8
word_8346E:	.word 1			/*  DATA XREF: ROM:000832E2o */
		.byte  0xF8,   5,	  1, 0x40, 0xFF, 0xF8
word_83476:	.word 1			/*  DATA XREF: ROM:000832E2o */
		.byte  0xF8,   5,	  1, 0x44, 0xFF, 0xF8
word_8347E:	.word 1			/*  DATA XREF: ROM:000832E2o */
		.byte  0xF8,   5,	  1, 0x48, 0xFF, 0xF8
word_83486:	.word 1			/*  DATA XREF: ROM:000832E2o */
		.byte  0xF8,   5,	  9, 0x44, 0xFF, 0xF8
word_8348E:	.word 1			/*  DATA XREF: ROM:000832E2o */
		.byte  0xF8,   5,	  9, 0x40, 0xFF, 0xF8
word_83496:	.word 1			/*  DATA XREF: ROM:000832E2o */
		.byte  0xF8,   5,	0x19, 0x44, 0xFF, 0xF8
word_8349E:	.word 1			/*  DATA XREF: ROM:000832E2o */
		.byte  0xF8,   5,	  1, 0x4C, 0xFF, 0xF8
word_834A6:	.word 1			/*  DATA XREF: ROM:000832E2o */
		.byte  0xF8,   5,	  1, 0x50, 0xFF, 0xF8
word_834AE:	.word 1			/*  DATA XREF: ROM:000832E2o */
		.byte  0xF8,   5,	  1, 0x54, 0xFF, 0xF8
word_834B6:	.word 1			/*  DATA XREF: ROM:000832E2o */
		.byte  0xF8,   5,	  1, 0x58, 0xFF, 0xF8
word_834BE:	.word 1			/*  DATA XREF: ROM:000832E2o */
		.byte  0xF8,   5,	0x11, 0x64, 0xFF, 0xF8
word_834C6:	.word 1			/*  DATA XREF: ROM:000832E2o */
		.byte  0xF8,   5,	0x19, 0x60, 0xFF, 0xF8
word_834CE:	.word 1			/*  DATA XREF: ROM:000832E2o */
		.byte  0xF8,   5,	  9, 0x5C, 0xFF, 0xF8
word_834D6:	.word 1			/*  DATA XREF: ROM:000832E2o */
		.byte  0xF8,   5,	  9, 0x60, 0xFF, 0xF8
word_834DE:	.word 1			/*  DATA XREF: ROM:000832E2o */
		.byte  0xF8,   5,	  1, 0x64, 0xFF, 0xF8
word_834E6:	.word 1			/*  DATA XREF: ROM:000832E2o */
		.byte  0xF8,   5,	  1, 0x60, 0xFF, 0xF8
word_834EE:	.word 1			/*  DATA XREF: ROM:000832E2o */
		.byte  0xF8,   5,	  1, 0x5C, 0xFF, 0xF8
word_834F6:	.word 1			/*  DATA XREF: ROM:000832E2o */
		.byte  0xF8,   5,	0x11, 0x60, 0xFF, 0xF8
word_834FE:	.word 1			/*  DATA XREF: ROM:000832E2o */
		.byte  0xFC,   0,	  1, 0x68, 0xFF, 0xFC
word_83506:	.word 1			/*  DATA XREF: ROM:000832E2o */
		.byte  0xF8,   5,	  1, 0x69, 0xFF, 0xF8
word_8350E:	.word 1			/*  DATA XREF: ROM:000832E2o */
		.byte  0xF0,  0xF,	  1, 0x6D, 0xFF, 0xF0
word_83516:	.word 4			/*  DATA XREF: ROM:000832E2o */
		.byte  0xE8,  0xA,	  1, 0x7D, 0xFF, 0xE8
		.byte  0xE8,  0xA,	  1, 0x86,   0,	 0
		.byte	0,  0xA,	  1, 0x8F, 0xFF, 0xE8
		.byte	0,  0xA,	  1, 0x98,   0,	 0
word_83530:	.word 0xA			/*  DATA XREF: ROM:000832E2o */
		.byte  0xE8,  0xA,	  1, 0x86,   0, 0x10
		.byte	0,  0xA,	  1, 0x98,   0, 0x10
		.byte  0xD8,  0xA,	  1, 0x7D, 0xFF, 0xE8
		.byte  0xD8,  0xA,	  1, 0x86,   0,	 0
		.byte  0xF0,  0xF,	  1, 0xA1, 0xFF, 0xE8
		.byte  0xF0,   7,	  1, 0xB1,   0,	 8
		.byte  0x10,  0xA,	  1, 0x8F, 0xFF, 0xE8
		.byte  0x10,  0xA,	  1, 0x98,   0,	 0
		.byte  0xE8,  0xA,	  1, 0x7D, 0xFF, 0xD8
		.byte	0,  0xA,	  1, 0x8F, 0xFF, 0xD8
word_8356E:	.word 1			/*  DATA XREF: ROM:000832E2o */
		.byte  0xF4,  0xA,	  1, 0xB9, 0xFF, 0xF4
word_83576:	.word 1			/*  DATA XREF: ROM:000832E2o */
		.byte  0xF4,  0xA,	  1, 0xC2, 0xFF, 0xF4
word_8357E:	.word 1			/*  DATA XREF: ROM:000832E2o */
		.byte  0xF3,  0xA,	  1, 0xB9, 0xFF, 0xF4
word_83586:	.word 1			/*  DATA XREF: ROM:000832E2o */
		.byte  0xF3,  0xA,	  1, 0xC2, 0xFF, 0xF4
word_8358E:	.word 1			/*  DATA XREF: ROM:000832E2o */
		.byte  0xFC,   0,	  1, 0xCB, 0xFF, 0xFC
word_83596:	.word 1			/*  DATA XREF: ROM:000832E2o */
		.byte  0xFC,   0,	  1, 0xCC, 0xFF, 0xFC
word_8359E:	.word 1			/*  DATA XREF: ROM:000832E2o */
		.byte  0xFD,   0,	  1, 0xCB, 0xFF, 0xFC
word_835A6:	.word 1			/*  DATA XREF: ROM:000832E2o */
		.byte  0xFD,   0,	  1, 0xCC, 0xFF, 0xFC
word_835AE:	.word 2			/*  DATA XREF: ROM:000832E2o */
		.byte  0xF4,   6,	  1, 0xCD,   0,	 0
		.byte  0xF4,   6,	  1, 0xD3, 0xFF, 0xF0
word_835BC:	.word 2			/*  DATA XREF: ROM:000832E2o */
		.byte  0xF4,   6,	  1, 0xCD,   0,	 0
		.byte  0xF4,   6,	  1, 0xD9, 0xFF, 0xF0
word_835CA:	.word 1			/*  DATA XREF: ROM:000832E2o */
		.byte  0xF8,   5,	  1, 0xDF, 0xFF, 0xF8
word_835D2:	.word 1			/*  DATA XREF: ROM:000832E2o */
		.byte  0xF4,   5,	  1, 0xE3, 0xFF, 0xF8
word_835DA:	.word 1			/*  DATA XREF: ROM:000832E2o */
		.byte  0xF4,   4,	  1, 0xE7, 0xFF, 0xF8
word_835E2:	.word 1			/*  DATA XREF: ROM:000832E2o */
		.byte  0xFC,   5,	0x11, 0xE3, 0xFF, 0xF8
word_835EA:	.word 1			/*  DATA XREF: ROM:000832E2o */
		.byte	4,   4,	0x11, 0xE7, 0xFF, 0xF8
word_835F2:	.word 4			/*  DATA XREF: ROM:000832E2o */
		.byte  0xD4,  0xF,	  0,   0, 0xFF, 0xF0
		.byte  0xD4,  0xF,	  0, 0x10,   0, 0x10
		.byte  0xE4,   0,	  0, 0x20,   0, 0x30
		.byte  0xF4,  0xF,	  0, 0x4A,   0, 0x10
word_8360C:	.word 0			/*  DATA XREF: ROM:000832E2o */
word_8360E:	.word 5			/*  DATA XREF: ROM:000832E2o */
		.byte  0xF8,  0xE,	  0, 0x85, 0xFF, 0xDC
		.byte  0xF8,   6,	  0, 0x91, 0xFF, 0xFC
		.byte  0xF0,  0xB,	  0, 0x97,   0,	0xC
		.byte  0xDC,  0xB,	  0, 0x73, 0xFF, 0xD0
		.byte  0xFC,   9,	  0, 0x7F, 0xFF, 0xD0
word_8362E:	.word 5			/*  DATA XREF: ROM:000832E2o */
		.byte  0xF9,  0xE,	  0, 0x85, 0xFF, 0xDC
		.byte  0xF9,   6,	  0, 0x91, 0xFF, 0xFC
		.byte  0xF1,  0xB,	  0, 0x97,   0,	0xC
		.byte  0xDD,  0xB,	  0, 0x73, 0xFF, 0xD0
		.byte  0xFD,   9,	  0, 0x7F, 0xFF, 0xD0
word_8364E:	.word 5			/*  DATA XREF: ROM:000832E2o */
		.byte  0xFA,  0xE,	  0, 0x85, 0xFF, 0xDC
		.byte  0xFA,   6,	  0, 0x91, 0xFF, 0xFC
		.byte  0xF2,  0xB,	  0, 0x97,   0,	0xC
		.byte  0xDD,  0xB,	  0, 0x73, 0xFF, 0xD0
		.byte  0xFD,   9,	  0, 0x7F, 0xFF, 0xD0
word_8366E:	.word 6			/*  DATA XREF: ROM:000832E2o */
		.byte  0xE4,   7,	  0, 0xB3, 0xFF, 0xDC
		.byte  0xDC,  0xF,	  0, 0xBB, 0xFF, 0xEC
		.byte  0xE4,  0xA,	  0, 0xCB,   0,	0xC
		.byte  0xFC,  0xC,	  0, 0xD4, 0xFF, 0xEC
		.byte	4,  0xB,	  0, 0xD8, 0xFF, 0xEC
		.byte  0xCC,  0xF,	  0, 0xA3,   0,	 4
word_83694:	.word 6			/*  DATA XREF: ROM:000832E2o */
		.byte  0xE5,   7,	  0, 0xB3, 0xFF, 0xDC
		.byte  0xDD,  0xF,	  0, 0xBB, 0xFF, 0xEC
		.byte  0xE5,  0xA,	  0, 0xCB,   0,	0xC
		.byte  0xFD,  0xC,	  0, 0xD4, 0xFF, 0xEC
		.byte	5,  0xB,	  0, 0xD8, 0xFF, 0xEC
		.byte  0xCD,  0xF,	  0, 0xA3,   0,	 4
word_836BA:	.word 6			/*  DATA XREF: ROM:000832E2o */
		.byte  0xE6,   7,	  0, 0xB3, 0xFF, 0xDC
		.byte  0xDE,  0xF,	  0, 0xBB, 0xFF, 0xEC
		.byte  0xE6,  0xA,	  0, 0xCB,   0,	0xC
		.byte  0xFE,  0xC,	  0, 0xD4, 0xFF, 0xEC
		.byte	6,  0xB,	  0, 0xD8, 0xFF, 0xEC
		.byte  0xCD,  0xF,	  0, 0xA3,   0,	 4
