Map_361CB8:	.word Frame_361CC8-Map_361CB8 /* ...*/
		.word Frame_361CDC-Map_361CB8
		.word Frame_361CF0-Map_361CB8
		.word Frame_361D04-Map_361CB8
		.word Frame_361D0C-Map_361CB8
		.word Frame_361D14-Map_361CB8
		.word Frame_361D1C-Map_361CB8
		.word Frame_361D24-Map_361CB8
Frame_361CC8:	.word 3
		.byte 0xE8,  7,  0,  0,0xFF,0xF0
		.byte 0xE8,  7,  0,  0,  0,  0
		.byte   8,  4,  0,0x17,0xFF,0xF8
Frame_361CDC:	.word 3
		.byte 0xF0, 0xA,  0,  8,0xFF,0xE8
		.byte 0xF0, 0xA,  8,  8,  0,  0
		.byte   8,  4,  0,0x17,0xFF,0xF8
Frame_361CF0:	.word 3
		.byte 0xF8,  9,  0,0x11,0xFF,0xE8
		.byte 0xF8,  9,  8,0x11,  0,  0
		.byte   8,  4,  0,0x17,0xFF,0xF8
Frame_361D04:	.word 1
		.byte 0xFC,  4,  0,0x19,0xFF,0xF8
Frame_361D0C:	.word 1
		.byte 0xFC,  4,  0,0x1B,0xFF,0xF8
Frame_361D14:	.word 1
		.byte 0xFC,  0,  0,0x1D,0xFF,0xFC
Frame_361D1C:	.word 1
		.byte 0xFC,  0,  0,0x1E,0xFF,0xFC
Frame_361D24:	.word 0
