		.word byte_2372E-Ani_Spring
		.word byte_23731-Ani_Spring
		.word byte_2373D-Ani_Spring
		.word byte_23740-Ani_Spring
		.word byte_2374C-Ani_Spring
		.word byte_2374F-Ani_Spring
byte_2372E:	.byte   0xF,   0,	0xFF	
byte_23731:	.byte	0,   1,	  0,   0,   2,	 2,   2,   2,	2,   2,	0xFD,   0
					
byte_2373D:	.byte   0xF,   3,	0xFF	
byte_23740:	.byte	0,   4,	  3,   3,   5,	 5,   5,   5,	5,   5,	0xFD,   2
					
byte_2374C:	.byte   0xF,   7,	0xFF	
byte_2374F:	.byte	0,   8,	  7,   7,   9,	 9,   9,   9,	9,   9,	0xFD,   4,   0
					
