Map_2PSpring_:	.word word_23920-Map_2PSpring_

		.word word_2392E-Map_2PSpring_
		.word word_23936-Map_2PSpring_
		.word word_2394A-Map_2PSpring_
		.word word_23958-Map_2PSpring_
		.word word_23960-Map_2PSpring_
		.word word_23974-Map_2PSpring_
Map_Spring3:
Map_Spring3_:	.word word_23982-Map_Spring3_

		.word word_23990-Map_Spring3_
		.word word_23998-Map_Spring3_
		.word word_239AC-Map_Spring3_
		.word word_239BA-Map_Spring3_
		.word word_239C2-Map_Spring3_
		.word word_239D6-Map_Spring3_
word_23920:	.word 2
		.byte  0xF6,   8,	  0,   0, 0xFF, 0xF4
		.byte  0xFB,   8,	  0,   6, 0xFF, 0xF4
word_2392E:	.word 1
		.byte  0xFB,   8,	  0,   0, 0xFF, 0xF4
word_23936:	.word 3
		.byte  0xF1,   8,	  0,   0, 0xFF, 0xF4
		.byte  0xF3,   0,	  0,   9, 0xFF, 0xFC
		.byte  0xFB,   8,	  0,  0xA, 0xFF, 0xF4
word_2394A:	.word 2
		.byte  0xF4,   2,	  8,   0,   0,	 2
		.byte  0xF4,   2,	  8,   6, 0xFF, 0xFD
word_23958:	.word 1
		.byte  0xF4,   2,	  8,   0, 0xFF, 0xFD
word_23960:	.word 3
		.byte  0xF4,   2,	  8,   0,   0,	 7
		.byte  0xFC,   0,	  8,   9,   0,	 5
		.byte  0xF4,   2,	  8,  0xA, 0xFF, 0xFD
word_23974:	.word 2
		.byte	2,   8,	0x10,   0, 0xFF, 0xF4
		.byte  0xFD,   8,	0x10,   6, 0xFF, 0xF4
word_23982:	.word 2
		.byte  0xF6,   8,	  0,   3, 0xFF, 0xF4
		.byte  0xFB,   8,	  0,   6, 0xFF, 0xF4
word_23990:	.word 1
		.byte  0xFB,   8,	  0,   3, 0xFF, 0xF4
word_23998:	.word 3
		.byte  0xF1,   8,	  0,   3, 0xFF, 0xF4
		.byte  0xF3,   0,	  0,   9, 0xFF, 0xFC
		.byte  0xFB,   8,	  0,  0xA, 0xFF, 0xF4
word_239AC:	.word 2
		.byte  0xF4,   2,	  8,   3,   0,	 2
		.byte  0xF4,   2,	  8,   6, 0xFF, 0xFD
word_239BA:	.word 1
		.byte  0xF4,   2,	  8,   3, 0xFF, 0xFD
word_239C2:	.word 3
		.byte  0xF4,   2,	  8,   3,   0,	 7
		.byte  0xFC,   0,	  8,   9,   0,	 5
		.byte  0xF4,   2,	  8,  0xA, 0xFF, 0xFD
word_239D6:	.word 2
		.byte	2,   8,	0x10,   3, 0xFF, 0xF4
		.byte  0xFD,   8,	0x10,   6, 0xFF, 0xF4