Map_PathSwap_:	.word word_1D06A-Map_PathSwap_
		.word word_1D084-Map_PathSwap_
		.word word_1D09E-Map_PathSwap_
		.word word_1D09E-Map_PathSwap_
		.word word_1D0B8-Map_PathSwap_
		.word word_1D0D2-Map_PathSwap_
		.word word_1D0EC-Map_PathSwap_
		.word word_1D0EC-Map_PathSwap_
word_1D06A:	.word 4			/*  DATA XREF: ROM:0001D05Ao */
		.byte  0xE0,   5,	  0,   0, 0xFF, 0xF8
		.byte  0xF0,   5,	  0,   0, 0xFF, 0xF8
		.byte	0,   5,	  0,   0, 0xFF, 0xF8
		.byte  0x10,   5,	  0,   0, 0xFF, 0xF8
word_1D084:	.word 4			/*  DATA XREF: ROM:0001D05Ao */
		.byte  0xC0,   5,	  0,   0, 0xFF, 0xF8
		.byte  0xE0,   5,	  0,   0, 0xFF, 0xF8
		.byte	0,   5,	  0,   0, 0xFF, 0xF8
		.byte  0x30,   5,	  0,   0, 0xFF, 0xF8
word_1D09E:	.word 4			/*  DATA XREF: ROM:0001D05Ao */
		.byte  0x80,   5,	  0,   0, 0xFF, 0xF8
		.byte  0xE0,   5,	  0,   0, 0xFF, 0xF8
		.byte	0,   5,	  0,   0, 0xFF, 0xF8
		.byte  0x70,   5,	  0,   0, 0xFF, 0xF8
word_1D0B8:	.word 4			/*  DATA XREF: ROM:0001D05Ao */
		.byte  0xF8,   5,	  0,   0, 0xFF, 0xE0
		.byte  0xF8,   5,	  0,   0, 0xFF, 0xF0
		.byte  0xF8,   5,	  0,   0,   0,	 0
		.byte  0xF8,   5,	  0,   0,   0, 0x10
word_1D0D2:	.word 4			/*  DATA XREF: ROM:0001D05Ao */
		.byte  0xF8,   5,	  0,   0, 0xFF, 0xC0
		.byte  0xF8,   5,	  0,   0, 0xFF, 0xE0
		.byte  0xF8,   5,	  0,   0,   0,	 0
		.byte  0xF8,   5,	  0,   0,   0, 0x30
word_1D0EC:	.word 4			/*  DATA XREF: ROM:0001D05Ao */
		.byte  0xF8,   5,	  0,   0, 0xFF, 0x80
		.byte  0xF8,   5,	  0,   0, 0xFF, 0xE0
		.byte  0xF8,   5,	  0,   0,   0,	 0
		.byte  0xF8,   5,	  0,   0,   0, 0x70
