Map_18595E:		.word word_185980-Map_18595E
		.word word_185982-Map_18595E
		.word word_185990-Map_18595E
		.word word_18599E-Map_18595E
		.word word_1859AC-Map_18595E
		.word word_1859BA-Map_18595E
		.word word_1859D4-Map_18595E
		.word word_1859EE-Map_18595E
		.word word_185A08-Map_18595E
		.word word_185A22-Map_18595E
		.word word_185A48-Map_18595E
		.word word_185A6E-Map_18595E
		.word word_185A94-Map_18595E
		.word word_185ABA-Map_18595E
		.word word_185AEC-Map_18595E
		.word word_185B1E-Map_18595E
		.word word_185B50-Map_18595E
word_185980:	.word 0			
word_185982:	.word 2			
		.byte  0xFC,   0,	  7, 0xC0,   0,	 8
		.byte  0xFC,   0,	  0,   0,   0,	 0
word_185990:	.word 2			
		.byte  0xF8,   1,	  7, 0xC0,   0,	 8
		.byte  0xF8,   1,	  0,   0,   0,	 0
word_18599E:	.word 2			
		.byte  0xF4,   2,	  7, 0xC0,   0,	 8
		.byte  0xF4,   2,	  0,   0,   0,	 0
word_1859AC:	.word 2			
		.byte  0xF0,   3,	  7, 0xC0,   0,	 8
		.byte  0xF0,   3,	  0,   0,   0,	 0
word_1859BA:	.word 4			
		.byte  0xEC,   3,	  7, 0xC0,   0,	 8
		.byte  0xEC,   3,	  0,   0,   0,	 0
		.byte   0xC,   0,	  7, 0xC0,   0,	 8
		.byte   0xC,   0,	  0,   0,   0,	 0
word_1859D4:	.word 4			
		.byte  0xE8,   3,	  7, 0xC0,   0,	 8
		.byte  0xE8,   3,	  0,   0,   0,	 0
		.byte	8,   1,	  7, 0xC0,   0,	 8
		.byte	8,   1,	  0,   0,   0,	 0
word_1859EE:	.word 4			
		.byte  0xE4,   3,	  7, 0xC0,   0,	 8
		.byte  0xE4,   3,	  0,   0,   0,	 0
		.byte	4,   2,	  7, 0xC0,   0,	 8
		.byte	4,   2,	  0,   0,   0,	 0
word_185A08:	.word 4			
		.byte  0xE0,   3,	  7, 0xC0,   0,	 8
		.byte  0xE0,   3,	  0,   0,   0,	 0
		.byte	0,   3,	  7, 0xC0,   0,	 8
		.byte	0,   3,	  0,   0,   0,	 0
word_185A22:	.word 6			
		.byte  0xDC,   3,	  7, 0xC0,   0,	 8
		.byte  0xDC,   3,	  0,   0,   0,	 0
		.byte  0xFC,   3,	  7, 0xC0,   0,	 8
		.byte  0xFC,   3,	  0,   0,   0,	 0
		.byte  0x1C,   0,	  7, 0xC0,   0,	 8
		.byte  0x1C,   0,	  0,   0,   0,	 0
word_185A48:	.word 6			
		.byte  0xD8,   3,	  7, 0xC0,   0,	 8
		.byte  0xD8,   3,	  0,   0,   0,	 0
		.byte  0xF8,   3,	  7, 0xC0,   0,	 8
		.byte  0xF8,   3,	  0,   0,   0,	 0
		.byte  0x18,   1,	  7, 0xC0,   0,	 8
		.byte  0x18,   1,	  0,   0,   0,	 0
word_185A6E:	.word 6			
		.byte  0xD4,   3,	  7, 0xC0,   0,	 8
		.byte  0xD4,   3,	  0,   0,   0,	 0
		.byte  0xF4,   3,	  7, 0xC0,   0,	 8
		.byte  0xF4,   3,	  0,   0,   0,	 0
		.byte  0x14,   2,	  7, 0xC0,   0,	 8
		.byte  0x14,   2,	  0,   0,   0,	 0
word_185A94:	.word 6			
		.byte  0xD0,   3,	  7, 0xC0,   0,	 8
		.byte  0xD0,   3,	  0,   0,   0,	 0
		.byte  0xF0,   3,	  7, 0xC0,   0,	 8
		.byte  0xF0,   3,	  0,   0,   0,	 0
		.byte  0x10,   3,	  7, 0xC0,   0,	 8
		.byte  0x10,   3,	  0,   0,   0,	 0
word_185ABA:	.word 8			
		.byte  0xCC,   3,	  7, 0xC0,   0,	 8
		.byte  0xCC,   3,	  0,   0,   0,	 0
		.byte  0xEC,   3,	  7, 0xC0,   0,	 8
		.byte  0xEC,   3,	  0,   0,   0,	 0
		.byte   0xC,   3,	  7, 0xC0,   0,	 8
		.byte   0xC,   3,	  0,   0,   0,	 0
		.byte  0x2C,   0,	  7, 0xC0,   0,	 8
		.byte  0x2C,   0,	  0,   0,   0,	 0
word_185AEC:	.word 8			
		.byte  0xC8,   3,	  7, 0xC0,   0,	 8
		.byte  0xC8,   3,	  0,   0,   0,	 0
		.byte  0xE8,   3,	  7, 0xC0,   0,	 8
		.byte  0xE8,   3,	  0,   0,   0,	 0
		.byte	8,   3,	  7, 0xC0,   0,	 8
		.byte	8,   3,	  0,   0,   0,	 0
		.byte  0x28,   1,	  7, 0xC0,   0,	 8
		.byte  0x28,   1,	  0,   0,   0,	 0
word_185B1E:	.word 8			
		.byte  0xC4,   3,	  7, 0xC0,   0,	 8
		.byte  0xC4,   3,	  0,   0,   0,	 0
		.byte  0xE4,   3,	  7, 0xC0,   0,	 8
		.byte  0xE4,   3,	  0,   0,   0,	 0
		.byte	4,   3,	  7, 0xC0,   0,	 8
		.byte	4,   3,	  0,   0,   0,	 0
		.byte  0x24,   2,	  7, 0xC0,   0,	 8
		.byte  0x24,   2,	  0,   0,   0,	 0
word_185B50:	.word 8			
		.byte  0xC0,   3,	  7, 0xC0,   0,	 8
		.byte  0xC0,   3,	  0,   0,   0,	 0
		.byte  0xE0,   3,	  7, 0xC0,   0,	 8
		.byte  0xE0,   3,	  0,   0,   0,	 0
		.byte	0,   3,	  7, 0xC0,   0,	 8
		.byte	0,   3,	  0,   0,   0,	 0
		.byte  0x20,   3,	  7, 0xC0,   0,	 8
		.byte  0x20,   3,	  0,   0,   0,	 0
