Map_2PRetractingSpring_:.word word_23F5A-Map_2PRetractingSpring_
		.word word_23F5C-Map_2PRetractingSpring_
		.word word_23F64-Map_2PRetractingSpring_
		.word word_23F64-Map_2PRetractingSpring_
Map_2PRetractingSpring_2:
Map_2PRetractingSpring_2_:.word word_23F5A-Map_2PRetractingSpring_2_

		.word word_23F6C-Map_2PRetractingSpring_2_
		.word word_23F64-Map_2PRetractingSpring_2_
		.word word_23F64-Map_2PRetractingSpring_2_
word_23F5A:	.word 0

word_23F5C:	.word 1
		.byte  0xF4,   6,	  8, 0x2F, 0xFF, 0xF8
word_23F64:	.word 1

		.byte  0xF8,   9,	0x60,  0xD, 0xFF, 0xF4
word_23F6C:	.word 1
		.byte  0xF4,  0xA,	0x47, 0x74, 0xFF, 0xF0