Ani_7B21C:		.word byte_7B22C-Ani_7B21C
		.word byte_7B22F-Ani_7B21C
		.word byte_7B233-Ani_7B21C
		.word byte_7B248-Ani_7B21C
		.word byte_7B24C-Ani_7B21C
		.word byte_7B257-Ani_7B21C
		.word byte_7B262-Ani_7B21C
		.word byte_7B265-Ani_7B21C
byte_7B22C:	.byte   0xF,   2,	0xFF
byte_7B22F:	.byte	1,   0,	  1, 0xFF
byte_7B233:	.byte    3,   2,   2,   2,   2,   2,   2,   2,   2,   3,   4,   3,   4,   3,   4,   5,   6,   7,   8, 0xFE
		.byte    1
byte_7B248:	.byte	7,  0xC,	 0xD, 0xFF
byte_7B24C:	.byte	7,  0xE,	 0xF,  0xE,  0xF,	0xE,  0xF,  0xE,  0xF, 0xFD,	  3
byte_7B257:	.byte	7, 0x10,	0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0xFD,	  3
byte_7B262:	.byte	1,  0xE,	0xFC
byte_7B265:	.byte	7, 0x11,	0xFF
