Map_186DAC:		.word word_186DE6-Map_186DAC
		.word word_186DEE-Map_186DAC
		.word word_186DF6-Map_186DAC
		.word word_186DFE-Map_186DAC
		.word word_186E06-Map_186DAC
		.word word_186E0E-Map_186DAC
		.word word_186E16-Map_186DAC
		.word word_186E24-Map_186DAC
		.word word_186E32-Map_186DAC
		.word word_186E46-Map_186DAC
		.word word_186E46-Map_186DAC
		.word word_186E46-Map_186DAC
		.word word_186E46-Map_186DAC
		.word word_186E4E-Map_186DAC
		.word word_186E62-Map_186DAC
		.word word_186E24-Map_186DAC
		.word word_186E24-Map_186DAC
		.word word_186E24-Map_186DAC
		.word word_186E24-Map_186DAC
		.word word_186E24-Map_186DAC
		.word word_186E24-Map_186DAC
		.word word_186E24-Map_186DAC
		.word word_186E24-Map_186DAC
		.word word_186E24-Map_186DAC
		.word word_186E24-Map_186DAC
		.word word_186E24-Map_186DAC
		.word word_186E24-Map_186DAC
		.word word_186E24-Map_186DAC
		.word word_186E24-Map_186DAC
word_186DE6:	.word 1			
		.byte  0xF4,  0xA,	0x20,   0, 0xFF, 0xF4
word_186DEE:	.word 1			
		.byte  0xF4,  0xA,	0x20,   9, 0xFF, 0xF4
word_186DF6:	.word 1			
		.byte  0xF4,   6,	0x20, 0x12, 0xFF, 0xF8
word_186DFE:	.word 1			
		.byte  0xF4,   2,	0x20, 0x18, 0xFF, 0xFC
word_186E06:	.word 1			
		.byte  0xF8,   9,	0x20, 0x1B, 0xFF, 0xF4
word_186E0E:	.word 1			
		.byte  0xF8,   5,	0x20, 0x21, 0xFF, 0xF8
word_186E16:	.word 2			
		.byte  0xF8,   9,	  0, 0x25, 0xFF, 0xF4
		.byte  0xF0,   8,	0x20, 0x4F, 0xFF, 0xF4
word_186E24:	.word 2			
		.byte  0xF4,  0xE,	  0, 0x2B, 0xFF, 0xF0
		.byte  0xEC,   9,	0x20, 0x52, 0xFF, 0xF4
word_186E32:	.word 3			
		.byte  0xF0,  0xB,	  0, 0x37, 0xFF, 0xE8
		.byte  0xF0,  0xB,	  0, 0x43,   0,	 0
		.byte  0xE0,  0xE,	0x20, 0x58, 0xFF, 0xF0
word_186E46:	.word 1			
		.byte  0xF8,   5,	  0, 0x64, 0xFF, 0xF8
word_186E4E:	.word 3			
		.byte  0xF8,   5,	  8, 0x64, 0xFF, 0xE8
		.byte  0xF8,   5,	  0, 0x68, 0xFF, 0xF8
		.byte  0xF8,   5,	  0, 0x68,   0,	 8
word_186E62:	.word 4			
		.byte  0xE8,  0xA,	  0, 0x6C, 0xFF, 0xE8
		.byte  0xE8,  0xA,	  8, 0x6C,   0,	 0
		.byte	0,  0xA,	0x10, 0x6C, 0xFF, 0xE8
		.byte	0,  0xA,	0x18, 0x6C,   0,	 0
