		.word word_46A54-Map_SSZBouncyCloud
		.word word_46A62-Map_SSZBouncyCloud
		.word word_46A6A-Map_SSZBouncyCloud
		.word word_46A72-Map_SSZBouncyCloud
		.word word_46A80-Map_SSZBouncyCloud
		.word word_46A94-Map_SSZBouncyCloud
		.word word_46AA8-Map_SSZBouncyCloud
		.word word_46AB6-Map_SSZBouncyCloud
word_46A54:	.word 2			/* DATA XREF: ROM:00046A44o*/
		.byte  0xF0,  0xB,	  0,   0, 0xFF, 0xE8
		.byte  0xF0,  0xB,	  0,  0xC,   0,	 0
word_46A62:	.word 1			/* DATA XREF: ROM:00046A44o*/
		.byte  0xFC,   0,	  0, 0x18, 0xFF, 0xFC
word_46A6A:	.word 1			/* DATA XREF: ROM:00046A44o*/
		.byte  0xFC,   0,	  0, 0x19, 0xFF, 0xFC
word_46A72:	.word 2			/* DATA XREF: ROM:00046A44o*/
		.byte  0xF0,  0xF,	  0, 0x1A, 0xFF, 0xE0
		.byte  0xF0,  0xF,	  0, 0x2A,   0,	 0
word_46A80:	.word 3			/* DATA XREF: ROM:00046A44o*/
		.byte  0xF0,  0xF,	  0, 0x3A, 0xFF, 0xE0
		.byte  0xF0,   8,	  0, 0x4A,   0,	 0
		.byte  0xF8,  0xE,	  0, 0x4D,   0,	 0
word_46A94:	.word 3			/* DATA XREF: ROM:00046A44o*/
		.byte  0xF0,  0xF,	  0, 0x59, 0xFF, 0xE0
		.byte  0xF0,   8,	  0, 0x69,   0,	 0
		.byte  0xF8,  0xE,	  0, 0x6C,   0,	 0
word_46AA8:	.word 2			/* DATA XREF: ROM:00046A44o*/
		.byte  0xF0,  0xF,	  0, 0x78, 0xFF, 0xE0
		.byte  0xF0,  0xF,	  0, 0x88,   0,	 0
word_46AB6:	.word 2			/* DATA XREF: ROM:00046A44o*/
		.byte  0xF0,  0xF,	  0, 0x98, 0xFF, 0xE0
		.byte  0xF0,  0xF,	  0, 0xA8,   0,	 0
