		.word	word_46AE4-Map_SSZElevatorBar
		.word word_46AFE-Map_SSZElevatorBar
		.word word_46B1E-Map_SSZElevatorBar
		.word word_46B26-Map_SSZElevatorBar
		.word word_46B34-Map_SSZElevatorBar
word_46AE4:	.word 4			/*  DATA XREF: ROM:00046ADAo */
		.byte  0xFE,   8,	  0,   0, 0xFF, 0xD0
		.byte  0xFE,   8,	  0,   0, 0xFF, 0xE8
		.byte  0xFE,   8,	  0,   0,   0,	 0
		.byte  0xFE,   8,	  0,   0,   0, 0x18
word_46AFE:	.word 5			/*  DATA XREF: ROM:00046ADAo */
		.byte  0xFE,   8,	  0,   0, 0xFF, 0xCD
		.byte  0xFE,   8,	  0,   0, 0xFF, 0xE5
		.byte  0xF8,   5,	0x20, 0x10, 0xFF, 0xF8
		.byte  0xFE,   8,	  0,   0,   0,	 0
		.byte  0xFE,   8,	  0,   0,   0, 0x18
word_46B1E:	.word 1			/*  DATA XREF: ROM:00046ADAo */
		.byte  0xF8,   5,	  0,  0xC, 0xFF, 0xF8
word_46B26:	.word 2			/*  DATA XREF: ROM:00046ADAo */
		.byte  0xF4,  0xA,	  0,   3, 0xFF, 0xE8
		.byte  0xF4,  0xA,	  8,   3,   0,	 0
word_46B34:	.word 1			/*  DATA XREF: ROM:00046ADAo */
		.byte  0xF8,   5,	0x20, 0x10, 0xFF, 0xF8
