		.word word_46974-Map_SSZCollapsingBridge
		.word word_46982-Map_SSZCollapsingBridge
		.word word_4698A-Map_SSZCollapsingBridge
		.word word_46992-Map_SSZCollapsingBridge
		.word word_469AC-Map_SSZCollapsingBridge
		.word word_469B4-Map_SSZCollapsingBridge
		.word word_469BC-Map_SSZCollapsingBridge
		.word word_469D0-Map_SSZCollapsingBridge
		.word word_469DE-Map_SSZCollapsingBridge
		.word word_469E6-Map_SSZCollapsingBridge
		.word word_46A00-Map_SSZCollapsingBridge
		.word word_46A1A-Map_SSZCollapsingBridge
		.word word_46A2E-Map_SSZCollapsingBridge
		.word word_46A3C-Map_SSZCollapsingBridge
word_46974:	.word 2			/* DATA XREF: ROM:00046958o*/
		.byte  0xF8,  0xE,	  0,   0, 0xFF, 0xE0
		.byte  0xF8,  0xE,	  0,   0,   0,	 0
word_46982:	.word 1			/* DATA XREF: ROM:00046958o*/
		.byte  0xF8,   6,	  0,   0, 0xFF, 0xF8
word_4698A:	.word 1			/* DATA XREF: ROM:00046958o*/
		.byte  0xF8,   6,	  0,   6, 0xFF, 0xF8
word_46992:	.word 4			/* DATA XREF: ROM:00046958o*/
		.byte	0,  0xF,	  0,  0xC, 0xFF, 0xC0
		.byte  0xF8,  0xF,	  0,  0xC, 0xFF, 0xE0
		.byte  0xF0,  0xF,	  0,  0xC,   0,	 0
		.byte  0xE8,  0xF,	  0,  0xC,   0, 0x20
word_469AC:	.word 1			/* DATA XREF: ROM:00046958o*/
		.byte  0xF0,   7,	  0,  0xC, 0xFF, 0xF8
word_469B4:	.word 1			/* DATA XREF: ROM:00046958o*/
		.byte  0xF0,   7,	  0, 0x14, 0xFF, 0xF8
word_469BC:	.word 3			/* DATA XREF: ROM:00046958o*/
		.byte  0xF8,  0xF,	  0,  0xC, 0xFF, 0xD0
		.byte  0xF0,  0xF,	  0,  0xC, 0xFF, 0xF0
		.byte  0xE8,  0xF,	  0,  0xC,   0, 0x10
word_469D0:	.word 2			/* DATA XREF: ROM:00046958o*/
		.byte  0xF0,  0xF,	  0,  0xC, 0xFF, 0xF0
		.byte  0xE8,  0xF,	  0,  0xC,   0, 0x10
word_469DE:	.word 1			/* DATA XREF: ROM:00046958o*/
		.byte  0xE8,  0xF,	  0,  0xC,   0, 0x10
word_469E6:	.word 4			/* DATA XREF: ROM:00046958o*/
		.byte  0xE4,   8,	  0,   0, 0xFF, 0xF8
		.byte  0xEC,  0xE,	  0,   3, 0xFF, 0xF0
		.byte	4,   9,	  0,  0xF, 0xFF, 0xF0
		.byte  0x14,   4,	  0, 0x15, 0xFF, 0xF8
word_46A00:	.word 4			/* DATA XREF: ROM:00046958o*/
		.byte  0xFC,   7,	  0, 0x17, 0xFF, 0xE8
		.byte  0xE4,   9,	  0, 0x1F,   0,	 0
		.byte  0xF4,  0xF,	  0, 0x25, 0xFF, 0xF8
		.byte  0x14,   4,	  0, 0x35, 0xFF, 0xF8
word_46A1A:	.word 3			/* DATA XREF: ROM:00046958o*/
		.byte  0xE8,  0xF,	  8,  0xC, 0xFF, 0xD0
		.byte  0xF0,  0xF,	  8,  0xC, 0xFF, 0xF0
		.byte  0xF8,  0xF,	  8,  0xC,   0, 0x10
word_46A2E:	.word 2			/* DATA XREF: ROM:00046958o*/
		.byte  0xE8,  0xF,	  8,  0xC, 0xFF, 0xD0
		.byte  0xF0,  0xF,	  8,  0xC, 0xFF, 0xF0
word_46A3C:	.word 1			/* DATA XREF: ROM:00046958o*/
		.byte  0xE8,  0xF,	  8,  0xC, 0xFF, 0xD0
