Map_7D6D8:		.word word_7D6E0-Map_7D6D8
		.word word_7D6EE-Map_7D6D8
		.word word_7D6F6-Map_7D6D8
		.word word_7D704-Map_7D6D8
word_7D6E0:	.word 2			
		.byte  0xEC,  0xC,	  0, 0x22, 0xFF, 0xE4
		.byte  0xE4,   4,	  0, 0x49, 0xFF, 0xEC
word_7D6EE:	.word 1			
		.byte  0xEC,   8,	  0, 0x26,   0,	 4
word_7D6F6:	.word 2			
		.byte  0xF4,  0xE,	  0, 0x29, 0xFF, 0xE4
		.byte   0xC,   8,	  0, 0x3E, 0xFF, 0xEC
word_7D704:	.word 2			
		.byte  0xF4,  0xA,	  0, 0x35,   0,	 4
		.byte   0xC,   4,	  0, 0x41,   0,	 4
