		.word word_4690E-Map_SSZFloatingPlatform
		.word word_46910-Map_SSZFloatingPlatform
		.word word_4691E-Map_SSZFloatingPlatform
		.word word_46938-Map_SSZFloatingPlatform
		.word word_46940-Map_SSZFloatingPlatform
		.word word_46948-Map_SSZFloatingPlatform
		.word word_46950-Map_SSZFloatingPlatform
word_4690E:	.word 0			/* DATA XREF: ROM:00046900o*/
word_46910:	.word 2			/* DATA XREF: ROM:00046900o*/
		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xE0
		.byte  0xF0,  0xF,	  8,   0,   0,	 0
word_4691E:	.word 4			/* DATA XREF: ROM:00046900o*/
		.byte  0xE0,  0xD,	  0,   0, 0xFF, 0xF0
		.byte  0xF0,  0xD,	  0,   0, 0xFF, 0xF0
		.byte	0,  0xD,	  0,   0, 0xFF, 0xF0
		.byte  0x10,  0xD,	  0,   8, 0xFF, 0xF0
word_46938:	.word 1			/* DATA XREF: ROM:00046900o*/
		.byte  0xF8,   5,	  0,   0, 0xFF, 0xF8
word_46940:	.word 1			/* DATA XREF: ROM:00046900o*/
		.byte  0xF8,   5,	  0,   4, 0xFF, 0xF8
word_46948:	.word 1			/* DATA XREF: ROM:00046900o*/
		.byte  0xF8,   5,	  0,   8, 0xFF, 0xF8
word_46950:	.word 1			/* DATA XREF: ROM:00046900o*/
		.byte  0xF8,   5,	  0,  0xC, 0xFF, 0xF8
