Map_2CF50:		.word word_2CF5E-Map_2CF50
		.word word_2CF66-Map_2CF50
		.word word_2CF6E-Map_2CF50
		.word word_2CF76-Map_2CF50
		.word word_2CF84-Map_2CF50
		.word word_2CF8C-Map_2CF50
		.word word_2CF9A-Map_2CF50
word_2CF5E:	.word 1			
		.byte  0xFC,   4,	  0,   0, 0xFF, 0xFA
word_2CF66:	.word 1			
		.byte  0xFC,   4,	  0,   2, 0xFF, 0xF8
word_2CF6E:	.word 1			
		.byte  0xFC,   4,	  0,   4, 0xFF, 0xF8
word_2CF76:	.word 2			
		.byte  0xFC,   0,	  0,   0, 0xFF, 0xF8
		.byte  0xFC,   4,	  0,   6,   0,	 0
word_2CF84:	.word 1			
		.byte  0xFC,   0,	  0,   0, 0xFF, 0xFC
word_2CF8C:	.word 2			
		.byte  0xFC,   4,	  0,   0, 0xFF, 0xF8
		.byte  0xFC,   4,	  0,   6,   0,	 5
word_2CF9A:	.word 2			
		.byte  0xFC,   4,	  0,   4, 0xFF, 0xF8
		.byte  0xFC,   4,	  0,   6,   0,	 7
