		.word word_1E762-Map_Explosion
		.word word_1E76A-Map_Explosion
		.word word_1E772-Map_Explosion
		.word word_1E77A-Map_Explosion
		.word word_1E782-Map_Explosion
word_1E762:	.word 1			/* DATA XREF: ROM:0001E758o*/
		.byte  0xF8,   5,	  0,   0, 0xFF, 0xF8
word_1E76A:	.word 1			/* DATA XREF: ROM:0001E758o*/
		.byte  0xF0,  0xF,	  0,   4, 0xFF, 0xF0
word_1E772:	.word 1			/* DATA XREF: ROM:0001E758o*/
		.byte  0xF0,  0xF,	  0, 0x14, 0xFF, 0xF0
word_1E77A:	.word 1			/* DATA XREF: ROM:0001E758o*/
		.byte  0xF0,  0xF,	  0, 0x24, 0xFF, 0xF0
word_1E782:	.word 1			/* DATA XREF: ROM:0001E758o*/
		.byte  0xF0,  0xF,	  0, 0x34, 0xFF, 0xF0
