Ani_2BF9C:		.word byte_2BFAC-Ani_2BF9C
		.word byte_2BFB3-Ani_2BF9C
		.word byte_2BFB9-Ani_2BF9C
		.word byte_2BFBD-Ani_2BF9C
		.word byte_2BFC2-Ani_2BF9C
		.word byte_2BFC8-Ani_2BF9C
		.word byte_2BFCE-Ani_2BF9C
		.word byte_2BFD4-Ani_2BF9C
byte_2BFAC:	.byte	3,   0,	  1,   2,   3,	 4, 0xFF	
byte_2BFB3:	.byte	3,   5,	  6,   7,   8, 0xFF 
byte_2BFB9:	.byte	7,   9,	 0xA, 0xFF 
byte_2BFBD:	.byte	4,  0xB,	 0xC,  0xD, 0xFF 
byte_2BFC2:	.byte	7,  0xE,	 0xF, 0x10, 0x11, 0xFF 
byte_2BFC8:	.byte	7, 0x12,	0x13, 0x14, 0x15, 0xFF 
byte_2BFCE:	.byte	7, 0x16,	0x17, 0x18, 0x19, 0xFF 
byte_2BFD4:	.byte	7, 0x1A,	0x1B, 0x1C, 0x1D, 0xFF 
