		.word word_2B6E6-Map_AnimatedStillSprites
		.word word_2B6EE-Map_AnimatedStillSprites
		.word word_2B6F6-Map_AnimatedStillSprites
		.word word_2B6FE-Map_AnimatedStillSprites
		.word word_2B706-Map_AnimatedStillSprites
		.word word_2B70E-Map_AnimatedStillSprites
		.word word_2B716-Map_AnimatedStillSprites
		.word word_2B71E-Map_AnimatedStillSprites
		.word word_2B726-Map_AnimatedStillSprites
word_2B6E6:	.word 1
		.byte  0xF4,   6,   0, 0xEA, 0xFF, 0xF8
word_2B6EE:	.word 1
		.byte  0xF4,   6,   0, 0xF0, 0xFF, 0xF8
word_2B6F6:	.word 1
		.byte  0xF4,   6,   0, 0xF6, 0xFF, 0xF8
word_2B6FE:	.word 1
		.byte  0xF4,   6,   0, 0xFC, 0xFF, 0xF8
word_2B706:	.word 1
		.byte  0xF4,   6,   8, 0xF0, 0xFF, 0xF8
word_2B70E:	.word 1
		.byte  0xF0,   7,   1,   2, 0xFF, 0xF8
word_2B716:	.word 1
		.byte  0xF0,   7,   1,  0xA, 0xFF, 0xF8
word_2B71E:	.word 1
		.byte  0xF0,   7,   1, 0x12, 0xFF, 0xF8
word_2B726:	.word 1
		.byte  0xF0,   7,   1, 0x1A, 0xFF, 0xF8
