		.word word_2C016-Map_AnimatedStillSprites
		.word word_2C01E-Map_AnimatedStillSprites
		.word word_2C026-Map_AnimatedStillSprites
		.word word_2C02E-Map_AnimatedStillSprites
		.word word_2C036-Map_AnimatedStillSprites
		.word word_2C03E-Map_AnimatedStillSprites
		.word word_2C046-Map_AnimatedStillSprites
		.word word_2C04E-Map_AnimatedStillSprites
		.word word_2C056-Map_AnimatedStillSprites
		.word word_2C05E-Map_AnimatedStillSprites
		.word word_2C06C-Map_AnimatedStillSprites
		.word word_2C07A-Map_AnimatedStillSprites
		.word word_2C088-Map_AnimatedStillSprites
		.word word_2C090-Map_AnimatedStillSprites
		.word word_2C098-Map_AnimatedStillSprites
		.word word_2C0A0-Map_AnimatedStillSprites
		.word word_2C0A8-Map_AnimatedStillSprites
		.word word_2C0B0-Map_AnimatedStillSprites
		.word word_2C0B8-Map_AnimatedStillSprites
		.word word_2C0C6-Map_AnimatedStillSprites
		.word word_2C0D4-Map_AnimatedStillSprites
		.word word_2C0E2-Map_AnimatedStillSprites
		.word word_2C0F0-Map_AnimatedStillSprites
		.word word_2C10A-Map_AnimatedStillSprites
		.word word_2C124-Map_AnimatedStillSprites
		.word word_2C13E-Map_AnimatedStillSprites
		.word word_2C158-Map_AnimatedStillSprites
		.word word_2C17E-Map_AnimatedStillSprites
		.word word_2C1A4-Map_AnimatedStillSprites
		.word word_2C1CA-Map_AnimatedStillSprites
word_2C016:	.word 1			/*  DATA XREF: ROM:0002BFDAo */
		.byte  0xF4,   6,	  0, 0xEA, 0xFF, 0xF8
word_2C01E:	.word 1			/*  DATA XREF: ROM:0002BFDAo */
		.byte  0xF4,   6,	  0, 0xF0, 0xFF, 0xF8
word_2C026:	.word 1			/*  DATA XREF: ROM:0002BFDAo */
		.byte  0xF4,   6,	  0, 0xF6, 0xFF, 0xF8
word_2C02E:	.word 1			/*  DATA XREF: ROM:0002BFDAo */
		.byte  0xF4,   6,	  0, 0xFC, 0xFF, 0xF8
word_2C036:	.word 1			/*  DATA XREF: ROM:0002BFDAo */
		.byte  0xF4,   6,	  8, 0xF0, 0xFF, 0xF8
word_2C03E:	.word 1			/*  DATA XREF: ROM:0002BFDAo */
		.byte  0xF0,   7,	  1,   2, 0xFF, 0xF8
word_2C046:	.word 1			/*  DATA XREF: ROM:0002BFDAo */
		.byte  0xF0,   7,	  1,  0xA, 0xFF, 0xF8
word_2C04E:	.word 1			/*  DATA XREF: ROM:0002BFDAo */
		.byte  0xF0,   7,	  1, 0x12, 0xFF, 0xF8
word_2C056:	.word 1			/*  DATA XREF: ROM:0002BFDAo */
		.byte  0xF0,   7,	  1, 0x1A, 0xFF, 0xF8
word_2C05E:	.word 2			/*  DATA XREF: ROM:0002BFDAo */
		.byte  0xFC,   4,	  0, 0x68, 0xFF, 0xF0
		.byte  0xFC,   4,	  0, 0x68,   0,	 0
word_2C06C:	.word 2			/*  DATA XREF: ROM:0002BFDAo */
		.byte  0xFC,   4,	  8, 0x68, 0xFF, 0xF0
		.byte  0xFC,   4,	  8, 0x68,   0,	 0
word_2C07A:	.word 2			/*  DATA XREF: ROM:0002BFDAo */
		.byte  0xF0,   7,	  0, 0x37, 0xFF, 0xF0
		.byte  0xF0,   7,	  0, 0x3F,   0,	 0
word_2C088:	.word 1			/*  DATA XREF: ROM:0002BFDAo */
		.byte  0xF0,  0xF,	  0, 0x47, 0xFF, 0xF0
word_2C090:	.word 1			/*  DATA XREF: ROM:0002BFDAo */
		.byte  0xF0,  0xF,	  8, 0x47, 0xFF, 0xF0
word_2C098:	.word 1			/*  DATA XREF: ROM:0002BFDAo */
		.byte  0xFC,   0,	  0,   0, 0xFF, 0xFC
word_2C0A0:	.word 1			/*  DATA XREF: ROM:0002BFDAo */
		.byte  0xFC,   0,	  0,   1, 0xFF, 0xFC
word_2C0A8:	.word 1			/*  DATA XREF: ROM:0002BFDAo */
		.byte  0xFC,   0,	  8,   1, 0xFF, 0xFC
word_2C0B0:	.word 1			/*  DATA XREF: ROM:0002BFDAo */
		.byte  0xFC,   0,	  8,   0, 0xFF, 0xFC
word_2C0B8:	.word 2			/*  DATA XREF: ROM:0002BFDAo */
		.byte  0xFC,   0,	  0,   0, 0xFF, 0xEC
		.byte  0xFC,   0,	  0,   0,   0,	0xC
word_2C0C6:	.word 2			/*  DATA XREF: ROM:0002BFDAo */
		.byte  0xFC,   0,	  0,   1, 0xFF, 0xEC
		.byte  0xFC,   0,	  0,   1,   0,	0xC
word_2C0D4:	.word 2			/*  DATA XREF: ROM:0002BFDAo */
		.byte  0xFC,   0,	  8,   1, 0xFF, 0xEC
		.byte  0xFC,   0,	  8,   1,   0,	0xC
word_2C0E2:	.word 2			/*  DATA XREF: ROM:0002BFDAo */
		.byte  0xFC,   0,	  8,   0, 0xFF, 0xEC
		.byte  0xFC,   0,	  8,   0,   0,	0xC
word_2C0F0:	.word 4			/*  DATA XREF: ROM:0002BFDAo */
		.byte  0xFC,   0,	  0,   0, 0xFF, 0xCC
		.byte  0xFC,   0,	  0,   0, 0xFF, 0xEC
		.byte  0xFC,   0,	  0,   0,   0,	0xC
		.byte  0xFC,   0,	  0,   0,   0, 0x2C
word_2C10A:	.word 4			/*  DATA XREF: ROM:0002BFDAo */
		.byte  0xFC,   0,	  0,   1, 0xFF, 0xCC
		.byte  0xFC,   0,	  0,   1, 0xFF, 0xEC
		.byte  0xFC,   0,	  0,   1,   0,	0xC
		.byte  0xFC,   0,	  0,   1,   0, 0x2C
word_2C124:	.word 4			/*  DATA XREF: ROM:0002BFDAo */
		.byte  0xFC,   0,	  8,   1, 0xFF, 0xCC
		.byte  0xFC,   0,	  8,   1, 0xFF, 0xEC
		.byte  0xFC,   0,	  8,   1,   0,	0xC
		.byte  0xFC,   0,	  8,   1,   0, 0x2C
word_2C13E:	.word 4			/*  DATA XREF: ROM:0002BFDAo */
		.byte  0xFC,   0,	  8,   0, 0xFF, 0xCC
		.byte  0xFC,   0,	  8,   0, 0xFF, 0xEC
		.byte  0xFC,   0,	  8,   0,   0,	0xC
		.byte  0xFC,   0,	  8,   0,   0, 0x2C
word_2C158:	.word 6			/*  DATA XREF: ROM:0002BFDAo */
		.byte  0xFC,   0,	  0,   0, 0xFF, 0xAC
		.byte  0xFC,   0,	  0,   0, 0xFF, 0xCC
		.byte  0xFC,   0,	  0,   0, 0xFF, 0xEC
		.byte  0xFC,   0,	  0,   0,   0,	0xC
		.byte  0xFC,   0,	  0,   0,   0, 0x2C
		.byte  0xFC,   0,	  0,   0,   0, 0x4C
word_2C17E:	.word 6			/*  DATA XREF: ROM:0002BFDAo */
		.byte  0xFC,   0,	  0,   1, 0xFF, 0xAC
		.byte  0xFC,   0,	  0,   1, 0xFF, 0xCC
		.byte  0xFC,   0,	  0,   1, 0xFF, 0xEC
		.byte  0xFC,   0,	  0,   1,   0,	0xC
		.byte  0xFC,   0,	  0,   1,   0, 0x2C
		.byte  0xFC,   0,	  0,   1,   0, 0x4C
word_2C1A4:	.word 6			/*  DATA XREF: ROM:0002BFDAo */
		.byte  0xFC,   0,	  8,   1, 0xFF, 0xAC
		.byte  0xFC,   0,	  8,   1, 0xFF, 0xCC
		.byte  0xFC,   0,	  8,   1, 0xFF, 0xEC
		.byte  0xFC,   0,	  8,   1,   0,	0xC
		.byte  0xFC,   0,	  8,   1,   0, 0x2C
		.byte  0xFC,   0,	  8,   1,   0, 0x4C
word_2C1CA:	.word 6			/*  DATA XREF: ROM:0002BFDAo */
		.byte  0xFC,   0,	  8,   0, 0xFF, 0xAC
		.byte  0xFC,   0,	  8,   0, 0xFF, 0xCC
		.byte  0xFC,   0,	  8,   0, 0xFF, 0xEC
		.byte  0xFC,   0,	  8,   0,   0,	0xC
		.byte  0xFC,   0,	  8,   0,   0, 0x2C
		.byte  0xFC,   0,	  8,   0,   0, 0x4C
