		.word	word_410A0-Map_SOZLightSwitch
		.word word_410AE-Map_SOZLightSwitch
		.word word_410C2-Map_SOZLightSwitch
		.word word_410DC-Map_SOZLightSwitch
		.word word_410FC-Map_SOZLightSwitch
		.word word_41122-Map_SOZLightSwitch
		.word word_4114E-Map_SOZLightSwitch
		.word word_41156-Map_SOZLightSwitch
word_410A0:	.word 2			/*  DATA XREF: ROM:00041090o */
		.byte	8,  0xA,	  0,   5, 0xFF, 0xE8
		.byte	8,  0xA,	  8,   5,   0,	 0
word_410AE:	.word 3			/*  DATA XREF: ROM:00041090o */
		.byte	0,   0,	  0,   4, 0xFF, 0xFC
		.byte	8,  0xA,	  0,   5, 0xFF, 0xE8
		.byte	8,  0xA,	  8,   5,   0,	 0
word_410C2:	.word 4			/*  DATA XREF: ROM:00041090o */
		.byte  0xF8,   0,	  0,   4, 0xFF, 0xFC
		.byte	0,   0,	  0,   4, 0xFF, 0xFC
		.byte	8,  0xA,	  0,   5, 0xFF, 0xE8
		.byte	8,  0xA,	  8,   5,   0,	 0
word_410DC:	.word 5			/*  DATA XREF: ROM:00041090o */
		.byte  0xF0,   0,	  0,   4, 0xFF, 0xFC
		.byte  0xF8,   0,	  0,   4, 0xFF, 0xFC
		.byte	0,   0,	  0,   4, 0xFF, 0xFC
		.byte	8,  0xA,	  0,   5, 0xFF, 0xE8
		.byte	8,  0xA,	  8,   5,   0,	 0
word_410FC:	.word 6			/*  DATA XREF: ROM:00041090o */
		.byte  0xE8,   0,	  0,   4, 0xFF, 0xFC
		.byte  0xF0,   0,	  0,   4, 0xFF, 0xFC
		.byte  0xF8,   0,	  0,   4, 0xFF, 0xFC
		.byte	0,   0,	  0,   4, 0xFF, 0xFC
		.byte	8,  0xA,	  0,   5, 0xFF, 0xE8
		.byte	8,  0xA,	  8,   5,   0,	 0
word_41122:	.word 7			/*  DATA XREF: ROM:00041090o */
		.byte  0xE0,   0,	  0,   4, 0xFF, 0xFC
		.byte  0xE8,   0,	  0,   4, 0xFF, 0xFC
		.byte  0xF0,   0,	  0,   4, 0xFF, 0xFC
		.byte  0xF8,   0,	  0,   4, 0xFF, 0xFC
		.byte	0,   0,	  0,   4, 0xFF, 0xFC
		.byte	8,  0xA,	  0,   5, 0xFF, 0xE8
		.byte	8,  0xA,	  8,   5,   0,	 0
word_4114E:	.word 1			/*  DATA XREF: ROM:00041090o */
		.byte	0,  0xC,	  0,   0, 0xFF, 0xF0
word_41156:	.word 3			/*  DATA XREF: ROM:00041090o */
		.byte	0,  0xC,	  0,   0, 0xFF, 0xF0
		.byte	8,  0xA,	  0,   5, 0xFF, 0xE8
		.byte	8,  0xA,	  8,   5,   0,	 0
