		.word word_41838-Map_SOZBreakableSandRock
		.word word_41846-Map_SOZBreakableSandRock
		.word word_41854-Map_SOZBreakableSandRock
		.word word_41862-Map_SOZBreakableSandRock
		.word word_41870-Map_SOZBreakableSandRock
word_41838:	.word 2			/* DATA XREF: ROM:0004182Eo*/
		.byte  0xF0,  0xB,	  0,   0, 0xFF, 0xE8
		.byte  0xF0,  0xB,	  0,  0xC,   0,	 0
word_41846:	.word 2			/* DATA XREF: ROM:0004182Eo*/
		.byte  0xF0,  0xB,	  0, 0x18, 0xFF, 0xE8
		.byte  0xF0,  0xB,	  8, 0x18,   0,	 0
word_41854:	.word 2			/* DATA XREF: ROM:0004182Eo*/
		.byte  0xF8,  0xA,	  0, 0x24, 0xFF, 0xE8
		.byte  0xF8,  0xA,	  8, 0x24,   0,	 0
word_41862:	.word 2			/* DATA XREF: ROM:0004182Eo*/
		.byte	0,   9,	  0, 0x2D, 0xFF, 0xE8
		.byte	0,   9,	  8, 0x2D,   0,	 0
word_41870:	.word 2			/* DATA XREF: ROM:0004182Eo*/
		.byte	8,   8,	  0, 0x33, 0xFF, 0xE8
		.byte	8,   8,	  8, 0x33,   0,	 0
