Map_774A6:		.word word_774DC-Map_774A6
		.word word_774F6-Map_774A6
		.word word_77510-Map_774A6
		.word word_7752A-Map_774A6
		.word word_77532-Map_774A6
		.word word_7753A-Map_774A6
		.word word_77542-Map_774A6
		.word word_7754A-Map_774A6
		.word word_77558-Map_774A6
		.word word_77566-Map_774A6
		.word word_7756E-Map_774A6
		.word word_7757C-Map_774A6
		.word word_7758A-Map_774A6
		.word word_77592-Map_774A6
		.word word_7759A-Map_774A6
		.word word_775A2-Map_774A6
		.word word_775AA-Map_774A6
		.word word_775B8-Map_774A6
		.word word_775C6-Map_774A6
		.word word_775CE-Map_774A6
		.word word_775D6-Map_774A6
		.word word_775DE-Map_774A6
		.word word_775E6-Map_774A6
		.word word_775EE-Map_774A6
		.word word_775F6-Map_774A6
		.word word_7760A-Map_774A6
		.word word_77624-Map_774A6
word_774DC:	.word 4			/* DATA XREF: ROM:000774A6o*/
		.byte  0xF4,  0xE,	  0,   0, 0xFF, 0xE8
		.byte  0xF4,   6,	  0,  0xC,   0,	 8
		.byte  0xDC,  0xA,	  0, 0x4D, 0xFF, 0xE8
		.byte  0xDC,  0xA,	  8, 0x4D,   0,	 0
word_774F6:	.word 4			/* DATA XREF: ROM:000774A6o*/
		.byte  0xF4,  0xE,	  0,   0, 0xFF, 0xE8
		.byte  0xF4,   6,	  0,  0xC,   0,	 8
		.byte  0xD4,  0xB,	  0, 0x2C, 0xFF, 0xE8
		.byte  0xDC,  0xA,	  8, 0x4D,   0,	 0
word_77510:	.word 4			/* DATA XREF: ROM:000774A6o*/
		.byte  0xF4,  0xE,	  0, 0x12, 0xFF, 0xE8
		.byte  0xF4,   6,	  0, 0x1E,   0,	 8
		.byte  0xD4,  0xB,	  0, 0x38, 0xFF, 0xE8
		.byte  0xDC,  0xA,	  8, 0x44,   0,	 0
word_7752A:	.word 1			/* DATA XREF: ROM:000774A6o*/
		.byte  0xF8,  0xD,	  0, 0x24, 0xFF, 0xF0
word_77532:	.word 1			/* DATA XREF: ROM:000774A6o*/
		.byte  0xF0,  0xB,	  0, 0x2C, 0xFF, 0xF4
word_7753A:	.word 1			/* DATA XREF: ROM:000774A6o*/
		.byte  0xF0,  0xB,	  0, 0x38, 0xFF, 0xF4
word_77542:	.word 1			/* DATA XREF: ROM:000774A6o*/
		.byte  0xF0,  0xF,	  0, 0x56, 0xFF, 0xF0
word_7754A:	.word 2			/* DATA XREF: ROM:000774A6o*/
		.byte  0xF0,  0xB,	  0, 0x66, 0xFF, 0xEC
		.byte  0xF0,   6,	  0, 0x72,   0,	 4
word_77558:	.word 2			/* DATA XREF: ROM:000774A6o*/
		.byte  0xF4,  0xE,	  0, 0x78, 0xFF, 0xEC
		.byte  0xF4,   2,	  0, 0x84,   0,	0xC
word_77566:	.word 1			/* DATA XREF: ROM:000774A6o*/
		.byte  0xF0,  0xF,	  0, 0x87, 0xFF, 0xF0
word_7756E:	.word 2			/* DATA XREF: ROM:000774A6o*/
		.byte  0xEC,  0xE,	  0, 0x97, 0xFF, 0xF0
		.byte	4,   9,	  0, 0xA3, 0xFF, 0xF8
word_7757C:	.word 2			/* DATA XREF: ROM:000774A6o*/
		.byte  0xF8,   1,	  0, 0xA9, 0xFF, 0xEC
		.byte  0xF0,  0xF,	  0, 0xAB, 0xFF, 0xF4
word_7758A:	.word 1			/* DATA XREF: ROM:000774A6o*/
		.byte  0xF4,  0xA,	  0, 0xBB, 0xFF, 0xF4
word_77592:	.word 1			/* DATA XREF: ROM:000774A6o*/
		.byte  0xF4,  0xE,	  0, 0xC4, 0xFF, 0xF0
word_7759A:	.word 1			/* DATA XREF: ROM:000774A6o*/
		.byte  0xF4,  0xA,	  0, 0xD0, 0xFF, 0xF4
word_775A2:	.word 1			/* DATA XREF: ROM:000774A6o*/
		.byte  0xF4,  0xA,	  0, 0xD9, 0xFF, 0xF4
word_775AA:	.word 2			/* DATA XREF: ROM:000774A6o*/
		.byte  0xF8,  0xD,	  0, 0xE2, 0xFF, 0xEC
		.byte  0xF8,   1,	  0, 0xEA,   0,	0xC
word_775B8:	.word 2			/* DATA XREF: ROM:000774A6o*/
		.byte  0xF8,  0xD,	  0, 0xEC, 0xFF, 0xEC
		.byte  0xF8,   1,	  0, 0xF4,   0,	0xC
word_775C6:	.word 1			/* DATA XREF: ROM:000774A6o*/
		.byte  0xF0,  0xB,	  0, 0xF6, 0xFF, 0xF4
word_775CE:	.word 1			/* DATA XREF: ROM:000774A6o*/
		.byte  0xF0,  0xB,	  1,   2, 0xFF, 0xF8
word_775D6:	.word 1			/* DATA XREF: ROM:000774A6o*/
		.byte  0xF0,  0xB,	  1,  0xE, 0xFF, 0xFC
word_775DE:	.word 1			/* DATA XREF: ROM:000774A6o*/
		.byte  0xF0,  0xF,	  1, 0x1A, 0xFF, 0xF0
word_775E6:	.word 1			/* DATA XREF: ROM:000774A6o*/
		.byte  0xF0,  0xF,	  1, 0x2A, 0xFF, 0xF0
word_775EE:	.word 1			/* DATA XREF: ROM:000774A6o*/
		.byte  0xF8,   5,	  1, 0x3A, 0xFF, 0xF8
word_775F6:	.word 3			/* DATA XREF: ROM:000774A6o*/
		.byte  0xE8,  0xF,	  1, 0x1A, 0xFF, 0xF0
		.byte	4,  0xF,	  0, 0x56, 0xFF, 0xE4
		.byte  0xFC,   5,	  1, 0x3A, 0xFF, 0xF8
word_7760A:	.word 4			/* DATA XREF: ROM:000774A6o*/
		.byte  0xF4,  0xE,	  0,   0, 0xFF, 0xE8
		.byte  0xF4,   6,	  0,  0xC,   0,	 8
		.byte  0xD4,  0xB,	  0, 0x38, 0xFF, 0xE8
		.byte  0xDC,  0xA,	  8, 0x4D,   0,	 0
word_77624:	.word 0			/* DATA XREF: ROM:000774A6o*/
