		.word word_4B21E-Map_SOZRapelWire
		.word word_4B226-Map_SOZRapelWire
		.word word_4B22E-Map_SOZRapelWire
		.word word_4B236-Map_SOZRapelWire
		.word word_4B23E-Map_SOZRapelWire
		.word word_4B246-Map_SOZRapelWire
		.word word_4B24E-Map_SOZRapelWire
		.word word_4B256-Map_SOZRapelWire
		.word word_4B25E-Map_SOZRapelWire
		.word word_4B266-Map_SOZRapelWire
		.word word_4B26E-Map_SOZRapelWire
		.word word_4B276-Map_SOZRapelWire
		.word word_4B27E-Map_SOZRapelWire
		.word word_4B286-Map_SOZRapelWire
		.word word_4B28E-Map_SOZRapelWire
		.word word_4B296-Map_SOZRapelWire
		.word word_4B29E-Map_SOZRapelWire
		.word word_4B2A6-Map_SOZRapelWire
		.word word_4B2AE-Map_SOZRapelWire
		.word word_4B2B6-Map_SOZRapelWire
		.word word_4B2BE-Map_SOZRapelWire
		.word word_4B2C6-Map_SOZRapelWire
		.word word_4B2CE-Map_SOZRapelWire
		.word word_4B2D6-Map_SOZRapelWire
		.word word_4B2DE-Map_SOZRapelWire
		.word word_4B2E6-Map_SOZRapelWire
		.word word_4B2EE-Map_SOZRapelWire
		.word word_4B2F6-Map_SOZRapelWire
		.word word_4B2FE-Map_SOZRapelWire
		.word word_4B306-Map_SOZRapelWire
		.word word_4B30E-Map_SOZRapelWire
		.word word_4B316-Map_SOZRapelWire
		.word word_4B31E-Map_SOZRapelWire
		.word word_4B326-Map_SOZRapelWire
		.word word_4B32E-Map_SOZRapelWire
		.word word_4B336-Map_SOZRapelWire
		.word word_4B33E-Map_SOZRapelWire
		.word word_4B346-Map_SOZRapelWire
		.word word_4B34E-Map_SOZRapelWire
word_4B21E:	.word 1			/*  DATA XREF: ROM:0004B1D0o */
		.byte	0,   1,	  0, 0x16, 0xFF, 0xF8
word_4B226:	.word 1			/*  DATA XREF: ROM:0004B1D0o */
		.byte	0,   1,	  0, 0x14, 0xFF, 0xF8
word_4B22E:	.word 1			/*  DATA XREF: ROM:0004B1D0o */
		.byte	0,   1,	  0, 0x12, 0xFF, 0xF8
word_4B236:	.word 1			/*  DATA XREF: ROM:0004B1D0o */
		.byte	0,   5,	  0,  0xE, 0xFF, 0xF0
word_4B23E:	.word 1			/*  DATA XREF: ROM:0004B1D0o */
		.byte	0,   5,	  0,  0xA, 0xFF, 0xF0
word_4B246:	.word 1			/*  DATA XREF: ROM:0004B1D0o */
		.byte	0,   5,	  0,   6, 0xFF, 0xF0
word_4B24E:	.word 1			/*  DATA XREF: ROM:0004B1D0o */
		.byte	0,   4,	  0,   4, 0xFF, 0xF0
word_4B256:	.word 1			/*  DATA XREF: ROM:0004B1D0o */
		.byte	0,   4,	  0,   2, 0xFF, 0xF0
word_4B25E:	.word 1			/*  DATA XREF: ROM:0004B1D0o */
		.byte	0,   4,	  0,   0, 0xFF, 0xF0
word_4B266:	.word 1			/*  DATA XREF: ROM:0004B1D0o */
		.byte  0xF9,   4,	0x10,   2, 0xFF, 0xF0
word_4B26E:	.word 1			/*  DATA XREF: ROM:0004B1D0o */
		.byte  0xF9,   4,	0x10,   4, 0xFF, 0xF0
word_4B276:	.word 1			/*  DATA XREF: ROM:0004B1D0o */
		.byte  0xF1,   5,	0x10,   6, 0xFF, 0xF0
word_4B27E:	.word 1			/*  DATA XREF: ROM:0004B1D0o */
		.byte  0xF1,   5,	0x10,  0xA, 0xFF, 0xF0
word_4B286:	.word 1			/*  DATA XREF: ROM:0004B1D0o */
		.byte  0xF1,   5,	0x10,  0xE, 0xFF, 0xF0
word_4B28E:	.word 1			/*  DATA XREF: ROM:0004B1D0o */
		.byte  0xF1,   1,	0x10, 0x12, 0xFF, 0xF8
word_4B296:	.word 1			/*  DATA XREF: ROM:0004B1D0o */
		.byte  0xF1,   1,	0x10, 0x14, 0xFF, 0xF8
word_4B29E:	.word 1			/*  DATA XREF: ROM:0004B1D0o */
		.byte  0xF1,   1,	0x10, 0x16, 0xFF, 0xF8
word_4B2A6:	.word 1			/*  DATA XREF: ROM:0004B1D0o */
		.byte  0xF1,   1,	0x18, 0x14, 0xFF, 0xFF
word_4B2AE:	.word 1			/*  DATA XREF: ROM:0004B1D0o */
		.byte  0xF1,   1,	0x18, 0x12, 0xFF, 0xFF
word_4B2B6:	.word 1			/*  DATA XREF: ROM:0004B1D0o */
		.byte  0xF1,   5,	0x18,  0xE, 0xFF, 0xFF
word_4B2BE:	.word 1			/*  DATA XREF: ROM:0004B1D0o */
		.byte  0xF1,   5,	0x18,  0xA, 0xFF, 0xFF
word_4B2C6:	.word 1			/*  DATA XREF: ROM:0004B1D0o */
		.byte  0xF1,   5,	0x18,   6, 0xFF, 0xFF
word_4B2CE:	.word 1			/*  DATA XREF: ROM:0004B1D0o */
		.byte  0xF9,   4,	0x18,   4, 0xFF, 0xFF
word_4B2D6:	.word 1			/*  DATA XREF: ROM:0004B1D0o */
		.byte  0xF9,   4,	0x18,   2, 0xFF, 0xFF
word_4B2DE:	.word 1			/*  DATA XREF: ROM:0004B1D0o */
		.byte	0,   4,	  8,   0, 0xFF, 0xFF
word_4B2E6:	.word 1			/*  DATA XREF: ROM:0004B1D0o */
		.byte	0,   4,	  8,   2, 0xFF, 0xFF
word_4B2EE:	.word 1			/*  DATA XREF: ROM:0004B1D0o */
		.byte	0,   4,	  8,   4, 0xFF, 0xFF
word_4B2F6:	.word 1			/*  DATA XREF: ROM:0004B1D0o */
		.byte	0,   5,	  8,   6, 0xFF, 0xFF
word_4B2FE:	.word 1			/*  DATA XREF: ROM:0004B1D0o */
		.byte	0,   5,	  8,  0xA, 0xFF, 0xFF
word_4B306:	.word 1			/*  DATA XREF: ROM:0004B1D0o */
		.byte	0,   5,	  8,  0xE, 0xFF, 0xFF
word_4B30E:	.word 1			/*  DATA XREF: ROM:0004B1D0o */
		.byte	0,   1,	  8, 0x12, 0xFF, 0xFF
word_4B316:	.word 1			/*  DATA XREF: ROM:0004B1D0o */
		.byte	0,   1,	  8, 0x14, 0xFF, 0xFF
word_4B31E:	.word 1			/*  DATA XREF: ROM:0004B1D0o */
		.byte  0xF0,   5,	0xFF, 0xC4, 0xFF, 0xFD
word_4B326:	.word 1			/*  DATA XREF: ROM:0004B1D0o */
		.byte  0xFC,   8,	  0, 0x18, 0xFF, 0xF4
word_4B32E:	.word 1			/*  DATA XREF: ROM:0004B1D0o */
		.byte  0xFC,   8,	  0, 0x1B, 0xFF, 0xF4
word_4B336:	.word 1			/*  DATA XREF: ROM:0004B1D0o */
		.byte  0xFC,   4,	  0, 0x1E, 0xFF, 0xF8
word_4B33E:	.word 1			/*  DATA XREF: ROM:0004B1D0o */
		.byte  0xFC,   0,	  0, 0x20, 0xFF, 0xFC
word_4B346:	.word 1			/*  DATA XREF: ROM:0004B1D0o */
		.byte  0xFC,   4,	  8, 0x1E, 0xFF, 0xF8
word_4B34E:	.word 1			/*  DATA XREF: ROM:0004B1D0o */
		.byte  0xFC,   8,	  8, 0x1B, 0xFF, 0xF4
