		.word word_40D2C-Map_SOZRisingSandWall
		.word word_40D58-Map_SOZRisingSandWall
		.word word_40D84-Map_SOZRisingSandWall
		.word word_40DB0-Map_SOZRisingSandWall
		.word word_40DD6-Map_SOZRisingSandWall
		.word word_40DF6-Map_SOZRisingSandWall
		.word word_40E10-Map_SOZRisingSandWall
		.word word_40E24-Map_SOZRisingSandWall
		.word word_40E32-Map_SOZRisingSandWall
		.word word_40E3A-Map_SOZRisingSandWall
		.word word_40E42-Map_SOZRisingSandWall
		.word word_40E4A-Map_SOZRisingSandWall
		.word word_40E52-Map_SOZRisingSandWall
		.word word_40E5A-Map_SOZRisingSandWall
word_40D2C:	.word 7			/*  DATA XREF: ROM:00040D10o */
		.byte  0xCC,   8,	  0,   0, 0xFF, 0xF4
		.byte  0xD4,   9,	  0,   3, 0xFF, 0xF4
		.byte  0xE4,   9,	  0,   3, 0xFF, 0xF4
		.byte  0xF4,   9,	  0,   3, 0xFF, 0xF4
		.byte	4,   9,	  0,   3, 0xFF, 0xF4
		.byte  0x14,   9,	  0,   3, 0xFF, 0xF4
		.byte  0x24,   9,	  0,   3, 0xFF, 0xF4
word_40D58:	.word 7			/*  DATA XREF: ROM:00040D10o */
		.byte  0xCC,   8,	  0,   9, 0xFF, 0xF4
		.byte  0xD4,   9,	  0,   3, 0xFF, 0xF4
		.byte  0xE4,   9,	  0,   3, 0xFF, 0xF4
		.byte  0xF4,   9,	  0,   3, 0xFF, 0xF4
		.byte	4,   9,	  0,   3, 0xFF, 0xF4
		.byte  0x14,   9,	  0,   3, 0xFF, 0xF4
		.byte  0x24,   9,	  0,   3, 0xFF, 0xF4
word_40D84:	.word 7			/*  DATA XREF: ROM:00040D10o */
		.byte  0xCC,   8,	  0,  0xC, 0xFF, 0xF4
		.byte  0xD4,   9,	  0,  0xF, 0xFF, 0xF4
		.byte  0xE4,   9,	  0,   3, 0xFF, 0xF4
		.byte  0xF4,   9,	  0,   3, 0xFF, 0xF4
		.byte	4,   9,	  0,   3, 0xFF, 0xF4
		.byte  0x14,   9,	  0,   3, 0xFF, 0xF4
		.byte  0x24,   9,	  0,   3, 0xFF, 0xF4
word_40DB0:	.word 6			/*  DATA XREF: ROM:00040D10o */
		.byte  0xD4,   9,	  0, 0x15, 0xFF, 0xF4
		.byte  0xE4,   9,	  8,  0xF, 0xFF, 0xF4
		.byte  0xF4,   9,	  0,   3, 0xFF, 0xF4
		.byte	4,   9,	  0,   3, 0xFF, 0xF4
		.byte  0x14,   9,	  0,   3, 0xFF, 0xF4
		.byte  0x24,   9,	  0,   3, 0xFF, 0xF4
word_40DD6:	.word 5			/*  DATA XREF: ROM:00040D10o */
		.byte  0xE4,   9,	  8, 0x15, 0xFF, 0xF4
		.byte  0xF4,   9,	  0,  0xF, 0xFF, 0xF4
		.byte	4,   9,	  0,   3, 0xFF, 0xF4
		.byte  0x14,   9,	  0,   3, 0xFF, 0xF4
		.byte  0x24,   9,	  0,   3, 0xFF, 0xF4
word_40DF6:	.word 4			/*  DATA XREF: ROM:00040D10o */
		.byte  0xF4,   9,	  0, 0x15, 0xFF, 0xF4
		.byte	4,   9,	  8,  0xF, 0xFF, 0xF4
		.byte  0x14,   9,	  0,   3, 0xFF, 0xF4
		.byte  0x24,   9,	  0,   3, 0xFF, 0xF4
word_40E10:	.word 3			/*  DATA XREF: ROM:00040D10o */
		.byte	4,   9,	  8, 0x15, 0xFF, 0xF4
		.byte  0x14,   9,	  0,  0xF, 0xFF, 0xF4
		.byte  0x24,   9,	  0,   3, 0xFF, 0xF4
word_40E24:	.word 2			/*  DATA XREF: ROM:00040D10o */
		.byte  0x14,   9,	  0, 0x15, 0xFF, 0xF4
		.byte  0x24,   9,	  8,  0xF, 0xFF, 0xF4
word_40E32:	.word 1			/*  DATA XREF: ROM:00040D10o */
		.byte  0x24,   9,	  8, 0x15, 0xFF, 0xF4
word_40E3A:	.word 1			/*  DATA XREF: ROM:00040D10o */
		.byte  0xC4,  0xC,	  0, 0x1B, 0xFF, 0xF0
word_40E42:	.word 1			/*  DATA XREF: ROM:00040D10o */
		.byte  0xC4,  0xC,	  0, 0x1F, 0xFF, 0xF0
word_40E4A:	.word 1			/*  DATA XREF: ROM:00040D10o */
		.byte  0xC4,  0xC,	  8, 0x1B, 0xFF, 0xF0
word_40E52:	.word 1			/*  DATA XREF: ROM:00040D10o */
		.byte  0xC4,  0xC,	  8, 0x1F, 0xFF, 0xF0
word_40E5A:	.word 0			/*  DATA XREF: ROM:00040D10o */
