		.word AniTails_Tail00-AniTails_Tail
		.word AniTails_Tail01-AniTails_Tail
		.word AniTails_Tail02-AniTails_Tail
		.word AniTails_Tail03-AniTails_Tail
		.word AniTails_Tail04-AniTails_Tail
		.word AniTails_Tail05-AniTails_Tail
		.word AniTails_Tail06-AniTails_Tail
		.word AniTails_Tail07-AniTails_Tail
		.word AniTails_Tail08-AniTails_Tail
		.word AniTails_Tail09-AniTails_Tail
		.word AniTails_Tail0A-AniTails_Tail
		.word AniTails_Tail0B-AniTails_Tail
		.word AniTails_Tail0C-AniTails_Tail
AniTails_Tail00:.byte  0x20,   0, 0xFF
AniTails_Tail01:.byte    7, 0x22, 0x23, 0x24, 0x25, 0x26, 0xFF
AniTails_Tail02:.byte    3, 0x22, 0x23, 0x24, 0x25, 0x26, 0xFD,   1
AniTails_Tail03:.byte  0xFC,   5,   6,   7,   8, 0xFF
AniTails_Tail04:.byte    3,   9,  0xA,  0xB,  0xC, 0xFF
AniTails_Tail05:.byte    3,  0xD,  0xE,  0xF, 0x10, 0xFF
AniTails_Tail06:.byte    3, 0x11, 0x12, 0x13, 0x14, 0xFF
AniTails_Tail07:.byte    2,   1,   2,   3,   4, 0xFF
AniTails_Tail08:.byte    2, 0x1A, 0x1B, 0x1C, 0x1D, 0xFF
AniTails_Tail09:.byte    9, 0x1E, 0x1F, 0x20, 0x21, 0xFF
AniTails_Tail0A:.byte    9, 0x29, 0x2A, 0x2B, 0x2C, 0xFF
AniTails_Tail0B:.byte    1, 0x27, 0x28, 0xFF
AniTails_Tail0C:.byte    0, 0x27, 0x28, 0xFF
		.align 2
