		.word AniTails2P00-AniTails2P
		.word AniTails2P01-AniTails2P
		.word AniTails2P02-AniTails2P
		.word AniTails2P03-AniTails2P
		.word AniTails2P04-AniTails2P
		.word AniTails2P05-AniTails2P
		.word AniTails2P05-AniTails2P
		.word AniTails2P05-AniTails2P
		.word AniTails2P08-AniTails2P
		.word AniTails2P09-AniTails2P
		.word AniTails2P05-AniTails2P
		.word AniTails2P05-AniTails2P
		.word AniTails2P05-AniTails2P
		.word AniTails2P0D-AniTails2P
		.word AniTails2P0E-AniTails2P
		.word AniTails2P0F-AniTails2P
		.word AniTails2P10-AniTails2P
		.word AniTails2P11-AniTails2P
		.word AniTails2P12-AniTails2P
		.word AniTails2P13-AniTails2P
		.word AniTails2P14-AniTails2P
		.word AniTails2P15-AniTails2P
		.word AniTails2P16-AniTails2P
		.word AniTails2P17-AniTails2P
		.word AniTails2P18-AniTails2P
		.word AniTails2P19-AniTails2P
		.word AniTails2P19-AniTails2P
		.word AniTails2P1B-AniTails2P
		.word AniTails2P1C-AniTails2P
		.word AniTails2P1D-AniTails2P
		.word AniTails2P1E-AniTails2P
		.word AniTails2P1F-AniTails2P
		.word AniTails2P20-AniTails2P
AniTails2P00:	.byte  0xFF,   1,   2,   3,   2, 0xFF
AniTails2P01:	.byte  0xFF,  0xD,  0xE, 0xFF, 0xFF, 0xFF
AniTails2P02:	.byte    1, 0x28, 0x29, 0x2A, 0xFF
AniTails2P03:	.byte    1, 0x28, 0x29, 0x2A, 0xFF
AniTails2P04:	.byte  0xFD, 0x25, 0x26, 0xFF, 0xFF, 0xFF
AniTails2P05:	.byte    7, 0x1B, 0x1B, 0x1B, 0x1B, 0x1B, 0x1B, 0x1B, 0x1B, 0x1C, 0x1C, 0x1C, 0x1C, 0x1C, 0x1C, 0x1D
		.byte  0x1E, 0x1D, 0x1E, 0x1D, 0x1E, 0x1D, 0x1E, 0x1D, 0x1E, 0xFE, 0x10
AniTails2P08:	.byte    5, 0x2B, 0xFF
AniTails2P09:	.byte    0, 0x23, 0x24, 0xFF
AniTails2P0D:	.byte    5, 0x22, 0x22, 0x22, 0x22, 0xFD,   0
AniTails2P0E:	.byte    7, 0x15, 0xFF
AniTails2P0F:	.byte    7, 0x15, 0xFF
AniTails2P10:	.byte  0x2F, 0x15, 0xFD,   0
AniTails2P11:	.byte    1, 0x15, 0xFF
AniTails2P12:	.byte   0xF, 0x1F, 0xFF
AniTails2P13:	.byte   0xF, 0x1F, 0xFF
AniTails2P14:	.byte  0x13, 0x15, 0xFF
AniTails2P15:	.byte   0xB, 0x15, 0xFF
AniTails2P16:	.byte  0x20, 0x20, 0xFF
AniTails2P17:	.byte  0x20, 0x20, 0xFF
AniTails2P18:	.byte  0x20, 0x20, 0xFF
AniTails2P19:	.byte  0x40, 0x21, 0xFF
AniTails2P1B:	.byte    9, 0x21, 0xFF
AniTails2P1C:	.byte  0x77,   0, 0xFF
AniTails2P1D:	.byte    3, 0x1B, 0xFF
AniTails2P1E:	.byte    3, 0x1B, 0xFF
AniTails2P1F:	.byte  0xFF,  0xD,  0xE, 0xFF, 0xFF, 0xFF
AniTails2P20:	.byte    1, 0x2C, 0x2D, 0xFF
		.balign 2
