		.word word_1A46A-Map_SuperTails_Birds
		.word word_1A472-Map_SuperTails_Birds
		.word word_1A47A-Map_SuperTails_Birds
word_1A46A:	.word 1			/*  DATA XREF: ROM:0001A464o */
		.byte  0xF8,   5,	  0,   6, 0xFF, 0xF8
word_1A472:	.word 1			/*  DATA XREF: ROM:0001A464o */
		.byte  0xF8,   5,	  0,  0xA, 0xFF, 0xF8
word_1A47A:	.word 1			/*  DATA XREF: ROM:0001A464o */
		.byte  0xF4,   6,	  0,   0, 0xFF, 0xF8
		.word 1
		.byte  0x89, 0xED,	  0,  0xB
		.word 1
		.byte  0x8A,   2,	0x16,  0xD
		.word 1
		.byte  0x8A, 0x1B,	0x2C,  0xD
