Map_2A00A4:	.word Frame_2A00C4-Map_2A00A4 /*  ... */
		.word Frame_2A00C6-Map_2A00A4
		.word Frame_2A00CE-Map_2A00A4
		.word Frame_2A00D6-Map_2A00A4
		.word Frame_2A00DE-Map_2A00A4
		.word Frame_2A00E6-Map_2A00A4
		.word Frame_2A00EE-Map_2A00A4
		.word Frame_2A00F6-Map_2A00A4
		.word Frame_2A00FE-Map_2A00A4
		.word Frame_2A0106-Map_2A00A4
		.word Frame_2A010E-Map_2A00A4
		.word Frame_2A0116-Map_2A00A4
		.word Frame_2A011E-Map_2A00A4
		.word Frame_2A0126-Map_2A00A4
		.word Frame_2A012E-Map_2A00A4
		.word Frame_2A0136-Map_2A00A4
Frame_2A00C4:	.word 0
Frame_2A00C6:	.word 1
		.byte 0xFC,  5,  0,  0,0xFF,0xF0
Frame_2A00CE:	.word 1
		.byte 0xFC,  5,  0,  0,0xFF,0xF0
Frame_2A00D6:	.word 1
		.byte 0xFC,  5,  0,  0,0xFF,0xF0
Frame_2A00DE:	.word 1
		.byte 0xFC,  4,  0,  0,0xFF,0xEC
Frame_2A00E6:	.word 1
		.byte 0xFC,  4,  0,  0,0xFF,0xEC
Frame_2A00EE:	.word 1
		.byte 0xFC,  4,  0,  0,0xFF,0xEC
Frame_2A00F6:	.word 1
		.byte   3,  5,  0,  0,0xFF,0xED
Frame_2A00FE:	.word 1
		.byte   3,  5,  0,  0,0xFF,0xED
Frame_2A0106:	.word 1
		.byte   7,  4,  0,  0,0xFF,0xED
Frame_2A010E:	.word 1
		.byte   2,  1,  0,  0,0xFF,0xFC
Frame_2A0116:	.word 1
		.byte   2,  1,  0,  0,0xFF,0xFC
Frame_2A011E:	.word 1
		.byte   2,  1,  0,  0,0xFF,0xFC
Frame_2A0126:	.word 1
		.byte   3,  5,  0,  0,  0,  5
Frame_2A012E:	.word 1
		.byte   3,  5,  0,  0,  0,  3
Frame_2A0136:	.word 1
		.byte   3,  1,  0,  0,  0,  7
