/* Tails mappings*/
Map_148EB8:		.word word_1490AE-Map_148EB8/* 0*/
		.word word_1490B0-Map_148EB8/* 1*/
		.word word_1490CA-Map_148EB8/* 2*/
		.word word_1490E4-Map_148EB8/* 3*/
		.word word_1490F8-Map_148EB8/* 4*/
		.word word_149112-Map_148EB8/* 5*/
		.word word_14912C-Map_148EB8/* 6*/
		.word word_149146-Map_148EB8/* 7*/
		.word word_14915A-Map_148EB8/* 8*/
		.word word_149174-Map_148EB8/* 9*/
		.word word_14918E-Map_148EB8/* 10*/
		.word word_1491A2-Map_148EB8/* 11*/
		.word word_1491BC-Map_148EB8/* 12*/
		.word word_1491D0-Map_148EB8/* 13*/
		.word word_1491E4-Map_148EB8/* 14*/
		.word word_1491F8-Map_148EB8/* 15*/
		.word word_14920C-Map_148EB8/* 16*/
		.word word_149226-Map_148EB8/* 17*/
		.word word_14923A-Map_148EB8/* 18*/
		.word word_14924E-Map_148EB8/* 19*/
		.word word_149262-Map_148EB8/* 20*/
		.word word_149270-Map_148EB8/* 21*/
		.word word_149284-Map_148EB8/* 22*/
		.word word_149292-Map_148EB8/* 23*/
		.word word_1492A6-Map_148EB8/* 24*/
		.word word_1492B4-Map_148EB8/* 25*/
		.word word_1492C8-Map_148EB8/* 26*/
		.word word_1492E2-Map_148EB8/* 27*/
		.word word_1492FC-Map_148EB8/* 28*/
		.word word_149310-Map_148EB8/* 29*/
		.word word_149324-Map_148EB8/* 30*/
		.word word_14933E-Map_148EB8/* 31*/
		.word word_149352-Map_148EB8/* 32*/
		.word word_14936C-Map_148EB8/* 33*/
		.word word_149386-Map_148EB8/* 34*/
		.word word_1493A0-Map_148EB8/* 35*/
		.word word_1493BA-Map_148EB8/* 36*/
		.word word_1493D4-Map_148EB8/* 37*/
		.word word_1493EE-Map_148EB8/* 38*/
		.word word_149408-Map_148EB8/* 39*/
		.word word_149422-Map_148EB8/* 40*/
		.word word_14943C-Map_148EB8/* 41*/
		.word word_149456-Map_148EB8/* 42*/
		.word word_149470-Map_148EB8/* 43*/
		.word word_14948A-Map_148EB8/* 44*/
		.word word_1494A4-Map_148EB8/* 45*/
		.word word_1494BE-Map_148EB8/* 46*/
		.word word_1494D8-Map_148EB8/* 47*/
		.word word_1494F2-Map_148EB8/* 48*/
		.word word_14950C-Map_148EB8/* 49*/
		.word word_149514-Map_148EB8/* 50*/
		.word word_149522-Map_148EB8/* 51*/
		.word word_14952A-Map_148EB8/* 52*/
		.word word_149532-Map_148EB8/* 53*/
		.word word_149540-Map_148EB8/* 54*/
		.word word_14954E-Map_148EB8/* 55*/
		.word word_14955C-Map_148EB8/* 56*/
		.word word_14956A-Map_148EB8/* 57*/
		.word word_149578-Map_148EB8/* 58*/
		.word word_149586-Map_148EB8/* 59*/
		.word word_149594-Map_148EB8/* 60*/
		.word word_1495A2-Map_148EB8/* 61*/
		.word word_1495B0-Map_148EB8/* 62*/
		.word word_1495BE-Map_148EB8/* 63*/
		.word word_1495C6-Map_148EB8/* 64*/
		.word word_1495DA-Map_148EB8/* 65*/
		.word word_1495E2-Map_148EB8/* 66*/
		.word word_1495EA-Map_148EB8/* 67*/
		.word word_1495FE-Map_148EB8/* 68*/
		.word word_14960C-Map_148EB8/* 69*/
		.word word_14961A-Map_148EB8/* 70*/
		.word word_149628-Map_148EB8/* 71*/
		.word word_14963C-Map_148EB8/* 72*/
		.word word_14964A-Map_148EB8/* 73*/
		.word word_14965E-Map_148EB8/* 74*/
		.word word_14966C-Map_148EB8/* 75*/
		.word word_149680-Map_148EB8/* 76*/
		.word word_14968E-Map_148EB8/* 77*/
		.word word_1496A2-Map_148EB8/* 78*/
		.word word_1496BC-Map_148EB8/* 79*/
		.word word_1496D6-Map_148EB8/* 80*/
		.word word_1496F0-Map_148EB8/* 81*/
		.word word_149704-Map_148EB8/* 82*/
		.word word_149718-Map_148EB8/* 83*/
		.word word_149726-Map_148EB8/* 84*/
		.word word_149734-Map_148EB8/* 85*/
		.word word_149748-Map_148EB8/* 86*/
		.word word_149750-Map_148EB8/* 87*/
		.word word_149764-Map_148EB8/* 88*/
		.word word_14976C-Map_148EB8/* 89*/
		.word word_149774-Map_148EB8/* 90*/
		.word word_149788-Map_148EB8/* 91*/
		.word word_149790-Map_148EB8/* 92*/
		.word word_1497AA-Map_148EB8/* 93*/
		.word word_1497B2-Map_148EB8/* 94*/
		.word word_1497C6-Map_148EB8/* 95*/
		.word word_1497D4-Map_148EB8/* 96*/
		.word word_1497DC-Map_148EB8/* 97*/
		.word word_1497E4-Map_148EB8/* 98*/
		.word word_1497F8-Map_148EB8/* 99*/
		.word word_149812-Map_148EB8/* 100*/
		.word word_14981A-Map_148EB8/* 101*/
		.word word_149828-Map_148EB8/* 102*/
		.word word_149836-Map_148EB8/* 103*/
		.word word_14983E-Map_148EB8/* 104*/
		.word word_149846-Map_148EB8/* 105*/
		.word word_14985A-Map_148EB8/* 106*/
		.word word_14986E-Map_148EB8/* 107*/
		.word word_14987C-Map_148EB8/* 108*/
		.word word_14988A-Map_148EB8/* 109*/
		.word word_149898-Map_148EB8/* 110*/
		.word word_1498A6-Map_148EB8/* 111*/
		.word word_1498B4-Map_148EB8/* 112*/
		.word word_1498C2-Map_148EB8/* 113*/
		.word word_1498D0-Map_148EB8/* 114*/
		.word word_1498D8-Map_148EB8/* 115*/
		.word word_1498E6-Map_148EB8/* 116*/
		.word word_1498EE-Map_148EB8/* 117*/
		.word word_1498F6-Map_148EB8/* 118*/
		.word word_149904-Map_148EB8/* 119*/
		.word word_149912-Map_148EB8/* 120*/
		.word word_14992C-Map_148EB8/* 121*/
		.word word_149946-Map_148EB8/* 122*/
		.word word_149960-Map_148EB8/* 123*/
		.word word_14997A-Map_148EB8/* 124*/
		.word word_149994-Map_148EB8/* 125*/
		.word word_1499AE-Map_148EB8/* 126*/
		.word word_1499C8-Map_148EB8/* 127*/
		.word word_1499E2-Map_148EB8/* 128*/
		.word word_1499F0-Map_148EB8/* 129*/
		.word word_149A0A-Map_148EB8/* 130*/
		.word word_149A24-Map_148EB8/* 131*/
		.word word_149A38-Map_148EB8/* 132*/
		.word word_149A4C-Map_148EB8/* 133*/
		.word word_149A66-Map_148EB8/* 134*/
		.word word_149A74-Map_148EB8/* 135*/
		.word word_149A82-Map_148EB8/* 136*/
		.word word_149A90-Map_148EB8/* 137*/
		.word word_149A98-Map_148EB8/* 138*/
		.word word_149AA0-Map_148EB8/* 139*/
		.word word_149AAE-Map_148EB8/* 140*/
		.word word_149ABC-Map_148EB8/* 141*/
		.word word_149ACA-Map_148EB8/* 142*/
		.word word_149ADE-Map_148EB8/* 143*/
		.word word_149AF2-Map_148EB8/* 144*/
		.word word_149B00-Map_148EB8/* 145*/
		.word word_149B0E-Map_148EB8/* 146*/
		.word word_149B1C-Map_148EB8/* 147*/
		.word word_149B24-Map_148EB8/* 148*/
		.word word_149B38-Map_148EB8/* 149*/
		.word word_149B4C-Map_148EB8/* 150*/
		.word word_149B54-Map_148EB8/* 151*/
		.word word_149B5C-Map_148EB8/* 152*/
		.word word_149B64-Map_148EB8/* 153*/
		.word word_149B6C-Map_148EB8/* 154*/
		.word word_149B80-Map_148EB8/* 155*/
		.word word_149B94-Map_148EB8/* 156*/
		.word word_149B9C-Map_148EB8/* 157*/
		.word word_149BAA-Map_148EB8/* 158*/
		.word word_149BBE-Map_148EB8/* 159*/
		.word word_149BD2-Map_148EB8/* 160*/
		.word word_149BE0-Map_148EB8/* 161*/
		.word word_149BEE-Map_148EB8/* 162*/
		.word word_149BFC-Map_148EB8/* 163*/
		.word word_149C0A-Map_148EB8/* 164*/
		.word word_149C18-Map_148EB8/* 165*/
		.word word_149C20-Map_148EB8/* 166*/
		.word word_149C3A-Map_148EB8/* 167*/
		.word word_149C48-Map_148EB8/* 168*/
		.word word_149C5C-Map_148EB8/* 169*/
		.word word_149C6A-Map_148EB8/* 170*/
		.word word_149C72-Map_148EB8/* 171*/
		.word word_149C7A-Map_148EB8/* 172*/
		.word word_149C82-Map_148EB8/* 173*/
		.word word_149C8A-Map_148EB8/* 174*/
		.word word_149C92-Map_148EB8/* 175*/
		.word word_149C9A-Map_148EB8/* 176*/
		.word word_149CA2-Map_148EB8/* 177*/
		.word word_149CAA-Map_148EB8/* 178*/
		.word word_149CB2-Map_148EB8/* 179*/
		.word word_149CBA-Map_148EB8/* 180*/
		.word word_149CC2-Map_148EB8/* 181*/
		.word word_149CD6-Map_148EB8/* 182*/
		.word word_149CE4-Map_148EB8/* 183*/
		.word word_149CEC-Map_148EB8/* 184*/
		.word word_149CFA-Map_148EB8/* 185*/
		.word word_149D0E-Map_148EB8/* 186*/
		.word word_149D22-Map_148EB8/* 187*/
		.word word_149D30-Map_148EB8/* 188*/
		.word word_149D44-Map_148EB8/* 189*/
		.word word_149D58-Map_148EB8/* 190*/
		.word word_149D6C-Map_148EB8/* 191*/
		.word word_149D7A-Map_148EB8/* 192*/
		.word word_149D94-Map_148EB8/* 193*/
		.word word_149DA2-Map_148EB8/* 194*/
		.word word_149DB6-Map_148EB8/* 195*/
		.word word_149DD0-Map_148EB8/* 196*/
		.word word_149DEA-Map_148EB8/* 197*/
		.word word_149E04-Map_148EB8/* 198*/
		.word word_149E1E-Map_148EB8/* 199*/
		.word word_149E38-Map_148EB8/* 200*/
		.word word_149E52-Map_148EB8/* 201*/
		.word word_149E6C-Map_148EB8/* 202*/
		.word word_149E86-Map_148EB8/* 203*/
		.word word_149E8E-Map_148EB8/* 204*/
		.word word_149E96-Map_148EB8/* 205*/
		.word word_149EAA-Map_148EB8/* 206*/
		.word word_149EBE-Map_148EB8/* 207*/
		.word word_149ECC-Map_148EB8/* 208*/
		.word word_149EDA-Map_148EB8/* 209*/
		.word word_149EDA-Map_148EB8/* 210*/
		.word word_149EDA-Map_148EB8/* 211*/
		.word word_149EDA-Map_148EB8/* 212*/
		.word word_149EDA-Map_148EB8/* 213*/
		.word word_149EDA-Map_148EB8/* 214*/
		.word word_149EDA-Map_148EB8/* 215*/
		.word word_149EDA-Map_148EB8/* 216*/
		.word word_149EDA-Map_148EB8/* 217*/
		.word word_149EDA-Map_148EB8/* 218*/
		.word word_149EDA-Map_148EB8/* 219*/
		.word word_149EDA-Map_148EB8/* 220*/
		.word word_149EDA-Map_148EB8/* 221*/
		.word word_149EDA-Map_148EB8/* 222*/
		.word word_149EDA-Map_148EB8/* 223*/
		.word word_149EEE-Map_148EB8/* 224*/
		.word word_149EFC-Map_148EB8/* 225*/
		.word word_149F10-Map_148EB8/* 226*/
		.word word_149F1E-Map_148EB8/* 227*/
		.word word_149F38-Map_148EB8/* 228*/
		.word word_149F52-Map_148EB8/* 229*/
		.word word_149F66-Map_148EB8/* 230*/
		.word word_149F74-Map_148EB8/* 231*/
		.word word_149F88-Map_148EB8/* 232*/
		.word word_149F96-Map_148EB8/* 233*/
		.word word_149FAA-Map_148EB8/* 234*/
		.word word_149FBE-Map_148EB8/* 235*/
		.word word_149FC6-Map_148EB8/* 236*/
		.word word_149FDA-Map_148EB8/* 237*/
		.word word_149FDA-Map_148EB8/* 238*/
		.word word_149FEE-Map_148EB8/* 239*/
		.word word_149FFC-Map_148EB8/* 240*/
		.word word_14A00A-Map_148EB8/* 241*/
		.word word_14A018-Map_148EB8/* 242*/
		.word word_14A020-Map_148EB8/* 243*/
		.word word_14A02E-Map_148EB8/* 244*/
		.word word_14A03C-Map_148EB8/* 245*/
		.word word_14A04A-Map_148EB8/* 246*/
		.word word_14A058-Map_148EB8/* 247*/
		.word word_14A066-Map_148EB8/* 248*/
		.word word_14A06E-Map_148EB8/* 249*/
		.word word_14A07C-Map_148EB8/* 250*/
word_1490AE:	.word 0			/* DATA XREF: ROM:00148EB8o*/
word_1490B0:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte	0,   9,	  0,   0, 0xFF, 0xE4
		.byte  0xEC,   4,	  0,   6, 0xFF, 0xF9
		.byte  0xF4,   9,	  0,   8, 0xFF, 0xF1
		.byte	4,  0xD,	  0,  0xE, 0xFF, 0xF1
word_1490CA:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte	0,   9,	  0,   0, 0xFF, 0xE2
		.byte  0xF0,  0xD,	  0,   6, 0xFF, 0xED
		.byte	0,   8,	  0,  0xE, 0xFF, 0xED
		.byte	8,  0xC,	  0, 0x11, 0xFF, 0xED
word_1490E4:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xFC,   9,	  0,   0, 0xFF, 0xE6
		.byte  0xF0,  0xA,	  0,   6, 0xFF, 0xFB
		.byte	8,   8,	  0,  0xF, 0xFF, 0xF3
word_1490F8:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xFE,   9,	  0,   0, 0xFF, 0xE4
		.byte  0xF0,  0xD,	  0,   6, 0xFF, 0xF0
		.byte	0,   8,	  0,  0xE, 0xFF, 0xF0
		.byte	8,  0xC,	  0, 0x11, 0xFF, 0xF0
word_149112:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte	0,   9,	  0,   0, 0xFF, 0xE4
		.byte  0xEC,   4,	  0,   6, 0xFF, 0xF8
		.byte  0xF4,   9,	  0,   8, 0xFF, 0xF0
		.byte	4,  0xD,	  0,  0xE, 0xFF, 0xF0
word_14912C:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte	0,   9,	  0,   0, 0xFF, 0xE4
		.byte  0xF0,  0xD,	  0,   6, 0xFF, 0xF0
		.byte	0,   8,	  0,  0xE, 0xFF, 0xF0
		.byte	8,  0xC,	  0, 0x11, 0xFF, 0xF0
word_149146:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xFE,   9,	  0,   0, 0xFF, 0xE4
		.byte  0xF0,  0xA,	  0,   6, 0xFF, 0xF8
		.byte	8,   8,	  0,  0xF, 0xFF, 0xF0
word_14915A:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xFE,   9,	  0,   0, 0xFF, 0xE4
		.byte  0xF0,  0xD,	  0,   6, 0xFF, 0xF0
		.byte	0,   8,	  0,  0xE, 0xFF, 0xF0
		.byte	8,  0xC,	  0, 0x11, 0xFF, 0xF0
word_149174:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xEE,   4,	  0,   0, 0xFF, 0xF2
		.byte  0xF6,  0xD,	  0,   2, 0xFF, 0xF2
		.byte	6,   8,	  0,  0xA, 0xFF, 0xFA
		.byte   0xE,   8,	  0,  0xD, 0xFF, 0xF2
word_14918E:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,  0xB,	  0,   0, 0xFF, 0xF1
		.byte  0xF8,   6,	  0,  0xC,   0,	 9
		.byte  0x10,   8,	  0, 0x12, 0xFF, 0xF1
word_1491A2:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xEA,   4,	  0,   0, 0xFF, 0xF8
		.byte  0xF2,  0xD,	  0,   2, 0xFF, 0xF0
		.byte	2,   8,	  0,  0xA, 0xFF, 0xF8
		.byte   0xA,  0xD,	  0,  0xD, 0xFF, 0xF0
word_1491BC:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xEF,   4,	  0,   0, 0xFF, 0xF6
		.byte  0xF7,  0xF,	  0,   2, 0xFF, 0xEE
		.byte  0xFF,   0,	  0, 0x12,   0,	0xE
word_1491D0:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xED,   8,	  0,   0, 0xFF, 0xF2
		.byte  0xF5,  0xD,	  0,   3, 0xFF, 0xF2
		.byte	5,   9,	  0,  0xB, 0xFF, 0xF2
word_1491E4:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF2,   4,	  0,   0, 0xFF, 0xF7
		.byte  0xFA,  0xB,	  0,   2, 0xFF, 0xEF
		.byte	2,   5,	  0,  0xE,   0,	 7
word_1491F8:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,   4,	  0,   0, 0xFF, 0xF7
		.byte  0xF8,   8,	  0,   2, 0xFF, 0xEF
		.byte	0,  0xE,	  0,   5, 0xFF, 0xEF
word_14920C:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xEC,   0,	  0,   0, 0xFF, 0xFC
		.byte  0xF4,   9,	  0,   1, 0xFF, 0xF4
		.byte	4,  0xC,	  0,   7, 0xFF, 0xF4
		.byte   0xC,  0xC,	  0,  0xB, 0xFF, 0xEC
word_149226:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte	6,   6,	  0,   0, 0xFF, 0xFC
		.byte  0xEE,   4,	  0,   6,   0,	 0
		.byte  0xF6,  0xE,	  0,   8, 0xFF, 0xF0
word_14923A:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte	4,   6,	  0,   0, 0xFF, 0xFC
		.byte  0xF2,  0xE,	  0,   6, 0xFF, 0xF0
		.byte   0xA,   0,	  0, 0x12,   0,	 8
word_14924E:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte	4,   6,	  0,   0, 0xFF, 0xFC
		.byte  0xF2,   8,	  0,   6, 0xFF, 0xF0
		.byte  0xFA,  0xD,	  0,   9, 0xFF, 0xF0
word_149262:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte	6,   6,	  0,   0, 0xFF, 0xFC
		.byte  0xF4,  0xE,	  0,   6, 0xFF, 0xF0
word_149270:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte	4,   6,	  0,   0, 0xFF, 0xFC
		.byte  0xED,   4,	  0,   6,   0,	 0
		.byte  0xF5,  0xE,	  0,   8, 0xFF, 0xF0
word_149284:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte	6,   6,	  0,   0, 0xFF, 0xFC
		.byte  0xF4,  0xE,	  0,   6, 0xFF, 0xF0
word_149292:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte	4,   6,	  0,   0, 0xFF, 0xFC
		.byte  0xF1,   8,	  0,   6, 0xFF, 0xF0
		.byte  0xF9,  0xD,	  0,   9, 0xFF, 0xF0
word_1492A6:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte	2,   6,	  0,   0, 0xFF, 0xFC
		.byte  0xF4,  0xE,	  0,   6, 0xFF, 0xF0
word_1492B4:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xEF,   8,	  0,   0, 0xFF, 0xF5
		.byte  0xF7,  0xE,	  0,   3, 0xFF, 0xF5
		.byte  0xFF,   1,	  0,  0xF, 0xFF, 0xED
word_1492C8:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xE8,   4,	  0,   0, 0xFF, 0xF8
		.byte  0xF0,   8,	  0,   2, 0xFF, 0xF8
		.byte  0xF8,  0xE,	  0,   5, 0xFF, 0xF0
		.byte  0xF8,   2,	  0, 0x11,   0, 0x10
word_1492E2:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,  0xC,	  0,   0, 0xFF, 0xF1
		.byte  0xF8,  0xC,	  0,   4, 0xFF, 0xE9
		.byte	0,   9,	  0,   8, 0xFF, 0xF1
		.byte  0xF8,   6,	  0,  0xE,   0,	 9
word_1492FC:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xEA,   0,	  0,   0, 0xFF, 0xFE
		.byte  0xF2,  0xF,	  0,   1, 0xFF, 0xF6
		.byte  0xFA,   1,	  0, 0x11, 0xFF, 0xEE
word_149310:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xEF,   4,	  0,   0, 0xFF, 0xF7
		.byte  0xF7,  0xE,	  0,   2, 0xFF, 0xEF
		.byte  0xF7,   2,	  0,  0xE,   0,	0xF
word_149324:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xE9,   0,	  0,   0,   0,	 0
		.byte  0xF1,   4,	  0,   1,   0,	 0
		.byte  0xF9,  0xE,	  0,   3, 0xFF, 0xF8
		.byte  0xF9,   1,	  0,  0xF, 0xFF, 0xF0
word_14933E:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF1,   8,	  0,   0,   0,	 0
		.byte  0xF9,  0xE,	  0,   3, 0xFF, 0xF8
		.byte  0xF9,   1,	  0,  0xF, 0xFF, 0xF0
word_149352:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xEC,   0,	  0,   0,   0,	 4
		.byte  0xF4,  0xE,	  0,   1, 0xFF, 0xF4
		.byte  0xFC,   0,	  0,  0xD, 0xFF, 0xEC
		.byte   0xC,   0,	  0,  0xE,   0,	0xC
word_14936C:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,   7,	  0,   0, 0xFF, 0xEA
		.byte  0xF0,   9,	  0,   8, 0xFF, 0xF8
		.byte	0,  0xC,	  0,  0xE, 0xFF, 0xF0
		.byte	8,   4,	  0, 0x12, 0xFF, 0xF0
word_149386:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xFC,   4,	  0,   0, 0xFF, 0xEA
		.byte  0xF0,   9,	  0,   2, 0xFF, 0xF8
		.byte	0,  0xC,	  0,   8, 0xFF, 0xF0
		.byte	8,   4,	  0,  0xC, 0xFF, 0xF0
word_1493A0:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF8,   5,	  0,   0, 0xFF, 0xEA
		.byte  0xF0,   9,	  0,   4, 0xFF, 0xF8
		.byte	0,  0xC,	  0,  0xA, 0xFF, 0xF0
		.byte	8,   4,	  0,  0xE, 0xFF, 0xF0
word_1493BA:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,   7,	  0,   0, 0xFF, 0xEA
		.byte  0xF0,   9,	  0,   8, 0xFF, 0xF8
		.byte	0,  0xC,	  0,  0xE, 0xFF, 0xF0
		.byte	8,   4,	  0, 0x12, 0xFF, 0xF0
word_1493D4:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xFC,  0xB,	  0,   0, 0xFF, 0xE8
		.byte  0xEC,   4,	  0,  0xC, 0xFF, 0xF8
		.byte  0xF4,   9,	  0,  0xE, 0xFF, 0xF0
		.byte	4,   5,	  0, 0x14, 0xFF, 0xF8
word_1493EE:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte	0,   9,	  0,   0, 0xFF, 0xE4
		.byte  0xED,   4,	  0,   6, 0xFF, 0xF8
		.byte  0xF5,   9,	  0,   8, 0xFF, 0xF0
		.byte	5,   5,	  0,  0xE, 0xFF, 0xF8
word_149408:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte	0,   5,	  0,   0, 0xFF, 0xF0
		.byte  0xEC,   4,	  0,   4, 0xFF, 0xF8
		.byte  0xF4,   9,	  0,   6, 0xFF, 0xF0
		.byte	4,   5,	  0,  0xC, 0xFF, 0xF8
word_149422:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte	0,   6,	  0,   0, 0xFF, 0xEF
		.byte  0xED,   4,	  0,   6, 0xFF, 0xF8
		.byte  0xF5,   9,	  0,   8, 0xFF, 0xF0
		.byte	5,   5,	  0,  0xE, 0xFF, 0xF8
word_14943C:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte	6,  0xD,	  0,   0, 0xFF, 0xF0
		.byte  0xF0,   9,	  0,   8, 0xFF, 0xF0
		.byte	0,  0xC,	  0,  0xE, 0xFF, 0xF0
		.byte	8,   4,	  0, 0x12,   0,	 0
word_149456:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte	6,   1,	  0,   0, 0xFF, 0xFC
		.byte  0xF0,   9,	  0,   2, 0xFF, 0xF0
		.byte	0,  0xC,	  0,   8, 0xFF, 0xF0
		.byte	8,   4,	  0,  0xC,   0,	 0
word_149470:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte	6,   5,	  0,   0, 0xFF, 0xF8
		.byte  0xF0,   9,	  0,   4, 0xFF, 0xF0
		.byte	0,  0xC,	  0,  0xA, 0xFF, 0xF0
		.byte	8,   4,	  0,  0xE,   0,	 0
word_14948A:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte	6,  0xD,	  0,   0, 0xFF, 0xF0
		.byte  0xF0,   9,	  0,   8, 0xFF, 0xF0
		.byte	0,  0xC,	  0,  0xE, 0xFF, 0xF0
		.byte	8,   4,	  0, 0x12,   0,	 0
word_1494A4:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xFC,  0xE,	  0,   0, 0xFF, 0xF7
		.byte  0xF8,  0xD,	  0,  0xC, 0xFF, 0xEC
		.byte  0xF8,   1,	  0, 0x14,   0,	0xC
		.byte	8,   4,	  0, 0x16, 0xFF, 0xF4
word_1494BE:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xFE,   6,	  0,   0, 0xFF, 0xFC
		.byte  0xF8,  0xD,	  0,   6, 0xFF, 0xEB
		.byte  0xF8,   1,	  0,  0xE,   0,	0xB
		.byte	8,   4,	  0, 0x10, 0xFF, 0xF3
word_1494D8:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xFD,   5,	  0,   0, 0xFF, 0xFB
		.byte  0xF8,  0xD,	  0,   4, 0xFF, 0xEC
		.byte  0xF8,   1,	  0,  0xC,   0,	0xC
		.byte	8,   4,	  0,  0xE, 0xFF, 0xF4
word_1494F2:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xFC,   9,	  0,   0, 0xFF, 0xFA
		.byte  0xF8,  0xD,	  0,   6, 0xFF, 0xEB
		.byte  0xF8,   1,	  0,  0xE,   0,	0xB
		.byte	8,   4,	  0, 0x10, 0xFF, 0xF3
word_14950C:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,  0xB,	  0,   0, 0xFF, 0xF1
word_149514:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xEC,  0xB,	  0,   0, 0xFF, 0xF1
		.byte   0xC,   4,	  0,  0xC, 0xFF, 0xF1
word_149522:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xED,  0xB,	  0,   0, 0xFF, 0xF3
word_14952A:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF8,  0xA,	  0,   0, 0xFF, 0xF3
word_149532:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF3,  0xA,	  0,   0, 0xFF, 0xF3
		.byte   0xB,   0,	  0,   9,   0,	 3
word_149540:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xEF,   4,	  0,   0, 0xFF, 0xF2
		.byte  0xF7,  0xA,	  0,   2, 0xFF, 0xF2
word_14954E:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF2,   4,	  0,   0, 0xFF, 0xF2
		.byte  0xFA,  0xA,	  0,   2, 0xFF, 0xF2
word_14955C:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,   4,	  0,   0, 0xFF, 0xF4
		.byte  0xF8,  0xA,	  0,   2, 0xFF, 0xF4
word_14956A:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xEE,   4,	  0,   0, 0xFF, 0xF4
		.byte  0xF6,  0xA,	  0,   2, 0xFF, 0xF4
word_149578:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF4,   9,	  0,   0, 0xFF, 0xF1
		.byte	4,   4,	  0,   6, 0xFF, 0xF9
word_149586:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF4,  0xA,	  0,   0, 0xFF, 0xF1
		.byte   0xC,   0,	  0,   9, 0xFF, 0xF1
word_149594:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF1,   9,	  0,   0, 0xFF, 0xF4
		.byte	1,   5,	  0,   6, 0xFF, 0xF4
word_1495A2:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF1,  0xA,	  0,   0, 0xFF, 0xF2
		.byte	9,   4,	  0,   9, 0xFF, 0xFA
word_1495B0:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xED,   0,	  0,   0,   0,	 1
		.byte  0xF5,  0xA,	  0,   1, 0xFF, 0xF1
word_1495BE:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF3,  0xA,	  0,   0, 0xFF, 0xF3
word_1495C6:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xEE,   4,	  0,   0, 0xFF, 0xF2
		.byte  0xF6,   9,	  0,   2, 0xFF, 0xF2
		.byte	6,   4,	  0,   8, 0xFF, 0xFA
word_1495DA:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,  0xB,	  0,   0, 0xFF, 0xF1
word_1495E2:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF1,  0xB,	  0,   0, 0xFF, 0xF0
word_1495EA:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,   8,	  0,   0, 0xFF, 0xF4
		.byte  0xF8,   4,	  0,   3, 0xFF, 0xF4
		.byte	0,   9,	  0,   5, 0xFF, 0xF4
word_1495FE:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xEC,   0,	  0,   0, 0xFF, 0xF9
		.byte  0xF4,  0xA,	  0,   1, 0xFF, 0xF1
word_14960C:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF4,   9,	  0,   0, 0xFF, 0xF1
		.byte	4,   0,	  0,   6, 0xFF, 0xF1
word_14961A:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF2,   4,	  0,   0, 0xFF, 0xF7
		.byte  0xFA,   9,	  0,   2, 0xFF, 0xEF
word_149628:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xED,   4,	  0,   0, 0xFF, 0xF5
		.byte  0xF5,   9,	  0,   2, 0xFF, 0xF5
		.byte	5,   4,	  0,   8, 0xFF, 0xF5
word_14963C:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xEF,  0xA,	  0,   0, 0xFF, 0xF1
		.byte	7,   4,	  0,   9, 0xFF, 0xF9
word_14964A:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF2,   8,	  0,   0, 0xFF, 0xF5
		.byte  0xFA,  0xD,	  0,   3, 0xFF, 0xED
		.byte  0xFA,   0,	  0,  0xB,   0,	0xD
word_14965E:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF2,   8,	  0,   0, 0xFF, 0xF8
		.byte  0xFA,  0xD,	  0,   3, 0xFF, 0xF0
word_14966C:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF2,   4,	  0,   0, 0xFF, 0xF7
		.byte  0xFA,   8,	  0,   2, 0xFF, 0xF7
		.byte	2,  0xC,	  0,   5, 0xFF, 0xEF
word_149680:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,   4,	  0,   0, 0xFF, 0xFC
		.byte  0xF8,  0xA,	  0,   2, 0xFF, 0xF4
word_14968E:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,   4,	  0,   0, 0xFF, 0xFC
		.byte  0xF8,   9,	  0,   2, 0xFF, 0xF4
		.byte	8,   4,	  0,   8, 0xFF, 0xF4
word_1496A2:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xEA,   0,	  0,   0,   0,	 0
		.byte  0xF2,   4,	  0,   1,   0,	 0
		.byte  0xFA,  0xC,	  0,   3, 0xFF, 0xF0
		.byte	2,   9,	  0,   7, 0xFF, 0xF0
word_1496BC:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xED,   4,	  0,   0,   0,	 0
		.byte  0xF5,  0xC,	  0,   2, 0xFF, 0xF0
		.byte  0xFD,   9,	  0,   6, 0xFF, 0xF0
		.byte   0xD,   4,	  0,  0xC, 0xFF, 0xF8
word_1496D6:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xEB,   4,	  0,   0, 0xFF, 0xF9
		.byte  0xF3,  0xC,	  0,   2, 0xFF, 0xF1
		.byte  0xFB,   9,	  0,   6, 0xFF, 0xF1
		.byte   0xB,   0,	  0,  0xC, 0xFF, 0xF9
word_1496F0:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xEF,   4,	  0,   0, 0xFF, 0xFA
		.byte  0xF7,   9,	  0,   2, 0xFF, 0xF2
		.byte	7,   4,	  0,   8, 0xFF, 0xFA
word_149704:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF4,   4,	  0,   0, 0xFF, 0xF8
		.byte  0xFC,  0xC,	  0,   2, 0xFF, 0xF0
		.byte	4,   4,	  0,   6, 0xFF, 0xF8
word_149718:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF4,  0xD,	  0,   0, 0xFF, 0xF0
		.byte	4,   8,	  0,   8, 0xFF, 0xF0
word_149726:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF3,   8,	  0,   0, 0xFF, 0xF6
		.byte  0xFB,  0xD,	  0,   3, 0xFF, 0xEE
word_149734:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,   8,	  0,   0, 0xFF, 0xF8
		.byte  0xF8,  0xC,	  0,   3, 0xFF, 0xF0
		.byte	0,   9,	  0,   7, 0xFF, 0xF0
word_149748:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,  0xB,	  0,   0, 0xFF, 0xF3
word_149750:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,   8,	  0,   0, 0xFF, 0xF7
		.byte  0xF8,   5,	  0,   3, 0xFF, 0xF7
		.byte	8,   8,	  0,   7, 0xFF, 0xF7
word_149764:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,  0xB,	  0,   0, 0xFF, 0xF3
word_14976C:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,  0xB,	  0,   0, 0xFF, 0xF3
word_149774:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,   4,	  0,   0, 0xFF, 0xF7
		.byte  0xF8,   9,	  0,   2, 0xFF, 0xF7
		.byte	8,   4,	  0,   8, 0xFF, 0xF7
word_149788:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,  0xB,	  0,   0, 0xFF, 0xF4
word_149790:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF4,   8,	  0,   0, 0xFF, 0xF0
		.byte  0xF4,   4,	  0,   3,   0, 0x10
		.byte  0xFC,  0xD,	  0,   5, 0xFF, 0xF0
		.byte  0xFC,   5,	  0,  0xD,   0, 0x10
word_1497AA:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF4,  0xE,	  0,   0, 0xFF, 0xFD
word_1497B2:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF4,  0xE,	  0,   0, 0xFF, 0xF1
		.byte  0xF4,   0,	  0,  0xC, 0xFF, 0xE9
		.byte	4,   0,	  0,  0xD, 0xFF, 0xE9
word_1497C6:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF4,  0xE,	  0,   0, 0xFF, 0xF1
		.byte  0xF4,   6,	  0,  0xC, 0xFF, 0xE1
word_1497D4:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF4,  0xE,	  0,   0, 0xFF, 0xF4
word_1497DC:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF4,  0xE,	  0,   0, 0xFF, 0xE6
word_1497E4:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF4,   8,	  0,   0, 0xFF, 0xF4
		.byte  0xFC,  0xD,	  0,   3, 0xFF, 0xEC
		.byte  0xFC,   1,	  0,  0xB,   0,	0xC
word_1497F8:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xE8,  0xA,	  0,   0, 0xFF, 0xF5
		.byte	0,   4,	  0,   9, 0xFF, 0xF5
		.byte	8,   8,	  0,  0xB, 0xFF, 0xF5
		.byte  0x10,   8,	  0,  0xE, 0xFF, 0xF5
word_149812:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF1,  0xB,	  0,   0, 0xFF, 0xF4
word_14981A:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xE9,  0xB,	  0,   0, 0xFF, 0xF4
		.byte	9,   8,	  0,  0xC, 0xFF, 0xF4
word_149828:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xE7,  0xB,	  0,   0, 0xFF, 0xF4
		.byte	7,   9,	  0,  0xC, 0xFF, 0xF4
word_149836:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,  0xB,	  0,   0, 0xFF, 0xF4
word_14983E:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,  0xB,	  0,   0, 0xFF, 0xF4
word_149846:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xEF,   8,	  0,   0, 0xFF, 0xF7
		.byte  0xF7,  0xE,	  0,   3, 0xFF, 0xEF
		.byte	7,   0,	  0,  0xF,   0,	0xF
word_14985A:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xEE,   4,	  0,   0, 0xFF, 0xF7
		.byte  0xF6,  0xD,	  0,   2, 0xFF, 0xEF
		.byte	6,   8,	  0,  0xA, 0xFF, 0xF7
word_14986E:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xEE,   4,	  0,   0, 0xFF, 0xF3
		.byte  0xF6,  0xA,	  0,   2, 0xFF, 0xF3
word_14987C:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF1,   8,	  0,   0, 0xFF, 0xEE
		.byte  0xF9,  0xD,	  0,   3, 0xFF, 0xEE
word_14988A:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF3,   8,	  0,   0, 0xFF, 0xEF
		.byte  0xFB,  0xD,	  0,   3, 0xFF, 0xEF
word_149898:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF8,  0xD,	  0,   0, 0xFF, 0xF1
		.byte	8,   8,	  0,   8, 0xFF, 0xF9
word_1498A6:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF6,   9,	  0,   0, 0xFF, 0xF4
		.byte	6,   4,	  0,   6, 0xFF, 0xFC
word_1498B4:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF6,   9,	  0,   0, 0xFF, 0xF4
		.byte	6,  0xC,	  0,   6, 0xFF, 0xEC
word_1498C2:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF7,  0xD,	  0,   0, 0xFF, 0xEF
		.byte	7,   8,	  0,   8, 0xFF, 0xEF
word_1498D0:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF6,  0xE,	  0,   0, 0xFF, 0xEF
word_1498D8:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF6,  0xE,	  0,   0, 0xFF, 0xF7
		.byte  0xFE,   1,	  0,  0xC, 0xFF, 0xEF
word_1498E6:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF5,  0xE,	  0,   0, 0xFF, 0xF2
word_1498EE:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF7,  0xA,	  0,   0, 0xFF, 0xF2
word_1498F6:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF4,   8,	  0,   0, 0xFF, 0xF2
		.byte  0xFC,  0xD,	  0,   3, 0xFF, 0xF2
word_149904:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF3,   8,	  0,   0, 0xFF, 0xF0
		.byte  0xFB,  0xD,	  0,   3, 0xFF, 0xF0
word_149912:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xE6,  0xC,	  0,   0, 0xFF, 0xF2
		.byte  0xEE,   9,	  0,   4, 0xFF, 0xF2
		.byte  0xFE,  0xC,	  0,  0xA, 0xFF, 0xF2
		.byte	6,   8,	  0,  0xE, 0xFF, 0xFA
word_14992C:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xE2,   4,	  0,   0, 0xFF, 0xEE
		.byte  0xEA,   9,	  0,   2, 0xFF, 0xE6
		.byte  0xF2,   1,	  0,   8,   0,	 6
		.byte  0xFA,   9,	  0,  0xA, 0xFF, 0xEE
word_149946:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xEE,   0,	  0,   0, 0xFF, 0xE4
		.byte  0xEE,   6,	  0,   1, 0xFF, 0xFC
		.byte  0xF6,   9,	  0,   7, 0xFF, 0xE4
		.byte	6,  0xC,	  0,  0xD, 0xFF, 0xE4
word_149960:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF4,   4,	  0,   0, 0xFF, 0xF1
		.byte  0xFC,   6,	  0,   2, 0xFF, 0xF9
		.byte	4,   9,	  0,   8, 0xFF, 0xE1
		.byte  0x14,   4,	  0,  0xE, 0xFF, 0xE9
word_14997A:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte  0x14,  0xC,	0x18,   0, 0xFF, 0xEE
		.byte	4,   9,	0x18,   4, 0xFF, 0xF6
		.byte  0xFC,  0xC,	0x18,  0xA, 0xFF, 0xEE
		.byte  0xF4,   8,	0x18,  0xE, 0xFF, 0xEE
word_149994:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte  0x16,   4,	0x18,   0,   0,	 3
		.byte	6,   9,	0x18,   2,   0,	 3
		.byte  0xFE,   1,	0x18,   8, 0xFF, 0xF3
		.byte  0xF6,   9,	0x18,  0xA, 0xFF, 0xFB
word_1499AE:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte   0xA,   0,	0x18,   0,   0, 0x15
		.byte  0xFA,   6,	0x18,   1, 0xFF, 0xF5
		.byte  0xFA,   9,	  0,   7,   0,	 5
		.byte  0xF2,  0xC,	0x18,  0xD, 0xFF, 0xFD
word_1499C8:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte	5,   4,	0x18,   0,   0,	 1
		.byte  0xED,   6,	0x18,   2, 0xFF, 0xF9
		.byte  0xED,   9,	0x18,   8,   0,	 9
		.byte  0xE5,   4,	0x18,  0xE,   0,	 9
word_1499E2:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xE8,  0xD,	  0,   0, 0xFF, 0xEF
		.byte  0xF8,  0xA,	  0,   8, 0xFF, 0xEF
word_1499F0:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xE9,  0xC,	  0,   0, 0xFF, 0xEE
		.byte  0xF1,   8,	  0,   4, 0xFF, 0xEE
		.byte  0xF9,  0xE,	  0,   7, 0xFF, 0xE6
		.byte  0x11,   4,	  0, 0x13, 0xFF, 0xEE
word_149A0A:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xE9,  0xA,	  0,   0, 0xFF, 0xF6
		.byte  0xF9,   4,	  0,   9, 0xFF, 0xE6
		.byte	1,  0xC,	  0,  0xB, 0xFF, 0xE6
		.byte	9,   5,	  0,  0xF, 0xFF, 0xF6
word_149A24:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xE8,  0xF,	  0,   0, 0xFF, 0xEC
		.byte  0xE8,   0,	  0, 0x10,   0,	0xC
		.byte	8,   8,	  0, 0x11, 0xFF, 0xF4
word_149A38:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xE9,   9,	  0,   0, 0xFF, 0xF6
		.byte  0xF9,  0xD,	  0,   6, 0xFF, 0xE6
		.byte	9,   5,	  0,  0xE, 0xFF, 0xF6
word_149A4C:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xE9,   9,	  0,   0, 0xFF, 0xF5
		.byte  0xF9,  0xC,	  0,   6, 0xFF, 0xED
		.byte	1,   8,	  0,  0xA, 0xFF, 0xED
		.byte	9,   5,	  0,  0xD, 0xFF, 0xF5
word_149A66:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF8,  0xC,	  0,   0, 0xFF, 0xF8
		.byte	0,   9,	  0,   4, 0xFF, 0xF8
word_149A74:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF8,  0xD,	  0,   0, 0xFF, 0xF8
		.byte	8,   8,	  0,   8, 0xFF, 0xF8
word_149A82:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF8,  0xC,	  0,   0, 0xFF, 0xF8
		.byte	0,   9,	  0,   4, 0xFF, 0xF8
word_149A90:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xF0
word_149A98:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xF0
word_149AA0:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xE9,   5,	  0,   0, 0xFF, 0xF9
		.byte  0xF9,  0xB,	  0,   4, 0xFF, 0xF1
word_149AAE:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xE9,   5,	  0,   0, 0xFF, 0xF9
		.byte  0xF9,  0xB,	  0,   4, 0xFF, 0xF1
word_149ABC:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xEE,   4,	  0,   0, 0xFF, 0xF6
		.byte  0xF6,  0xE,	  0,   2, 0xFF, 0xEE
word_149ACA:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,   9,	  0,   0, 0xFF, 0xF0
		.byte	0,  0xC,	  0,   6, 0xFF, 0xF0
		.byte	8,   8,	  0,  0xA, 0xFF, 0xF8
word_149ADE:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,   9,	  0,   0, 0xFF, 0xF0
		.byte	0,  0xC,	  0,   6, 0xFF, 0xF0
		.byte	8,   8,	  0,  0xA, 0xFF, 0xF8
word_149AF2:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xE9,  0xB,	  0,   0, 0xFF, 0xF5
		.byte	7,   4,	  0,  0xC, 0xFF, 0xFD
word_149B00:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xE9,   9,	  0,   0, 0xFF, 0xF5
		.byte  0xF9,  0xD,	  0,   6, 0xFF, 0xF5
word_149B0E:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xE9,   9,	  0,   0, 0xFF, 0xF5
		.byte  0xF9,  0xD,	  0,   6, 0xFF, 0xF5
word_149B1C:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xE9,  0xA,	  0,   0, 0xFF, 0xF5
word_149B24:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xE9,  0xD,	  0,   0, 0xFF, 0xF1
		.byte  0xEC,  0xB,	  0,   8, 0xFF, 0xF4
		.byte   0xC,   8,	  0, 0x14, 0xFF, 0xF4
word_149B38:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xE8,   9,	  0,   0, 0xFF, 0xF5
		.byte  0xEC,  0xB,	  0,   6, 0xFF, 0xF4
		.byte   0xC,   8,	  0, 0x12, 0xFF, 0xF4
word_149B4C:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xF0
word_149B54:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xF0
word_149B5C:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xF0
word_149B64:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF8,  0xA,	  0,   0, 0xFF, 0xFA
word_149B6C:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,   8,	  0,   0, 0xFF, 0xF2
		.byte  0xF8,  0xD,	  0,   3, 0xFF, 0xEA
		.byte	8,   4,	  0,  0xB, 0xFF, 0xF2
word_149B80:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,   9,	  0,   0, 0xFF, 0xF1
		.byte	0,  0xC,	  0,   6, 0xFF, 0xE9
		.byte	8,   8,	  0,  0xA, 0xFF, 0xE9
word_149B94:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xF1
word_149B9C:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xEE,   7,	  0,   0, 0xFF, 0xE6
		.byte  0xF6,  0xA,	  0,   8, 0xFF, 0xF6
word_149BAA:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xEE,   4,	  0,   0, 0xFF, 0xEE
		.byte  0xF6,  0xE,	  0,   2, 0xFF, 0xE6
		.byte  0xF6,   2,	  0,  0xE,   0,	 6
word_149BBE:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF1,   8,	  0,   0, 0xFF, 0xF6
		.byte  0xF9,  0xD,	  0,   3, 0xFF, 0xEE
		.byte	9,   8,	  0,  0xB, 0xFF, 0xEE
word_149BD2:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xED,   8,	  0,   0, 0xFF, 0xF3
		.byte  0xF5,  0xE,	  0,   3, 0xFF, 0xEB
word_149BE0:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xED,   8,	  0,   0, 0xFF, 0xF3
		.byte  0xF5,  0xE,	  0,   3, 0xFF, 0xEB
word_149BEE:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xED,   8,	  0,   0, 0xFF, 0xF3
		.byte  0xF5,  0xE,	  0,   3, 0xFF, 0xEB
word_149BFC:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xED,   8,	  0,   0, 0xFF, 0xF3
		.byte  0xF5,  0xE,	  0,   3, 0xFF, 0xEB
word_149C0A:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xED,   8,	  0,   0, 0xFF, 0xF3
		.byte  0xF5,  0xE,	  0,   3, 0xFF, 0xEB
word_149C18:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,  0xB,	  0,   0, 0xFF, 0xF4
word_149C20:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xE8,   0,	  0,   0, 0xFF, 0xFE
		.byte  0xF0,  0xD,	  0,   1, 0xFF, 0xEE
		.byte	0,  0xD,	  0,   9, 0xFF, 0xE6
		.byte	8,   0,	  0, 0x11,   0,	 6
word_149C3A:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xED,  0xD,	  0,   0, 0xFF, 0xF2
		.byte  0xFD,  0xA,	  0,   8, 0xFF, 0xF2
word_149C48:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xED,   8,	  0,   0, 0xFF, 0xF2
		.byte  0xF5,  0xD,	  0,   3, 0xFF, 0xF2
		.byte	5,   9,	  0,  0xB, 0xFF, 0xF2
word_149C5C:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,  0xA,	  0,   0, 0xFF, 0xF6
		.byte	8,  0xC,	  0,   9, 0xFF, 0xEE
word_149C6A:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,  0xB,	  0,   0, 0xFF, 0xF6
word_149C72:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,  0xB,	  0,   0, 0xFF, 0xF6
word_149C7A:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,  0xB,	  0,   0, 0xFF, 0xF6
word_149C82:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,  0xB,	  0,   0, 0xFF, 0xF4
word_149C8A:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,  0xB,	  0,   0, 0xFF, 0xF4
word_149C92:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,  0xB,	  0,   0, 0xFF, 0xF4
word_149C9A:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,  0xB,	  0,   0, 0xFF, 0xF4
word_149CA2:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,  0xB,	  0,   0, 0xFF, 0xF4
word_149CAA:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,  0xB,	  0,   0, 0xFF, 0xF4
word_149CB2:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,  0xB,	  0,   0, 0xFF, 0xF4
word_149CBA:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,  0xB,	  0,   0, 0xFF, 0xF4
word_149CC2:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,   0,	  0,   0,   0,	 0
		.byte  0xF8,  0xD,	  0,   1, 0xFF, 0xE8
		.byte  0xF8,   5,	  0,   9,   0,	 8
word_149CD6:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,  0xA,	  0,   0, 0xFF, 0xFC
		.byte  0xF8,   5,	  0,   9, 0xFF, 0xEC
word_149CE4:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,  0xE,	  0,   0, 0xFF, 0xF0
word_149CEC:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,  0xA,	  8,   0, 0xFF, 0xEC
		.byte  0xF8,   5,	  8,   9,   0,	 4
word_149CFA:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,   0,	  8,   0, 0xFF, 0xF8
		.byte  0xF8,  0xD,	  8,   1, 0xFF, 0xF8
		.byte  0xF8,   5,	  8,   9, 0xFF, 0xE8
word_149D0E:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,   4,	  0,   0, 0xFF, 0xF4
		.byte  0xF8,  0xD,	  0,   2, 0xFF, 0xEC
		.byte  0xF8,   1,	  0,  0xA,   0,	0xC
word_149D22:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,   9,	  0,   0, 0xFF, 0xF0
		.byte	0,  0xC,	  0,   6, 0xFF, 0xF0
word_149D30:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,   4,	  8,   0, 0xFF, 0xFC
		.byte  0xF8,  0xD,	  8,   2, 0xFF, 0xF4
		.byte  0xF8,   1,	  8,  0xA, 0xFF, 0xEC
word_149D44:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF2,   1,	  0,   0, 0xFF, 0xEA
		.byte  0xF2,  0xE,	  0,   2, 0xFF, 0xF2
		.byte   0xA,   8,	  0,  0xE, 0xFF, 0xF2
word_149D58:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF2,  0xE,	  0,   0, 0xFF, 0xF4
		.byte  0xF2,   1,	  0,  0xC, 0xFF, 0xEC
		.byte   0xA,   8,	  0,  0xE, 0xFF, 0xF4
word_149D6C:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF2,  0xF,	  0,   0, 0xFF, 0xEE
		.byte	2,   0,	  0, 0x10,   0,	0xE
word_149D7A:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF2,  0xD,	  0,   0, 0xFF, 0xF2
		.byte  0xF2,   0,	  0,   8, 0xFF, 0xEA
		.byte	2,  0xD,	  0,   9, 0xFF, 0xEA
		.byte	2,   0,	  0, 0x11,   0,	0xA
word_149D94:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF2,  0xF,	  0,   0, 0xFF, 0xED
		.byte  0xF2,   1,	  0, 0x10,   0,	0xD
word_149DA2:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF5,  0xE,	  0,   0, 0xFF, 0xF3
		.byte  0xF5,   2,	  0,  0xC, 0xFF, 0xEB
		.byte  0xED,   4,	  0,  0xF, 0xFF, 0xEB
word_149DB6:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,   9,	  0,   8, 0xFF, 0xF8
		.byte	0,  0xC,	  0,  0xE, 0xFF, 0xF0
		.byte	8,   4,	  0, 0x12, 0xFF, 0xF0
		.byte  0xF0,   7,	  0,   0, 0xFF, 0xEB
word_149DD0:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,   9,	  0,   8, 0xFF, 0xF8
		.byte	0,  0xC,	  0,  0xE, 0xFF, 0xF0
		.byte	8,   4,	  0, 0x12, 0xFF, 0xF0
		.byte  0xF0,   7,	  8,   0, 0xFF, 0xEB
word_149DEA:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xEC,   4,	  0,   9, 0xFF, 0xF8
		.byte  0xF4,   9,	  0,  0xB, 0xFF, 0xF0
		.byte	4,   5,	  0, 0x11, 0xFF, 0xF8
		.byte  0xF8,  0xA,	  0,   0, 0xFF, 0xE9
word_149E04:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xEC,   4,	  0,   9, 0xFF, 0xF8
		.byte  0xF4,   9,	  0,  0xB, 0xFF, 0xF0
		.byte	4,   5,	  0, 0x11, 0xFF, 0xF8
		.byte  0xF8,  0xA,	  0,   0, 0xFF, 0xE9
word_149E1E:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,   9,	  0,   8, 0xFF, 0xF0
		.byte	0,  0xC,	  0,  0xE, 0xFF, 0xF0
		.byte	8,   4,	  0, 0x12,   0,	 0
		.byte	5,  0xD,	  0,   0, 0xFF, 0xF0
word_149E38:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,   9,	  0,   8, 0xFF, 0xF0
		.byte	0,  0xC,	  0,  0xE, 0xFF, 0xF0
		.byte	8,   4,	  0, 0x12,   0,	 0
		.byte	5,  0xD,	  8,   0, 0xFF, 0xF0
word_149E52:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF8,  0xD,	  0,   9, 0xFF, 0xEC
		.byte  0xF8,   1,	  0, 0x11,   0,	0xC
		.byte	8,   4,	  0, 0x13, 0xFF, 0xF4
		.byte  0xFF,  0xA,	  8,   0, 0xFF, 0xF9
word_149E6C:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF8,  0xD,	  0,   9, 0xFF, 0xEC
		.byte  0xF8,   1,	  0, 0x11,   0,	0xC
		.byte	8,   4,	  0, 0x13, 0xFF, 0xF4
		.byte  0xFF,  0xA,	  8,   0, 0xFF, 0xF9
word_149E86:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF8,  0xF,	  0,   0, 0xFF, 0xF0
word_149E8E:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF8,  0xF,	  0,   0, 0xFF, 0xF0
word_149E96:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xED,   4,	  0,   0, 0xFF, 0xEB
		.byte  0xF5,  0xE,	  0,   2, 0xFF, 0xF3
		.byte	5,   0,	  0,  0xE, 0xFF, 0xEB
word_149EAA:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xED,   4,	  0,   0, 0xFF, 0xF3
		.byte  0xF5,  0xE,	  0,   2, 0xFF, 0xF3
		.byte	5,   0,	  0,  0xE, 0xFF, 0xEB
word_149EBE:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xE6,   4,	  0,   0, 0xFF, 0xF4
		.byte  0xEE,  0xB,	  0,   2, 0xFF, 0xF4
word_149ECC:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xE6,   4,	  0,   0, 0xFF, 0xF4
		.byte  0xEE,  0xB,	  0,   2, 0xFF, 0xF4
word_149EDA:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xEC,   9,	  0,   0, 0xFF, 0xF0
		.byte  0xFC,  0xC,	  0,   6, 0xFF, 0xF0
		.byte	4,   1,	  0,  0xA,   0,	 0
word_149EEE:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xEF,   4,	  0,   0, 0xFF, 0xF4
		.byte  0xF7,  0xA,	  0,   2, 0xFF, 0xF4
word_149EFC:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xEC,   4,	  0,   0, 0xFF, 0xF6
		.byte  0xF4,  0xA,	  0,   2, 0xFF, 0xF6
		.byte   0xC,   4,	  0,  0xB, 0xFF, 0xFE
word_149F10:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xEC,  0xB,	  0,   0, 0xFF, 0xF4
		.byte   0xC,   0,	  0,  0xC, 0xFF, 0xFC
word_149F1E:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xEC,   8,	  0,   0, 0xFF, 0xF2
		.byte  0xF4,  0xD,	  0,   3, 0xFF, 0xF2
		.byte	4,   8,	  0,  0xB, 0xFF, 0xFA
		.byte   0xC,   0,	  0,  0xE, 0xFF, 0xFA
word_149F38:	.word 4			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xEC,   8,	  0,   0, 0xFF, 0xF6
		.byte  0xF4,  0xD,	  0,   3, 0xFF, 0xEE
		.byte	4,   8,	  0,  0xB, 0xFF, 0xF6
		.byte   0xC,   4,	  0,  0xE, 0xFF, 0xFE
word_149F52:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xEC,  0xA,	  0,   0, 0xFF, 0xF4
		.byte	4,  0xC,	  0,   9, 0xFF, 0xF4
		.byte   0xC,   8,	  0,  0xD, 0xFF, 0xFC
word_149F66:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xEC,  0xA,	  0,   0, 0xFF, 0xF4
		.byte	4,   5,	  0,   9, 0xFF, 0xFC
word_149F74:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xEC,  0xA,	  0,   0, 0xFF, 0xF5
		.byte	4,   0,	  0,   9, 0xFF, 0xFD
		.byte   0xC,   4,	  0,  0xA, 0xFF, 0xFD
word_149F88:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xEC,  0xB,	  0,   0, 0xFF, 0xF4
		.byte   0xC,   4,	  0,  0xC, 0xFF, 0xF4
word_149F96:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xEC,   9,	  0,   0, 0xFF, 0xF2
		.byte  0xFC,   5,	  0,   6, 0xFF, 0xFA
		.byte   0xC,   8,	  0,  0xA, 0xFF, 0xF2
word_149FAA:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xEC,  0xA,	  0,   0, 0xFF, 0xF5
		.byte	4,   0,	  0,   9, 0xFF, 0xFD
		.byte   0xC,   4,	  0,  0xA, 0xFF, 0xFD
word_149FBE:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF4,  0xA,	  0,   0, 0xFF, 0xF4
word_149FC6:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xEC,   8,	  0,   0, 0xFF, 0xF0
		.byte  0xF4,  0xD,	  0,   3, 0xFF, 0xF0
		.byte	4,   9,	  0,  0xB, 0xFF, 0xF0
word_149FDA:	.word 3			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xEC,   8,	  0,   0, 0xFF, 0xF0
		.byte  0xF4,  0xD,	  0,   3, 0xFF, 0xF0
		.byte	4,   9,	  0,  0xB, 0xFF, 0xF0
word_149FEE:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,  0xE,	  0,   0, 0xFF, 0xF0
		.byte	8,   4,	  0,  0xC, 0xFF, 0xF0
word_149FFC:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,  0xE,	  0,   0, 0xFF, 0xF0
		.byte	8,   8,	  0,  0xC, 0xFF, 0xF0
word_14A00A:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,  0xE,	  0,   0, 0xFF, 0xF0
		.byte	8,   8,	  0,  0xC, 0xFF, 0xF0
word_14A018:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xF0
word_14A020:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,  0xE,	  8,   0, 0xFF, 0xF0
		.byte	8,   8,	  8,  0xC, 0xFF, 0xF8
word_14A02E:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,  0xE,	  8,   0, 0xFF, 0xF0
		.byte	8,   8,	  8,  0xC, 0xFF, 0xF8
word_14A03C:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,  0xE,	  8,   0, 0xFF, 0xF0
		.byte	8,   4,	  8,  0xC,   0,	 0
word_14A04A:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,  0xE,	  0,   0, 0xFF, 0xF0
		.byte	8,   4,	  0,  0xC,   0,	 0
word_14A058:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,  0xE,	  0,   0, 0xFF, 0xF0
		.byte	8,   8,	  0,  0xC, 0xFF, 0xF8
word_14A066:	.word 1			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xF0
word_14A06E:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,  0xE,	  8,   0, 0xFF, 0xF0
		.byte	8,   8,	  8,  0xC, 0xFF, 0xF0
word_14A07C:	.word 2			/* DATA XREF: ROM:00148EB8o*/
		.byte  0xF0,  0xE,	  8,   0, 0xFF, 0xF0
		.byte	8,   4,	  8,  0xC, 0xFF, 0xF0
