Map_29FEE6:	.word Frame_29FF42-Map_29FEE6
		.word Frame_29FF44-Map_29FEE6
		.word Frame_29FF4C-Map_29FEE6
		.word Frame_29FF54-Map_29FEE6
		.word Frame_29FF5C-Map_29FEE6
		.word Frame_29FF64-Map_29FEE6
		.word Frame_29FF6C-Map_29FEE6
		.word Frame_29FF74-Map_29FEE6
		.word Frame_29FF7C-Map_29FEE6
		.word Frame_29FF84-Map_29FEE6
		.word Frame_29FF8C-Map_29FEE6
		.word Frame_29FF94-Map_29FEE6
		.word Frame_29FF9C-Map_29FEE6
		.word Frame_29FFA4-Map_29FEE6
		.word Frame_29FFAC-Map_29FEE6
		.word Frame_29FFB4-Map_29FEE6
		.word Frame_29FFBC-Map_29FEE6
		.word Frame_29FFC4-Map_29FEE6
		.word Frame_29FFCC-Map_29FEE6
		.word Frame_29FFD4-Map_29FEE6
		.word Frame_29FFDC-Map_29FEE6
		.word Frame_29FFE4-Map_29FEE6
		.word Frame_29FFEC-Map_29FEE6
		.word Frame_29FFF4-Map_29FEE6
		.word Frame_29FFFC-Map_29FEE6
		.word Frame_2A0004-Map_29FEE6
		.word Frame_2A000C-Map_29FEE6
		.word Frame_2A0014-Map_29FEE6
		.word Frame_2A001C-Map_29FEE6
		.word Frame_2A0024-Map_29FEE6
		.word Frame_2A002C-Map_29FEE6
		.word Frame_2A0034-Map_29FEE6
		.word Frame_2A003C-Map_29FEE6
		.word Frame_2A0044-Map_29FEE6
		.word Frame_2A004C-Map_29FEE6
		.word Frame_2A0054-Map_29FEE6
		.word Frame_2A005C-Map_29FEE6
		.word Frame_2A0064-Map_29FEE6
		.word Frame_2A006C-Map_29FEE6
		.word Frame_2A006C-Map_29FEE6
		.word Frame_2A0074-Map_29FEE6
		.word Frame_2A007C-Map_29FEE6
		.word Frame_2A0084-Map_29FEE6
		.word Frame_2A008C-Map_29FEE6
		.word Frame_2A0094-Map_29FEE6
		.word Frame_2A009C-Map_29FEE6
Frame_29FF42:	.word 0
Frame_29FF44:	.word 1
		.byte 0xF4, 0xE,  0,  0,0xFF,0xF0
Frame_29FF4C:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF0
Frame_29FF54:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF0
Frame_29FF5C:	.word 1
		.byte 0xF6, 0xA,  0,  0,0xFF,0xF6
Frame_29FF64:	.word 1
		.byte 0xF6, 0xA,  0,  0,0xFF,0xF6
Frame_29FF6C:	.word 1
		.byte 0xF6, 0xA,  0,  0,0xFF,0xF6
Frame_29FF74:	.word 1
		.byte 0xF0, 0xB,  0,  0,0xFF,0xF4
Frame_29FF7C:	.word 1
		.byte 0xF8, 0xA,  0,  0,0xFF,0xF4
Frame_29FF84:	.word 1
		.byte 0xF8, 0xA,  0,  0,0xFF,0xF4
Frame_29FF8C:	.word 1
		.byte 0xF2, 0xA,  0,  0,0xFF,0xF6
Frame_29FF94:	.word 1
		.byte 0xF2, 0xA,  0,  0,0xFF,0xF6
Frame_29FF9C:	.word 1
		.byte 0xF2, 0xA,  0,  0,0xFF,0xF6
Frame_29FFA4:	.word 1
		.byte 0xF7, 0xA,  0,  0,0xFF,0xF4
Frame_29FFAC:	.word 1
		.byte 0xF7, 0xA,  0,  0,0xFF,0xF4
Frame_29FFB4:	.word 1
		.byte 0xF2, 0xB,  0,  0,0xFF,0xF2
Frame_29FFBC:	.word 1
		.byte 0xF6,  6,  0,  0,0xFF,0xF8
Frame_29FFC4:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF7
Frame_29FFCC:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF7
Frame_29FFD4:	.word 1
		.byte 0xF6, 0xE,  0,  0,0xFF,0xF2
Frame_29FFDC:	.word 1
		.byte 0xF8,  9,  0,  0,0xFF,0xF6
Frame_29FFE4:	.word 1
		.byte 0xF4,  6,  0,  0,0xFF,0xF8
Frame_29FFEC:	.word 1
		.byte 0xF4,  6,  0,  0,0xFF,0xF8
Frame_29FFF4:	.word 1
		.byte 0xF4,  6,  0,  0,0xFF,0xF8
Frame_29FFFC:	.word 1
		.byte 0xF4,  6,  0,  0,0xFF,0xF8
Frame_2A0004:	.word 1
		.byte 0xF4,  6,  0,  0,0xFF,0xF8
Frame_2A000C:	.word 1
		.byte 0xF4,  6,  0,  0,0xFF,0xF8
Frame_2A0014:	.word 1
		.byte 0xF4,  6,  0,  0,0xFF,0xF8
Frame_2A001C:	.word 1
		.byte 0xF4,  6,  0,  0,0xFF,0xF8
Frame_2A0024:	.word 1
		.byte 0xF4,  6,  0,  0,0xFF,0xF8
Frame_2A002C:	.word 1
		.byte 0xF4,  6,  0,  0,0xFF,0xF8
Frame_2A0034:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A003C:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A0044:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A004C:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A0054:	.word 1
		.byte 0xFC, 0xD,  0,  0,0xFF,0xEA
Frame_2A005C:	.word 1
		.byte 0xFC, 0xD,  0,  0,0xFF,0xEA
Frame_2A0064:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A006C:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A0074:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A007C:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A0084:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A008C:	.word 1
		.byte 0xFC,  5,  0,  0,0xFF,0xF8
Frame_2A0094:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
Frame_2A009C:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF4
