Map_344BB8:	.word Frame_344C12-Map_344BB8 /*  ... */
		.word Frame_344C14-Map_344BB8
		.word Frame_344C1C-Map_344BB8
		.word Frame_344C24-Map_344BB8
		.word Frame_344C2C-Map_344BB8
		.word Frame_344C34-Map_344BB8
		.word Frame_344C3C-Map_344BB8
		.word Frame_344C44-Map_344BB8
		.word Frame_344C4C-Map_344BB8
		.word Frame_344C54-Map_344BB8
		.word Frame_344C5C-Map_344BB8
		.word Frame_344C64-Map_344BB8
		.word Frame_344C6C-Map_344BB8
		.word Frame_344C74-Map_344BB8
		.word Frame_344C7C-Map_344BB8
		.word Frame_344C84-Map_344BB8
		.word Frame_344C8C-Map_344BB8
		.word Frame_344C94-Map_344BB8
		.word Frame_344C9C-Map_344BB8
		.word Frame_344CA4-Map_344BB8
		.word Frame_344CAC-Map_344BB8
		.word Frame_344CB4-Map_344BB8
		.word Frame_344CBC-Map_344BB8
		.word Frame_344CC4-Map_344BB8
		.word Frame_344CCC-Map_344BB8
		.word Frame_344CD4-Map_344BB8
		.word Frame_344CDC-Map_344BB8
		.word Frame_344CE4-Map_344BB8
		.word Frame_344CEC-Map_344BB8
		.word Frame_344CF4-Map_344BB8
		.word Frame_344CFC-Map_344BB8
		.word Frame_344D04-Map_344BB8
		.word Frame_344D0C-Map_344BB8
		.word Frame_344D14-Map_344BB8
		.word Frame_344D1C-Map_344BB8
		.word Frame_344D24-Map_344BB8
		.word Frame_344D2C-Map_344BB8
		.word Frame_344D34-Map_344BB8
		.word Frame_344D3C-Map_344BB8
		.word Frame_344D44-Map_344BB8
		.word Frame_344D4C-Map_344BB8
		.word Frame_344D54-Map_344BB8
		.word Frame_344D5C-Map_344BB8
		.word Frame_344D64-Map_344BB8
		.word Frame_344D6C-Map_344BB8
Frame_344C12:	.word	 0
Frame_344C14:	.word 1
		.byte 0xFC,  9,  0,  0,0xFF,0xE2
Frame_344C1C:	.word	 1
		.byte 0xFC,  9,  0,  0,0xFF,0xE2
Frame_344C24:	.word	 1
		.byte 0xFC,  9,  0,  0,0xFF,0xE2
Frame_344C2C:	.word 1
		.byte 0xFC,  9,  0,  0,0xFF,0xE2
Frame_344C34:	.word	 1
		.byte 0xF8,  9,  0,  0,0xFF,0xDC
Frame_344C3C:	.word	 1
		.byte 0xF8,  9,  0,  0,0xFF,0xDC
Frame_344C44:	.word 1
		.byte 0xF8,  9,  0,  0,0xFF,0xDC
Frame_344C4C:	.word	 1
		.byte 0xF8,  9,  0,  0,0xFF,0xDC
Frame_344C54:	.word	 1
		.byte   7,  9,  0,  0,0xFF,0xE1
Frame_344C5C:	.word 1
		.byte   7,  9,  0,  0,0xFF,0xE1
Frame_344C64:	.word	 1
		.byte   7,  9,  0,  0,0xFF,0xE1
Frame_344C6C:	.word	 1
		.byte   7,  9,  0,  0,0xFF,0xE1
Frame_344C74:	.word 1
		.byte  0xC,  6,  0,  0,0xFF,0xF8
Frame_344C7C:	.word	 1
		.byte  0xC,  6,  0,  0,0xFF,0xF8
Frame_344C84:	.word	 1
		.byte  0xC,  6,  0,  0,0xFF,0xF8
Frame_344C8C:	.word 1
		.byte  0xC,  6,  0,  0,0xFF,0xF8
Frame_344C94:	.word	 1
		.byte   7,  6,  0,  0,  0,  7
Frame_344C9C:	.word	 1
		.byte   7,  6,  0,  0,  0,  7
Frame_344CA4:	.word 1
		.byte   7,  6,  0,  0,  0,  7
Frame_344CAC:	.word	 1
		.byte   7,  6,  0,  0,  0,  7
Frame_344CB4:	.word	 1
		.byte 0xF4,  6,  0,  0,0xFF,0xE6
Frame_344CBC:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xDE
Frame_344CC4:	.word	 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xDE
Frame_344CCC:	.word	 1
		.byte 0xFC,  9,  0,  0,0xFF,0xDE
Frame_344CD4:	.word 1
		.byte 0xF4, 0xA,  0,  0,0xFF,0xDE
Frame_344CDC:	.word	 1
		.byte 0xFE,  9,  0,  0,0xFF,0xE3
Frame_344CE4:	.word	 1
		.byte 0xFE,  9,  0,  0,0xFF,0xE3
Frame_344CEC:	.word 1
		.byte 0xFE,  9,  0,  0,0xFF,0xE3
Frame_344CF4:	.word	 1
		.byte 0xFE,  9,  0,  0,0xFF,0xE3
Frame_344CFC:	.word	 1
		.byte 0xFD,  9,  0,  0,0xFF,0xE3
Frame_344D04:	.word 1
		.byte 0xFD,  9,  0,  0,0xFF,0xE3
Frame_344D0C:	.word	 1
		.byte 0xFD,  9,  0,  0,0xFF,0xE3
Frame_344D14:	.word	 1
		.byte 0xFD,  9,  0,  0,0xFF,0xE3
Frame_344D1C:	.word 1
		.byte 0xF8,  6,  0,  0,0xFF,0xEB
Frame_344D24:	.word	 1
		.byte 0xF8, 0xA,  0,  0,0xFF,0xE4
Frame_344D2C:	.word	 1
		.byte 0xF8, 0xA,  0,  0,0xFF,0xE4
Frame_344D34:	.word 1
		.byte   0,  9,  0,  0,0xFF,0xE4
Frame_344D3C:	.word	 1
		.byte 0xF8, 0xA,  0,  0,0xFF,0xE4
Frame_344D44:	.word	 1
		.byte 0xEC, 0xC,  0,  0,0xFF,0xE7
Frame_344D4C:	.word 1
		.byte 0xEC, 0xC,  8,  0,0xFF,0xE7
Frame_344D54:	.word	 1
		.byte 0xF8,  9,  0,  0,0xFF,0xE4
Frame_344D5C:	.word	 1
		.byte 0xF8,  9,  0,  0,0xFF,0xE4
Frame_344D64:	.word	 1
		.byte 0xF8,  9,  0,  0,0xFF,0xE4
Frame_344D6C:	.word	 1
		.byte 0xF8,  9,  0,  0,0xFF,0xE4
