Map_SStageTailstails_:.word word_91124-Map_SStageTailstails_
		.word word_91126-Map_SStageTailstails_
		.word word_9112E-Map_SStageTailstails_
		.word word_91136-Map_SStageTailstails_
		.word word_9113E-Map_SStageTailstails_
		.word word_91146-Map_SStageTailstails_
		.word word_9114E-Map_SStageTailstails_
		.word word_91156-Map_SStageTailstails_
		.word word_9115E-Map_SStageTailstails_
		.word word_91166-Map_SStageTailstails_
		.word word_9116E-Map_SStageTailstails_
		.word word_91176-Map_SStageTailstails_
		.word word_9117E-Map_SStageTailstails_
		.word word_91186-Map_SStageTailstails_
		.word word_9118E-Map_SStageTailstails_
PLC_SStageTailstails:.word word_91124-PLC_SStageTailstails
		.word word_91196-PLC_SStageTailstails
		.word word_9119A-PLC_SStageTailstails
		.word word_9119E-PLC_SStageTailstails
		.word word_911A2-PLC_SStageTailstails
		.word word_911A6-PLC_SStageTailstails
		.word word_911AA-PLC_SStageTailstails
		.word word_911AE-PLC_SStageTailstails
		.word word_911B2-PLC_SStageTailstails
		.word word_911B6-PLC_SStageTailstails
		.word word_911BA-PLC_SStageTailstails
		.word word_911BE-PLC_SStageTailstails
		.word word_911C2-PLC_SStageTailstails
		.word word_911C6-PLC_SStageTailstails
		.word word_911CA-PLC_SStageTailstails
word_91124:     .word 0		 
word_91126:     .word 1		 
		.byte 0xEA,  6,  0,  0,0xFF,0xF8
word_9112E:     .word 1		 
		.byte 0xF2, 0xA,  0,  0,0xFF,0xF8
word_91136:     .word 1		 
		.byte 0xFA,  9,  0,  0,0xFF,0xF8
word_9113E:     .word 1		 
		.byte 0xF2,  6,  0,  0,0xFF,0xF8
word_91146:     .word 1		 
		.byte 0xEA,  7,  0,  0,0xFF,0xF8
word_9114E:     .word 1		 
		.byte 0xEA, 0xA,  0,  0,0xFF,0xF0
word_91156:     .word 1		 
		.byte 0xEA,  6,  0,  0,0xFF,0xF8
word_9115E:     .word 1		 
		.byte 0xEA,  6,  8,  0,0xFF,0xF8
word_91166:     .word 1		 
		.byte 0xF2, 0xA,  8,  0,0xFF,0xF0
word_9116E:     .word 1		 
		.byte 0xFA,  9,  0,  0,0xFF,0xF0
word_91176:     .word 1		 
		.byte 0xF2,  6,  8,  0,0xFF,0xF8
word_9117E:     .word 1		 
		.byte 0xEA,  7,  8,  0,0xFF,0xF8
word_91186:     .word 1		 
		.byte 0xEA, 0xA,  8,  0,0xFF,0xF8
word_9118E:     .word 1		 
		.byte 0xEA,  6,  8,  0,0xFF,0xF8
word_91196:     .word 1		 
		.word 0x5000
word_9119A:     .word 1		 
		.word 0x8006
word_9119E:     .word 1		 
		.word 0x500F
word_911A2:     .word 1		 
		.word 0x5015
word_911A6:     .word 1		 
		.word 0x701B
word_911AA:     .word 1		 
		.word 0x8023
word_911AE:     .word 1		 
		.word 0x502C
word_911B2:     .word 1		 
		.word 0x5000
word_911B6:     .word 1		 
		.word 0x8006
word_911BA:     .word 1		 
		.word 0x5032
word_911BE:     .word 1		 
		.word 0x5015
word_911C2:     .word 1		 
		.word 0x701B
word_911C6:     .word 1		 
		.word 0x8023
word_911CA:     .word 1		 
		.word 0x502C
