Map_SStageTails_:.word word_908EA-Map_SStageTails_
		.word word_90904-Map_SStageTails_
		.word word_90912-Map_SStageTails_
		.word word_90926-Map_SStageTails_
		.word word_9093A-Map_SStageTails_
		.word word_9094E-Map_SStageTails_
		.word word_90962-Map_SStageTails_
		.word word_90976-Map_SStageTails_
		.word word_9098A-Map_SStageTails_
		.word word_908EC-Map_SStageTails_
		.word word_908F4-Map_SStageTails_
		.word word_908FC-Map_SStageTails_
PLC_SStageTails:.word word_908EA-PLC_SStageTails
		.word word_909AA-PLC_SStageTails
		.word word_909B0-PLC_SStageTails
		.word word_909B8-PLC_SStageTails
		.word word_909C0-PLC_SStageTails
		.word word_909C8-PLC_SStageTails
		.word word_909D0-PLC_SStageTails
		.word word_909D8-PLC_SStageTails
		.word word_909E0-PLC_SStageTails
		.word word_9099E-PLC_SStageTails
		.word word_909A2-PLC_SStageTails
		.word word_909A6-PLC_SStageTails
word_908EA:     .word 0		 
word_908EC:     .word 1		 
		.byte 0xDD, 0xB,  0,  0,0xFF,0xF4
word_908F4:     .word 1		 
		.byte 0xDD, 0xB,  0,  0,0xFF,0xF4
word_908FC:     .word 1		 
		.byte 0xDD, 0xB,  0,  0,0xFF,0xF4
word_90904:     .word 2		 
		.byte 0xE1, 0xC,  0,  0,0xFF,0xF4
		.byte 0xE9, 0xB,  0,  4,0xFF,0xF4
word_90912:     .word 3		 
		.byte 0xDD, 0xC,  0,  0,0xFF,0xF3
		.byte 0xE5, 0xB,  0,  4,0xFF,0xF3
		.byte   5,  8,  0,0x10,0xFF,0xF3
word_90926:     .word 3		 
		.byte 0xDD, 0xC,  0,  0,0xFF,0xF4
		.byte 0xE5, 0xB,  0,  4,0xFF,0xF4
		.byte   5,  4,  0,0x10,0xFF,0xF4
word_9093A:     .word 3		 
		.byte 0xDD, 0xB,  0,  0,0xFF,0xF5
		.byte 0xFD,  8,  0, 0xC,0xFF,0xF5
		.byte   5,  4,  0, 0xF,0xFF,0xF5
word_9094E:     .word 3		 
		.byte 0xDD, 0xC,  0,  0,0xFF,0xF4
		.byte 0xE5, 0xB,  0,  4,0xFF,0xF4
		.byte   5,  0,  0,0x10,0xFF,0xF4
word_90962:     .word 3		 
		.byte 0xDD, 0xC,  8,  0,0xFF,0xEC
		.byte 0xE5, 0xB,  8,  4,0xFF,0xF4
		.byte   5,  4,  8,0x10,0xFF,0xFC
word_90976:     .word 3		 
		.byte 0xDD, 0xB,  8,  0,0xFF,0xF3
		.byte 0xFD,  8,  8, 0xC,0xFF,0xF3
		.byte   5,  4,  8, 0xF,0xFF,0xFB
word_9098A:     .word 3		 
		.byte 0xDD, 0xC,  8,  0,0xFF,0xEC
		.byte 0xE5, 0xB,  8,  4,0xFF,0xF4
		.byte   5,  0,  8,0x10,  0,  4
word_9099E:     .word 1		 
		.word 0xB000
word_909A2:     .word 1		 
		.word 0xB00C
word_909A6:     .word 1		 
		.word 0xB018
word_909AA:     .word 2		 
		.word 0x3024
		.word 0xB028
word_909B0:     .word 3		 
		.word 0x3034
		.word 0xB038
		.word 0x2044
word_909B8:     .word 3		 
		.word 0x3047
		.word 0xB04B
		.word 0x1057
word_909C0:     .word 3		 
		.word 0xB059
		.word 0x2065
		.word 0x1068
word_909C8:     .word 3		 
		.word 0x306A
		.word 0xB06E
		.word 0x7A
word_909D0:     .word 3		 
		.word 0x3047
		.word 0xB04B
		.word 0x1057
word_909D8:     .word 3		 
		.word 0xB059
		.word 0x2065
		.word 0x1068
word_909E0:     .word 3		 
		.word 0x306A
		.word 0xB06E
		.word 0x7A
