/* Tails pattern load cues*/
PLC_14A08A:		.word word_14A280-PLC_14A08A/* 0*/
		.word word_14A282-PLC_14A08A/* 1*/
		.word word_14A28C-PLC_14A08A/* 2*/
		.word word_14A296-PLC_14A08A/* 3*/
		.word word_14A29E-PLC_14A08A/* 4*/
		.word word_14A2A8-PLC_14A08A/* 5*/
		.word word_14A2B2-PLC_14A08A/* 6*/
		.word word_14A2BC-PLC_14A08A/* 7*/
		.word word_14A2C4-PLC_14A08A/* 8*/
		.word word_14A2CE-PLC_14A08A/* 9*/
		.word word_14A2D8-PLC_14A08A/* 10*/
		.word word_14A2E0-PLC_14A08A/* 11*/
		.word word_14A2EA-PLC_14A08A/* 12*/
		.word word_14A2F2-PLC_14A08A/* 13*/
		.word word_14A2FA-PLC_14A08A/* 14*/
		.word word_14A302-PLC_14A08A/* 15*/
		.word word_14A30A-PLC_14A08A/* 16*/
		.word word_14A314-PLC_14A08A/* 17*/
		.word word_14A31C-PLC_14A08A/* 18*/
		.word word_14A324-PLC_14A08A/* 19*/
		.word word_14A32C-PLC_14A08A/* 20*/
		.word word_14A332-PLC_14A08A/* 21*/
		.word word_14A33A-PLC_14A08A/* 22*/
		.word word_14A340-PLC_14A08A/* 23*/
		.word word_14A348-PLC_14A08A/* 24*/
		.word word_14A34E-PLC_14A08A/* 25*/
		.word word_14A356-PLC_14A08A/* 26*/
		.word word_14A360-PLC_14A08A/* 27*/
		.word word_14A36A-PLC_14A08A/* 28*/
		.word word_14A372-PLC_14A08A/* 29*/
		.word word_14A37A-PLC_14A08A/* 30*/
		.word word_14A384-PLC_14A08A/* 31*/
		.word word_14A38C-PLC_14A08A/* 32*/
		.word word_14A396-PLC_14A08A/* 33*/
		.word word_14A3A0-PLC_14A08A/* 34*/
		.word word_14A3AA-PLC_14A08A/* 35*/
		.word word_14A3B4-PLC_14A08A/* 36*/
		.word word_14A3BE-PLC_14A08A/* 37*/
		.word word_14A3C8-PLC_14A08A/* 38*/
		.word word_14A3D2-PLC_14A08A/* 39*/
		.word word_14A3DC-PLC_14A08A/* 40*/
		.word word_14A3E6-PLC_14A08A/* 41*/
		.word word_14A3F0-PLC_14A08A/* 42*/
		.word word_14A3FA-PLC_14A08A/* 43*/
		.word word_14A404-PLC_14A08A/* 44*/
		.word word_14A40E-PLC_14A08A/* 45*/
		.word word_14A418-PLC_14A08A/* 46*/
		.word word_14A422-PLC_14A08A/* 47*/
		.word word_14A42C-PLC_14A08A/* 48*/
		.word word_14A436-PLC_14A08A/* 49*/
		.word word_14A43A-PLC_14A08A/* 50*/
		.word word_14A440-PLC_14A08A/* 51*/
		.word word_14A444-PLC_14A08A/* 52*/
		.word word_14A448-PLC_14A08A/* 53*/
		.word word_14A44E-PLC_14A08A/* 54*/
		.word word_14A454-PLC_14A08A/* 55*/
		.word word_14A45A-PLC_14A08A/* 56*/
		.word word_14A460-PLC_14A08A/* 57*/
		.word word_14A466-PLC_14A08A/* 58*/
		.word word_14A46C-PLC_14A08A/* 59*/
		.word word_14A472-PLC_14A08A/* 60*/
		.word word_14A478-PLC_14A08A/* 61*/
		.word word_14A47E-PLC_14A08A/* 62*/
		.word word_14A484-PLC_14A08A/* 63*/
		.word word_14A488-PLC_14A08A/* 64*/
		.word word_14A490-PLC_14A08A/* 65*/
		.word word_14A494-PLC_14A08A/* 66*/
		.word word_14A498-PLC_14A08A/* 67*/
		.word word_14A4A0-PLC_14A08A/* 68*/
		.word word_14A4A6-PLC_14A08A/* 69*/
		.word word_14A4AC-PLC_14A08A/* 70*/
		.word word_14A4B2-PLC_14A08A/* 71*/
		.word word_14A4BA-PLC_14A08A/* 72*/
		.word word_14A4C0-PLC_14A08A/* 73*/
		.word word_14A4C8-PLC_14A08A/* 74*/
		.word word_14A4CE-PLC_14A08A/* 75*/
		.word word_14A4D6-PLC_14A08A/* 76*/
		.word word_14A4DC-PLC_14A08A/* 77*/
		.word word_14A4E4-PLC_14A08A/* 78*/
		.word word_14A4EE-PLC_14A08A/* 79*/
		.word word_14A4F8-PLC_14A08A/* 80*/
		.word word_14A502-PLC_14A08A/* 81*/
		.word word_14A50A-PLC_14A08A/* 82*/
		.word word_14A512-PLC_14A08A/* 83*/
		.word word_14A518-PLC_14A08A/* 84*/
		.word word_14A51E-PLC_14A08A/* 85*/
		.word word_14A526-PLC_14A08A/* 86*/
		.word word_14A52A-PLC_14A08A/* 87*/
		.word word_14A532-PLC_14A08A/* 88*/
		.word word_14A536-PLC_14A08A/* 89*/
		.word word_14A53A-PLC_14A08A/* 90*/
		.word word_14A542-PLC_14A08A/* 91*/
		.word word_14A546-PLC_14A08A/* 92*/
		.word word_14A550-PLC_14A08A/* 93*/
		.word word_14A554-PLC_14A08A/* 94*/
		.word word_14A55C-PLC_14A08A/* 95*/
		.word word_14A562-PLC_14A08A/* 96*/
		.word word_14A566-PLC_14A08A/* 97*/
		.word word_14A56A-PLC_14A08A/* 98*/
		.word word_14A572-PLC_14A08A/* 99*/
		.word word_14A57C-PLC_14A08A/* 100*/
		.word word_14A580-PLC_14A08A/* 101*/
		.word word_14A586-PLC_14A08A/* 102*/
		.word word_14A58C-PLC_14A08A/* 103*/
		.word word_14A590-PLC_14A08A/* 104*/
		.word word_14A594-PLC_14A08A/* 105*/
		.word word_14A59C-PLC_14A08A/* 106*/
		.word word_14A5A4-PLC_14A08A/* 107*/
		.word word_14A5AA-PLC_14A08A/* 108*/
		.word word_14A5B0-PLC_14A08A/* 109*/
		.word word_14A5B6-PLC_14A08A/* 110*/
		.word word_14A5BC-PLC_14A08A/* 111*/
		.word word_14A5C2-PLC_14A08A/* 112*/
		.word word_14A5C8-PLC_14A08A/* 113*/
		.word word_14A5CE-PLC_14A08A/* 114*/
		.word word_14A5D2-PLC_14A08A/* 115*/
		.word word_14A5D8-PLC_14A08A/* 116*/
		.word word_14A5DC-PLC_14A08A/* 117*/
		.word word_14A5E0-PLC_14A08A/* 118*/
		.word word_14A5E6-PLC_14A08A/* 119*/
		.word word_14A5EC-PLC_14A08A/* 120*/
		.word word_14A5F6-PLC_14A08A/* 121*/
		.word word_14A600-PLC_14A08A/* 122*/
		.word word_14A60A-PLC_14A08A/* 123*/
		.word word_14A614-PLC_14A08A/* 124*/
		.word word_14A61E-PLC_14A08A/* 125*/
		.word word_14A628-PLC_14A08A/* 126*/
		.word word_14A632-PLC_14A08A/* 127*/
		.word word_14A63C-PLC_14A08A/* 128*/
		.word word_14A642-PLC_14A08A/* 129*/
		.word word_14A64C-PLC_14A08A/* 130*/
		.word word_14A656-PLC_14A08A/* 131*/
		.word word_14A65E-PLC_14A08A/* 132*/
		.word word_14A666-PLC_14A08A/* 133*/
		.word word_14A670-PLC_14A08A/* 134*/
		.word word_14A676-PLC_14A08A/* 135*/
		.word word_14A67C-PLC_14A08A/* 136*/
		.word word_14A682-PLC_14A08A/* 137*/
		.word word_14A686-PLC_14A08A/* 138*/
		.word word_14A68A-PLC_14A08A/* 139*/
		.word word_14A690-PLC_14A08A/* 140*/
		.word word_14A696-PLC_14A08A/* 141*/
		.word word_14A69C-PLC_14A08A/* 142*/
		.word word_14A6A4-PLC_14A08A/* 143*/
		.word word_14A6AC-PLC_14A08A/* 144*/
		.word word_14A6B2-PLC_14A08A/* 145*/
		.word word_14A6B8-PLC_14A08A/* 146*/
		.word word_14A6BE-PLC_14A08A/* 147*/
		.word word_14A6C2-PLC_14A08A/* 148*/
		.word word_14A6CA-PLC_14A08A/* 149*/
		.word word_14A6D2-PLC_14A08A/* 150*/
		.word word_14A6D6-PLC_14A08A/* 151*/
		.word word_14A6DA-PLC_14A08A/* 152*/
		.word word_14A6DE-PLC_14A08A/* 153*/
		.word word_14A6E2-PLC_14A08A/* 154*/
		.word word_14A6EA-PLC_14A08A/* 155*/
		.word word_14A6F2-PLC_14A08A/* 156*/
		.word word_14A6F6-PLC_14A08A/* 157*/
		.word word_14A6FC-PLC_14A08A/* 158*/
		.word word_14A704-PLC_14A08A/* 159*/
		.word word_14A70C-PLC_14A08A/* 160*/
		.word word_14A712-PLC_14A08A/* 161*/
		.word word_14A718-PLC_14A08A/* 162*/
		.word word_14A71E-PLC_14A08A/* 163*/
		.word word_14A724-PLC_14A08A/* 164*/
		.word word_14A72A-PLC_14A08A/* 165*/
		.word word_14A72E-PLC_14A08A/* 166*/
		.word word_14A738-PLC_14A08A/* 167*/
		.word word_14A73E-PLC_14A08A/* 168*/
		.word word_14A746-PLC_14A08A/* 169*/
		.word word_14A74C-PLC_14A08A/* 170*/
		.word word_14A750-PLC_14A08A/* 171*/
		.word word_14A754-PLC_14A08A/* 172*/
		.word word_14A758-PLC_14A08A/* 173*/
		.word word_14A75C-PLC_14A08A/* 174*/
		.word word_14A760-PLC_14A08A/* 175*/
		.word word_14A764-PLC_14A08A/* 176*/
		.word word_14A768-PLC_14A08A/* 177*/
		.word word_14A76C-PLC_14A08A/* 178*/
		.word word_14A770-PLC_14A08A/* 179*/
		.word word_14A774-PLC_14A08A/* 180*/
		.word word_14A778-PLC_14A08A/* 181*/
		.word word_14A780-PLC_14A08A/* 182*/
		.word word_14A786-PLC_14A08A/* 183*/
		.word word_14A78A-PLC_14A08A/* 184*/
		.word word_14A778-PLC_14A08A/* 185*/
		.word word_14A790-PLC_14A08A/* 186*/
		.word word_14A798-PLC_14A08A/* 187*/
		.word word_14A790-PLC_14A08A/* 188*/
		.word word_14A79E-PLC_14A08A/* 189*/
		.word word_14A7A6-PLC_14A08A/* 190*/
		.word word_14A7AE-PLC_14A08A/* 191*/
		.word word_14A7B4-PLC_14A08A/* 192*/
		.word word_14A7BE-PLC_14A08A/* 193*/
		.word word_14A7C4-PLC_14A08A/* 194*/
		.word word_14A7CC-PLC_14A08A/* 195*/
		.word word_14A7D6-PLC_14A08A/* 196*/
		.word word_14A7E0-PLC_14A08A/* 197*/
		.word word_14A7EA-PLC_14A08A/* 198*/
		.word word_14A7F4-PLC_14A08A/* 199*/
		.word word_14A7FE-PLC_14A08A/* 200*/
		.word word_14A808-PLC_14A08A/* 201*/
		.word word_14A812-PLC_14A08A/* 202*/
		.word word_14A81C-PLC_14A08A/* 203*/
		.word word_14A820-PLC_14A08A/* 204*/
		.word word_14A824-PLC_14A08A/* 205*/
		.word word_14A82C-PLC_14A08A/* 206*/
		.word word_14A834-PLC_14A08A/* 207*/
		.word word_14A83A-PLC_14A08A/* 208*/
		.word word_14A840-PLC_14A08A/* 209*/
		.word word_14A840-PLC_14A08A/* 210*/
		.word word_14A840-PLC_14A08A/* 211*/
		.word word_14A840-PLC_14A08A/* 212*/
		.word word_14A840-PLC_14A08A/* 213*/
		.word word_14A840-PLC_14A08A/* 214*/
		.word word_14A840-PLC_14A08A/* 215*/
		.word word_14A840-PLC_14A08A/* 216*/
		.word word_14A840-PLC_14A08A/* 217*/
		.word word_14A840-PLC_14A08A/* 218*/
		.word word_14A840-PLC_14A08A/* 219*/
		.word word_14A840-PLC_14A08A/* 220*/
		.word word_14A840-PLC_14A08A/* 221*/
		.word word_14A840-PLC_14A08A/* 222*/
		.word word_14A840-PLC_14A08A/* 223*/
		.word word_14A848-PLC_14A08A/* 224*/
		.word word_14A84E-PLC_14A08A/* 225*/
		.word word_14A856-PLC_14A08A/* 226*/
		.word word_14A85C-PLC_14A08A/* 227*/
		.word word_14A866-PLC_14A08A/* 228*/
		.word word_14A870-PLC_14A08A/* 229*/
		.word word_14A878-PLC_14A08A/* 230*/
		.word word_14A87E-PLC_14A08A/* 231*/
		.word word_14A886-PLC_14A08A/* 232*/
		.word word_14A88C-PLC_14A08A/* 233*/
		.word word_14A894-PLC_14A08A/* 234*/
		.word word_14A89C-PLC_14A08A/* 235*/
		.word word_14A8A0-PLC_14A08A/* 236*/
		.word word_14A8A8-PLC_14A08A/* 237*/
		.word word_14A8A8-PLC_14A08A/* 238*/
		.word word_14A8B0-PLC_14A08A/* 239*/
		.word word_14A8B6-PLC_14A08A/* 240*/
		.word word_14A8BC-PLC_14A08A/* 241*/
		.word word_14A8C2-PLC_14A08A/* 242*/
		.word word_14A8BC-PLC_14A08A/* 243*/
		.word word_14A8B6-PLC_14A08A/* 244*/
		.word word_14A8B0-PLC_14A08A/* 245*/
		.word word_14A8C6-PLC_14A08A/* 246*/
		.word word_14A8CC-PLC_14A08A/* 247*/
		.word word_14A8D2-PLC_14A08A/* 248*/
		.word word_14A8CC-PLC_14A08A/* 249*/
		.word word_14A8C6-PLC_14A08A/* 250*/
word_14A280:	.word 0			/* DATA XREF: ROM:0014A08Ao*/
word_14A282:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x5062
		.word 0x1000
		.word 0x5002
		.word 0x7008
word_14A28C:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x5068
		.word 0x7010
		.word 0x2018
		.word 0x301B
word_14A296:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x506E
		.word 0x801F
		.word 0x2028
word_14A29E:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x5074
		.word 0x702B
		.word 0x2033
		.word 0x3036
word_14A2A8:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x5062
		.word 0x1000
		.word 0x503A
		.word 0x7040
word_14A2B2:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x5068
		.word 0x7010
		.word 0x2048
		.word 0x304B
word_14A2BC:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x506E
		.word 0x804F
		.word 0x2058
word_14A2C4:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x5074
		.word 0x702B
		.word 0x205B
		.word 0x305E
word_14A2CE:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x107A
		.word 0x707C
		.word 0x2084
		.word 0x2087
word_14A2D8:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB08A
		.word 0x5096
		.word 0x209C
word_14A2E0:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x109F
		.word 0x70A1
		.word 0x20A9
		.word 0x70AC
word_14A2EA:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x10B4
		.word 0xF0B6
		.word 0xC6
word_14A2F2:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x20C7
		.word 0x70CA
		.word 0x50D2
word_14A2FA:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x10D8
		.word 0xB0DA
		.word 0x30E6
word_14A302:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x10EA
		.word 0x20EC
		.word 0xB0EF
word_14A30A:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xFB
		.word 0x50FC
		.word 0x3102
		.word 0x3106
word_14A314:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x516D
		.word 0x110A
		.word 0xB10C
word_14A31C:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x5173
		.word 0xB118
		.word 0x124
word_14A324:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x5179
		.word 0x2125
		.word 0x7128
word_14A32C:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x517F
		.word 0xB130
word_14A332:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x516D
		.word 0x113C
		.word 0xB13E
word_14A33A:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x5173
		.word 0xB14A
word_14A340:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x5179
		.word 0x2156
		.word 0x7159
word_14A348:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x517F
		.word 0xB161
word_14A34E:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x2185
		.word 0xB188
		.word 0x1194
word_14A356:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x1196
		.word 0x2198
		.word 0xB19B
		.word 0x21A7
word_14A360:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x31AA
		.word 0x31AE
		.word 0x51B2
		.word 0x51B8
word_14A36A:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x1BE
		.word 0xF1BF
		.word 0x11CF
word_14A372:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x11D1
		.word 0xB1D3
		.word 0x21DF
word_14A37A:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x1E2
		.word 0x11E3
		.word 0xB1E5
		.word 0x11F1
word_14A384:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x21F3
		.word 0xB1F6
		.word 0x1202
word_14A38C:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x204
		.word 0xB205
		.word 0x211
		.word 0x212
word_14A396:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x722B
		.word 0x5213
		.word 0x3219
		.word 0x121D
word_14A3A0:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x1233
		.word 0x521F
		.word 0x3225
		.word 0x1229
word_14A3AA:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x3235
		.word 0x5213
		.word 0x3219
		.word 0x121D
word_14A3B4:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x7239
		.word 0x521F
		.word 0x3225
		.word 0x1229
word_14A3BE:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB259
		.word 0x1241
		.word 0x5243
		.word 0x3249
word_14A3C8:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x5265
		.word 0x124D
		.word 0x524F
		.word 0x3255
word_14A3D2:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x326B
		.word 0x1241
		.word 0x5243
		.word 0x3249
word_14A3DC:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x526F
		.word 0x124D
		.word 0x524F
		.word 0x3255
word_14A3E6:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x729F
		.word 0x5287
		.word 0x328D
		.word 0x1291
word_14A3F0:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x12A7
		.word 0x5293
		.word 0x3299
		.word 0x129D
word_14A3FA:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x32A9
		.word 0x5287
		.word 0x328D
		.word 0x1291
word_14A404:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x72AD
		.word 0x5293
		.word 0x3299
		.word 0x129D
word_14A40E:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB2CD
		.word 0x72B5
		.word 0x12BD
		.word 0x12BF
word_14A418:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x52D9
		.word 0x72C1
		.word 0x12C9
		.word 0x12CB
word_14A422:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x32DF
		.word 0x72B5
		.word 0x12BD
		.word 0x12BF
word_14A42C:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x52E3
		.word 0x72C1
		.word 0x12C9
		.word 0x12CB
word_14A436:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB2E9
word_14A43A:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB2F5
		.word 0x1301
word_14A440:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB303
word_14A444:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x830F
word_14A448:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x8318
		.word 0x321
word_14A44E:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x1322
		.word 0x8324
word_14A454:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x132D
		.word 0x832F
word_14A45A:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x1338
		.word 0x833A
word_14A460:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x1343
		.word 0x8345
word_14A466:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x534E
		.word 0x1354
word_14A46C:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x8356
		.word 0x35F
word_14A472:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x5360
		.word 0x3366
word_14A478:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x83D8
		.word 0x13E1
word_14A47E:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x3CE
		.word 0x83CF
word_14A484:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x83C5
word_14A488:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x13BB
		.word 0x53BD
		.word 0x13C3
word_14A490:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB3AF
word_14A494:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB3A3
word_14A498:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x2398
		.word 0x139B
		.word 0x539D
word_14A4A0:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x38E
		.word 0x838F
word_14A4A6:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x5387
		.word 0x38D
word_14A4AC:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x137F
		.word 0x5381
word_14A4B2:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x1375
		.word 0x5377
		.word 0x137D
word_14A4BA:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x836A
		.word 0x1373
word_14A4C0:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x23E3
		.word 0x73E6
		.word 0x3EE
word_14A4C8:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x23EF
		.word 0x73F2
word_14A4CE:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x13FA
		.word 0x23FC
		.word 0x33FF
word_14A4D6:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x1403
		.word 0x8405
word_14A4DC:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x140E
		.word 0x5410
		.word 0x1416
word_14A4E4:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x418
		.word 0x1419
		.word 0x341B
		.word 0x541F
word_14A4EE:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x1425
		.word 0x3427
		.word 0x542B
		.word 0x1431
word_14A4F8:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x1433
		.word 0x3435
		.word 0x5439
		.word 0x43F
word_14A502:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x1440
		.word 0x5442
		.word 0x1448
word_14A50A:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x144A
		.word 0x344C
		.word 0x1450
word_14A512:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x7452
		.word 0x245A
word_14A518:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x245D
		.word 0x7460
word_14A51E:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x2468
		.word 0x346B
		.word 0x546F
word_14A526:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB475
word_14A52A:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x2481
		.word 0x3484
		.word 0x2488
word_14A532:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB48B
word_14A536:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB497
word_14A53A:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x14A3
		.word 0x54A5
		.word 0x14AB
word_14A542:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB4AD
word_14A546:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x24B9
		.word 0x14BC
		.word 0x74BE
		.word 0x34C6
word_14A550:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB4CA
word_14A554:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB4D6
		.word 0x4E2
		.word 0x4E3
word_14A55C:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB4E4
		.word 0x54F0
word_14A562:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB4F6
word_14A566:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB502
word_14A56A:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x250E
		.word 0x7511
		.word 0x1519
word_14A572:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x851B
		.word 0x1524
		.word 0x2526
		.word 0x2529
word_14A57C:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB52C
word_14A580:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB538
		.word 0x2544
word_14A586:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB547
		.word 0x5553
word_14A58C:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB559
word_14A590:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB565
word_14A594:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x2571
		.word 0xB574
		.word 0x580
word_14A59C:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x1581
		.word 0x7583
		.word 0x258B
word_14A5A4:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x158E
		.word 0x8590
word_14A5AA:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x2599
		.word 0x759C
word_14A5B0:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x25A4
		.word 0x75A7
word_14A5B6:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x75AF
		.word 0x25B7
word_14A5BC:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x55BA
		.word 0x15C0
word_14A5C2:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x55C2
		.word 0x35C8
word_14A5C8:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x75CC
		.word 0x25D4
word_14A5CE:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB5D7
word_14A5D2:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB5E3
		.word 0x15EF
word_14A5D8:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB5F1
word_14A5DC:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x85FD
word_14A5E0:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x2606
		.word 0x7609
word_14A5E6:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x2611
		.word 0x7614
word_14A5EC:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x361C
		.word 0x5620
		.word 0x3626
		.word 0x262A
word_14A5F6:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x162D
		.word 0x562F
		.word 0x1635
		.word 0x5637
word_14A600:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x63D
		.word 0x563E
		.word 0x5644
		.word 0x364A
word_14A60A:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x164E
		.word 0x5650
		.word 0x5656
		.word 0x165C
word_14A614:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x361C
		.word 0x5620
		.word 0x3626
		.word 0x262A
word_14A61E:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x162D
		.word 0x562F
		.word 0x1635
		.word 0x5637
word_14A628:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x63D
		.word 0x563E
		.word 0x565E
		.word 0x364A
word_14A632:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x164E
		.word 0x5650
		.word 0x5656
		.word 0x165C
word_14A63C:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x7664
		.word 0x866C
word_14A642:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x3675
		.word 0x2679
		.word 0xB67C
		.word 0x1688
word_14A64C:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x868A
		.word 0x1693
		.word 0x3695
		.word 0x3699
word_14A656:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xF69D
		.word 0x6AD
		.word 0x26AE
word_14A65E:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x56B1
		.word 0x76B7
		.word 0x36BF
word_14A666:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x56C3
		.word 0x36C9
		.word 0x26CD
		.word 0x36D0
word_14A670:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x36D4
		.word 0x56D8
word_14A676:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x76DE
		.word 0x26E6
word_14A67C:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x36E9
		.word 0x56ED
word_14A682:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xF6F3
word_14A686:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xF703
word_14A68A:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x3713
		.word 0xB717
word_14A690:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x3713
		.word 0xB723
word_14A696:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x172F
		.word 0xB731
word_14A69C:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x5830
		.word 0x3836
		.word 0x283A
word_14A6A4:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x583D
		.word 0x3843
		.word 0x2847
word_14A6AC:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB73D
		.word 0x1749
word_14A6B2:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x574B
		.word 0x7751
word_14A6B8:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x5759
		.word 0x775F
word_14A6BE:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x8767
word_14A6C2:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x7770
		.word 0xB77E
		.word 0x278A
word_14A6CA:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x5778
		.word 0xB77E
		.word 0x278A
word_14A6D2:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xF78D
word_14A6D6:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xF79D
word_14A6DA:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xF7AD
word_14A6DE:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x8800
word_14A6E2:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x2862
		.word 0x7865
		.word 0x186D
word_14A6EA:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x586F
		.word 0x3875
		.word 0x2879
word_14A6F2:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xF7ED
word_14A6F6:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x787C
		.word 0x8884
word_14A6FC:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x188D
		.word 0xB88F
		.word 0x289B
word_14A704:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x289E
		.word 0x78A1
		.word 0x28A9
word_14A70C:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x28AC
		.word 0xB8AF
word_14A712:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x28BB
		.word 0xB8BE
word_14A718:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x28AC
		.word 0xB8CA
word_14A71E:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x28D6
		.word 0xB8D9
word_14A724:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x28E5
		.word 0xB8E8
word_14A72A:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB8F8
word_14A72E:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x904
		.word 0x7905
		.word 0x790D
		.word 0x915
word_14A738:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x7AD0
		.word 0x8AD8
word_14A73E:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x2AE1
		.word 0x7AE4
		.word 0x5AEC
word_14A746:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x8916
		.word 0x391F
word_14A74C:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB923
word_14A750:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB92F
word_14A754:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB93B
word_14A758:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB947
word_14A75C:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB953
word_14A760:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB95F
word_14A764:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB96B
word_14A768:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB977
word_14A76C:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB983
word_14A770:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB98F
word_14A774:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB99B
word_14A778:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x9A7
		.word 0x79A8
		.word 0x39B0
word_14A780:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x89B4
		.word 0x39BD
word_14A786:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB9C1
word_14A78A:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x89B4
		.word 0x39BD
word_14A790:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x19CD
		.word 0x79CF
		.word 0x19D7
word_14A798:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x59D9
		.word 0x39DF
word_14A79E:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x19E3
		.word 0xB9E5
		.word 0x29F1
word_14A7A6:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB9F4
		.word 0x1A00
		.word 0x2A02
word_14A7AE:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xFA05
		.word 0xA15
word_14A7B4:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x7A16
		.word 0xA1E
		.word 0x7A1F
		.word 0xA27
word_14A7BE:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xFA28
		.word 0x1A38
word_14A7C4:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xBA3A
		.word 0x2A46
		.word 0x1A49
word_14A7CC:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x7239
		.word 0x5213
		.word 0x3219
		.word 0x121D
word_14A7D6:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x7239
		.word 0x521F
		.word 0x3225
		.word 0x1229
word_14A7E0:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x8275
		.word 0x1241
		.word 0x5243
		.word 0x3249
word_14A7EA:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x827E
		.word 0x124D
		.word 0x524F
		.word 0x3255
word_14A7F4:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x72AD
		.word 0x5287
		.word 0x328D
		.word 0x1291
word_14A7FE:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x72AD
		.word 0x5293
		.word 0x3299
		.word 0x129D
word_14A808:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x827E
		.word 0x72B5
		.word 0x12BD
		.word 0x12BF
word_14A812:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x8275
		.word 0x72C1
		.word 0x12C9
		.word 0x12CB
word_14A81C:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xF6F3
word_14A820:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xF703
word_14A824:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x1AF2
		.word 0xBAF4
		.word 0xA48
word_14A82C:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x1B00
		.word 0xBB02
		.word 0xA48
word_14A834:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x1B0E
		.word 0xBB10
word_14A83A:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x1B1C
		.word 0xBB1E
word_14A840:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x5000
		.word 0x3006
		.word 0x100A
word_14A848:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x100C
		.word 0x800E
word_14A84E:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x1017
		.word 0x8019
		.word 0x1022
word_14A856:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB024
		.word 0x30
word_14A85C:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x2031
		.word 0x7034
		.word 0x203C
		.word 0x3F
word_14A866:	.word 4			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x2040
		.word 0x7043
		.word 0x204B
		.word 0x104E
word_14A870:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x8050
		.word 0x3059
		.word 0x205D
word_14A878:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x8060
		.word 0x3069
word_14A87E:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x806D
		.word 0x76
		.word 0x1077
word_14A886:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB079
		.word 0x1085
word_14A88C:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x5087
		.word 0x308D
		.word 0x2091
word_14A894:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x8094
		.word 0x9D
		.word 0x109E
word_14A89C:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x80A0
word_14A8A0:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x20A9
		.word 0x70AC
		.word 0x50B4
word_14A8A8:	.word 3			/* DATA XREF: ROM:0014A08Ao*/
		.word 0x20BA
		.word 0x70BD
		.word 0x50C5
word_14A8B0:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB0E0
		.word 0x10EC
word_14A8B6:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB0EE
		.word 0x20FA
word_14A8BC:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB0FD
		.word 0x2109
word_14A8C2:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xF10C
word_14A8C6:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB11C
		.word 0x1128
word_14A8CC:	.word 2			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xB12A
		.word 0x2136
word_14A8D2:	.word 1			/* DATA XREF: ROM:0014A08Ao*/
		.word 0xF139
