		.word word_1445F8-PLC_Tails
		.word word_1445FA-PLC_Tails
		.word word_144604-PLC_Tails
		.word word_14460E-PLC_Tails
		.word word_144616-PLC_Tails
		.word word_144620-PLC_Tails
		.word word_14462A-PLC_Tails
		.word word_144634-PLC_Tails
		.word word_14463C-PLC_Tails
		.word word_144646-PLC_Tails
		.word word_144650-PLC_Tails
		.word word_144658-PLC_Tails
		.word word_144662-PLC_Tails
		.word word_14466A-PLC_Tails
		.word word_144672-PLC_Tails
		.word word_14467A-PLC_Tails
		.word word_144682-PLC_Tails
		.word word_14468C-PLC_Tails
		.word word_144694-PLC_Tails
		.word word_14469C-PLC_Tails
		.word word_1446A4-PLC_Tails
		.word word_1446AA-PLC_Tails
		.word word_1446B2-PLC_Tails
		.word word_1446B8-PLC_Tails
		.word word_1446C0-PLC_Tails
		.word word_1446C6-PLC_Tails
		.word word_1446CE-PLC_Tails
		.word word_1446D8-PLC_Tails
		.word word_1446E2-PLC_Tails
		.word word_1446EA-PLC_Tails
		.word word_1446F2-PLC_Tails
		.word word_1446FC-PLC_Tails
		.word word_144704-PLC_Tails
		.word word_14470E-PLC_Tails
		.word word_144718-PLC_Tails
		.word word_144722-PLC_Tails
		.word word_14472C-PLC_Tails
		.word word_144736-PLC_Tails
		.word word_144740-PLC_Tails
		.word word_14474A-PLC_Tails
		.word word_144754-PLC_Tails
		.word word_14475E-PLC_Tails
		.word word_144768-PLC_Tails
		.word word_144772-PLC_Tails
		.word word_14477C-PLC_Tails
		.word word_144786-PLC_Tails
		.word word_144790-PLC_Tails
		.word word_14479A-PLC_Tails
		.word word_1447A4-PLC_Tails
		.word word_1447AE-PLC_Tails
		.word word_1447B2-PLC_Tails
		.word word_1447B8-PLC_Tails
		.word word_1447BC-PLC_Tails
		.word word_1447C0-PLC_Tails
		.word word_1447C6-PLC_Tails
		.word word_1447CC-PLC_Tails
		.word word_1447D2-PLC_Tails
		.word word_1447D8-PLC_Tails
		.word word_1447DE-PLC_Tails
		.word word_1447E4-PLC_Tails
		.word word_1447EA-PLC_Tails
		.word word_1447F0-PLC_Tails
		.word word_1447F6-PLC_Tails
		.word word_1447FC-PLC_Tails
		.word word_144800-PLC_Tails
		.word word_144808-PLC_Tails
		.word word_14480C-PLC_Tails
		.word word_144810-PLC_Tails
		.word word_144818-PLC_Tails
		.word word_14481E-PLC_Tails
		.word word_144824-PLC_Tails
		.word word_14482A-PLC_Tails
		.word word_144832-PLC_Tails
		.word word_144838-PLC_Tails
		.word word_144840-PLC_Tails
		.word word_144846-PLC_Tails
		.word word_14484E-PLC_Tails
		.word word_144854-PLC_Tails
		.word word_14485C-PLC_Tails
		.word word_144866-PLC_Tails
		.word word_144870-PLC_Tails
		.word word_14487A-PLC_Tails
		.word word_144882-PLC_Tails
		.word word_14488A-PLC_Tails
		.word word_144890-PLC_Tails
		.word word_144896-PLC_Tails
		.word word_14489E-PLC_Tails
		.word word_1448A2-PLC_Tails
		.word word_1448AA-PLC_Tails
		.word word_1448AE-PLC_Tails
		.word word_1448B2-PLC_Tails
		.word word_1448BA-PLC_Tails
		.word word_1448BE-PLC_Tails
		.word word_1448C8-PLC_Tails
		.word word_1448CC-PLC_Tails
		.word word_1448D4-PLC_Tails
		.word word_1448DA-PLC_Tails
		.word word_1448DE-PLC_Tails
		.word word_1448E2-PLC_Tails
		.word word_1448EA-PLC_Tails
		.word word_1448F4-PLC_Tails
		.word word_1448F8-PLC_Tails
		.word word_1448FE-PLC_Tails
		.word word_144904-PLC_Tails
		.word word_144908-PLC_Tails
		.word word_14490C-PLC_Tails
		.word word_144914-PLC_Tails
		.word word_14491C-PLC_Tails
		.word word_144922-PLC_Tails
		.word word_144928-PLC_Tails
		.word word_14492E-PLC_Tails
		.word word_144934-PLC_Tails
		.word word_14493A-PLC_Tails
		.word word_144940-PLC_Tails
		.word word_144946-PLC_Tails
		.word word_14494A-PLC_Tails
		.word word_144950-PLC_Tails
		.word word_144954-PLC_Tails
		.word word_144958-PLC_Tails
		.word word_14495E-PLC_Tails
		.word word_144964-PLC_Tails
		.word word_14496E-PLC_Tails
		.word word_144978-PLC_Tails
		.word word_144982-PLC_Tails
		.word word_14498C-PLC_Tails
		.word word_144996-PLC_Tails
		.word word_1449A0-PLC_Tails
		.word word_1449AA-PLC_Tails
		.word word_1449B4-PLC_Tails
		.word word_1449BA-PLC_Tails
		.word word_1449C4-PLC_Tails
		.word word_1449CE-PLC_Tails
		.word word_1449D6-PLC_Tails
		.word word_1449DE-PLC_Tails
		.word word_1449E8-PLC_Tails
		.word word_1449EE-PLC_Tails
		.word word_1449F4-PLC_Tails
		.word word_1449FA-PLC_Tails
		.word word_1449FE-PLC_Tails
		.word word_144A02-PLC_Tails
		.word word_144A08-PLC_Tails
		.word word_144A0E-PLC_Tails
		.word word_144A14-PLC_Tails
		.word word_144A1C-PLC_Tails
		.word word_144A24-PLC_Tails
		.word word_144A2A-PLC_Tails
		.word word_144A30-PLC_Tails
		.word word_144A36-PLC_Tails
		.word word_144A3A-PLC_Tails
		.word word_144A42-PLC_Tails
		.word word_144A4A-PLC_Tails
		.word word_144A4E-PLC_Tails
		.word word_144A52-PLC_Tails
		.word word_144A56-PLC_Tails
		.word word_144A5A-PLC_Tails
		.word word_144A62-PLC_Tails
		.word word_144A6A-PLC_Tails
		.word word_144A6E-PLC_Tails
		.word word_144A74-PLC_Tails
		.word word_144A7C-PLC_Tails
		.word word_144A84-PLC_Tails
		.word word_144A8A-PLC_Tails
		.word word_144A90-PLC_Tails
		.word word_144A96-PLC_Tails
		.word word_144A9C-PLC_Tails
		.word word_144AA2-PLC_Tails
		.word word_144AA6-PLC_Tails
		.word word_144AB0-PLC_Tails
		.word word_144AB6-PLC_Tails
		.word word_144ABE-PLC_Tails
		.word word_144AC4-PLC_Tails
		.word word_144AC8-PLC_Tails
		.word word_144ACC-PLC_Tails
		.word word_144AD0-PLC_Tails
		.word word_144AD4-PLC_Tails
		.word word_144AD8-PLC_Tails
		.word word_144ADC-PLC_Tails
		.word word_144AE0-PLC_Tails
		.word word_144AE4-PLC_Tails
		.word word_144AE8-PLC_Tails
		.word word_144AEC-PLC_Tails
		.word word_144AF0-PLC_Tails
		.word word_144AF8-PLC_Tails
		.word word_144AFE-PLC_Tails
		.word word_144B02-PLC_Tails
		.word word_144AF0-PLC_Tails
		.word word_144B08-PLC_Tails
		.word word_144B10-PLC_Tails
		.word word_144B08-PLC_Tails
		.word word_144B16-PLC_Tails
		.word word_144B1E-PLC_Tails
		.word word_144B26-PLC_Tails
		.word word_144B2C-PLC_Tails
		.word word_144B36-PLC_Tails
		.word word_144B3C-PLC_Tails
		.word word_144B44-PLC_Tails
		.word word_144B4E-PLC_Tails
		.word word_144B58-PLC_Tails
		.word word_144B62-PLC_Tails
		.word word_144B6C-PLC_Tails
		.word word_144B76-PLC_Tails
		.word word_144B80-PLC_Tails
		.word word_144B8A-PLC_Tails
		.word word_144B94-PLC_Tails
		.word word_144B98-PLC_Tails
		.word word_144B9C-PLC_Tails
		.word word_144BA4-PLC_Tails
		.word word_144BAC-PLC_Tails
		.word word_144BB2-PLC_Tails
word_1445F8:	.word 0
word_1445FA:	.word 4
		.word 0x5062
		.word 0x1000
		.word 0x5002
		.word 0x7008
word_144604:	.word 4
		.word 0x5068
		.word 0x7010
		.word 0x2018
		.word 0x301B
word_14460E:	.word 3
		.word 0x506E
		.word 0x801F
		.word 0x2028
word_144616:	.word 4
		.word 0x5074
		.word 0x702B
		.word 0x2033
		.word 0x3036
word_144620:	.word 4
		.word 0x5062
		.word 0x1000
		.word 0x503A
		.word 0x7040
word_14462A:	.word 4
		.word 0x5068
		.word 0x7010
		.word 0x2048
		.word 0x304B
word_144634:	.word 3
		.word 0x506E
		.word 0x804F
		.word 0x2058
word_14463C:	.word 4
		.word 0x5074
		.word 0x702B
		.word 0x205B
		.word 0x305E
word_144646:	.word 4
		.word 0x107A
		.word 0x707C
		.word 0x2084
		.word 0x2087
word_144650:	.word 3
		.word 0xB08A
		.word 0x5096
		.word 0x209C
word_144658:	.word 4
		.word 0x109F
		.word 0x70A1
		.word 0x20A9
		.word 0x70AC
word_144662:	.word 3
		.word 0x10B4
		.word 0xF0B6
		.word 0xC6
word_14466A:	.word 3
		.word 0x20C7
		.word 0x70CA
		.word 0x50D2
word_144672:	.word 3
		.word 0x10D8
		.word 0xB0DA
		.word 0x30E6
word_14467A:	.word 3
		.word 0x10EA
		.word 0x20EC
		.word 0xB0EF
word_144682:	.word 4
		.word 0xFB
		.word 0x50FC
		.word 0x3102
		.word 0x3106
word_14468C:	.word 3
		.word 0x516D
		.word 0x110A
		.word 0xB10C
word_144694:	.word 3
		.word 0x5173
		.word 0xB118
		.word 0x124
word_14469C:	.word 3
		.word 0x5179
		.word 0x2125
		.word 0x7128
word_1446A4:	.word 2
		.word 0x517F
		.word 0xB130
word_1446AA:	.word 3
		.word 0x516D
		.word 0x113C
		.word 0xB13E
word_1446B2:	.word 2
		.word 0x5173
		.word 0xB14A
word_1446B8:	.word 3
		.word 0x5179
		.word 0x2156
		.word 0x7159
word_1446C0:	.word 2
		.word 0x517F
		.word 0xB161
word_1446C6:	.word 3
		.word 0x2185
		.word 0xB188
		.word 0x1194
word_1446CE:	.word 4
		.word 0x1196
		.word 0x2198
		.word 0xB19B
		.word 0x21A7
word_1446D8:	.word 4
		.word 0x31AA
		.word 0x31AE
		.word 0x51B2
		.word 0x51B8
word_1446E2:	.word 3
		.word 0x1BE
		.word 0xF1BF
		.word 0x11CF
word_1446EA:	.word 3
		.word 0x11D1
		.word 0xB1D3
		.word 0x21DF
word_1446F2:	.word 4
		.word 0x1E2
		.word 0x11E3
		.word 0xB1E5
		.word 0x11F1
word_1446FC:	.word 3
		.word 0x21F3
		.word 0xB1F6
		.word 0x1202
word_144704:	.word 4
		.word 0x204
		.word 0xB205
		.word 0x211
		.word 0x212
word_14470E:	.word 4
		.word 0x722B
		.word 0x5213
		.word 0x3219
		.word 0x121D
word_144718:	.word 4
		.word 0x1233
		.word 0x521F
		.word 0x3225
		.word 0x1229
word_144722:	.word 4
		.word 0x3235
		.word 0x5213
		.word 0x3219
		.word 0x121D
word_14472C:	.word 4
		.word 0x7239
		.word 0x521F
		.word 0x3225
		.word 0x1229
word_144736:	.word 4
		.word 0xB259
		.word 0x1241
		.word 0x5243
		.word 0x3249
word_144740:	.word 4
		.word 0x5265
		.word 0x124D
		.word 0x524F
		.word 0x3255
word_14474A:	.word 4
		.word 0x326B
		.word 0x1241
		.word 0x5243
		.word 0x3249
word_144754:	.word 4
		.word 0x526F
		.word 0x124D
		.word 0x524F
		.word 0x3255
word_14475E:	.word 4
		.word 0x729F
		.word 0x5287
		.word 0x328D
		.word 0x1291
word_144768:	.word 4
		.word 0x12A7
		.word 0x5293
		.word 0x3299
		.word 0x129D
word_144772:	.word 4
		.word 0x32A9
		.word 0x5287
		.word 0x328D
		.word 0x1291
word_14477C:	.word 4
		.word 0x72AD
		.word 0x5293
		.word 0x3299
		.word 0x129D
word_144786:	.word 4
		.word 0xB2CD
		.word 0x72B5
		.word 0x12BD
		.word 0x12BF
word_144790:	.word 4
		.word 0x52D9
		.word 0x72C1
		.word 0x12C9
		.word 0x12CB
word_14479A:	.word 4
		.word 0x32DF
		.word 0x72B5
		.word 0x12BD
		.word 0x12BF
word_1447A4:	.word 4
		.word 0x52E3
		.word 0x72C1
		.word 0x12C9
		.word 0x12CB
word_1447AE:	.word 1
		.word 0xB2E9
word_1447B2:	.word 2
		.word 0xB2F5
		.word 0x1301
word_1447B8:	.word 1
		.word 0xB303
word_1447BC:	.word 1
		.word 0x830F
word_1447C0:	.word 2
		.word 0x8318
		.word 0x321
word_1447C6:	.word 2
		.word 0x1322
		.word 0x8324
word_1447CC:	.word 2
		.word 0x132D
		.word 0x832F
word_1447D2:	.word 2
		.word 0x1338
		.word 0x833A
word_1447D8:	.word 2
		.word 0x1343
		.word 0x8345
word_1447DE:	.word 2
		.word 0x534E
		.word 0x1354
word_1447E4:	.word 2
		.word 0x8356
		.word 0x35F
word_1447EA:	.word 2
		.word 0x5360
		.word 0x3366
word_1447F0:	.word 2
		.word 0x83D8
		.word 0x13E1
word_1447F6:	.word 2
		.word 0x3CE
		.word 0x83CF
word_1447FC:	.word 1
		.word 0x83C5
word_144800:	.word 3
		.word 0x13BB
		.word 0x53BD
		.word 0x13C3
word_144808:	.word 1
		.word 0xB3AF
word_14480C:	.word 1
		.word 0xB3A3
word_144810:	.word 3
		.word 0x2398
		.word 0x139B
		.word 0x539D
word_144818:	.word 2
		.word 0x38E
		.word 0x838F
word_14481E:	.word 2
		.word 0x5387
		.word 0x38D
word_144824:	.word 2
		.word 0x137F
		.word 0x5381
word_14482A:	.word 3
		.word 0x1375
		.word 0x5377
		.word 0x137D
word_144832:	.word 2
		.word 0x836A
		.word 0x1373
word_144838:	.word 3
		.word 0x23E3
		.word 0x73E6
		.word 0x3EE
word_144840:	.word 2
		.word 0x23EF
		.word 0x73F2
word_144846:	.word 3
		.word 0x13FA
		.word 0x23FC
		.word 0x33FF
word_14484E:	.word 2
		.word 0x1403
		.word 0x8405
word_144854:	.word 3
		.word 0x140E
		.word 0x5410
		.word 0x1416
word_14485C:	.word 4
		.word 0x418
		.word 0x1419
		.word 0x341B
		.word 0x541F
word_144866:	.word 4
		.word 0x1425
		.word 0x3427
		.word 0x542B
		.word 0x1431
word_144870:	.word 4
		.word 0x1433
		.word 0x3435
		.word 0x5439
		.word 0x43F
word_14487A:	.word 3
		.word 0x1440
		.word 0x5442
		.word 0x1448
word_144882:	.word 3
		.word 0x144A
		.word 0x344C
		.word 0x1450
word_14488A:	.word 2
		.word 0x7452
		.word 0x245A
word_144890:	.word 2
		.word 0x245D
		.word 0x7460
word_144896:	.word 3
		.word 0x2468
		.word 0x346B
		.word 0x546F
word_14489E:	.word 1
		.word 0xB475
word_1448A2:	.word 3
		.word 0x2481
		.word 0x3484
		.word 0x2488
word_1448AA:	.word 1
		.word 0xB48B
word_1448AE:	.word 1
		.word 0xB497
word_1448B2:	.word 3
		.word 0x14A3
		.word 0x54A5
		.word 0x14AB
word_1448BA:	.word 1
		.word 0xB4AD
word_1448BE:	.word 4
		.word 0x24B9
		.word 0x14BC
		.word 0x74BE
		.word 0x34C6
word_1448C8:	.word 1
		.word 0xB4CA
word_1448CC:	.word 3
		.word 0xB4D6
		.word 0x4E2
		.word 0x4E3
word_1448D4:	.word 2
		.word 0xB4E4
		.word 0x54F0
word_1448DA:	.word 1
		.word 0xB4F6
word_1448DE:	.word 1
		.word 0xB502
word_1448E2:	.word 3
		.word 0x250E
		.word 0x7511
		.word 0x1519
word_1448EA:	.word 4
		.word 0x851B
		.word 0x1524
		.word 0x2526
		.word 0x2529
word_1448F4:	.word 1
		.word 0xB52C
word_1448F8:	.word 2
		.word 0xB538
		.word 0x2544
word_1448FE:	.word 2
		.word 0xB547
		.word 0x5553
word_144904:	.word 1
		.word 0xB559
word_144908:	.word 1
		.word 0xB565
word_14490C:	.word 3
		.word 0x2571
		.word 0xB574
		.word 0x580
word_144914:	.word 3
		.word 0x1581
		.word 0x7583
		.word 0x258B
word_14491C:	.word 2
		.word 0x158E
		.word 0x8590
word_144922:	.word 2
		.word 0x2599
		.word 0x759C
word_144928:	.word 2
		.word 0x25A4
		.word 0x75A7
word_14492E:	.word 2
		.word 0x75AF
		.word 0x25B7
word_144934:	.word 2
		.word 0x55BA
		.word 0x15C0
word_14493A:	.word 2
		.word 0x55C2
		.word 0x35C8
word_144940:	.word 2
		.word 0x75CC
		.word 0x25D4
word_144946:	.word 1
		.word 0xB5D7
word_14494A:	.word 2
		.word 0xB5E3
		.word 0x15EF
word_144950:	.word 1
		.word 0xB5F1
word_144954:	.word 1
		.word 0x85FD
word_144958:	.word 2
		.word 0x2606
		.word 0x7609
word_14495E:	.word 2
		.word 0x2611
		.word 0x7614
word_144964:	.word 4
		.word 0x361C
		.word 0x5620
		.word 0x3626
		.word 0x262A
word_14496E:	.word 4
		.word 0x162D
		.word 0x562F
		.word 0x1635
		.word 0x5637
word_144978:	.word 4
		.word 0x63D
		.word 0x563E
		.word 0x5644
		.word 0x364A
word_144982:	.word 4
		.word 0x164E
		.word 0x5650
		.word 0x5656
		.word 0x165C
word_14498C:	.word 4
		.word 0x361C
		.word 0x5620
		.word 0x3626
		.word 0x262A
word_144996:	.word 4
		.word 0x162D
		.word 0x562F
		.word 0x1635
		.word 0x5637
word_1449A0:	.word 4
		.word 0x63D
		.word 0x563E
		.word 0x565E
		.word 0x364A
word_1449AA:	.word 4
		.word 0x164E
		.word 0x5650
		.word 0x5656
		.word 0x165C
word_1449B4:	.word 2
		.word 0x7664
		.word 0x866C
word_1449BA:	.word 4
		.word 0x3675
		.word 0x2679
		.word 0xB67C
		.word 0x1688
word_1449C4:	.word 4
		.word 0x868A
		.word 0x1693
		.word 0x3695
		.word 0x3699
word_1449CE:	.word 3
		.word 0xF69D
		.word 0x6AD
		.word 0x26AE
word_1449D6:	.word 3
		.word 0x56B1
		.word 0x76B7
		.word 0x36BF
word_1449DE:	.word 4
		.word 0x56C3
		.word 0x36C9
		.word 0x26CD
		.word 0x36D0
word_1449E8:	.word 2
		.word 0x36D4
		.word 0x56D8
word_1449EE:	.word 2
		.word 0x76DE
		.word 0x26E6
word_1449F4:	.word 2
		.word 0x36E9
		.word 0x56ED
word_1449FA:	.word 1
		.word 0xF6F3
word_1449FE:	.word 1
		.word 0xF703
word_144A02:	.word 2
		.word 0x3713
		.word 0xB717
word_144A08:	.word 2
		.word 0x3713
		.word 0xB723
word_144A0E:	.word 2
		.word 0x172F
		.word 0xB731
word_144A14:	.word 3
		.word 0x5830
		.word 0x3836
		.word 0x283A
word_144A1C:	.word 3
		.word 0x583D
		.word 0x3843
		.word 0x2847
word_144A24:	.word 2
		.word 0xB73D
		.word 0x1749
word_144A2A:	.word 2
		.word 0x574B
		.word 0x7751
word_144A30:	.word 2
		.word 0x5759
		.word 0x775F
word_144A36:	.word 1
		.word 0x8767
word_144A3A:	.word 3
		.word 0x7770
		.word 0xB77E
		.word 0x278A
word_144A42:	.word 3
		.word 0x5778
		.word 0xB77E
		.word 0x278A
word_144A4A:	.word 1
		.word 0xF78D
word_144A4E:	.word 1
		.word 0xF79D
word_144A52:	.word 1
		.word 0xF7AD
word_144A56:	.word 1
		.word 0x8800
word_144A5A:	.word 3
		.word 0x2862
		.word 0x7865
		.word 0x186D
word_144A62:	.word 3
		.word 0x586F
		.word 0x3875
		.word 0x2879
word_144A6A:	.word 1
		.word 0xF7ED
word_144A6E:	.word 2
		.word 0x787C
		.word 0x8884
word_144A74:	.word 3
		.word 0x188D
		.word 0xB88F
		.word 0x289B
word_144A7C:	.word 3
		.word 0x289E
		.word 0x78A1
		.word 0x28A9
word_144A84:	.word 2
		.word 0x28AC
		.word 0xB8AF
word_144A8A:	.word 2
		.word 0x28BB
		.word 0xB8BE
word_144A90:	.word 2
		.word 0x28AC
		.word 0xB8CA
word_144A96:	.word 2
		.word 0x28D6
		.word 0xB8D9
word_144A9C:	.word 2
		.word 0x28E5
		.word 0xB8E8
word_144AA2:	.word 1
		.word 0xB8F8
word_144AA6:	.word 4
		.word 0x904
		.word 0x7905
		.word 0x790D
		.word 0x915
word_144AB0:	.word 2
		.word 0x7AD0
		.word 0x8AD8
word_144AB6:	.word 3
		.word 0x2AE1
		.word 0x7AE4
		.word 0x5AEC
word_144ABE:	.word 2
		.word 0x8916
		.word 0x391F
word_144AC4:	.word 1
		.word 0xB923
word_144AC8:	.word 1
		.word 0xB92F
word_144ACC:	.word 1
		.word 0xB93B
word_144AD0:	.word 1
		.word 0xB947
word_144AD4:	.word 1
		.word 0xB953
word_144AD8:	.word 1
		.word 0xB95F
word_144ADC:	.word 1
		.word 0xB96B
word_144AE0:	.word 1
		.word 0xB977
word_144AE4:	.word 1
		.word 0xB983
word_144AE8:	.word 1
		.word 0xB98F
word_144AEC:	.word 1
		.word 0xB99B
word_144AF0:	.word 3
		.word 0x9A7
		.word 0x79A8
		.word 0x39B0
word_144AF8:	.word 2
		.word 0x89B4
		.word 0x39BD
word_144AFE:	.word 1
		.word 0xB9C1
word_144B02:	.word 2
		.word 0x89B4
		.word 0x39BD
word_144B08:	.word 3
		.word 0x19CD
		.word 0x79CF
		.word 0x19D7
word_144B10:	.word 2
		.word 0x59D9
		.word 0x39DF
word_144B16:	.word 3
		.word 0x19E3
		.word 0xB9E5
		.word 0x29F1
word_144B1E:	.word 3
		.word 0xB9F4
		.word 0x1A00
		.word 0x2A02
word_144B26:	.word 2
		.word 0xFA05
		.word 0xA15
word_144B2C:	.word 4
		.word 0x7A16
		.word 0xA1E
		.word 0x7A1F
		.word 0xA27
word_144B36:	.word 2
		.word 0xFA28
		.word 0x1A38
word_144B3C:	.word 3
		.word 0xBA3A
		.word 0x2A46
		.word 0x1A49
word_144B44:	.word 4
		.word 0x7239
		.word 0x5213
		.word 0x3219
		.word 0x121D
word_144B4E:	.word 4
		.word 0x7239
		.word 0x521F
		.word 0x3225
		.word 0x1229
word_144B58:	.word 4
		.word 0x8275
		.word 0x1241
		.word 0x5243
		.word 0x3249
word_144B62:	.word 4
		.word 0x827E
		.word 0x124D
		.word 0x524F
		.word 0x3255
word_144B6C:	.word 4
		.word 0x72AD
		.word 0x5287
		.word 0x328D
		.word 0x1291
word_144B76:	.word 4
		.word 0x72AD
		.word 0x5293
		.word 0x3299
		.word 0x129D
word_144B80:	.word 4
		.word 0x827E
		.word 0x72B5
		.word 0x12BD
		.word 0x12BF
word_144B8A:	.word 4
		.word 0x8275
		.word 0x72C1
		.word 0x12C9
		.word 0x12CB
word_144B94:	.word 1
		.word 0xF6F3
word_144B98:	.word 1
		.word 0xF703
word_144B9C:	.word 3
		.word 0x1AF2
		.word 0xBAF4
		.word 0xA48
word_144BA4:	.word 3
		.word 0x1B00
		.word 0xBB02
		.word 0xA48
word_144BAC:	.word 2
		.word 0x1B0E
		.word 0xBB10
word_144BB2:	.word 2
		.word 0x1B1C
		.word 0xBB1E
