Map_6731C:		.word word_67328-Map_6731C
		.word word_6732A-Map_6731C
		.word word_67332-Map_6731C
		.word word_6733A-Map_6731C
		.word word_67342-Map_6731C
		.word word_6734A-Map_6731C
word_67328:	.word 0			
word_6732A:	.word 1			
		.byte  0xF4,   8,	  0,   0, 0xFF, 0xF0
word_67332:	.word 1			
		.byte  0xF4,   8,	  0,   3, 0xFF, 0xF0
word_6733A:	.word 1			
		.byte  0xF4,   8,	  0,   6, 0xFF, 0xF0
word_67342:	.word 1			
		.byte  0xF4,   8,	  0,   9, 0xFF, 0xF0
word_6734A:	.word 1			
		.byte  0xF4,   8,	  0,  0xC, 0xFF, 0xF0
