Map_9147E:		.word word_9148E-Map_9147E
		.word word_91496-Map_9147E
		.word word_9149E-Map_9147E
		.word word_914A6-Map_9147E
		.word word_914AE-Map_9147E
		.word word_914B6-Map_9147E
		.word word_914BE-Map_9147E
		.word word_914C6-Map_9147E
word_9148E:	.word 1			
		.byte  0xFC,   0,	  0,   6, 0xFF, 0xFC
word_91496:	.word 1			
		.byte  0xFC,   0,	  0,   2, 0xFF, 0xFC
word_9149E:	.word 1			
		.byte  0xFC,   0,	  0,   5, 0xFF, 0xFC
word_914A6:	.word 1			
		.byte  0xFC,   0,	  0,   0, 0xFF, 0xFC
word_914AE:	.word 1			
		.byte  0xFC,   0,	  0,   7, 0xFF, 0xFC
word_914B6:	.word 1			
		.byte  0xFC,   0,	  0,   1, 0xFF, 0xFC
word_914BE:	.word 1			
		.byte  0xFC,   0,	  0,   3, 0xFF, 0xFC
word_914C6:	.word 1			
		.byte  0xFC,   0,	  0,   4, 0xFF, 0xFC
