DPLC_8E4B8:		.word word_8E4D4-DPLC_8E4B8
		.word word_8E4DC-DPLC_8E4B8
		.word word_8E4E4-DPLC_8E4B8
		.word word_8E4EC-DPLC_8E4B8
		.word word_8E4F2-DPLC_8E4B8
		.word word_8E4F8-DPLC_8E4B8
		.word word_8E4FE-DPLC_8E4B8
		.word word_8E506-DPLC_8E4B8
		.word word_8E50E-DPLC_8E4B8
		.word word_8E516-DPLC_8E4B8
		.word word_8E51C-DPLC_8E4B8
		.word word_8E522-DPLC_8E4B8
		.word word_8E528-DPLC_8E4B8
		.word word_8E52E-DPLC_8E4B8
word_8E4D4:	.word 2			
		.word 8
		.word 0x91
		.word 0xB1
word_8E4DC:	.word 2			
		.word 0xD8
		.word 0x91
		.word 0xB1
word_8E4E4:	.word 2			
		.word 0x168
		.word 0x91
		.word 0xB1
word_8E4EC:	.word 1			
		.word 0x1FB
		.word 0xB1
word_8E4F2:	.word 1			
		.word 0x2BB
		.word 0x372
word_8E4F8:	.word 1			
		.word 0x3AB
		.word 0x462
word_8E4FE:	.word 2			
		.word 0x492
		.word 0x4CB
		.word 0x581
word_8E506:	.word 2			
		.word 0x5A2
		.word 0x5DB
		.word 0x581
word_8E50E:	.word 2			
		.word 0x691
		.word 0x6BB
		.word 0x581
word_8E516:	.word 1			
		.word 0x77B
		.word 0x831
word_8E51C:	.word 1			
		.word 0x85B
		.word 0x581
word_8E522:	.word 1			
		.word 0x9DB
		.word 0x441
word_8E528:	.word 1			
		.word 0x91B
		.word 0x91
word_8E52E:	.word 2			
		.word 0xA98
		.word 0xB1
		.word 0x91
