/* Cluckoid mappings*/
		.word word_8E562-Map_Cluckoid
		.word word_8E576-Map_Cluckoid
		.word word_8E58A-Map_Cluckoid
		.word word_8E59E-Map_Cluckoid
		.word word_8E5AC-Map_Cluckoid
		.word word_8E5BA-Map_Cluckoid
		.word word_8E5C8-Map_Cluckoid
		.word word_8E5DC-Map_Cluckoid
		.word word_8E5F0-Map_Cluckoid
		.word word_8E604-Map_Cluckoid
		.word word_8E612-Map_Cluckoid
		.word word_8E620-Map_Cluckoid
		.word word_8E62E-Map_Cluckoid
		.word word_8E63C-Map_Cluckoid
word_8E562:	.word 3			/* DATA XREF: ROM:0008E546o*/
		.byte  0xF0,  0xA,	  0,   0, 0xFF, 0xF0
		.byte  0xF8,   1,	  0,   9,   0,	 8
		.byte	8,   4,	  0,  0xB, 0xFF, 0xF8
word_8E576:	.word 3			/* DATA XREF: ROM:0008E546o*/
		.byte  0xF0,  0xA,	  0,   0, 0xFF, 0xF0
		.byte  0xF8,   1,	  0,   9,   0,	 8
		.byte	8,   4,	  0,  0xB, 0xFF, 0xF8
word_8E58A:	.word 3			/* DATA XREF: ROM:0008E546o*/
		.byte  0xF0,  0xA,	  0,   0, 0xFF, 0xF0
		.byte  0xF8,   1,	  0,   9,   0,	 8
		.byte	8,   4,	  0,  0xB, 0xFF, 0xF8
word_8E59E:	.word 2			/* DATA XREF: ROM:0008E546o*/
		.byte  0xF0,  0xE,	  0,   0, 0xFF, 0xF0
		.byte	8,   4,	  0,  0xC, 0xFF, 0xF8
word_8E5AC:	.word 2			/* DATA XREF: ROM:0008E546o*/
		.byte  0xF0,  0xE,	  0,   0, 0xFF, 0xF0
		.byte	8,   8,	  0,  0xC, 0xFF, 0xF0
word_8E5BA:	.word 2			/* DATA XREF: ROM:0008E546o*/
		.byte  0xF0,  0xE,	  0,   0, 0xFF, 0xF0
		.byte	8,   8,	  0,  0xC, 0xFF, 0xF0
word_8E5C8:	.word 3			/* DATA XREF: ROM:0008E546o*/
		.byte  0xF0,   8,	  0,   0, 0xFF, 0xF0
		.byte  0xF8,  0xE,	  0,   3, 0xFF, 0xE8
		.byte  0xF8,   1,	  0,  0xF,   0,	 8
word_8E5DC:	.word 3			/* DATA XREF: ROM:0008E546o*/
		.byte  0xF0,   8,	  0,   0, 0xFF, 0xF0
		.byte  0xF8,  0xE,	  0,   3, 0xFF, 0xE8
		.byte  0xF8,   1,	  0,  0xF,   0,	 8
word_8E5F0:	.word 3			/* DATA XREF: ROM:0008E546o*/
		.byte	0,   1,	  0,   0, 0xFF, 0xE8
		.byte  0xF0,  0xB,	  0,   2, 0xFF, 0xF0
		.byte  0xF8,   1,	  0,  0xE,   0,	 8
word_8E604:	.word 2			/* DATA XREF: ROM:0008E546o*/
		.byte  0xF0,  0xB,	  0,   0, 0xFF, 0xED
		.byte  0xF8,   1,	  0,  0xC,   0,	 5
word_8E612:	.word 2			/* DATA XREF: ROM:0008E546o*/
		.byte  0xF0,  0xB,	  0,   0, 0xFF, 0xF0
		.byte  0xF8,   1,	  0,  0xC,   0,	 8
word_8E620:	.word 2			/* DATA XREF: ROM:0008E546o*/
		.byte  0xF0,  0xB,	  0,   0, 0xFF, 0xF0
		.byte  0xF8,   1,	  0,  0xC,   0,	 8
word_8E62E:	.word 2			/* DATA XREF: ROM:0008E546o*/
		.byte  0xF0,  0xB,	  0,   0, 0xFF, 0xF0
		.byte  0xF8,   1,	  0,  0xC,   0,	 8
word_8E63C:	.word 3			/* DATA XREF: ROM:0008E546o*/
		.byte  0xF0,  0xA,	  0,   0, 0xFF, 0xF0
		.byte	8,   4,	  0,   9, 0xFF, 0xF8
		.byte  0xF8,   1,	  0,  0xB,   0,	 8
