		.word word_30F8C-Map_HCZCNZDEZDoor
		.word word_30F9A-Map_HCZCNZDEZDoor
		.word word_30FB4-Map_HCZCNZDEZDoor
word_30F8C:	.word 2			/* DATA XREF: ROM:00030F86o*/
		.byte  0xE0,  0xF,	  0,   0, 0xFF, 0xF0
		.byte	0,  0xF,	  0,   0, 0xFF, 0xF0
word_30F9A:	.word 4			/* DATA XREF: ROM:00030F86o*/
		.byte  0xE0,   5,	  0,   0, 0xFF, 0xF8
		.byte  0xF0,   5,	  0,   0, 0xFF, 0xF8
		.byte	0,   5,	  0,   0, 0xFF, 0xF8
		.byte  0x10,   5,	  0,   0, 0xFF, 0xF8
word_30FB4:	.word 4			/* DATA XREF: ROM:00030F86o*/
		.byte  0xE0,   7,	  0,   0, 0xFF, 0xF0
		.byte  0xE0,   7,	  8,   0,   0,	 0
		.byte	0,   7,	  0,   0, 0xFF, 0xF0
		.byte	0,   7,	  8,   0,   0,	 0
