		.word word_209FE-Map_AIZRideVine
		.word word_20A06-Map_AIZRideVine
		.word word_20A0E-Map_AIZRideVine
		.word word_20A16-Map_AIZRideVine
		.word word_20A1E-Map_AIZRideVine
		.word word_20A26-Map_AIZRideVine
		.word word_20A2E-Map_AIZRideVine
		.word word_20A36-Map_AIZRideVine
		.word word_20A3E-Map_AIZRideVine
		.word word_20A46-Map_AIZRideVine
		.word word_20A4E-Map_AIZRideVine
		.word word_20A56-Map_AIZRideVine
		.word word_20A5E-Map_AIZRideVine
		.word word_20A66-Map_AIZRideVine
		.word word_20A6E-Map_AIZRideVine
		.word word_20A76-Map_AIZRideVine
		.word word_20A7E-Map_AIZRideVine
		.word word_20A86-Map_AIZRideVine
		.word word_20A8E-Map_AIZRideVine
		.word word_20A96-Map_AIZRideVine
		.word word_20A9E-Map_AIZRideVine
		.word word_20AA6-Map_AIZRideVine
		.word word_20AAE-Map_AIZRideVine
		.word word_20AB6-Map_AIZRideVine
		.word word_20ABE-Map_AIZRideVine
		.word word_20AC6-Map_AIZRideVine
		.word word_20ACE-Map_AIZRideVine
		.word word_20AD6-Map_AIZRideVine
		.word word_20ADE-Map_AIZRideVine
		.word word_20AE6-Map_AIZRideVine
		.word word_20AEE-Map_AIZRideVine
		.word word_20AF6-Map_AIZRideVine
		.word word_20AFE-Map_AIZRideVine
		.word word_20B06-Map_AIZRideVine
word_209FE:	.word 1
		.byte    0,   1,   0, 0x1B, 0xFF, 0xF8
word_20A06:	.word 1
		.byte    0,   1,   0, 0x19, 0xFF, 0xF8
word_20A0E:	.word 1
		.byte    0,   1,   0, 0x17, 0xFF, 0xF8
word_20A16:	.word 1
		.byte    0,   5,   0, 0x13, 0xFF, 0xF0
word_20A1E:	.word 1
		.byte    0,   5,   0,  0xF, 0xFF, 0xF0
word_20A26:	.word 1
		.byte    0,   5,   0,  0xB, 0xFF, 0xF0
word_20A2E:	.word 1
		.byte    0,   4,   0,   9, 0xFF, 0xF0
word_20A36:	.word 1
		.byte    0,   4,   0,   7, 0xFF, 0xF0
word_20A3E:	.word 1
		.byte    0,   4,   0,   5, 0xFF, 0xF0
word_20A46:	.word 1
		.byte  0xF9,   4, 0x10,   7, 0xFF, 0xF0
word_20A4E:	.word 1
		.byte  0xF9,   4, 0x10,   9, 0xFF, 0xF0
word_20A56:	.word 1
		.byte  0xF1,   5, 0x10,  0xB, 0xFF, 0xF0
word_20A5E:	.word 1
		.byte  0xF1,   5, 0x10,  0xF, 0xFF, 0xF0
word_20A66:	.word 1
		.byte  0xF1,   5, 0x10, 0x13, 0xFF, 0xF0
word_20A6E:	.word 1
		.byte  0xF1,   1, 0x10, 0x17, 0xFF, 0xF8
word_20A76:	.word 1
		.byte  0xF1,   1, 0x10, 0x19, 0xFF, 0xF8
word_20A7E:	.word 1
		.byte  0xF1,   1, 0x10, 0x1B, 0xFF, 0xF8
word_20A86:	.word 1
		.byte  0xF1,   1, 0x18, 0x19, 0xFF, 0xFF
word_20A8E:	.word 1
		.byte  0xF1,   1, 0x18, 0x17, 0xFF, 0xFF
word_20A96:	.word 1
		.byte  0xF1,   5, 0x18, 0x13, 0xFF, 0xFF
word_20A9E:	.word 1
		.byte  0xF1,   5, 0x18,  0xF, 0xFF, 0xFF
word_20AA6:	.word 1
		.byte  0xF1,   5, 0x18,  0xB, 0xFF, 0xFF
word_20AAE:	.word 1
		.byte  0xF9,   4, 0x18,   9, 0xFF, 0xFF
word_20AB6:	.word 1
		.byte  0xF9,   4, 0x18,   7, 0xFF, 0xFF
word_20ABE:	.word 1
		.byte    0,   4,   8,   5, 0xFF, 0xFF
word_20AC6:	.word 1
		.byte    0,   4,   8,   7, 0xFF, 0xFF
word_20ACE:	.word 1
		.byte    0,   4,   8,   9, 0xFF, 0xFF
word_20AD6:	.word 1
		.byte    0,   5,   8,  0xB, 0xFF, 0xFF
word_20ADE:	.word 1
		.byte    0,   5,   8,  0xF, 0xFF, 0xFF
word_20AE6:	.word 1
		.byte    0,   5,   8, 0x13, 0xFF, 0xFF
word_20AEE:	.word 1
		.byte    0,   1,   8, 0x17, 0xFF, 0xFF
word_20AF6:	.word 1
		.byte    0,   1,   8, 0x19, 0xFF, 0xFF
word_20AFE:	.word 1
		.byte  0xFC,   8,   0,   0, 0xFF, 0xF4
word_20B06:	.word 1
		.byte  0xFC,   4,   0,   3, 0xFF, 0xF8
