Map_AIZ2BombExplode_:.word word_23C1CA-Map_AIZ2BombExplode_
		.word word_23C1D2-Map_AIZ2BombExplode_
		.word word_23C1DA-Map_AIZ2BombExplode_
		.word word_23C1E2-Map_AIZ2BombExplode_
		.word word_23C1EA-Map_AIZ2BombExplode_
		.word word_23C1F2-Map_AIZ2BombExplode_
		.word word_23C1FA-Map_AIZ2BombExplode_
		.word word_23C202-Map_AIZ2BombExplode_
		.word word_23C20A-Map_AIZ2BombExplode_
		.word word_23C212-Map_AIZ2BombExplode_
		.word word_23C21A-Map_AIZ2BombExplode_
		.word word_23C222-Map_AIZ2BombExplode_
word_23C1CA:     .word 1
		.byte 0xF0, 0xB,0x20,  8,0xFF,0xF4
word_23C1D2:     .word 1
		.byte 0xFC, 0xE,  0,0x14,0xFF,0xF0
word_23C1DA:     .word 1
		.byte 0xF4, 0xF,  0,0x20,0xFF,0xF0
word_23C1E2:     .word 1
		.byte 0xF4, 0xF,  0,0x30,0xFF,0xF0
word_23C1EA:     .word 1
		.byte 0xF4, 0xE,  0,0x40,0xFF,0xF0
word_23C1F2:     .word 1
		.byte 0xF4, 0xE,  0,0x4C,0xFF,0xF0
word_23C1FA:     .word 1
		.byte   0,  5,  0,0x58,0xFF,0xF8
word_23C202:     .word 1
		.byte 0xFC, 0xA,  0,0x5C,0xFF,0xF4
word_23C20A:     .word 1
		.byte 0xFC, 0xA,  0,0x65,0xFF,0xF4
word_23C212:     .word 1
		.byte 0xFC, 0xA,  0,0x6E,0xFF,0xF4
word_23C21A:     .word 1
		.byte 0xFC, 0xA,  0,0x77,0xFF,0xF4
word_23C222:     .word 1
		.byte 0xFC,  9,  0,0x80,0xFF,0xF4
