Map_AIZRideVine_:.word word_22BE6-Map_AIZRideVine_
		.word word_22BEE-Map_AIZRideVine_
		.word word_22BF6-Map_AIZRideVine_
		.word word_22BFE-Map_AIZRideVine_
		.word word_22C06-Map_AIZRideVine_
		.word word_22C0E-Map_AIZRideVine_
		.word word_22C16-Map_AIZRideVine_
		.word word_22C1E-Map_AIZRideVine_
		.word word_22C26-Map_AIZRideVine_
		.word word_22C2E-Map_AIZRideVine_
		.word word_22C36-Map_AIZRideVine_
		.word word_22C3E-Map_AIZRideVine_
		.word word_22C46-Map_AIZRideVine_
		.word word_22C4E-Map_AIZRideVine_
		.word word_22C56-Map_AIZRideVine_
		.word word_22C5E-Map_AIZRideVine_
		.word word_22C66-Map_AIZRideVine_
		.word word_22C6E-Map_AIZRideVine_
		.word word_22C76-Map_AIZRideVine_
		.word word_22C7E-Map_AIZRideVine_
		.word word_22C86-Map_AIZRideVine_
		.word word_22C8E-Map_AIZRideVine_
		.word word_22C96-Map_AIZRideVine_
		.word word_22C9E-Map_AIZRideVine_
		.word word_22CA6-Map_AIZRideVine_
		.word word_22CAE-Map_AIZRideVine_
		.word word_22CB6-Map_AIZRideVine_
		.word word_22CBE-Map_AIZRideVine_
		.word word_22CC6-Map_AIZRideVine_
		.word word_22CCE-Map_AIZRideVine_
		.word word_22CD6-Map_AIZRideVine_
		.word word_22CDE-Map_AIZRideVine_
		.word word_22CE6-Map_AIZRideVine_
		.word word_22CEE-Map_AIZRideVine_
		.word word_22CF6-Map_AIZRideVine_
		.word word_22CFE-Map_AIZRideVine_
word_22BE6:	.word 1			/* DATA XREF: ROM:00022B9Eo*/
		.byte	0,   1,	  0, 0x1B, 0xFF, 0xF8
word_22BEE:	.word 1			/* DATA XREF: ROM:00022B9Eo*/
		.byte	0,   1,	  0, 0x19, 0xFF, 0xF8
word_22BF6:	.word 1			/* DATA XREF: ROM:00022B9Eo*/
		.byte	0,   1,	  0, 0x17, 0xFF, 0xF8
word_22BFE:	.word 1			/* DATA XREF: ROM:00022B9Eo*/
		.byte	0,   5,	  0, 0x13, 0xFF, 0xF0
word_22C06:	.word 1			/* DATA XREF: ROM:00022B9Eo*/
		.byte	0,   5,	  0,  0xF, 0xFF, 0xF0
word_22C0E:	.word 1			/* DATA XREF: ROM:00022B9Eo*/
		.byte	0,   5,	  0,  0xB, 0xFF, 0xF0
word_22C16:	.word 1			/* DATA XREF: ROM:00022B9Eo*/
		.byte	0,   4,	  0,   9, 0xFF, 0xF0
word_22C1E:	.word 1			/* DATA XREF: ROM:00022B9Eo*/
		.byte	0,   4,	  0,   7, 0xFF, 0xF0
word_22C26:	.word 1			/* DATA XREF: ROM:00022B9Eo*/
		.byte	0,   4,	  0,   5, 0xFF, 0xF0
word_22C2E:	.word 1			/* DATA XREF: ROM:00022B9Eo*/
		.byte  0xF9,   4,	0x10,   7, 0xFF, 0xF0
word_22C36:	.word 1			/* DATA XREF: ROM:00022B9Eo*/
		.byte  0xF9,   4,	0x10,   9, 0xFF, 0xF0
word_22C3E:	.word 1			/* DATA XREF: ROM:00022B9Eo*/
		.byte  0xF1,   5,	0x10,  0xB, 0xFF, 0xF0
word_22C46:	.word 1			/* DATA XREF: ROM:00022B9Eo*/
		.byte  0xF1,   5,	0x10,  0xF, 0xFF, 0xF0
word_22C4E:	.word 1			/* DATA XREF: ROM:00022B9Eo*/
		.byte  0xF1,   5,	0x10, 0x13, 0xFF, 0xF0
word_22C56:	.word 1			/* DATA XREF: ROM:00022B9Eo*/
		.byte  0xF1,   1,	0x10, 0x17, 0xFF, 0xF8
word_22C5E:	.word 1			/* DATA XREF: ROM:00022B9Eo*/
		.byte  0xF1,   1,	0x10, 0x19, 0xFF, 0xF8
word_22C66:	.word 1			/* DATA XREF: ROM:00022B9Eo*/
		.byte  0xF1,   1,	0x10, 0x1B, 0xFF, 0xF8
word_22C6E:	.word 1			/* DATA XREF: ROM:00022B9Eo*/
		.byte  0xF1,   1,	0x18, 0x19, 0xFF, 0xFF
word_22C76:	.word 1			/* DATA XREF: ROM:00022B9Eo*/
		.byte  0xF1,   1,	0x18, 0x17, 0xFF, 0xFF
word_22C7E:	.word 1			/* DATA XREF: ROM:00022B9Eo*/
		.byte  0xF1,   5,	0x18, 0x13, 0xFF, 0xFF
word_22C86:	.word 1			/* DATA XREF: ROM:00022B9Eo*/
		.byte  0xF1,   5,	0x18,  0xF, 0xFF, 0xFF
word_22C8E:	.word 1			/* DATA XREF: ROM:00022B9Eo*/
		.byte  0xF1,   5,	0x18,  0xB, 0xFF, 0xFF
word_22C96:	.word 1			/* DATA XREF: ROM:00022B9Eo*/
		.byte  0xF9,   4,	0x18,   9, 0xFF, 0xFF
word_22C9E:	.word 1			/* DATA XREF: ROM:00022B9Eo*/
		.byte  0xF9,   4,	0x18,   7, 0xFF, 0xFF
word_22CA6:	.word 1			/* DATA XREF: ROM:00022B9Eo*/
		.byte	0,   4,	  8,   5, 0xFF, 0xFF
word_22CAE:	.word 1			/* DATA XREF: ROM:00022B9Eo*/
		.byte	0,   4,	  8,   7, 0xFF, 0xFF
word_22CB6:	.word 1			/* DATA XREF: ROM:00022B9Eo*/
		.byte	0,   4,	  8,   9, 0xFF, 0xFF
word_22CBE:	.word 1			/* DATA XREF: ROM:00022B9Eo*/
		.byte	0,   5,	  8,  0xB, 0xFF, 0xFF
word_22CC6:	.word 1			/* DATA XREF: ROM:00022B9Eo*/
		.byte	0,   5,	  8,  0xF, 0xFF, 0xFF
word_22CCE:	.word 1			/* DATA XREF: ROM:00022B9Eo*/
		.byte	0,   5,	  8, 0x13, 0xFF, 0xFF
word_22CD6:	.word 1			/* DATA XREF: ROM:00022B9Eo*/
		.byte	0,   1,	  8, 0x17, 0xFF, 0xFF
word_22CDE:	.word 1			/* DATA XREF: ROM:00022B9Eo*/
		.byte	0,   1,	  8, 0x19, 0xFF, 0xFF
word_22CE6:	.word 1			/* DATA XREF: ROM:00022B9Eo*/
		.byte  0xFC,   8,	  0,   0, 0xFF, 0xF4
word_22CEE:	.word 1			/* DATA XREF: ROM:00022B9Eo*/
		.byte  0xFC,   4,	  0,   3, 0xFF, 0xF8
word_22CF6:	.word 1			/* DATA XREF: ROM:00022B9Eo*/
		.byte  0xFC,   8,	  0, 0x20, 0xFF, 0xF4
word_22CFE:	.word 1			/* DATA XREF: ROM:00022B9Eo*/
		.byte  0xFC,   8,	  0, 0x1D, 0xFF, 0xF7

