Map_AIZShipPropeller_:.word word_23C18A-Map_AIZShipPropeller_
		.word word_23C192-Map_AIZShipPropeller_
		.word word_23C19A-Map_AIZShipPropeller_
		.word word_23C1A2-Map_AIZShipPropeller_
word_23C18A:     .word 1
		.byte 0xF0,  3,0xA0,  0,0xFF,0xFC
word_23C192:     .word 1
		.byte 0xF4,  2,0xA0,  4,0xFF,0xFC
word_23C19A:     .word 1
		.byte 0xFC,  0,0xA0,  7,0xFF,0xFC
word_23C1A2:     .word 1
		.byte 0xF4,  2,0xB0,  4,0xFF,0xFC
