		.word	word_2B076-Map_AIZCollapsingLogBridge
		.word word_2B076-Map_AIZCollapsingLogBridge
		.word word_2B07E-Map_AIZCollapsingLogBridge
word_2B076:	.word 1			/* DATA XREF: ROM:0002B070o*/
		.byte  0xF8,  0xD,	  0, 0x2D, 0xFF, 0xF0
word_2B07E:	.word 3			/* DATA XREF: ROM:0002B070o*/
		.byte  0xF8,  0xD,	  0, 0x2D, 0xFF, 0xF0
		.byte	8,   8,	  1, 0x2D, 0xFF, 0xF8
		.byte  0x10,   4,	  1, 0x30,   0,	 0
