DPLC_31B72:		.word word_31B9A-DPLC_31B72
		.word word_31B94-DPLC_31B72
		.word word_31B8E-DPLC_31B72
		.word word_31B88-DPLC_31B72
		.word word_31B84-DPLC_31B72
		.word word_31B88-DPLC_31B72
		.word word_31B8E-DPLC_31B72
		.word word_31B94-DPLC_31B72
		.word word_31B9A-DPLC_31B72
word_31B84:	.word 1			/* DATA XREF: ROM:00031B72o*/
		.word 0xB000
word_31B88:	.word 2			/* DATA XREF: ROM:00031B72o*/
		.word 0x700C
		.word 0x8014
word_31B8E:	.word 2			/* DATA XREF: ROM:00031B72o*/
		.word 0x701D
		.word 0xB025
word_31B94:	.word 2			/* DATA XREF: ROM:00031B72o*/
		.word 0x7031
		.word 0x8039
word_31B9A:	.word 1			/* DATA XREF: ROM:00031B72o*/
		.word 0xB042
