DPLC_8E160:		.word word_8E16A-DPLC_8E160
		.word word_8E16E-DPLC_8E160
		.word word_8E172-DPLC_8E160
		.word word_8E176-DPLC_8E160
		.word word_8E17A-DPLC_8E160
word_8E16A:	.word 0			/*  DATA XREF: ROM:0008E160o */
		.word 8
word_8E16E:	.word 0			/*  DATA XREF: ROM:0008E160o */
		.word 0x98
word_8E172:	.word 0			/*  DATA XREF: ROM:0008E160o */
		.word 0x127
word_8E176:	.word 0			/*  DATA XREF: ROM:0008E160o */
		.word 0x1A7
word_8E17A:	.word 0			/*  DATA XREF: ROM:0008E160o */
		.word 0x228
