/*  Butterdroid mappings */
		.word word_8E138-Map_Butterdroid
		.word word_8E140-Map_Butterdroid
		.word word_8E148-Map_Butterdroid
		.word word_8E150-Map_Butterdroid
		.word word_8E158-Map_Butterdroid
word_8E138:	.word 1			/*  DATA XREF: ROM:0008E12Eo */
		.byte  0xF4,  0xA,	  0,   0, 0xFF, 0xF4
word_8E140:	.word 1			/*  DATA XREF: ROM:0008E12Eo */
		.byte  0xF4,  0xA,	  0,   0, 0xFF, 0xF4
word_8E148:	.word 1			/*  DATA XREF: ROM:0008E12Eo */
		.byte  0xFC,  0xD,	  0,   0, 0xFF, 0xEF
word_8E150:	.word 1			/*  DATA XREF: ROM:0008E12Eo */
		.byte	0,  0xD,	  0,   0, 0xFF, 0xEC
word_8E158:	.word 1			/*  DATA XREF: ROM:0008E12Eo */
		.byte	0,  0xA,	  0,   0, 0xFF, 0xF4
