Map_Ring_:	.word word_1A9AC-Map_Ring_
		.word word_1A9B4-Map_Ring_
		.word word_1A9BC-Map_Ring_
		.word word_1A9C4-Map_Ring_
		.word word_1A9CC-Map_Ring_
		.word word_1A9D4-Map_Ring_
		.word word_1A9DC-Map_Ring_
		.word word_1A9E4-Map_Ring_
		.word word_1A9EC-Map_Ring_
word_1A9AC:	.word 1			/*  DATA XREF: ROM:0001A99Ao */
		.byte  0xF8,   5,	  0,   0, 0xFF, 0xF8
word_1A9B4:	.word 1			/*  DATA XREF: ROM:0001A99Ao */
		.byte  0xF8,   5,	  0,   4, 0xFF, 0xF8
word_1A9BC:	.word 1			/*  DATA XREF: ROM:0001A99Ao */
		.byte  0xF8,   1,	  0,   8, 0xFF, 0xFC
word_1A9C4:	.word 1			/*  DATA XREF: ROM:0001A99Ao */
		.byte  0xF8,   5,	  8,   4, 0xFF, 0xF8
word_1A9CC:	.word 1			/*  DATA XREF: ROM:0001A99Ao */
		.byte  0xF8,   5,	  0,  0xA, 0xFF, 0xF8
word_1A9D4:	.word 1			/*  DATA XREF: ROM:0001A99Ao */
		.byte  0xF8,   5,	0x18,  0xA, 0xFF, 0xF8
word_1A9DC:	.word 1			/*  DATA XREF: ROM:0001A99Ao */
		.byte  0xF8,   5,	  8,  0xA, 0xFF, 0xF8
word_1A9E4:	.word 1			/*  DATA XREF: ROM:0001A99Ao */
		.byte  0xF8,   5,	0x10,  0xA, 0xFF, 0xF8
word_1A9EC:	.word 0			/*  DATA XREF: ROM:0001A99Ao */
