Ani_Monitor_:	.word byte_1DB50-Ani_Monitor_
		.word byte_1DB54-Ani_Monitor_
		.word byte_1DB5C-Ani_Monitor_
		.word byte_1DB64-Ani_Monitor_
		.word byte_1DB6C-Ani_Monitor_
		.word byte_1DB74-Ani_Monitor_
		.word byte_1DB7C-Ani_Monitor_
		.word byte_1DB84-Ani_Monitor_
		.word byte_1DB8C-Ani_Monitor_
		.word byte_1DB94-Ani_Monitor_
		.word byte_1DB9C-Ani_Monitor_
byte_1DB50:	.byte	1,   0,	  1, 0xFF 
byte_1DB54:	.byte	1,   0,	  2,   2,   1,	 2,   2, 0xFF 
byte_1DB5C:	.byte	1,   0,	  3,   3,   1,	 3,   3, 0xFF 
byte_1DB64:	.byte	1,   0,	  4,   4,   1,	 4,   4, 0xFF 
byte_1DB6C:	.byte	1,   0,	  5,   5,   1,	 5,   5, 0xFF 
byte_1DB74:	.byte	1,   0,	  6,   6,   1,	 6,   6, 0xFF 
byte_1DB7C:	.byte	1,   0,	  7,   7,   1,	 7,   7, 0xFF 
byte_1DB84:	.byte	1,   0,	  8,   8,   1,	 8,   8, 0xFF 
byte_1DB8C:	.byte	1,   0,	  9,   9,   1,	 9,   9, 0xFF 
byte_1DB94:	.byte	1,   0,	 0xA,  0xA,   1,	0xA,  0xA, 0xFF 
byte_1DB9C:	.byte	2,   0,	  1,  0xB, 0xFE,	 1 
