Map_Monitor_:	.word word_1DBBA-Map_Monitor_
		.word word_1DBC2-Map_Monitor_
		.word word_1DBD0-Map_Monitor_
		.word word_1DBDE-Map_Monitor_
		.word word_1DBEC-Map_Monitor_
		.word word_1DBFA-Map_Monitor_
		.word word_1DC08-Map_Monitor_
		.word word_1DC16-Map_Monitor_
		.word word_1DC24-Map_Monitor_
		.word word_1DC32-Map_Monitor_
		.word word_1DC40-Map_Monitor_
		.word word_1DC4E-Map_Monitor_
word_1DBBA:	.word 1			/* DATA XREF: ROM:0001DBA2o*/
		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xF0
word_1DBC2:	.word 2			/* DATA XREF: ROM:0001DBA2o*/
		.byte  0xF3,   5,	  0, 0x18, 0xFF, 0xF8
		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xF0
word_1DBD0:	.word 2			/* DATA XREF: ROM:0001DBA2o*/
		.byte  0xF3,   5,	  3, 0x10, 0xFF, 0xF8
		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xF0
word_1DBDE:	.word 2			/* DATA XREF: ROM:0001DBA2o*/
		.byte  0xF3,   5,	  0, 0x1C, 0xFF, 0xF8
		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xF0
word_1DBEC:	.word 2			/* DATA XREF: ROM:0001DBA2o*/
		.byte  0xF3,   5,	0x20, 0x20, 0xFF, 0xF8
		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xF0
word_1DBFA:	.word 2			/* DATA XREF: ROM:0001DBA2o*/
		.byte  0xF3,   5,	  0, 0x24, 0xFF, 0xF8
		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xF0
word_1DC08:	.word 2			/* DATA XREF: ROM:0001DBA2o*/
		.byte  0xF3,   5,	  0, 0x30, 0xFF, 0xF8
		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xF0
word_1DC16:	.word 2			/* DATA XREF: ROM:0001DBA2o*/
		.byte  0xF3,   5,	  0, 0x2C, 0xFF, 0xF8
		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xF0
word_1DC24:	.word 2			/* DATA XREF: ROM:0001DBA2o*/
		.byte  0xF3,   5,	  0, 0x34, 0xFF, 0xF8
		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xF0
word_1DC32:	.word 2			/* DATA XREF: ROM:0001DBA2o*/
		.byte  0xF3,   5,	  0, 0x28, 0xFF, 0xF8
		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xF0
word_1DC40:	.word 2			/* DATA XREF: ROM:0001DBA2o*/
		.byte  0xF3,   5,	  0, 0x38, 0xFF, 0xF8
		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xF0
word_1DC4E:	.word 1			/* DATA XREF: ROM:0001DBA2o*/
		.byte	0,  0xD,	  0, 0x10, 0xFF, 0xF0
