/*  Dragonfly mappings */
		.word word_8DFEE-Map_Dragonfly
		.word word_8E008-Map_Dragonfly
		.word word_8E022-Map_Dragonfly
		.word word_8E03C-Map_Dragonfly
		.word word_8E056-Map_Dragonfly
		.word word_8E070-Map_Dragonfly
		.word word_8E078-Map_Dragonfly
		.word word_8E080-Map_Dragonfly
		.word word_8E08E-Map_Dragonfly
		.word word_8E09C-Map_Dragonfly
word_8DFEE:	.word 4			/*  DATA XREF: ROM:0008DFDAo */
		.byte  0xFA,   4,	  0,   4, 0xFF, 0xF8
		.byte  0xFC,   0,	  0,   6, 0xFF, 0xF0
		.byte  0xFC,   0,	  0,   6,   0,	 8
		.byte  0xF8,   5,	  0,   0, 0xFF, 0xF8
word_8E008:	.word 4			/*  DATA XREF: ROM:0008DFDAo */
byte_8E00A:	.byte  0xFB,   4,	  0,   4, 0xFF, 0xF8
		.byte  0xFC,   0,	  0,   6, 0xFF, 0xF0
		.byte  0xFC,   0,	  0,   6,   0,	 8
		.byte  0xF8,   5,	  0,   0, 0xFF, 0xF8
word_8E022:	.word 4			/*  DATA XREF: ROM:0008DFDAo */
		.byte  0xFC,   4,	  0,   4, 0xFF, 0xF8
		.byte  0xFC,   0,	  0,   6, 0xFF, 0xF0
		.byte  0xFC,   0,	  0,   6,   0,	 8
		.byte  0xF8,   5,	  0,   0, 0xFF, 0xF8
word_8E03C:	.word 4			/*  DATA XREF: ROM:0008DFDAo */
		.byte  0xFD,   4,	  0,   4, 0xFF, 0xF8
		.byte  0xFC,   0,	  0,   6, 0xFF, 0xF0
		.byte  0xFC,   0,	  0,   6,   0,	 8
		.byte  0xF8,   5,	  0,   0, 0xFF, 0xF8
word_8E056:	.word 4			/*  DATA XREF: ROM:0008DFDAo */
		.byte  0xFE,   4,	  0,   4, 0xFF, 0xF8
		.byte  0xFC,   0,	  0,   6, 0xFF, 0xF0
		.byte  0xFC,   0,	  0,   6,   0,	 8
		.byte  0xF8,   5,	  0,   0, 0xFF, 0xF8
word_8E070:	.word 1			/*  DATA XREF: ROM:0008DFDAo */
		.byte  0xFC,   4,	  0,   7, 0xFF, 0xF8
word_8E078:	.word 1			/*  DATA XREF: ROM:0008DFDAo */
		.byte  0xFC,   0,	  0,   9, 0xFF, 0xFC
word_8E080:	.word 2			/*  DATA XREF: ROM:0008DFDAo */
		.byte  0xF8,   8,	  0,  0xA, 0xFF, 0xD8
		.byte  0xF8,   8,	  8,  0xA,   0, 0x10
word_8E08E:	.word 2			/*  DATA XREF: ROM:0008DFDAo */
		.byte	0,   8,	0x10,  0xA, 0xFF, 0xD8
		.byte	0,   8,	0x18,  0xA,   0, 0x10
word_8E09C:	.word 0			/*  DATA XREF: ROM:0008DFDAo */
