/* Mushmeanie mappings*/
		.word word_8DD00-Map_Mushmeanie
		.word word_8DD08-Map_Mushmeanie
		.word word_8DD16-Map_Mushmeanie
		.word word_8DD24-Map_Mushmeanie
word_8DD00:	.word 1			/* DATA XREF: ROM:0008DCF8o*/
		.byte  0xF8,   9,	  0,   0, 0xFF, 0xF4
word_8DD08:	.word 2			/* DATA XREF: ROM:0008DCF8o*/
		.byte  0xF8,   5,	  0,   6, 0xFF, 0xF8
		.byte	7,   0,	  0,  0xA, 0xFF, 0xFC
word_8DD16:	.word 2			/* DATA XREF: ROM:0008DCF8o*/
		.byte  0xF8,   5,	  0,   6, 0xFF, 0xF8
		.byte	2,   1,	  0,  0xB, 0xFF, 0xFC
word_8DD24:	.word 2			/* DATA XREF: ROM:0008DCF8o*/
		.byte  0xF8,   5,	  0,   6, 0xFF, 0xF8
		.byte	5,   1,	  0,  0xD, 0xFF, 0xFC
