Ani_488C2:		.word byte_488E2-Ani_488C2
		.word byte_488F4-Ani_488C2
		.word byte_48906-Ani_488C2
		.word byte_48918-Ani_488C2
		.word byte_4892A-Ani_488C2
		.word byte_4893C-Ani_488C2
		.word byte_4894E-Ani_488C2
		.word byte_48960-Ani_488C2
		.word byte_48972-Ani_488C2
		.word byte_48984-Ani_488C2
		.word byte_48996-Ani_488C2
		.word byte_489A8-Ani_488C2
		.word byte_489A8-Ani_488C2
		.word byte_489A8-Ani_488C2
		.word byte_48996-Ani_488C2
		.word byte_48984-Ani_488C2
byte_488E2:	.byte	2,   5,	  6,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0,   0,   6,	5, 0xFC
byte_488F4:	.byte	2,   5,	  6,   7,   7,	 7,   7,   7,	7,   7,	  7,   7,   7,	 7,   7,   6,	5, 0xFC
byte_48906:	.byte	2,   5,	  6,   8,   8,	 8,   8,   8,	8,   8,	  8,   8,   8,	 8,   8,   6,	5, 0xFC
byte_48918:	.byte	2,   5,	  6,   9,   9,	 9,   9,   9,	9,   9,	  9,   9,   9,	 9,   9,   6,	5, 0xFC
byte_4892A:	.byte	2,   5,	  6,  0xA,  0xA,	0xA,  0xA,  0xA,  0xA,  0xA,	 0xA,  0xA,  0xA,	0xA,  0xA,   6,	5, 0xFC
byte_4893C:	.byte	2,   5,	  6,  0xB,  0xB,	0xB,  0xB,  0xB,  0xB,  0xB,	 0xB,  0xB,  0xB,	0xB,  0xB,   6,	5, 0xFC
byte_4894E:	.byte	2,   5,	  6,  0xC,  0xC,	0xC,  0xC,  0xC,  0xC,  0xC,	 0xC,  0xC,  0xC,	0xC,  0xC,   6,	5, 0xFC
byte_48960:	.byte	2,   5,	  6,  0xD,  0xD,	0xD,  0xD,  0xD,  0xD,  0xD,	 0xD,  0xD,  0xD,	0xD,  0xD,   6,	5, 0xFC
byte_48972:	.byte	2,   5,	  6,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0,   0,   6,	5, 0xFC
byte_48984:	.byte	2,   5,	  6,   1,   1,	 1,   1,   1,	1,   1,	  1,   1,   1,	 1,   1,   6,	5, 0xFC
byte_48996:	.byte	2,   5,	  6,   2,   2,	 2,   2,   2,	2,   2,	  2,   2,   2,	 2,   2,   6,	5, 0xFC
byte_489A8:	.byte    2,   5,   6,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   6,   5, 0xFC,   2,   5
		.byte    6,   4,   4,   4,   4,   4,   4,   4,   4,   4,   4,   4,   4,   6,   5, 0xFC
