		.word word_25ACE-Map_DEZFloatingPlatform
		.word word_25ADC-Map_DEZFloatingPlatform
word_25ACE:	.word 2			/*  DATA XREF: ROM:00025ACAo */
		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xE0
		.byte  0xF0,  0xF,	  8,   0,   0,	 0
word_25ADC:	.word 3			/*  DATA XREF: ROM:00025ACAo */
		.byte  0xFC,   8,	  0, 0x10, 0xFF, 0xF4
		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xE0
		.byte  0xF0,  0xF,	  8,   0,   0,	 0
