		.word word_4761A-Map_DEZLiftPad
		.word word_4762E-Map_DEZLiftPad
		.word word_47636-Map_DEZLiftPad
word_4761A:	.word 3			/* DATA XREF: ROM:00047614o*/
		.byte  0xF8,   9,	  0,   0, 0xFF, 0xE8
		.byte  0xF8,   9,	  8,   0,   0,	 0
		.byte  0xF8,   5,	  0,   6,   0, 0x18
word_4762E:	.word 1			/* DATA XREF: ROM:00047614o*/
		.byte  0xFC,   0,	  0,  0xA, 0xFF, 0xFC
word_47636:	.word 1			/* DATA XREF: ROM:00047614o*/
		.byte  0xF8,   5,	  0,   6, 0xFF, 0xF8
