Map_48038:		.word word_48040-Map_48038
		.word word_48054-Map_48038
		.word word_48068-Map_48038
		.word word_4807C-Map_48038
word_48040:	.word 3			
		.byte  0x20,   0,	  0,   8, 0xFF, 0xC4
		.byte  0x1F,   0,	  0,   8,   0,	 4
		.byte	1,   0,	  0,   8,   0, 0x35
word_48054:	.word 3			
		.byte  0x20,   0,	  0,   8, 0xFF, 0xD4
		.byte  0x1C,   0,	  0,   8,   0, 0x13
		.byte  0xF3,   0,	  0,   8,   0, 0x3C
word_48068:	.word 3			
		.byte  0x20,   0,	  0,   8, 0xFF, 0xE4
		.byte  0x15,   0,	  0,   8,   0, 0x21
		.byte  0xE4,   0,	  0,   8,   0, 0x3F
word_4807C:	.word 2			
		.byte  0x20,   0,	  0,   8, 0xFF, 0xF4
		.byte   0xC,   0,	  0,   8,   0, 0x2C
