		.word word_48BEE-Map_DEZGravitySwitch
		.word word_48C08-Map_DEZGravitySwitch
word_48BEE:	.word 4			/*  DATA XREF: ROM:00048BEAo */
		.byte  0xF8,   4,	  0,   0, 0xFF, 0xF0
		.byte  0xF8,   4,	  8,   0,   0,	 0
		.byte	0,   4,	  0,   2, 0xFF, 0xF0
		.byte	0,   4,	  8,   2,   0,	 0
word_48C08:	.word 2			/*  DATA XREF: ROM:00048BEAo */
		.byte  0xF8,   4,	  0,   0, 0xFF, 0xF0
		.byte  0xF8,   4,	  8,   0,   0,	 0
