		.word word_472BC-Map_TorpedoLauncher
		.word word_472D0-Map_TorpedoLauncher
		.word word_472E4-Map_TorpedoLauncher
		.word word_472F8-Map_TorpedoLauncher
		.word word_4730C-Map_TorpedoLauncher
		.word word_47320-Map_TorpedoLauncher
		.word word_47334-Map_TorpedoLauncher
		.word word_47348-Map_TorpedoLauncher
		.word word_4735C-Map_TorpedoLauncher
		.word word_47370-Map_TorpedoLauncher
word_472BC:	.word 3			/* DATA XREF: ROM:000472A8o*/
		.byte  0xF0,   1,	  0,   0,   0,	 0
		.byte	0,   1,	0x10,   0,   0,	 0
		.byte  0xF8,   5,	0x20,   2, 0xFF, 0xF8
word_472D0:	.word 3			/* DATA XREF: ROM:000472A8o*/
		.byte  0xF0,   1,	  0,   0,   0,	 0
		.byte	0,   1,	0x10,   0,   0,	 0
		.byte  0xF8,   5,	0x20,   2, 0xFF, 0xF9
word_472E4:	.word 3			/* DATA XREF: ROM:000472A8o*/
		.byte  0xF0,   1,	  0,   0,   0,	 0
		.byte	0,   1,	0x10,   0,   0,	 0
		.byte  0xF8,   5,	0x20,   2, 0xFF, 0xFA
word_472F8:	.word 3			/* DATA XREF: ROM:000472A8o*/
		.byte  0xF0,   1,	  0,   0,   0,	 0
		.byte	0,   1,	0x10,   0,   0,	 0
		.byte  0xF8,   5,	0x20,   2, 0xFF, 0xFB
word_4730C:	.word 3			/* DATA XREF: ROM:000472A8o*/
		.byte  0xF0,   1,	  0,   0,   0,	 0
		.byte	0,   1,	0x10,   0,   0,	 0
		.byte  0xF8,   5,	0x20,   2, 0xFF, 0xFC
word_47320:	.word 3			/* DATA XREF: ROM:000472A8o*/
		.byte  0xF0,   1,	  0,   0,   0,	 0
		.byte	0,   1,	0x10,   0,   0,	 0
		.byte  0xF8,   5,	0x20,   2, 0xFF, 0xFD
word_47334:	.word 3			/* DATA XREF: ROM:000472A8o*/
		.byte  0xF0,   1,	  0,   0,   0,	 0
		.byte	0,   1,	0x10,   0,   0,	 0
		.byte  0xF8,   5,	0x20,   2, 0xFF, 0xFE
word_47348:	.word 3			/* DATA XREF: ROM:000472A8o*/
		.byte  0xF0,   1,	  0,   0,   0,	 0
		.byte	0,   1,	0x10,   0,   0,	 0
		.byte  0xF8,   5,	0x20,   2, 0xFF, 0xFF
word_4735C:	.word 3			/* DATA XREF: ROM:000472A8o*/
		.byte  0xF0,   1,	  0,   0,   0,	 0
		.byte	0,   1,	0x10,   0,   0,	 0
		.byte  0xF8,   5,	0x20,   2,   0,	 0
word_47370:	.word 1			/* DATA XREF: ROM:000472A8o*/
		.byte  0xF8,   5,	  0,   2, 0xFF, 0xF8
