Map_5A9AC:		.word word_5A9B4-Map_5A9AC
		.word word_5A9CE-Map_5A9AC
		.word word_5A9CE-Map_5A9AC
		.word word_5A9E8-Map_5A9AC
word_5A9B4:	.word 4			
		.byte  0xF0,   5,	  0,   0, 0xFF, 0xF0
		.byte  0xF0,   5,	  0,   4,   0,	 0
		.byte	0,   5,	  0, 0x10, 0xFF, 0xF0
		.byte	0,   5,	  0, 0x14,   0,	 0
word_5A9CE:	.word 4			
		.byte  0xF0,   5,	  0,   8, 0xFF, 0xF0
		.byte  0xF0,   5,	  0,   4,   0,	 0
		.byte	0,   5,	  0, 0x18, 0xFF, 0xF0
		.byte	0,   5,	  0, 0x14,   0,	 0
word_5A9E8:	.word 4			
		.byte  0xF0,   5,	  0,   8, 0xFF, 0xF0
		.byte  0xF0,   5,	  0,  0xC,   0,	 0
		.byte	0,   5,	  0, 0x18, 0xFF, 0xF0
		.byte	0,   5,	  0, 0x10,   0,	 0
