		.word word_49A76-Map_DEZGravityPuzzle
		.word word_49A9C-Map_DEZGravityPuzzle
		.word word_49AA4-Map_DEZGravityPuzzle
		.word word_49AAC-Map_DEZGravityPuzzle
		.word word_49AAC-Map_DEZGravityPuzzle
word_49A76:	.word 6			/* DATA XREF: ROM:00049A6Co*/
		.byte  0xD0,  0xF,	  0,   0, 0xFF, 0xE0
		.byte  0xD0,  0xF,	  8,   0,   0,	 0
		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xE0
		.byte  0xF0,  0xF,	  8,   0,   0,	 0
		.byte  0x10,  0xF,	  0,   0, 0xFF, 0xE0
		.byte  0x10,  0xF,	  8,   0,   0,	 0
word_49A9C:	.word 1			/* DATA XREF: ROM:00049A6Co*/
		.byte  0xF0,   3,	  0, 0x1C, 0xFF, 0xFC
word_49AA4:	.word 1			/* DATA XREF: ROM:00049A6Co*/
		.byte  0xF0,   3,	  8, 0x1C, 0xFF, 0xFC
word_49AAC:	.word 0			/* DATA XREF: ROM:00049A6Co*/
