		.word word_48000-Map_DEZEnergyBridge
		.word word_4800E-Map_DEZEnergyBridge
		.word word_4801C-Map_DEZEnergyBridge
		.word word_4802A-Map_DEZEnergyBridge
word_48000:	.word 2			/* DATA XREF: ROM:00047FF8o*/
		.byte  0xF8,   0,	  0,   8, 0xFF, 0xC4
		.byte  0xF8,   0,	  0,   8,   0,	 4
word_4800E:	.word 2			/* DATA XREF: ROM:00047FF8o*/
		.byte  0xF8,   0,	  0,   8, 0xFF, 0xD4
		.byte  0xF8,   0,	  0,   8,   0, 0x14
word_4801C:	.word 2			/* DATA XREF: ROM:00047FF8o*/
		.byte  0xF8,   0,	  0,   8, 0xFF, 0xE4
		.byte  0xF8,   0,	  0,   8,   0, 0x24
word_4802A:	.word 2			/* DATA XREF: ROM:00047FF8o*/
		.byte  0xF8,   0,	  0,   8, 0xFF, 0xF4
		.byte  0xF8,   0,	  0,   8,   0, 0x34
