		.word word_4843A-Map_DEZTunnelLauncher
		.word word_4843C-Map_DEZTunnelLauncher
		.word word_4844A-Map_DEZTunnelLauncher
		.word word_48458-Map_DEZTunnelLauncher
		.word word_48466-Map_DEZTunnelLauncher
		.word word_48474-Map_DEZTunnelLauncher
		.word word_48482-Map_DEZTunnelLauncher
		.word word_48490-Map_DEZTunnelLauncher
		.word word_48498-Map_DEZTunnelLauncher
		.word word_484A0-Map_DEZTunnelLauncher
		.word word_484A8-Map_DEZTunnelLauncher
word_4843A:	.word 0			/* DATA XREF: ROM:00048424o*/
word_4843C:	.word 2			/* DATA XREF: ROM:00048424o*/
		.byte	0,   5,	  0, 0x10, 0xFF, 0xE8
		.byte	0,   5,	  0, 0x10,   0,	 8
word_4844A:	.word 2			/* DATA XREF: ROM:00048424o*/
		.byte	0,   5,	  0, 0x14, 0xFF, 0xE8
		.byte	0,   5,	  0, 0x14,   0,	 8
word_48458:	.word 2			/* DATA XREF: ROM:00048424o*/
		.byte	4,   5,	  0, 0x10, 0xFF, 0xE8
		.byte	4,   5,	  0, 0x10,   0,	 8
word_48466:	.word 2			/* DATA XREF: ROM:00048424o*/
		.byte	8,   5,	  0, 0x14, 0xFF, 0xE8
		.byte	8,   5,	  0, 0x14,   0,	 8
word_48474:	.word 2			/* DATA XREF: ROM:00048424o*/
		.byte   0xC,   5,	  0, 0x10, 0xFF, 0xE8
		.byte   0xC,   5,	  0, 0x10,   0,	 8
word_48482:	.word 2			/* DATA XREF: ROM:00048424o*/
		.byte  0x10,   5,	  0, 0x14, 0xFF, 0xE8
		.byte  0x10,   5,	  0, 0x14,   0,	 8
word_48490:	.word 1			/* DATA XREF: ROM:00048424o*/
		.byte  0xF8,   5,	  0,  0xC, 0xFF, 0xF8
word_48498:	.word 1			/* DATA XREF: ROM:00048424o*/
		.byte  0xF8,   5,	  0,   8, 0xFF, 0xF8
word_484A0:	.word 1			/* DATA XREF: ROM:00048424o*/
		.byte  0xF8,   5,	  0,   4, 0xFF, 0xF8
word_484A8:	.word 1			/* DATA XREF: ROM:00048424o*/
		.byte  0xF8,   5,	  0,   0, 0xFF, 0xF8
