		.word word_47938-Map_DEZLightning
		.word word_4793A-Map_DEZLightning
		.word word_47942-Map_DEZLightning
		.word word_4794A-Map_DEZLightning
		.word word_47958-Map_DEZLightning
word_47938:	.word 0			/*  DATA XREF: ROM:0004792Eo */
word_4793A:	.word 1			/*  DATA XREF: ROM:0004792Eo */
		.byte  0xE8,   5,	  0,   0, 0xFF, 0xF8
word_47942:	.word 1			/*  DATA XREF: ROM:0004792Eo */
		.byte  0xE8,   7,	  0,   4, 0xFF, 0xF8
word_4794A:	.word 2			/*  DATA XREF: ROM:0004792Eo */
		.byte  0xE8,   5,	  8,   0, 0xFF, 0xF8
		.byte  0xF8,   7,	  8,   4, 0xFF, 0xF8
word_47958:	.word 2			/*  DATA XREF: ROM:0004792Eo */
		.byte  0xE8,   5,	  0,   0, 0xFF, 0xF8
		.byte  0xF8,   7,	  0,   4, 0xFF, 0xF8
