DPLC_83B6C:		.word word_83B7A-DPLC_83B6C
		.word word_83B80-DPLC_83B6C
		.word word_83B86-DPLC_83B6C
		.word word_83B8C-DPLC_83B6C
		.word word_83B92-DPLC_83B6C
		.word word_83B96-DPLC_83B6C
		.word word_83B9A-DPLC_83B6C
word_83B7A:	.word 1			
		.word 0x20B
		.word 0x2CB
word_83B80:	.word 1			
		.word 0x38B
		.word 0x44B
word_83B86:	.word 1			
		.word 0x50B
		.word 0x5CB
word_83B8C:	.word 1			
		.word 0xB
		.word 0xB
word_83B92:	.word 0			
		.word 0xCF
word_83B96:	.word 0			
		.word 0x1C3
word_83B9A:	.word 0			
		.word 0xCF
