Map_83B9E:		.word word_83BAC-Map_83B9E
		.word word_83BBA-Map_83B9E
		.word word_83BC8-Map_83B9E
		.word word_83BD6-Map_83B9E
		.word word_83BE4-Map_83B9E
		.word word_83BEC-Map_83B9E
		.word word_83BF4-Map_83B9E
word_83BAC:	.word 2			
		.byte  0xF0,  0xB,	  0,   0, 0xFF, 0xE8
		.byte  0xF0,  0xB,	  0,  0xC,   0,	 0
word_83BBA:	.word 2			
		.byte  0xF0,  0xB,	  0,   0, 0xFF, 0xE8
		.byte  0xF0,  0xB,	  0,  0xC,   0,	 0
word_83BC8:	.word 2			
		.byte  0xF0,  0xB,	  0,   0, 0xFF, 0xE8
		.byte  0xF0,  0xB,	  0,  0xC,   0,	 0
word_83BD6:	.word 2			
		.byte  0xF0,  0xB,	  0,   0, 0xFF, 0xE8
		.byte  0xF0,  0xB,	  8,  0xC,   0,	 0
word_83BE4:	.word 1			
		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xF0
word_83BEC:	.word 1			
		.byte  0xF0,   3,	  0,   0, 0xFF, 0xFC
word_83BF4:	.word 1			
		.byte  0xF0,  0xF,	  8,   0, 0xFF, 0xF0
