		.word word_21AC6-Map_CNZSOZBreakableWall
		.word word_21AE0-Map_CNZSOZBreakableWall
		.word word_21B12-Map_CNZSOZBreakableWall
		.word word_21B2C-Map_CNZSOZBreakableWall
		.word word_21B5E-Map_CNZSOZBreakableWall
		.word word_21B84-Map_CNZSOZBreakableWall
word_21AC6:	.word 4			/*  DATA XREF: ROM:00021ABAo */
		.byte  0xE0,  0xD,	  0,   0, 0xFF, 0xF0
		.byte  0xF0,  0xD,	  0,   0, 0xFF, 0xF0
		.byte	0,  0xD,	  0,   0, 0xFF, 0xF0
		.byte  0x10,  0xD,	  0,   0, 0xFF, 0xF0
word_21AE0:	.word 8			/*  DATA XREF: ROM:00021ABAo */
		.byte  0xE0,   5,	  0,   0, 0xFF, 0xF0
		.byte  0xE0,   5,	  0,   4,   0,	 0
		.byte  0xF0,   5,	  0,   0, 0xFF, 0xF0
		.byte  0xF0,   5,	  0,   4,   0,	 0
		.byte	0,   5,	  0,   0, 0xFF, 0xF0
		.byte	0,   5,	  0,   4,   0,	 0
		.byte  0x10,   5,	  0,   0, 0xFF, 0xF0
		.byte  0x10,   5,	  0,   4,   0,	 0
word_21B12:	.word 4			/*  DATA XREF: ROM:00021ABAo */
		.byte  0xE0,  0xD,	  0,   8, 0xFF, 0xF0
		.byte  0xF0,  0xD,	  0,   8, 0xFF, 0xF0
		.byte	0,  0xD,	  0,   8, 0xFF, 0xF0
		.byte  0x10,  0xD,	  0,   8, 0xFF, 0xF0
word_21B2C:	.word 8			/*  DATA XREF: ROM:00021ABAo */
		.byte  0xE0,   5,	  0,   8, 0xFF, 0xF0
		.byte  0xE0,   5,	  0,  0xC,   0,	 0
		.byte  0xF0,   5,	  0,   8, 0xFF, 0xF0
		.byte  0xF0,   5,	  0,  0xC,   0,	 0
		.byte	0,   5,	  0,   8, 0xFF, 0xF0
		.byte	0,   5,	  0,  0xC,   0,	 0
		.byte  0x10,   5,	  0,   8, 0xFF, 0xF0
		.byte  0x10,   5,	  0,  0xC,   0,	 0
word_21B5E:	.word 6			/*  DATA XREF: ROM:00021ABAo */
		.byte  0xD0,  0xD,	  0,   0, 0xFF, 0xF0
		.byte  0xE0,  0xD,	  0,   0, 0xFF, 0xF0
		.byte  0xF0,  0xD,	  0,   0, 0xFF, 0xF0
		.byte	0,  0xD,	  0,   0, 0xFF, 0xF0
		.byte  0x10,  0xD,	  0,   0, 0xFF, 0xF0
		.byte  0x20,  0xD,	  0,   0, 0xFF, 0xF0
word_21B84:	.word 0xC			/*  DATA XREF: ROM:00021ABAo */
		.byte  0xD0,   5,	  0,   0, 0xFF, 0xF0
		.byte  0xD0,   5,	  0,   4,   0,	 0
		.byte  0xE0,   5,	  0,   0, 0xFF, 0xF0
		.byte  0xE0,   5,	  0,   4,   0,	 0
		.byte  0xF0,   5,	  0,   0, 0xFF, 0xF0
		.byte  0xF0,   5,	  0,   4,   0,	 0
		.byte	0,   5,	  0,   0, 0xFF, 0xF0
		.byte	0,   5,	  0,   4,   0,	 0
		.byte  0x10,   5,	  0,   0, 0xFF, 0xF0
		.byte  0x10,   5,	  0,   4,   0,	 0
		.byte  0x20,   5,	  0,   0, 0xFF, 0xF0
		.byte  0x20,   5,	  0,   4,   0,	 0
