Map_681D4:		.word word_681DC-Map_681D4
		.word word_681E4-Map_681D4
		.word word_681EC-Map_681D4
		.word word_681F4-Map_681D4
word_681DC:	.word 1			/*  DATA XREF: ROM:000681D4o */
		.byte  0xF8,  0xD,	  0,   0, 0xFF, 0xF0
word_681E4:	.word 1			/*  DATA XREF: ROM:000681D4o */
		.byte  0xF8,  0xD,	  0,   8, 0xFF, 0xF0
word_681EC:	.word 1			/*  DATA XREF: ROM:000681D4o */
		.byte  0xF8,  0xD,	  0, 0x10, 0xFF, 0xF0
word_681F4:	.word 1			/*  DATA XREF: ROM:000681D4o */
		.byte  0xF8,  0xD,	  0, 0x18, 0xFF, 0xF0
