Ani_3BD5E:		.word byte_3BD6A-Ani_3BD5E
		.word byte_3BD70-Ani_3BD5E
		.word byte_3BD76-Ani_3BD5E
		.word byte_3BD7C-Ani_3BD5E
		.word byte_3BD82-Ani_3BD5E
		.word byte_3BD88-Ani_3BD5E
byte_3BD6A:	.byte	1,   0,	  3,   2,   1, 0xFF 
byte_3BD70:	.byte	1,   0,	  1,   2,   3, 0xFF 
byte_3BD76:	.byte	1,   4,	  5,   6,   7, 0xFF 
byte_3BD7C:	.byte	1,   4,	  7,   6,   5, 0xFF 
byte_3BD82:	.byte	1,   8,	  9,  0xA,  0xB, 0xFF 
byte_3BD88:	.byte	1,   8,	 0xB,  0xA,   9, 0xFF 
