		.word word_2A924-Map_FBZCorkFloor
		.word word_2A932-Map_FBZCorkFloor
word_2A924:	.word 2			/* DATA XREF: ROM:0002A920o*/
		.byte  0xF0,  0xD,	  0,   0, 0xFF, 0xF0
		.byte	0,  0xD,	  0,   0, 0xFF, 0xF0
word_2A932:	.word 4			/* DATA XREF: ROM:0002A920o*/
		.byte  0xF0,   5,	  0,   0, 0xFF, 0xF0
		.byte  0xF0,   5,	  0,   4,   0,	 0
		.byte	0,   5,	  0,   0, 0xFF, 0xF0
		.byte	0,   5,	  0,   4,   0,	 0
