		.word word_3C41E-Map_FBZPlatformBlocks
		.word word_3C426-Map_FBZPlatformBlocks
		.word word_3C434-Map_FBZPlatformBlocks
		.word word_3C448-Map_FBZPlatformBlocks
word_3C41E:	.word 1			/*  DATA XREF: ROM:0003C416o */
		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xF0
word_3C426:	.word 2			/*  DATA XREF: ROM:0003C416o */
		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xE0
		.byte  0xF0,  0xF,	  0,   0,   0,	 0
word_3C434:	.word 3			/*  DATA XREF: ROM:0003C416o */
		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xD0
		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xF0
		.byte  0xF0,  0xF,	  0,   0,   0, 0x10
word_3C448:	.word 4			/*  DATA XREF: ROM:0003C416o */
		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xC0
		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xE0
		.byte  0xF0,  0xF,	  0,   0,   0,	 0
		.byte  0xF0,  0xF,	  0,   0,   0, 0x20
