		.word word_3CFF4-Map_FBZFlameThrower
		.word word_3CFFC-Map_FBZFlameThrower
		.word word_3D00A-Map_FBZFlameThrower
		.word word_3D018-Map_FBZFlameThrower
		.word word_3D020-Map_FBZFlameThrower
		.word word_3D028-Map_FBZFlameThrower
		.word word_3D030-Map_FBZFlameThrower
		.word word_3D038-Map_FBZFlameThrower
		.word word_3D040-Map_FBZFlameThrower
		.word word_3D048-Map_FBZFlameThrower
		.word word_3D050-Map_FBZFlameThrower
		.word word_3D058-Map_FBZFlameThrower
		.word word_3D060-Map_FBZFlameThrower
		.word word_3D068-Map_FBZFlameThrower
		.word word_3D070-Map_FBZFlameThrower
		.word word_3D078-Map_FBZFlameThrower
		.word word_3D080-Map_FBZFlameThrower
		.word word_3D088-Map_FBZFlameThrower
word_3CFF4:	.word 1			/* DATA XREF: ROM:0003CFD0o*/
		.byte  0xF8,   0,	0x20, 0x1C,   0,	 0
word_3CFFC:	.word 2			/* DATA XREF: ROM:0003CFD0o*/
		.byte  0xF0,  0xC,	0x20,   0, 0xFF, 0xF0
		.byte	0,  0xC,	0x20,   6, 0xFF, 0xF0
word_3D00A:	.word 2			/* DATA XREF: ROM:0003CFD0o*/
		.byte  0xF8,  0xC,	0x20,   0, 0xFF, 0xF0
		.byte	0,  0xC,	0x20,   6, 0xFF, 0xF0
word_3D018:	.word 1			/* DATA XREF: ROM:0003CFD0o*/
		.byte	0,  0xC,	0x20,   6, 0xFF, 0xF0
word_3D020:	.word 1			/* DATA XREF: ROM:0003CFD0o*/
		.byte  0xF8,   5,	  0,  0xA, 0xFF, 0xF8
word_3D028:	.word 1			/* DATA XREF: ROM:0003CFD0o*/
		.byte  0xF8,   5,	  0,  0xE, 0xFF, 0xF8
word_3D030:	.word 1			/* DATA XREF: ROM:0003CFD0o*/
		.byte  0xF8,   5,	  8,  0xE, 0xFF, 0xF8
word_3D038:	.word 1			/* DATA XREF: ROM:0003CFD0o*/
		.byte  0xF8,   5,	  8,  0xA, 0xFF, 0xF8
word_3D040:	.word 1			/* DATA XREF: ROM:0003CFD0o*/
		.byte  0xF8,   5,	  0, 0x12, 0xFF, 0xF8
word_3D048:	.word 1			/* DATA XREF: ROM:0003CFD0o*/
		.byte  0xF8,   5,	  0, 0x16, 0xFF, 0xF8
word_3D050:	.word 1			/* DATA XREF: ROM:0003CFD0o*/
		.byte  0xF8,   5,	  8, 0x16, 0xFF, 0xF8
word_3D058:	.word 1			/* DATA XREF: ROM:0003CFD0o*/
		.byte  0xF8,   5,	  8, 0x12, 0xFF, 0xF8
word_3D060:	.word 1			/* DATA XREF: ROM:0003CFD0o*/
		.byte  0xFC,   0,	  0, 0x1A, 0xFF, 0xFC
word_3D068:	.word 1			/* DATA XREF: ROM:0003CFD0o*/
		.byte  0xFC,   0,	  0, 0x1B, 0xFF, 0xFC
word_3D070:	.word 1			/* DATA XREF: ROM:0003CFD0o*/
		.byte  0xFC,   0,	  8, 0x1B, 0xFF, 0xFC
word_3D078:	.word 1			/* DATA XREF: ROM:0003CFD0o*/
		.byte  0xFC,   0,	  8, 0x1A, 0xFF, 0xFC
word_3D080:	.word 1			/* DATA XREF: ROM:0003CFD0o*/
		.byte  0xF8,   0,	0x28, 0x1C, 0xFF, 0xF8
word_3D088:	.word 1			/* DATA XREF: ROM:0003CFD0o*/
		.byte  0xF8,   4,	0x20,   4, 0xFF, 0xF8
