		.word word_3B4E8-Map_FBZMagneticPlatform
		.word word_3B4F6-Map_FBZMagneticPlatform
		.word word_3B4FE-Map_FBZMagneticPlatform
		.word word_3B50C-Map_FBZMagneticPlatform
		.word word_3B51A-Map_FBZMagneticPlatform
word_3B4E8:	.word 2			/* DATA XREF: ROM:0003B4DEo*/
		.byte  0xF0,  0xB,	  0, 0x18, 0xFF, 0xE8
		.byte  0xF0,  0xB,	  8, 0x18,   0,	 0
word_3B4F6:	.word 1			/* DATA XREF: ROM:0003B4DEo*/
		.byte  0xF8,   1,	  0, 0x24, 0xFF, 0xFC
word_3B4FE:	.word 2			/* DATA XREF: ROM:0003B4DEo*/
		.byte  0xF8,   1,	  0, 0x24, 0xFF, 0xFC
		.byte	8,   1,	  0, 0x24, 0xFF, 0xFC
word_3B50C:	.word 2			/* DATA XREF: ROM:0003B4DEo*/
		.byte  0xFC,   4,	  0, 0x26, 0xFF, 0xF0
		.byte  0xFC,   4,	  8, 0x26,   0,	 0
word_3B51A:	.word 4			/* DATA XREF: ROM:0003B4DEo*/
		.byte	8,   4,	  0, 0x26, 0xFF, 0xF0
		.byte	8,   4,	  8, 0x26,   0,	 0
		.byte  0xF0,  0xB,	  0, 0x18, 0xFF, 0xE8
		.byte  0xF0,  0xB,	  8, 0x18,   0,	 0
