		.word word_3CC60-Map_FBZTrapSpring
		.word word_3CC6E-Map_FBZTrapSpring
		.word word_3CC7C-Map_FBZTrapSpring
word_3CC60:	.word 2			/* DATA XREF: ROM:0003CC5Ao*/
		.byte  0xF0,   7,	  0,   0, 0xFF, 0xF0
		.byte  0xF0,   7,	  8,   0,   0,	 0
word_3CC6E:	.word 2			/* DATA XREF: ROM:0003CC5Ao*/
		.byte  0xF0,   7,	  0,   8, 0xFF, 0xF0
		.byte  0xF0,   7,	  8,   8,   0,	 0
word_3CC7C:	.word 2			/* DATA XREF: ROM:0003CC5Ao*/
		.byte  0xF8,   5,	  0, 0x10, 0xFF, 0xF0
		.byte  0xF8,   5,	  8, 0x10,   0,	 0
