		.word word_3B742-Map_FBZBentPipe
		.word word_3B750-Map_FBZBentPipe
		.word word_3B758-Map_FBZBentPipe
word_3B742:	.word 2			/*  DATA XREF: ROM:0003B73Co */
		.byte  0xF0,  0xF,	  0,   9, 0xFF, 0xE8
		.byte  0xF0,   7,	  0, 0x19,   0,	 8
word_3B750:	.word 1			/*  DATA XREF: ROM:0003B73Co */
		.byte  0xF8,  0xD,	  0, 0x21, 0xFF, 0xF0
word_3B758:	.word 2			/*  DATA XREF: ROM:0003B73Co */
		.byte  0xF0,  0xF,	0x10,   9, 0xFF, 0xE8
		.byte  0xF0,   7,	  0, 0x19,   0,	 8
