		.word word_3C79C-Map_FBZMissileLauncher
		.word word_3C7AA-Map_FBZMissileLauncher
		.word word_3C7B8-Map_FBZMissileLauncher
		.word word_3C7C0-Map_FBZMissileLauncher
		.word word_3C7CE-Map_FBZMissileLauncher
		.word word_3C7D6-Map_FBZMissileLauncher
		.word word_3C7DE-Map_FBZMissileLauncher
word_3C79C:	.word 2			/* DATA XREF: ROM:0003C78Eo*/
		.byte  0xF0,   7,	  0,   0, 0xFF, 0xF0
		.byte  0xF0,   7,	  8,   0,   0,	 0
word_3C7AA:	.word 2			/* DATA XREF: ROM:0003C78Eo*/
		.byte  0xF0,   7,	  0,   8, 0xFF, 0xF0
		.byte  0xF0,   7,	  8,   8,   0,	 0
word_3C7B8:	.word 1			/* DATA XREF: ROM:0003C78Eo*/
		.byte  0xF4,   6,	  0, 0x10, 0xFF, 0xF8
word_3C7C0:	.word 2			/* DATA XREF: ROM:0003C78Eo*/
		.byte  0xF4,   6,	0x10, 0x10, 0xFF, 0xF8
		.byte  0xDC,  0xE,	  0, 0x16, 0xFF, 0xF0
word_3C7CE:	.word 1			/* DATA XREF: ROM:0003C78Eo*/
					/* ROM:0003C906t*/
		.byte  0xFC,  0xC,	  0, 0x22, 0xFF, 0xF0
word_3C7D6:	.word 1			/* DATA XREF: ROM:0003C78Eo*/
					/* ROM:0003C908t*/
		.byte  0xFC,  0xC,	  0, 0x26, 0xFF, 0xF0
word_3C7DE:	.word 2			/* DATA XREF: ROM:0003C78Eo*/
		.byte  0xF8,  0xD,	  0, 0x2A, 0xFF, 0xE0
		.byte  0xF8,  0xD,	  0, 0x2A,   0,	 0
