		.word word_3D9B6-Map_FBZMagneticPendulum
		.word word_3D9D0-Map_FBZMagneticPendulum
		.word word_3D9EA-Map_FBZMagneticPendulum
		.word word_3D9F2-Map_FBZMagneticPendulum
word_3D9B6:	.word 4			/* DATA XREF: ROM:0003D9AEo*/
		.byte  0xF0,   7,	  0,   0, 0xFF, 0xF0
		.byte  0xF0,   7,	  8,   0,   0,	 0
		.byte	0,   1,	  0, 0x14, 0xFF, 0xF8
		.byte	0,   1,	  8, 0x14,   0,	 0
word_3D9D0:	.word 4			/* DATA XREF: ROM:0003D9AEo*/
		.byte  0xF0,   7,	  0,   0, 0xFF, 0xF0
		.byte  0xF0,   7,	  8,   0,   0,	 0
		.byte  0xF8,   1,	  0, 0x14, 0xFF, 0xF0
		.byte  0xF8,   1,	  8, 0x14, 0xFF, 0xF8
word_3D9EA:	.word 1			/* DATA XREF: ROM:0003D9AEo*/
		.byte  0xF8,   5,	  0,   8, 0xFF, 0xF8
word_3D9F2:	.word 2			/* DATA XREF: ROM:0003D9AEo*/
		.byte  0xF0,   7,	  0,  0xC, 0xFF, 0xF0
		.byte  0xF0,   7,	  8,  0xC,   0,	 0
