Map_3C906:		.word word_3C7CE-Map_3C906
		.word word_3C7D6-Map_3C906
		.word word_3C916-Map_3C906
		.word word_3C91E-Map_3C906
		.word word_3C926-Map_3C906
		.word word_3C92E-Map_3C906
		.word word_3C936-Map_3C906
		.word word_3C93E-Map_3C906
word_3C916:	.word 1			
		.byte  0xFC,  0xC,	  0, 0x22, 0xFF, 0xF1
word_3C91E:	.word 1			
		.byte  0xFC,  0xC,	  0, 0x22, 0xFF, 0xF2
word_3C926:	.word 1			
		.byte  0xFC,  0xC,	  0, 0x22, 0xFF, 0xF3
word_3C92E:	.word 1			
		.byte  0xFC,  0xC,	  0, 0x22, 0xFF, 0xF4
word_3C936:	.word 1			
		.byte  0xFC,  0xC,	  0, 0x22, 0xFF, 0xF5
word_3C93E:	.word 1			
		.byte  0xFC,  0xC,	  0, 0x22, 0xFF, 0xF6
