Map_71090:		.word word_7109A-Map_71090
		.word word_710A2-Map_71090
		.word word_710AA-Map_71090
		.word word_710B2-Map_71090
		.word word_710BA-Map_71090
word_7109A:	.word 1			
		.byte  0xF4,  0xE,	  0,   0, 0xFF, 0xF0
word_710A2:	.word 1			
		.byte  0xEC,  0xF,	  0,  0xC, 0xFF, 0xF0
word_710AA:	.word 1			
		.byte  0xEC,  0xF,	  0, 0x1C, 0xFF, 0xF0
word_710B2:	.word 1			
		.byte  0xEC,  0xE,	  0, 0x2C, 0xFF, 0xF0
word_710BA:	.word 1			
		.byte  0xEC,  0xE,	  0, 0x38, 0xFF, 0xF0
