		.word word_3B26A-Map_FBZMagneticSpikeBall
		.word word_3B278-Map_FBZMagneticSpikeBall
		.word word_3B292-Map_FBZMagneticSpikeBall
		.word word_3B2AC-Map_FBZMagneticSpikeBall
		.word word_3B2C6-Map_FBZMagneticSpikeBall
		.word word_3B2E0-Map_FBZMagneticSpikeBall
		.word word_3B2F4-Map_FBZMagneticSpikeBall
word_3B26A:	.word 2			/* DATA XREF: ROM:0003B25Co*/
		.byte  0xF0,   7,	  0, 0x10, 0xFF, 0xF0
		.byte  0xF0,   7,	  8, 0x10,   0,	 0
word_3B278:	.word 4			/* DATA XREF: ROM:0003B25Co*/
		.byte  0xF8,   9,	  0,   4, 0xFF, 0xD0
		.byte  0xF8,   9,	  0,  0xA, 0xFF, 0xE8
		.byte  0xF8,   9,	  0,   4,   0,	 0
		.byte  0xF8,   9,	  0,  0xA,   0, 0x18
word_3B292:	.word 4			/* DATA XREF: ROM:0003B25Co*/
		.byte  0xF8,   9,	  0,  0xA, 0xFF, 0xD0
		.byte  0xF8,   9,	  0,   4, 0xFF, 0xE8
		.byte  0xF8,   9,	  0,  0xA,   0,	 0
		.byte  0xF8,   9,	  0,   4,   0, 0x18
word_3B2AC:	.word 4			/* DATA XREF: ROM:0003B25Co*/
		.byte  0xF8,   9,	  8,  0xA, 0xFF, 0xD0
		.byte  0xF8,   9,	  8,   4, 0xFF, 0xE8
		.byte  0xF8,   9,	  8,  0xA,   0,	 0
		.byte  0xF8,   9,	  8,   4,   0, 0x18
word_3B2C6:	.word 4			/* DATA XREF: ROM:0003B25Co*/
		.byte  0xF8,   9,	  8,   4, 0xFF, 0xD0
		.byte  0xF8,   9,	  8,  0xA, 0xFF, 0xE8
		.byte  0xF8,   9,	  8,   4,   0,	 0
		.byte  0xF8,   9,	  8,  0xA,   0, 0x18
word_3B2E0:	.word 3			/* DATA XREF: ROM:0003B25Co*/
		.byte  0xFC,   0,	  0,   0, 0xFF, 0xDC
		.byte  0xFC,   0,	  0,   0, 0xFF, 0xFC
		.byte  0xFC,   0,	  0,   0,   0, 0x1C
word_3B2F4:	.word 0			/* DATA XREF: ROM:0003B25Co*/
