		.word word_3BBC4-Map_FBZDisappearingPlatform
		.word word_3BBD2-Map_FBZDisappearingPlatform
		.word word_3BBE6-Map_FBZDisappearingPlatform
word_3BBC4:	.word 2			/* DATA XREF: ROM:0003BBBEo*/
		.byte  0xF0,  0xE,	  0,   9, 0xFF, 0xF0
		.byte	8,   8,	  0, 0x15, 0xFF, 0xF0
word_3BBD2:	.word 3			/* DATA XREF: ROM:0003BBBEo*/
		.byte  0xF0,   0,	  0,   0, 0xFF, 0xF0
		.byte  0xF8,   4,	  0,   1, 0xFF, 0xF0
		.byte	0,   9,	  0,   3, 0xFF, 0xF0
word_3BBE6:	.word 0			/* DATA XREF: ROM:0003BBBEo*/
