Map_A464:		.word word_A48A-Map_A464
		.word word_A492-Map_A464
		.word word_A49A-Map_A464
		.word word_A4A2-Map_A464
		.word word_A4AA-Map_A464
		.word word_A4B2-Map_A464
		.word word_A4BA-Map_A464
		.word word_A4C2-Map_A464
		.word word_A4CA-Map_A464
		.word word_A4D2-Map_A464
		.word word_A4DA-Map_A464
		.word word_A4DA-Map_A464
		.word word_A4E2-Map_A464
		.word word_A4E2-Map_A464
		.word word_A4EA-Map_A464
		.word word_A4EA-Map_A464
		.word word_A4F2-Map_A464
		.word word_A4FA-Map_A464
		.word word_A502-Map_A464
word_A48A:	.word 1			
		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xF0
word_A492:	.word 1			
		.byte  0xF0,  0xF,	  0, 0x10, 0xFF, 0xF0
word_A49A:	.word 1			
		.byte  0xF0,  0xF,	  0, 0x20, 0xFF, 0xF0
word_A4A2:	.word 1			
		.byte  0xF0,  0xF,	  0, 0x30, 0xFF, 0xF0
word_A4AA:	.word 1			
		.byte  0xF4,  0xA,	  0, 0x40, 0xFF, 0xF4
word_A4B2:	.word 1			
		.byte  0xF4,  0xA,	  0, 0x49, 0xFF, 0xF4
word_A4BA:	.word 1			
		.byte  0xF4,  0xA,	  0, 0x52, 0xFF, 0xF4
word_A4C2:	.word 1			
		.byte  0xF4,  0xA,	  0, 0x5B, 0xFF, 0xF4
word_A4CA:	.word 1			
		.byte  0xF8,   5,	  0, 0x64, 0xFF, 0xF8
word_A4D2:	.word 1			
		.byte  0xF8,   5,	  0, 0x68, 0xFF, 0xF8
word_A4DA:	.word 1			
		.byte  0xF8,   5,	  0, 0x6C, 0xFF, 0xF8
word_A4E2:	.word 1			
		.byte  0xF8,   5,	  0, 0x70, 0xFF, 0xF8
word_A4EA:	.word 1			
		.byte  0xFC,   0,	  0, 0x74, 0xFF, 0xFC
word_A4F2:	.word 1			
		.byte  0xFC,   0,	  0, 0x75, 0xFF, 0xFC
word_A4FA:	.word 1			
		.byte  0xFC,   0,	  0, 0x76, 0xFF, 0xFC
word_A502:	.word 1			
		.byte  0xFC,   0,	  0, 0x77, 0xFF, 0xFC
