Map_A50A:		.word word_A572-Map_A50A
		.word word_A57A-Map_A50A
		.word word_A582-Map_A50A
		.word word_A58A-Map_A50A
		.word word_A592-Map_A50A
		.word word_A59A-Map_A50A
		.word word_A5A2-Map_A50A
		.word word_A5AA-Map_A50A
		.word word_A5B2-Map_A50A
		.word word_A5BA-Map_A50A
		.word word_A5BA-Map_A50A
		.word word_A5BA-Map_A50A
		.word word_A5BA-Map_A50A
		.word word_A5BA-Map_A50A
		.word word_A5BA-Map_A50A
		.word word_A5BA-Map_A50A
		.word word_A5D2-Map_A50A
		.word word_A5DA-Map_A50A
		.word word_A5E2-Map_A50A
		.word word_A5EA-Map_A50A
		.word word_A5F2-Map_A50A
		.word word_A5FA-Map_A50A
		.word word_A602-Map_A50A
		.word word_A60A-Map_A50A
		.word word_A612-Map_A50A
		.word word_A61A-Map_A50A
		.word word_A61A-Map_A50A
		.word word_A61A-Map_A50A
		.word word_A61A-Map_A50A
		.word word_A61A-Map_A50A
		.word word_A61A-Map_A50A
		.word word_A61A-Map_A50A
		.word word_A632-Map_A50A
		.word word_A63A-Map_A50A
		.word word_A642-Map_A50A
		.word word_A64A-Map_A50A
		.word word_A652-Map_A50A
		.word word_A65A-Map_A50A
		.word word_A662-Map_A50A
		.word word_A66A-Map_A50A
		.word word_A672-Map_A50A
		.word word_A67A-Map_A50A
		.word word_A67A-Map_A50A
		.word word_A67A-Map_A50A
		.word word_A67A-Map_A50A
		.word word_A67A-Map_A50A
		.word word_A67A-Map_A50A
		.word word_A67A-Map_A50A
		.word word_A692-Map_A50A
		.word word_A69A-Map_A50A
		.word word_A6A2-Map_A50A
		.word word_A6AA-Map_A50A
word_A572:	.word 1			
		.byte  0xF8,   9,	  0,   0, 0xFF, 0xF4
word_A57A:	.word 1			
		.byte  0xF8,   9,	  0,  0xC, 0xFF, 0xF4
word_A582:	.word 1			
		.byte  0xF4,  0xA,	  0, 0x18, 0xFF, 0xF4
word_A58A:	.word 1			
		.byte  0xF8,   9,	  0, 0x27, 0xFF, 0xF4
word_A592:	.word 1			
		.byte  0xF8,   5,	  0, 0x33, 0xFF, 0xF8
word_A59A:	.word 1			
		.byte  0xF8,   5,	  0, 0x39, 0xFF, 0xF8
word_A5A2:	.word 1			
		.byte  0xF8,   5,	  0, 0x3F, 0xFF, 0xF8
word_A5AA:	.word 1			
		.byte  0xFC,   4,	  0, 0x45, 0xFF, 0xF8
word_A5B2:	.word 1			
		.byte  0xFC,   0,	  0, 0x48, 0xFF, 0xFC
word_A5BA:	.word 1			
		.byte  0xFC,   0,	  0, 0x4A, 0xFF, 0xFC
		.word 1
		.byte  0xFC,   0,	  0, 0x4C, 0xFF, 0xFC
		.word 1
		.byte  0xFC,   0,	  0, 0x4E, 0xFF, 0xFC
word_A5D2:	.word 1			
		.byte  0xF4,   6,	  0,   6, 0xFF, 0xF8
word_A5DA:	.word 1			
		.byte  0xF4,   6,	  0, 0x12, 0xFF, 0xF8
word_A5E2:	.word 1			
		.byte  0xF4,   6,	  0, 0x21, 0xFF, 0xF8
word_A5EA:	.word 1			
		.byte  0xF4,   6,	  0, 0x2D, 0xFF, 0xF8
word_A5F2:	.word 1			
		.byte  0xF8,   1,	  0, 0x37, 0xFF, 0xFC
word_A5FA:	.word 1			
		.byte  0xF8,   1,	  0, 0x3D, 0xFF, 0xFC
word_A602:	.word 1			
		.byte  0xF8,   1,	  0, 0x43, 0xFF, 0xFC
word_A60A:	.word 1			
		.byte  0xFC,   0,	  0, 0x47, 0xFF, 0xFC
word_A612:	.word 1			
		.byte  0xFC,   0,	  0, 0x49, 0xFF, 0xFC
word_A61A:	.word 1			
		.byte  0xFC,   0,	  0, 0x4B, 0xFF, 0xFC
		.word 1
		.byte  0xFC,   0,	  0, 0x4D, 0xFF, 0xFC
		.word 1
		.byte  0xFC,   0,	  0, 0x4F, 0xFF, 0xFC
word_A632:	.word 1			
		.byte  0xF4,   6,	  8,   6, 0xFF, 0xF8
word_A63A:	.word 1			
		.byte  0xF4,   6,	  8, 0x12, 0xFF, 0xF8
word_A642:	.word 1			
		.byte  0xF4,   6,	  8, 0x21, 0xFF, 0xF8
word_A64A:	.word 1			
		.byte  0xF4,   6,	  8, 0x2D, 0xFF, 0xF8
word_A652:	.word 1			
		.byte  0xF8,   1,	  8, 0x37, 0xFF, 0xFC
word_A65A:	.word 1			
		.byte  0xF8,   1,	  8, 0x3D, 0xFF, 0xFC
word_A662:	.word 1			
		.byte  0xF8,   1,	  8, 0x43, 0xFF, 0xFC
word_A66A:	.word 1			
		.byte  0xFC,   0,	  8, 0x47, 0xFF, 0xFC
word_A672:	.word 1			
		.byte  0xFC,   0,	  8, 0x49, 0xFF, 0xFC
word_A67A:	.word 1			
		.byte  0xFC,   0,	  8, 0x4B, 0xFF, 0xFC
		.word 1
		.byte  0xFC,   0,	  8, 0x4D, 0xFF, 0xFC
		.word 1
		.byte  0xFC,   0,	  8, 0x4F, 0xFF, 0xFC
word_A692:	.word 1			
		.byte  0xF4,  0xA,	  0, 0x50, 0xFF, 0xF4
word_A69A:	.word 1			
		.byte  0xF4,  0xA,	0x18, 0x50, 0xFF, 0xF4
word_A6A2:	.word 1			
		.byte  0xF4,  0xA,	  8, 0x50, 0xFF, 0xF4
word_A6AA:	.word 1			
		.byte  0xF4,  0xA,	0x10, 0x50, 0xFF, 0xF4
