Map_A6B2:		.word word_A6D2-Map_A6B2
		.word word_A6DA-Map_A6B2
		.word word_A6E2-Map_A6B2
		.word word_A6EA-Map_A6B2
		.word word_A6F2-Map_A6B2
		.word word_A6FA-Map_A6B2
		.word word_A702-Map_A6B2
		.word word_A70A-Map_A6B2
		.word word_A712-Map_A6B2
		.word word_A71A-Map_A6B2
		.word word_A722-Map_A6B2
		.word word_A722-Map_A6B2
		.word word_A72A-Map_A6B2
		.word word_A72A-Map_A6B2
		.word word_A732-Map_A6B2
		.word word_A73A-Map_A6B2
word_A6D2:	.word 1			
		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xF0
word_A6DA:	.word 1			
		.byte  0xF0,  0xF,	  0, 0x10, 0xFF, 0xF0
word_A6E2:	.word 1			
		.byte  0xF4,  0xA,	  0, 0x20, 0xFF, 0xF4
word_A6EA:	.word 1			
		.byte  0xF4,  0xA,	  0, 0x29, 0xFF, 0xF4
word_A6F2:	.word 1			
		.byte  0xF4,  0xA,	  0, 0x32, 0xFF, 0xF4
word_A6FA:	.word 1			
		.byte  0xF4,  0xA,	  0, 0x3B, 0xFF, 0xF4
word_A702:	.word 1			
		.byte  0xF8,   5,	  0, 0x44, 0xFF, 0xF8
word_A70A:	.word 1			
		.byte  0xF8,   5,	  0, 0x48, 0xFF, 0xF8
word_A712:	.word 1			
		.byte  0xF8,   5,	  0, 0x4C, 0xFF, 0xF8
word_A71A:	.word 1			
		.byte  0xF8,   5,	  0, 0x50, 0xFF, 0xF8
word_A722:	.word 1			
		.byte  0xFC,   0,	  0, 0x54, 0xFF, 0xFC
word_A72A:	.word 1			
		.byte  0xFC,   0,	  0, 0x55, 0xFF, 0xFC
word_A732:	.word 1			
		.byte  0xFC,   0,	  0, 0x56, 0xFF, 0xFC
word_A73A:	.word 1			
		.byte  0xFC,   0,	  0, 0x57, 0xFF, 0xFC
