		.word word_23BF0-Map_SphereTest
		.word word_23BF8-Map_SphereTest
		.word word_23C00-Map_SphereTest
		.word word_23C08-Map_SphereTest
		.word word_23C10-Map_SphereTest
		.word word_23C18-Map_SphereTest
		.word word_23C20-Map_SphereTest
		.word word_23C28-Map_SphereTest
		.word word_23C30-Map_SphereTest
		.word word_23C38-Map_SphereTest
		.word word_23C40-Map_SphereTest
		.word word_23C48-Map_SphereTest
		.word word_23C50-Map_SphereTest
		.word word_23C58-Map_SphereTest
		.word word_23C60-Map_SphereTest
		.word word_23C68-Map_SphereTest
word_23BF0:	.word 1
		.byte  0xF0,  0xF,   0,   0, 0xFF, 0xF0
word_23BF8:	.word 1
		.byte  0xF0,  0xF,   0, 0x10, 0xFF, 0xF0
word_23C00:	.word 1
		.byte  0xF0,  0xF,   0, 0x20, 0xFF, 0xF0
word_23C08:	.word 1
		.byte  0xF0,  0xF,   0, 0x30, 0xFF, 0xF0
word_23C10:	.word 1
		.byte  0xF0,  0xF,   0, 0x40, 0xFF, 0xF0
word_23C18:	.word 1
		.byte  0xF0,  0xF,   0, 0x50, 0xFF, 0xF0
word_23C20:	.word 1
		.byte  0xF0,  0xF,   0, 0x60, 0xFF, 0xF0
word_23C28:	.word 1
		.byte  0xF0,  0xF,   0, 0x70, 0xFF, 0xF0
word_23C30:	.word 1
		.byte  0xF8,   5,   0, 0x80, 0xFF, 0xF8
word_23C38:	.word 1
		.byte  0xF8,   5,   0, 0x84, 0xFF, 0xF8
word_23C40:	.word 1
		.byte  0xF8,   5,   0, 0x88, 0xFF, 0xF8
word_23C48:	.word 1
		.byte  0xF8,   5,   0, 0x8C, 0xFF, 0xF8
word_23C50:	.word 1
		.byte  0xF8,   5,   0, 0x90, 0xFF, 0xF8
word_23C58:	.word 1
		.byte  0xF8,   5,   0, 0x94, 0xFF, 0xF8
word_23C60:	.word 1
		.byte  0xF8,   5,   0, 0x98, 0xFF, 0xF8
word_23C68:	.word 1
		.byte  0xF8,   5,   0, 0x9C, 0xFF, 0xF8
