Ani_4495A:		.word byte_4495E-Ani_4495A
		.word byte_44964-Ani_4495A
byte_4495E:	.byte	3, 0x7F,	0xFC, 0xFF, 0xFD,	 1 
byte_44964:	.byte	4,  0xD,	  3,  0xD,   4,	0xB 
		.byte	3,  0xB,	  4,   9,   3,	 9
		.byte	4,   7,	  3,   7,   4,	 5
		.byte	3,   5,	  4,   3,   3,	 3
		.byte	4,   1,	  3,   1,   4,	 0
		.byte	3,   0,	  4,   0,   3,	 0
		.byte	4,   0,	  3,   0,   4,	 0
		.byte	3,   0,	  4,   0,   3,	 0
		.byte	4,   0,	  3,   0,   4,	 0
		.byte	3,   0,	  4,   0,   3,	 0
		.byte	4,   0,	  3,   0,   4,	 0
		.byte	3,   0,	  4,   0,   3,	 0
		.byte	4,   0,	  3,   0,   4,	 0
		.byte	3,   0,	  4,   0,   3,	 0
		.byte  0xFC, 0xFF,	0xFD,   0
