Map_LRZSwingingSpikeBall_:.word word_4366E-Map_LRZSwingingSpikeBall_
		.word word_43676-Map_LRZSwingingSpikeBall_
		.word word_43682-Map_LRZSwingingSpikeBall_
		.word word_43690-Map_LRZSwingingSpikeBall_
word_4366E:	.word 1
		.byte  0xF4,  0xA,	  0, 0x22, 0xFF, 0xF4
word_43676:	.word 1
		.byte  0xF8,   5,	  0, 0x2B, 0xFF, 0xF8
Map_LRZSwingingSpikeBall2:
Map_4367E:	.word word_43682-Map_4367E
		.word word_43690-Map_4367E
word_43682:	.word 2

		.byte  0xF0,   7,	  0, 0x10, 0xFF, 0xF0
		.byte  0xF0,   7,	  8, 0x10,   0,	 0
word_43690:	.word 1

		.byte  0xF8,   5,	  0, 0x18, 0xFF, 0xF8