		.word word_4409A-Map_LRZFlameThrower
		.word word_440A2-Map_LRZFlameThrower
		.word word_440AA-Map_LRZFlameThrower
		.word word_440B2-Map_LRZFlameThrower
		.word word_440BA-Map_LRZFlameThrower
		.word word_440C2-Map_LRZFlameThrower
		.word word_440CA-Map_LRZFlameThrower
		.word word_440DE-Map_LRZFlameThrower
word_4409A:	.word 1			/* DATA XREF: ROM:0004408Ao*/
		.byte  0xF8,   5,	  0, 0x24, 0xFF, 0xF8
word_440A2:	.word 1			/* DATA XREF: ROM:0004408Ao*/
		.byte  0xF8,   5,	  8, 0x24, 0xFF, 0xF8
word_440AA:	.word 1			/* DATA XREF: ROM:0004408Ao*/
		.byte  0xF4,   6,	  0, 0x28, 0xFF, 0xF8
word_440B2:	.word 1			/* DATA XREF: ROM:0004408Ao*/
		.byte  0xF4,   6,	  8, 0x28, 0xFF, 0xF8
word_440BA:	.word 1			/* DATA XREF: ROM:0004408Ao*/
		.byte  0xF4,  0xA,	  0, 0x2E, 0xFF, 0xF4
word_440C2:	.word 1			/* DATA XREF: ROM:0004408Ao*/
		.byte  0xF4,  0xA,	  8, 0x2E, 0xFF, 0xF4
word_440CA:	.word 3			/* DATA XREF: ROM:0004408Ao*/
		.byte  0xF0,  0xF,	0x48, 0x44, 0xFF, 0xE8
		.byte  0xF0,   5,	  8, 0x40,   0,	 8
		.byte	0,   5,	0x18, 0x40,   0,	 8
word_440DE:	.word 3			/* DATA XREF: ROM:0004408Ao*/
		.byte  0xF0,  0xE,	0x40, 0x88, 0xFF, 0xF0
		.byte	8,   4,	  0, 0x94, 0xFF, 0xF0
		.byte	8,   4,	  8, 0x94,   0,	 0
