		.word word_449C6-Map_LRZSpikeBallLauncher
		.word word_449D4-Map_LRZSpikeBallLauncher
		.word word_449DC-Map_LRZSpikeBallLauncher
		.word word_449E4-Map_LRZSpikeBallLauncher
		.word word_449F2-Map_LRZSpikeBallLauncher
word_449C6:	.word 2			/*  DATA XREF: ROM:000449BCo */
		.byte  0xF0,   7,	  0, 0x10, 0xFF, 0xF0
		.byte  0xF0,   7,	  8, 0x10,   0,	 0
word_449D4:	.word 1			/*  DATA XREF: ROM:000449BCo */
		.byte  0xF0,  0xF,	  0, 0x73, 0xFF, 0xF0
word_449DC:	.word 1			/*  DATA XREF: ROM:000449BCo */
		.byte  0xF0,  0xF,	  8, 0x73, 0xFF, 0xF0
word_449E4:	.word 2			/*  DATA XREF: ROM:000449BCo */
		.byte  0xFC,   4,	  0, 0x83, 0xFF, 0xF0
		.byte  0xFC,   4,	  8, 0x83,   0,	 0
word_449F2:	.word 4			/*  DATA XREF: ROM:000449BCo */
		.byte  0xFC,   4,	  0, 0x85, 0xFF, 0xF0
		.byte  0xFC,   4,	  8, 0x85,   0,	 0
		.byte  0xFC,   4,	  0, 0x83, 0xFF, 0xF0
		.byte  0xFC,   4,	  8, 0x83,   0,	 0
