		.word word_42CB8-Map_LRZFireballLauncher
		.word word_42CC0-Map_LRZFireballLauncher
		.word word_42CC8-Map_LRZFireballLauncher
word_42CB8:	.word 1			/*  DATA XREF: ROM:00042CB2o */
		.byte  0xF8,   9,	  0, 0x1C, 0xFF, 0xF4
word_42CC0:	.word 1			/*  DATA XREF: ROM:00042CB2o */
		.byte  0xF8,   9,	0x10, 0x1C, 0xFF, 0xF4
word_42CC8:	.word 2			/*  DATA XREF: ROM:00042CB2o */
		.byte  0xF0,   1,	  0, 0x1A, 0xFF, 0xFC
		.byte	0,   1,	0x10, 0x1A, 0xFF, 0xFC
