		.word word_2C74E-Map_LRZButton
		.word word_2C75C-Map_LRZButton
		.word word_2C76A-Map_LRZButton
word_2C74E:	.word 2			/* DATA XREF: ROM:0002C748o*/
		.byte  0xF6,   5,	  0,   0, 0xFF, 0xF0
		.byte  0xF6,   5,	  8,   0,   0,	 0
word_2C75C:	.word 2			/* DATA XREF: ROM:0002C748o*/
		.byte  0xF6,   5,	  0,   4, 0xFF, 0xF0
		.byte  0xF6,   5,	  8,   4,   0,	 0
word_2C76A:	.word 2			/* DATA XREF: ROM:0002C748o*/
		.byte  0xFA,   5,	  0,   0, 0xFF, 0xF0
		.byte  0xFA,   5,	  8,   0,   0,	 0
