		.word word_20492-Map_LRZBreakableRock2
		.word word_204A0-Map_LRZBreakableRock2
		.word word_204AE-Map_LRZBreakableRock2
		.word word_204BC-Map_LRZBreakableRock2
		.word word_20492-Map_LRZBreakableRock2
		.word word_204A0-Map_LRZBreakableRock2
		.word word_204AE-Map_LRZBreakableRock2
		.word word_204BC-Map_LRZBreakableRock2
		.word word_204CA-Map_LRZBreakableRock2
		.word word_204E4-Map_LRZBreakableRock2
		.word word_204E4-Map_LRZBreakableRock2
		.word word_204CA-Map_LRZBreakableRock2
word_20492:	.word 2			/*  DATA XREF: ROM:0002047Ao */
		.byte  0xF0,  0xD,	  0,   0, 0xFF, 0xF0
		.byte	0,  0xD,	  0,   8, 0xFF, 0xF0
word_204A0:	.word 2			/*  DATA XREF: ROM:0002047Ao */
		.byte  0xF0,  0xD,	  8,   0, 0xFF, 0xF0
		.byte	0,  0xD,	  8,   8, 0xFF, 0xF0
word_204AE:	.word 2			/*  DATA XREF: ROM:0002047Ao */
		.byte  0xF0,  0xD,	0x18,   8, 0xFF, 0xF0
		.byte	0,  0xD,	0x18,   0, 0xFF, 0xF0
word_204BC:	.word 2			/*  DATA XREF: ROM:0002047Ao */
		.byte  0xF0,  0xD,	0x10,   8, 0xFF, 0xF0
		.byte	0,  0xD,	0x10,   0, 0xFF, 0xF0
word_204CA:	.word 4			/*  DATA XREF: ROM:0002047Ao */
		.byte  0xE0,  0xD,	  0,   0, 0xFF, 0xF0
		.byte  0xF0,  0xD,	  0,   8, 0xFF, 0xF0
		.byte	0,  0xD,	  8,   0, 0xFF, 0xF0
		.byte  0x10,  0xD,	  8,   8, 0xFF, 0xF0
word_204E4:	.word 4			/*  DATA XREF: ROM:0002047Ao */
		.byte  0xF0,  0xD,	  0,   0, 0xFF, 0xE0
		.byte  0xF0,  0xD,	0x10,   8,   0,	 0
		.byte	0,  0xD,	  0,   8, 0xFF, 0xE0
		.byte	0,  0xD,	0x10,   0,   0,	 0
