Map_LRZButtonHorizontal_:.word word_42D82-Map_LRZButtonHorizontal_
		.word word_42D90-Map_LRZButtonHorizontal_
		.word word_42DA2-Map_LRZButtonHorizontal_
word_42D82:	.word 2
		.byte  0xF0,   5,	  0,   8, 0xFF, 0xF8
		.byte	0,   5,	0x10,   8, 0xFF, 0xF8
word_42D90:	.word 2
		.byte  0xF0,   5,	  0,  0xC, 0xFF, 0xF8
		.byte	0,   5,	0x10,  0xC, 0xFF, 0xF8
Map_LRZButtonHorizontal2:
Map_42D9E:	.word word_42DA2-Map_42D9E
		.word word_42DB0-Map_42D9E
word_42DA2:	.word 2

		.byte  0xF0,   5,	  0, 0x63, 0xFF, 0xF8
		.byte	0,   5,	0x10, 0x63, 0xFF, 0xF8
word_42DB0:	.word 2
		.byte  0xF0,   5,	  0, 0x67, 0xFF, 0xF8
		.byte	0,   5,	0x10, 0x67, 0xFF, 0xF8