	/*           Object			Mappings			Subtype Frame Arttile */
	dbglistobj Obj_Ring,			Map_Ring,			   0,   0, make_art_tile(ArtTile_Ring,1,1)
	dbglistobj Obj_Monitor,			Map_Monitor,			   9,   0, make_art_tile(ArtTile_Monitors,0,0)
	dbglistobj Obj_PathSwap,		Map_PathSwap,			   9,   1, make_art_tile(ArtTile_Ring,1,0)
	dbglistobj Obj_PathSwap,		Map_PathSwap,			  0xD,   5, make_art_tile(ArtTile_Ring,1,0)
	dbglistobj Obj_Spring,			Map_Spring,			 0x81,   0, make_art_tile(0x4A4,0,0)
	dbglistobj Obj_Spring,			Map_Spring,			 0x90,   3, make_art_tile(0x4B4,0,0)
	dbglistobj Obj_Spring,			Map_Spring,			 0xA0,   6, make_art_tile(0x4A4,0,0)
	dbglistobj Obj_Spikes,			Map_Spikes,			   0,   0, make_art_tile(0x49C,0,0)
