DPLC_8F6DC:		.word word_8F700-DPLC_8F6DC
		.word word_8F704-DPLC_8F6DC
		.word word_8F708-DPLC_8F6DC
		.word word_8F70C-DPLC_8F6DC
		.word word_8F710-DPLC_8F6DC
		.word word_8F714-DPLC_8F6DC
		.word word_8F718-DPLC_8F6DC
		.word word_8F71C-DPLC_8F6DC
		.word word_8F720-DPLC_8F6DC
		.word word_8F724-DPLC_8F6DC
		.word word_8F72A-DPLC_8F6DC
		.word word_8F730-DPLC_8F6DC
		.word word_8F736-DPLC_8F6DC
		.word word_8F73C-DPLC_8F6DC
		.word word_8F740-DPLC_8F6DC
		.word word_8F744-DPLC_8F6DC
		.word word_8F748-DPLC_8F6DC
		.word word_8F74C-DPLC_8F6DC
word_8F700:	.word 0			
		.word 8
word_8F704:	.word 0			
		.word 0x98
word_8F708:	.word 0			
		.word 0x128
word_8F70C:	.word 0			
		.word 0x1B8
word_8F710:	.word 0			
		.word 0x248
word_8F714:	.word 0			
		.word 0x2D8
word_8F718:	.word 0			
		.word 0x368
word_8F71C:	.word 0			
		.word 0x3F8
word_8F720:	.word 0			
		.word 0x48F
word_8F724:	.word 1			
		.word 0x585
		.word 0x5EB
word_8F72A:	.word 1			
		.word 0x6A5
		.word 0x70B
word_8F730:	.word 1			
		.word 0x7C5
		.word 0x82B
word_8F736:	.word 1			
		.word 0x6A5
		.word 0x8EB
word_8F73C:	.word 0			
		.word 0x9A8
word_8F740:	.word 0			
		.word 0xA38
word_8F744:	.word 0			
		.word 0xAC3
word_8F748:	.word 0			
		.word 0xB03
word_8F74C:	.word 0			
		.word 0xB40
