Map_1872B6:		.word word_1872DA-Map_1872B6
		.word word_1872E2-Map_1872B6
		.word word_1872EA-Map_1872B6
		.word word_1872F2-Map_1872B6
		.word word_1872FA-Map_1872B6
		.word word_187302-Map_1872B6
		.word word_18730A-Map_1872B6
		.word word_187312-Map_1872B6
		.word word_18731A-Map_1872B6
		.word word_187322-Map_1872B6
		.word word_187330-Map_1872B6
		.word word_18733E-Map_1872B6
		.word word_18734C-Map_1872B6
		.word word_18735A-Map_1872B6
		.word word_187362-Map_1872B6
		.word word_18736A-Map_1872B6
		.word word_187372-Map_1872B6
		.word word_18737A-Map_1872B6
word_1872DA:	.word 1			
		.byte  0xF4,  0xA,	  0,   0, 0xFF, 0xF4
word_1872E2:	.word 1			
		.byte  0xF4,  0xA,	  0,   0, 0xFF, 0xF4
word_1872EA:	.word 1			
		.byte  0xF4,  0xA,	  0,   0, 0xFF, 0xF4
word_1872F2:	.word 1			
		.byte  0xF4,  0xA,	  0,   0, 0xFF, 0xF4
word_1872FA:	.word 1			
		.byte  0xF4,  0xA,	  0,   0, 0xFF, 0xF4
word_187302:	.word 1			
		.byte  0xF4,  0xA,	  0,   0, 0xFF, 0xF4
word_18730A:	.word 1			
		.byte  0xF4,  0xA,	  0,   0, 0xFF, 0xF4
word_187312:	.word 1			
		.byte  0xF4,  0xA,	  0,   0, 0xFF, 0xF4
word_18731A:	.word 1			
		.byte  0xF0,  0xF,	  0,   0, 0xFF, 0xF0
word_187322:	.word 2			
		.byte  0xEC,   9,	  0,   0, 0xFF, 0xF0
		.byte  0xFC,  0xE,	  0,   6, 0xFF, 0xF0
word_187330:	.word 2			
		.byte  0xEC,   9,	  0,   0, 0xFF, 0xF0
		.byte  0xFC,  0xE,	  0,   6, 0xFF, 0xF0
word_18733E:	.word 2			
		.byte  0xEC,   9,	  0,   0, 0xFF, 0xF0
		.byte  0xFC,  0xE,	  0,   6, 0xFF, 0xF0
word_18734C:	.word 2			
		.byte  0xEC,   9,	  0,   0, 0xFF, 0xF0
		.byte  0xFC,  0xE,	  0,   6, 0xFF, 0xF0
word_18735A:	.word 1			
		.byte  0xF4,  0xA,	  0,   0, 0xFF, 0xF4
word_187362:	.word 1			
		.byte  0xF4,  0xA,	  0,   0, 0xFF, 0xF4
word_18736A:	.word 1			
		.byte  0xF8,   5,	  0,   0, 0xFF, 0xF8
word_187372:	.word 1			
		.byte  0xF8,   5,	  0,   0, 0xFF, 0xF8
word_18737A:	.word 1			
		.byte  0xFC,   0,	  0,   0, 0xFF, 0xFC
