		.word byte_2FC90-Ani_Bubbler
		.word byte_2FC95-Ani_Bubbler
		.word byte_2FC9B-Ani_Bubbler
		.word byte_2FCA2-Ani_Bubbler
		.word byte_2FCA6-Ani_Bubbler
		.word byte_2FCA6-Ani_Bubbler
		.word byte_2FCA8-Ani_Bubbler
		.word byte_2FCA8-Ani_Bubbler
		.word byte_2FCAC-Ani_Bubbler
byte_2FC90:	.byte   0xE,   0,	  1,   2, 0xFC 
byte_2FC95:	.byte   0xE,   1,	  2,   3,   4, 0xFC 
byte_2FC9B:	.byte   0xE,   2,	  3,   4,   5,	 6, 0xFC	
byte_2FCA2:	.byte	2,   5,	  6, 0xFC 
byte_2FCA6:	.byte	4, 0xFC		
byte_2FCA8:	.byte	4,   7,	  8, 0xFC 
byte_2FCAC:	.byte   0xF, 0x13,	0x14, 0x15, 0xFF,	 0 
