Map_Bubbler_:	.word word_2FD0E-Map_Bubbler_

		.word word_2FD16-Map_Bubbler_
		.word word_2FD1E-Map_Bubbler_
		.word word_2FD26-Map_Bubbler_
		.word word_2FD2E-Map_Bubbler_
		.word word_2FD36-Map_Bubbler_
		.word word_2FD3E-Map_Bubbler_
		.word word_2FD46-Map_Bubbler_
		.word word_2FD60-Map_Bubbler_
		.word word_2FD7A-Map_Bubbler_
		.word word_2FD7A-Map_Bubbler_
		.word word_2FD7A-Map_Bubbler_
		.word word_2FD7A-Map_Bubbler_
		.word word_2FD7A-Map_Bubbler_
		.word word_2FD7A-Map_Bubbler_
		.word word_2FD7A-Map_Bubbler_
		.word word_2FD7A-Map_Bubbler_
		.word word_2FD7A-Map_Bubbler_
		.word word_2FD7A-Map_Bubbler_
		.word word_2FD82-Map_Bubbler_
		.word word_2FD8A-Map_Bubbler_
		.word word_2FD92-Map_Bubbler_
		.word word_2FD9A-Map_Bubbler_
Map_Bubbler2:
Map_Bubbler2_:	.word word_2FD0E-Map_Bubbler2_

		.word word_2FD16-Map_Bubbler2_
		.word word_2FD1E-Map_Bubbler2_
		.word word_2FD26-Map_Bubbler2_
		.word word_2FD2E-Map_Bubbler2_
		.word word_2FD36-Map_Bubbler2_
		.word word_2FD3E-Map_Bubbler2_
		.word word_2FD46-Map_Bubbler2_
		.word word_2FD60-Map_Bubbler2_
		.word word_2FD9C-Map_Bubbler2_
		.word word_2FD9C-Map_Bubbler2_
		.word word_2FD9C-Map_Bubbler2_
		.word word_2FD9C-Map_Bubbler2_
		.word word_2FD9C-Map_Bubbler2_
		.word word_2FD9C-Map_Bubbler2_
		.word word_2FD9C-Map_Bubbler2_
		.word word_2FD9C-Map_Bubbler2_
		.word word_2FD9C-Map_Bubbler2_
		.word word_2FD9C-Map_Bubbler2_
		.word word_2FD82-Map_Bubbler2_
		.word word_2FD8A-Map_Bubbler2_
		.word word_2FD92-Map_Bubbler2_
		.word word_2FD9A-Map_Bubbler2_
word_2FD0E:	.word 1

		.byte  0xFC,   0,	  0,   0, 0xFF, 0xFC
word_2FD16:	.word 1

		.byte  0xFC,   0,	  0,   1, 0xFF, 0xFC
word_2FD1E:	.word 1

		.byte  0xFC,   0,	  0,   2, 0xFF, 0xFC
word_2FD26:	.word 1

		.byte  0xF8,   5,	  0,   3, 0xFF, 0xF8
word_2FD2E:	.word 1

		.byte  0xF8,   5,	  0,   7, 0xFF, 0xF8
word_2FD36:	.word 1

		.byte  0xF4,  0xA,	  0,  0xB, 0xFF, 0xF4
word_2FD3E:	.word 1

		.byte  0xF0,  0xF,	  0, 0x14, 0xFF, 0xF0
word_2FD46:	.word 4

		.byte  0xF0,   5,	  0, 0x24, 0xFF, 0xF0
		.byte  0xF0,   5,	  8, 0x24,   0,	 0
		.byte	0,   5,	0x10, 0x24, 0xFF, 0xF0
		.byte	0,   5,	0x18, 0x24,   0,	 0
word_2FD60:	.word 4

		.byte  0xF0,   5,	  0, 0x28, 0xFF, 0xF0
		.byte  0xF0,   5,	  8, 0x28,   0,	 0
		.byte	0,   5,	0x10, 0x28, 0xFF, 0xF0
		.byte	0,   5,	0x18, 0x28,   0,	 0
word_2FD7A:	.word 1
		.byte  0xF4,   6,	  3, 0x84, 0xFF, 0xF8
word_2FD82:	.word 1

		.byte  0xF8,   5,	  0, 0x2C, 0xFF, 0xF8
word_2FD8A:	.word 1

		.byte  0xF8,   5,	  0, 0x30, 0xFF, 0xF8
word_2FD92:	.word 1

		.byte  0xF8,   5,	  0, 0x34, 0xFF, 0xF8
word_2FD9A:	.word 0

word_2FD9C:	.word 1
		.byte  0xF4,   6,	  3, 0x94, 0xFF, 0xF8