		.word word_4FF4-Map_TitleTailsPlane
		.word word_5002-Map_TitleTailsPlane
		.word word_5010-Map_TitleTailsPlane
		.word word_501E-Map_TitleTailsPlane
		.word word_502C-Map_TitleTailsPlane
		.word word_503A-Map_TitleTailsPlane
word_4FF4:	.word 2			
		.byte  0xF4,  0xE,	  0, 0x84, 0xFF, 0xE8
		.byte  0xF4,   6,	  0, 0x9C,   0,	 8
word_5002:	.word 2			
		.byte  0xF4,  0xE,	  0, 0x90, 0xFF, 0xE8
		.byte  0xF4,   6,	  0, 0xA2,   0,	 8
word_5010:	.word 2			
		.byte  0xF4,  0xE,	  0, 0x84, 0xFF, 0xE8
		.byte  0xF4,   6,	  0, 0xA8,   0,	 8
word_501E:	.word 2			
		.byte  0xF4,  0xE,	  0, 0x90, 0xFF, 0xE8
		.byte  0xF4,   6,	  0, 0x9C,   0,	 8
word_502C:	.word 2			
		.byte  0xF4,  0xE,	  0, 0x84, 0xFF, 0xE8
		.byte  0xF4,   6,	  0, 0xA2,   0,	 8
word_503A:	.word 2			
		.byte  0xF4,  0xE,	  0, 0x90, 0xFF, 0xE8
		.byte  0xF4,   6,	  0, 0xA8,   0,	 8
