/*  Spikebonker mappings */
		.word word_184E64-Map_Spikebonker
		.word word_184E72-Map_Spikebonker
		.word word_184E7A-Map_Spikebonker
		.word word_184E82-Map_Spikebonker
word_184E64:	.word 2			/*  DATA XREF: ROM:00184E5Co */
		.byte  0xF0,  0xE,	  0,   0, 0xFF, 0xF5
		.byte	8,   9,	  0,  0xC, 0xFF, 0xF5
word_184E72:	.word 1			/*  DATA XREF: ROM:00184E5Co */
		.byte  0xF0,  0xF,	  0, 0x12, 0xFF, 0xF0
word_184E7A:	.word 1			/*  DATA XREF: ROM:00184E5Co */
		.byte  0xF0,  0xF,	  0, 0x22, 0xFF, 0xF0
word_184E82:	.word 1			/*  DATA XREF: ROM:00184E5Co */
		.byte  0xF0,  0xF,	  0, 0x32, 0xFF, 0xF0
