Map_7D7A2:		.word word_7D7C2-Map_7D7A2
		.word word_7D7CA-Map_7D7A2
		.word word_7D7D2-Map_7D7A2
		.word word_7D7DA-Map_7D7A2
		.word word_7D7E2-Map_7D7A2
		.word word_7D7EA-Map_7D7A2
		.word word_7D7F2-Map_7D7A2
		.word word_7D7FA-Map_7D7A2
		.word word_7D802-Map_7D7A2
		.word word_7D80A-Map_7D7A2
		.word word_7D812-Map_7D7A2
		.word word_7D81A-Map_7D7A2
		.word word_7D822-Map_7D7A2
		.word word_7D82A-Map_7D7A2
		.word word_7D832-Map_7D7A2
		.word word_7D83A-Map_7D7A2
word_7D7C2:	.word 1			
		.byte  0xFC,   0,	  0,   0, 0xFF, 0xFC
word_7D7CA:	.word 1			
		.byte  0xF8,   1,	  0,   1, 0xFF, 0xFC
word_7D7D2:	.word 1			
		.byte  0xF8,   1,	  0,   3, 0xFF, 0xFC
word_7D7DA:	.word 1			
		.byte  0xF8,   1,	  0,   5, 0xFF, 0xFC
word_7D7E2:	.word 1			
		.byte  0xF8,   1,	  0,   7, 0xFF, 0xFC
word_7D7EA:	.word 1			
		.byte  0xF8,   1,	  0,   9, 0xFF, 0xFC
word_7D7F2:	.word 1			
		.byte  0xF8,   1,	  0,  0xB, 0xFF, 0xFC
word_7D7FA:	.word 1			
		.byte  0xF8,   1,	  0,  0xD, 0xFF, 0xFC
word_7D802:	.word 1			
		.byte  0xF8,   1,	  0,  0xF, 0xFF, 0xFC
word_7D80A:	.word 1			
		.byte  0xF8,   1,	  0, 0x11, 0xFF, 0xFC
word_7D812:	.word 1			
		.byte  0xF8,   1,	  0, 0x13, 0xFF, 0xFC
word_7D81A:	.word 1			
		.byte  0xFC,   0,	  0, 0x15, 0xFF, 0xFC
word_7D822:	.word 1			
		.byte  0xF8,   1,	  0, 0x16, 0xFF, 0xFC
word_7D82A:	.word 1			
		.byte  0xF8,   1,	  0, 0x18, 0xFF, 0xFC
word_7D832:	.word 1			
		.byte  0xF8,   1,	  0, 0x1A, 0xFF, 0xFC
word_7D83A:	.word 1			
		.byte  0xF8,   1,	  0, 0x1C, 0xFF, 0xFC
