		.word	word_8F090-Map_Rockn
		.word word_8F098-Map_Rockn
		.word word_8F0A0-Map_Rockn
		.word word_8F0A8-Map_Rockn
		.word word_8F0B0-Map_Rockn
word_8F090:	.word 1			/*  DATA XREF: ROM:0008F086o */
		.byte  0xF8,   9,	  0,   0, 0xFF, 0xF4
word_8F098:	.word 1			/*  DATA XREF: ROM:0008F086o */
		.byte  0xF8,   9,	  0,   6, 0xFF, 0xF4
word_8F0A0:	.word 1			/*  DATA XREF: ROM:0008F086o */
		.byte  0xF8,  0xD,	  0,  0xC, 0xFF, 0xF0
word_8F0A8:	.word 1			/*  DATA XREF: ROM:0008F086o */
		.byte  0xF8,   5,	  0, 0x14, 0xFF, 0xE8
word_8F0B0:	.word 1			/*  DATA XREF: ROM:0008F086o */
		.byte	0,   4,	  0, 0x18, 0xFF, 0xE8
