Map_360F26:	.word Frame_360F2E-Map_360F26
		.word Frame_360F3C-Map_360F26
		.word Frame_360F4A-Map_360F26
		.word Frame_360F58-Map_360F26
Frame_360F2E:	.word 2
		.byte 0xF8,  5,  0,  0,0xFF,0xF4
		.byte 0xF8,  1,  0,  8,  0,  4
Frame_360F3C:	.word 2
		.byte 0xF8,  5,  0,  0,0xFF,0xF4
		.byte 0xF8,  1,  0, 0xA,  0,  4
Frame_360F4A:	.word 2
		.byte 0xF8,  5,  0,  4,0xFF,0xF4
		.byte 0xF8,  1,  0,  8,  0,  4
Frame_360F58:	.word 2
		.byte 0xF8,  5,  0,  4,0xFF,0xF4
		.byte 0xF8,  1,  0, 0xA,  0,  4
