		.word word_21250-Map_SurfboardSplash
		.word word_2125E-Map_SurfboardSplash
		.word word_2126C-Map_SurfboardSplash
		.word word_2127A-Map_SurfboardSplash
		.word word_21288-Map_SurfboardSplash
		.word word_21296-Map_SurfboardSplash
		.word word_212A4-Map_SurfboardSplash
word_21250:	.word 2
		.byte  0xF0,   9,   0,   0,   0,   0
		.byte  0xF8,  0xC,   0,   6,   0, 0x18
word_2125E:	.word 2
		.byte  0xF0,  0xD,   0,  0xA,   0,   0
		.byte  0xF0,   9,   0, 0x12,   0, 0x20
word_2126C:	.word 2
		.byte  0xF0,  0xD,   0, 0x18,   0,   0
		.byte  0xE8,  0xA,   0, 0x20,   0, 0x20
word_2127A:	.word 2
		.byte  0xF0,  0xD,   0, 0x29,   0,   0
		.byte  0xE8,  0xA,   0, 0x31,   0, 0x20
word_21288:	.word 2
		.byte  0xF0,  0xD,   0, 0x3A,   0,   0
		.byte  0xE8,  0xA,   0, 0x42,   0, 0x20
word_21296:	.word 2
		.byte  0xF8,  0xC,   0, 0x4B,   0,   0
		.byte  0xF0,   9,   0, 0x4F,   0, 0x20
word_212A4:	.word 2
		.byte  0xF8,  0xC,   0, 0x55,   0,   0
		.byte  0xF8,   8,   0, 0x59,   0, 0x20
