Map_36065A:	.word Frame_360684-Map_36065A
		.word Frame_360698-Map_36065A
		.word Frame_3606AC-Map_36065A
		.word Frame_3606C0-Map_36065A
		.word Frame_3606D4-Map_36065A
		.word Frame_3606E8-Map_36065A
		.word Frame_3606FC-Map_36065A
		.word Frame_360710-Map_36065A
		.word Frame_360724-Map_36065A
		.word Frame_360738-Map_36065A
		.word Frame_36074C-Map_36065A
		.word Frame_36075A-Map_36065A
		.word Frame_360768-Map_36065A
		.word Frame_36077C-Map_36065A
		.word Frame_36078A-Map_36065A
		.word Frame_360792-Map_36065A
		.word Frame_3607A0-Map_36065A
		.word Frame_3607AE-Map_36065A
		.word Frame_3607BC-Map_36065A
		.word Frame_3607CA-Map_36065A
		.word Frame_3607D8-Map_36065A
Frame_360684:	.word 3
		.byte   1,  5,  0,  0,  0,  7
		.byte 0xF8, 0xD,  0,  4,0xFF,0xF0
		.byte   1,  5,  8,  0,0xFF,0xF8
Frame_360698:	.word 3
		.byte   1,  5,  0,  0,  0,  7
		.byte 0xF8, 0xD,  0,  4,0xFF,0xF0
		.byte   1,  5,  8,  0,0xFF,0xF8
Frame_3606AC:	.word 3
		.byte 0xF9,  5,  0,  0,  0,  7
		.byte 0xF8, 0xD,  0,  4,0xFF,0xF0
		.byte 0xF9,  5,  8,  0,0xFF,0xF8
Frame_3606C0:	.word 3
		.byte 0xF9,  5,  0,  0,  0,  7
		.byte 0xF8, 0xD,  0,  4,0xFF,0xF0
		.byte 0xF9,  5,  8,  0,0xFF,0xF8
Frame_3606D4:	.word 3
		.byte 0xF3,  5,  0,  0,  0,  7
		.byte 0xF8, 0xD,  0,  4,0xFF,0xF0
		.byte 0xF3,  5,  8,  0,0xFF,0xF8
Frame_3606E8:	.word 3
		.byte 0xF3,  5,  0,  0,  0,  7
		.byte 0xF8, 0xD,  0,  4,0xFF,0xF0
		.byte 0xF3,  5,  8,  0,0xFF,0xF8
Frame_3606FC:	.word 3
		.byte   1,  8,  0,  0,  0,  7
		.byte 0xF8, 0xD,  0,  3,0xFF,0xF0
		.byte   1,  8,  8,  0,0xFF,0xF8
Frame_360710:	.word 3
		.byte   1,  8,  0,  0,  0,  7
		.byte 0xF8, 0xD,  0,  3,0xFF,0xF0
		.byte   1,  8,  8,  0,0xFF,0xF8
Frame_360724:	.word 3
		.byte   1,  5,  0,  0,  0,  7
		.byte 0xF8, 0xD,  0,  4,0xFF,0xF0
		.byte   1,  5,  8,  0,0xFF,0xF8
Frame_360738:	.word 3
		.byte   1,  5,  0,  0,  0,  7
		.byte 0xF8, 0xD,  0,  4,0xFF,0xF0
		.byte   1,  5,  8,  0,0xFF,0xF8
Frame_36074C:	.word 2
		.byte 0xF8, 0xD,  0,  0,0xFF,0xF0
		.byte   0,  0,  0,  8,  0,0x10
Frame_36075A:	.word 2
		.byte 0xF4, 0xD,  0,  0,0xFF,0xF4
		.byte   4,  0,  0,  8,  0, 0xC
Frame_360768:	.word 3
		.byte 0xF4, 0xD,  0,  0,0xFF,0xF0
		.byte 0xF4,  0,  0,  8,  0,0x10
		.byte   4,  0,  0,  9,  0,  8
Frame_36077C:	.word 2
		.byte 0xF8, 0xD,  0,  0,0xFF,0xF0
		.byte 0xF8,  1,  0,  8,  0,0x10
Frame_36078A:	.word 1
		.byte 0xF8, 0xD,  0,  0,0xFF,0xF0
Frame_360792:	.word 2
		.byte 0xF4,  4,  0,  0,  0,  4
		.byte 0xFC, 0xD,  0,  2,0xFF,0xF4
Frame_3607A0:	.word 2
		.byte 0xF4,  9,  0,  0,0xFF,0xFF
		.byte   4,  8,  0,  6,0xFF,0xF7
Frame_3607AE:	.word 2
		.byte 0xF4,  4,  0,  0,  0,  0
		.byte 0xFC, 0xA,  0,  2,0xFF,0xF8
Frame_3607BC:	.word 2
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF8
		.byte  0xC,  0,  0,  9,0xFF,0xF8
Frame_3607CA:	.word 2
		.byte 0xF4, 0xA,  0,  0,0xFF,0xF8
		.byte  0xC,  0,  0,  9,0xFF,0xF8
Frame_3607D8:	.word 3
		.byte 0xF8,  0,  0,  0,0xFF,0xF0
		.byte 0xF8, 0xA,  0,  1,0xFF,0xF8
		.byte 0x10,  0,  0, 0xA,  0,  8
