Map_226854:	.word Frame_2268C6-Map_226854 /* ...*/
		.word Frame_2268CE-Map_226854
		.word Frame_2268D6-Map_226854
		.word Frame_2268DE-Map_226854
		.word Frame_2268E6-Map_226854
		.word Frame_2268EE-Map_226854
		.word Frame_2268F6-Map_226854
		.word Frame_226864-Map_226854
Frame_226864:	.word 0x10
		.byte 0xE0,  5,  0,  4,0xFF,0xF0
		.byte 0xE0,  5,  8,  4,  0,  0
		.byte 0x10,  5,0x10,  4,0xFF,0xF0
		.byte 0x10,  5,0x18,  4,  0,  0
		.byte 0xF0,  1,  0,  8,0xFF,0xF1
		.byte 0xF0,  1,  0, 0xA,0xFF,0xF4
		.byte 0xF0,  1,  0, 0xC,0xFF,0xF9
		.byte 0xF0,  1,  0, 0xE,0xFF,0xFF
		.byte 0xF0,  1,  8, 0xA,  0,  4
		.byte 0xF0,  1,  8,  8,  0,  7
		.byte   0,  1,  0,  8,0xFF,0xF1
		.byte   0,  1,  0, 0xA,0xFF,0xF4
		.byte   0,  1,  0, 0xC,0xFF,0xF9
		.byte   0,  1,  0, 0xE,0xFF,0xFF
		.byte   0,  1,  8, 0xA,  0,  4
		.byte   0,  1,  8,  8,  0,  7
Frame_2268C6:	.word 1
		.byte   0,  1,  0,  8,  0,  0
Frame_2268CE:	.word 1
		.byte   0,  1,  0, 0xA,  0,  0
Frame_2268D6:	.word 1
		.byte   0,  1,  0, 0xC,  0,  0
Frame_2268DE:	.word 1
		.byte   0,  1,  0, 0xE,  0,  0
Frame_2268E6:	.word 1
		.byte   0,  1,  8, 0xC,  0,  0
Frame_2268EE:	.word 1
		.byte   0,  1,  8, 0xA,  0,  0
Frame_2268F6:	.word 1
		.byte   0,  1,  8,  8,  0,  0
