		.word word_2533E-Map_LBZMovingPlatform
		.word word_2534C-Map_LBZMovingPlatform
		.word word_2535A-Map_LBZMovingPlatform
word_2533E:	.word 2			/*  DATA XREF: ROM:00025338o */
		.byte  0xF8,  0xD,	  0,   0, 0xFF, 0xE0
		.byte  0xF8,  0xD,	  8,   0,   0,	 0
word_2534C:	.word 2			/*  DATA XREF: ROM:00025338o */
		.byte  0xF8,  0xD,	  0,   8, 0xFF, 0xE0
		.byte  0xF8,  0xD,	  8,   0,   0,	 0
word_2535A:	.word 2			/*  DATA XREF: ROM:00025338o */
		.byte	4,  0xC,	  0,   0, 0xFF, 0xE0
		.byte	4,  0xC,	  8,   0,   0,	 0
