		.word word_26A04-Map_LBZUnusedUnknown_2
		.word word_26A1E-Map_LBZUnusedUnknown_2
		.word word_26A38-Map_LBZUnusedUnknown_2
		.word word_26A58-Map_LBZUnusedUnknown_2
		.word word_26A72-Map_LBZUnusedUnknown_2
word_26A04:	.word 4
		.byte  0xE8,   7,   0, 0x10, 0xFF, 0xF0
		.byte  0xE8,   7,   8, 0x10,   0,   0
		.byte    8,   4,   0, 0x18, 0xFF, 0xF0
		.byte    8,   4,   8, 0x18,   0,   0
word_26A1E:	.word 4
		.byte  0xF0,   6,   0, 0x1A, 0xFF, 0xF0
		.byte  0xE8,   7,   0, 0x20,   0,   0
		.byte    8,   4,   0, 0x18, 0xFF, 0xF0
		.byte    8,   4,   8, 0x18,   0,   0
word_26A38:	.word 5
		.byte  0xE8,   4,   0, 0x28,   0,   8
		.byte  0xF0,   6,   0, 0x2A, 0xFF, 0xF0
		.byte    8,   4,   0, 0x18, 0xFF, 0xF0
		.byte  0xF0,   7,   0, 0x30,   0,   0
		.byte  0xF0,   0,   0, 0x38,   0, 0x10
word_26A58:	.word 4
		.byte  0xF0,   6,   8, 0x1A,   0,   0
		.byte  0xE8,   7,   8, 0x20, 0xFF, 0xF0
		.byte    8,   4,   8, 0x18,   0,   0
		.byte    8,   4,   0, 0x18, 0xFF, 0xF0
word_26A72:	.word 5
		.byte  0xE8,   4,   8, 0x28, 0xFF, 0xE8
		.byte  0xF0,   6,   8, 0x2A,   0,   0
		.byte    8,   4,   8, 0x18,   0,   0
		.byte  0xF0,   7,   8, 0x30, 0xFF, 0xF0
		.byte  0xF0,   0,   8, 0x38, 0xFF, 0xE8
