Map_361ABC:	.word Frame_361AD4-Map_361ABC /*  ... */
		.word Frame_361ADC-Map_361ABC
		.word Frame_361AE4-Map_361ABC
		.word Frame_361AEC-Map_361ABC
		.word Frame_361AF4-Map_361ABC
		.word Frame_361AFC-Map_361ABC
		.word Frame_361B04-Map_361ABC
		.word Frame_361B0C-Map_361ABC
		.word Frame_361B1A-Map_361ABC
		.word Frame_361B22-Map_361ABC
		.word Frame_361B2A-Map_361ABC
		.word Frame_361B32-Map_361ABC
Frame_361AD4:	.word 1
		.byte 0xF0, 0xF,  0,  0,0xFF,0xF0
Frame_361ADC:	.word 1
		.byte 0xF0, 0xF,  0,  0,0xFF,0xF0
Frame_361AE4:	.word 1
		.byte 0xF8, 0xE,  0,  0,0xFF,0xF0
Frame_361AEC:	.word 1
		.byte 0xF8, 0xE,  0,  0,0xFF,0xF0
Frame_361AF4:	.word 1
		.byte 0xF8, 0xE,  0,  0,0xFF,0xF0
Frame_361AFC:	.word 1
		.byte 0xF0, 0xF,  0,  0,0xFF,0xF0
Frame_361B04:	.word 1
		.byte 0xF0, 0xF,  0,  0,0xFF,0xF0
Frame_361B0C:	.word 2
		.byte 0xF8,  1,  0,  0,0xFF,0xE8
		.byte 0xF0, 0xF,  0,  2,0xFF,0xF0
Frame_361B1A:	.word 1
		.byte 0xF0, 0xF,  0,  0,0xFF,0xF0
Frame_361B22:	.word 1
		.byte 0xF8,  5,  0,  0,0xFF,0xF8
Frame_361B2A:	.word 1
		.byte 0xEF, 0xF,  0,  0,0xFF,0xF0
Frame_361B32:	.word 0
