Map_4E316:		.word word_4E324-Map_4E316
		.word word_4E32C-Map_4E316
		.word word_4E334-Map_4E316
		.word word_4E33C-Map_4E316
		.word word_4E344-Map_4E316
		.word word_4E34C-Map_4E316
		.word word_4E354-Map_4E316
word_4E324:	.word 1			
		.byte  0xF8,   5,	0x40, 0x4C, 0xFF, 0xF8
word_4E32C:	.word 1			
		.byte  0xF8,   5,	0x40, 0x48, 0xFF, 0xF8
word_4E334:	.word 1			
		.byte  0xF8,   5,	0x40, 0x50, 0xFF, 0xF8
word_4E33C:	.word 1			
		.byte  0xF8,   5,	0x20, 0x48, 0xFF, 0xF8
word_4E344:	.word 1			
		.byte  0xF8,   5,	  0, 0x58, 0xFF, 0xF8
word_4E34C:	.word 1			
		.byte  0xF8,   5,	  0, 0x54, 0xFF, 0xF8
word_4E354:	.word 1			
		.byte  0xF8,   5,	0x20, 0x4C, 0xFF, 0xF8
