Map_4D926:		.word word_4D936-Map_4D926
		.word word_4D93E-Map_4D926
		.word word_4D946-Map_4D926
		.word word_4D94E-Map_4D926
		.word word_4D956-Map_4D926
		.word word_4D95E-Map_4D926
		.word word_4D966-Map_4D926
		.word word_4D96E-Map_4D926
word_4D936:	.word 1			
		.byte  0xF8,   5,	  0,   6, 0xFF, 0xF8
word_4D93E:	.word 1			
		.byte 0xF8, 5, 0,	0xA, 0xFF, 0xF8
word_4D946:	.word 1			
		.byte  0xF8,   5,	  0,  0xE, 0xFF, 0xF8
word_4D94E:	.word 1			
		.byte  0xF8,   5,	  0, 0x12, 0xFF, 0xF8
word_4D956:	.word 1			
		.byte  0xF8,   5,	  0, 0x16, 0xFF, 0xF8
word_4D95E:	.word 1			
		.byte  0xF8,   5,	  8, 0x12, 0xFF, 0xF8
word_4D966:	.word 1			
		.byte  0xF8,   5,	  8,  0xE, 0xFF, 0xF8
word_4D96E:	.word 1			
		.byte  0xF8,   5,	  8,  0xA, 0xFF, 0xF8
