Map_4D8AE:		.word word_4D8C6-Map_4D8AE
		.word word_4D8CE-Map_4D8AE
		.word word_4D8D6-Map_4D8AE
		.word word_4D8DE-Map_4D8AE
		.word word_4D8E6-Map_4D8AE
		.word word_4D8EE-Map_4D8AE
		.word word_4D8F6-Map_4D8AE
		.word word_4D8FE-Map_4D8AE
		.word word_4D906-Map_4D8AE
		.word word_4D90E-Map_4D8AE
		.word word_4D916-Map_4D8AE
		.word word_4D91E-Map_4D8AE
word_4D8C6:	.word 1			
		.byte  0xF8,   1,	  0, 0x12, 0xFF, 0xFC
word_4D8CE:	.word 1			
		.byte  0xF8,   1,	  0, 0x14, 0xFF, 0xFC
word_4D8D6:	.word 1			
		.byte  0xF8,   1,	  0, 0x16, 0xFF, 0xFC
word_4D8DE:	.word 1			
		.byte  0xF8,   1,	  0, 0x18, 0xFF, 0xFC
word_4D8E6:	.word 1			
		.byte  0xF8,   1,	  0, 0x1A, 0xFF, 0xFC
word_4D8EE:	.word 1			
		.byte  0xF8,   1,	  0, 0x1C, 0xFF, 0xFC
word_4D8F6:	.word 1			
		.byte  0xF8,   1,	  0, 0x1E, 0xFF, 0xFC
word_4D8FE:	.word 1			
		.byte  0xF8,   1,	  0, 0x20, 0xFF, 0xFC
word_4D906:	.word 1			
		.byte  0xF8,   1,	  0, 0x22, 0xFF, 0xFC
word_4D90E:	.word 1			
		.byte  0xF8,   1,	  0, 0x24, 0xFF, 0xFC
word_4D916:	.word 1			
		.byte  0xF8,   5,	  0,   0, 0xFF, 0xF4
word_4D91E:	.word 1			
		.byte  0xF8,   5,	  0,   0, 0xFF, 0xFC
