/* Blaster mappings*/
		.word word_89792-Map_Blaster
		.word word_897AC-Map_Blaster
		.word word_897C6-Map_Blaster
		.word word_897E0-Map_Blaster
		.word word_897E8-Map_Blaster
		.word word_897F0-Map_Blaster
		.word word_897F8-Map_Blaster
		.word word_89800-Map_Blaster
		.word word_89808-Map_Blaster
		.word word_89810-Map_Blaster
		.word word_89818-Map_Blaster
word_89792:	.word 4			/* DATA XREF: ROM:0008977Co*/
		.byte	4,   0,	  0,   0, 0xFF, 0xEC
		.byte  0xF4,  0xE,	  0,   1, 0xFF, 0xF4
		.byte	7,  0xC,	  0,  0xD, 0xFF, 0xF0
		.byte  0xEC,   6,	  0, 0x11, 0xFF, 0xE4
word_897AC:	.word 4			/* DATA XREF: ROM:0008977Co*/
		.byte	3,   0,	  0,   0, 0xFF, 0xEC
		.byte  0xF3,  0xE,	  0,   1, 0xFF, 0xF4
		.byte	7,  0xC,	  0,  0xD, 0xFF, 0xF0
		.byte  0xEB,   6,	  0, 0x11, 0xFF, 0xE4
word_897C6:	.word 4			/* DATA XREF: ROM:0008977Co*/
		.byte	4,   0,	  0,   0, 0xFF, 0xEC
		.byte  0xF4,  0xE,	  0,   1, 0xFF, 0xF4
		.byte	7,  0xC,	  0,  0xD, 0xFF, 0xF0
		.byte  0xEC,   6,	  0, 0x17, 0xFF, 0xE4
word_897E0:	.word 1			/* DATA XREF: ROM:0008977Co*/
		.byte  0xF8,   5,	  0, 0x1D, 0xFF, 0xF8
word_897E8:	.word 1			/* DATA XREF: ROM:0008977Co*/
		.byte  0xF8,   5,	  0, 0x21, 0xFF, 0xF8
word_897F0:	.word 1			/* DATA XREF: ROM:0008977Co*/
		.byte  0xFC,   0,	  0, 0x25, 0xFF, 0xFC
word_897F8:	.word 1			/* DATA XREF: ROM:0008977Co*/
		.byte  0xFC,   0,	  0, 0x26, 0xFF, 0xFC
word_89800:	.word 1			/* DATA XREF: ROM:0008977Co*/
		.byte  0xFC,   0,	  0, 0x27, 0xFF, 0xFC
word_89808:	.word 1			/* DATA XREF: ROM:0008977Co*/
		.byte  0xFC,   0,	  8, 0x27, 0xFF, 0xFC
word_89810:	.word 1			/* DATA XREF: ROM:0008977Co*/
		.byte  0xFC,   0,	0x18, 0x27, 0xFF, 0xFC
word_89818:	.word 1			/* DATA XREF: ROM:0008977Co*/
		.byte  0xFC,   0,	0x10, 0x27, 0xFF, 0xFC
